### ISSUE TITLE
cant activate Mixcr license

### ISSUE THREAD

**Issue by leidenbi** [milaboratory/mixcr#1005]
## Checklist before submitting the issue:

 - [x] The issue is strongly related to the MiXCR software
 - [x] The issue can be reproduced with [the most recent version](https://github.com/milaboratory/mixcr/releases) of MiXCR
 - [ ] There is no answer to the question in the [official documentation](http://mixcr.readthedocs.io/) and there is no duplicate issue in the [bug tracker](https://github.com/milaboratory/mixcr/issues?utf8=✓&q=)  
 - [ ] Inspection of raw alignments with [exportAlignmentsPretty](http://mixcr.readthedocs.io/en/master/export.html#exporting-well-formatted-alignments-for-manual-inspection) shows that data has the expected architecture, and sample preparation artefacts are not the reason of the problem (if this is the matter of the issue)

## Expected Result

*A description of what you wanted to happen*

## Actual Result

*A description of what actually happened*

## Exact MiXCR commands 

*Paste here __exact__ MiXCR commands you used (enclose it with single `` ` ``  for better formatting)*

## MiXCR report files 

*Paste here content of the report files produced by MiXCR (enclose it with triple ```` ``` ````  for better formatting)*

**Comment by leidenbi** [comment]
The command 'mixcr activate-license' does not work. When I type this I get the error message : mixcr: command not found....

**Comment by PoslavskySV** [comment]
Hi, which version of mixcr you use?

**Comment by leidenbi** [comment]
> 

mixcr-4.2.0

**Comment by PoslavskySV** [comment]
How do you run it? If you didn't add it to PATH, you need to write ./mixcr 

Check video tutorial: https://youtu.be/zY0EOXDmaGY

**Comment by leidenbi** [comment]
I followed the steps, however it still does not work. When I use './mixcr activate license' it does nothing. So I get no error message but also no possibility to enter the license code.

**Comment by PoslavskySV** [comment]
Please, try 

```
./mixcr activate-license
```

**Comment by leidenbi** [comment]
I still don't get an option to enter the license code.

**Comment by PoslavskySV** [comment]
Which OS you have? Did you download .zip archive from [releases](https://github.com/milaboratory/mixcr/releases/tag/v4.2.0) page? I just downloaded it and tried:
<img width="888" alt="image" src="https://user-images.githubusercontent.com/3834261/218111478-d6e45964-1228-4177-89b5-106012442132.png">

**Comment by leidenbi** [comment]
I installed mixcr according to the manual on the site with the command 

'wget https://github.com/milaboratory/mixcr/releases/download/v4.2.0/mixcr-4.2.0.zip' 

I am working on a hpc cluster.

**Comment by leidenbi** [comment]
<img width="251" alt="Schermafbeelding 2023-02-10 om 15 15 22" src="https://user-images.githubusercontent.com/125039732/218114151-437fd946-fab5-4b55-8de6-4d0aee984ee7.png">

**Comment by PoslavskySV** [comment]
Can you try to run:
```
java -jar mixcr.jar activate-license
```

**Comment by leidenbi** [comment]
It works!!!
Thankyou so much :)

**Comment by PoslavskySV** [comment]
Great! Although it is strange that ./mixcr script doesn't work, will try to figure it out.
