### ISSUE TITLE
Correct handling on single description in paired end reads in exportReadsForClones

### ISSUE THREAD

**Issue by dbolotin** [milaboratory/mixcr#103]
Here:
https://github.com/milaboratory/mixcr/blob/develop/src/main/java/com/milaboratory/mixcr/cli/ActionExportCloneReads.java#L149

Something like this:
https://github.com/milaboratory/mixcr/blob/develop/src/main/java/com/milaboratory/mixcr/cli/ActionExportReads.java#L89

**Comment by PoslavskySV** [comment]
When this is possible (1 description but 2 reads)? All should be ok now since `createRead` always called using `createRead(vdjca.getOriginalSequences(), vdjca.getDescriptions())`

**Comment by dbolotin** [comment]
Actually just for comparison with some intermediate MiXCR versions with the following lines of code:
https://github.com/milaboratory/mixcr/blob/4887d2a2d1d8128e350060b5214dc4e5cefab447/src/main/java/com/milaboratory/mixcr/cli/ActionAlign.java#L200

And to make this part a bit more robust, in case we will decide to change something about read description.
