### ISSUE TITLE
Clone fraction by locus?

### ISSUE THREAD

**Issue by bbimber** [milaboratory/mixcr#105]
Hello,

We are aligning TCRA/B data using MiXCR.  These data are from single cells, and we expect a single TCRA and single TCRB.  I am trying to automate the filtering of data form MiXCR.  I was wondering if any of the following are possible:

1) Reporting fraction of clones, based on locus.  For example, if you run the tool w/ "loci=TCR", MiXCR will report data for both TCRA and TCRB.  Fraction of clones is really useful for filtering out data; however, in our case it makes most sense when calculated separately for TCRA/B.  I have been getting around this by running the tool twice, one for each locus.  Is there an alternative?

2) When exporting, is it possible to specify a threshold and only export records representing >X% of clones (or perhaps only those representing >X reads)?

Thanks.

**Comment by dbolotin** [comment]
1. In coming 1.8 release there will be a special option for filtering clones by specific locus:
  ```
  mixcr exportClones -l TRA clones.clns clones.txt
  ```
  And, in general, for 1.8 it is recommended to run mixcr without `--loci` option on alignment step as there is a chance of alignment of genes from one locus onto molecules from other locus.

2. I just created an issue to add this filters in 1.8. (see #107)

1.8 will be very soon.

**Comment by bbimber** [comment]
that's great - looking forward to 1.8
