### ISSUE TITLE
Error running importFromIMGT

### ISSUE THREAD

**Issue by KestindotC** [milaboratory/mixcr#106]
Hello,
I think there might be pup error in these message, but how could I fix it?

$ mixcr importFromIMGT
Starting importFromIMGT.sh script
By using this script you agree to the terms of use of IMGT website. (see http://www.imgt.org/ for details).
Press ENTER to continue or other key to exit...
~/.linuxbrew/Cellar/mixcr/1.7-5/importFromIMGT.sh: line 40: ~/.linuxbrew/bin/pup: cannot execute binary file: Exec format error
Available species:
Please select species (e.g. '5' for ): 
......

So I was wondering if any of solution to solve this problem?
Thanks!

**Comment by dbolotin** [comment]
Yap, there is a known issue with `pup` installed using `linuxbrew`.

Here is the solution:

1. Unlink `pup` installed using `brew`:
  ```
  brew unlink pup
  ```

2. Setup environment for `go`:
  ```
  mkdir ~/.go
  ```
  add the following lines to your `.bashrc` (or equivalent file):
  ```
  export GOPATH="$HOME/.go"
  export PATH="$HOME/.go/bin:$PATH"
  ```

3. Relogin to the shell and install pup using `go get`:
  ```
  go get github.com/ericchiang/pup
  ```

**Comment by KestindotC** [comment]
Thanks for the reply!! go get work ~

**Comment by dbolotin** [comment]
Good!
