### ISSUE TITLE
Generic RNA-Seq data

### ISSUE THREAD

**Issue by 3d7l** [milaboratory/mixcr#1062]
Hello,

Is there any recommendation
regarding the input data
to be analyzed by the rnaseq-cdr3 and rnaseq-full-length presets ?

Examples:
- single-end vs paired-end ?
- 3' vs 5' (for single-end) ?
- read size ?

Thanks

**Comment by mizraelson** [comment]
Hi, these presets are designed for bulk RNA-seq data. The longer the read size - the better the results will be (I would say everything above 80-90bp is totally fine).
For single cell data we have dedicated presets depending on the protocol.
Single-end and paired-end should both be fine, of course with pared-end you cover longer sequence.

Let me know if you need any help with choosing the right preset for your type of data.

Regards,
Mark

**Comment by 3d7l** [comment]
Thank you very much.
