### ISSUE TITLE
Occasionally 'Missing event detected'

### ISSUE THREAD

**Issue by omegahh** [milaboratory/mixcr#1070]
## Checklist before submitting the issue:

 - [ ] The issue is strongly related to the MiXCR software
 - [x] The issue can be reproduced with [the most recent version](https://github.com/milaboratory/mixcr/releases) of MiXCR
 - [x] There is no answer to the question in the [official documentation](http://mixcr.readthedocs.io/) and there is no duplicate issue in the [bug tracker](https://github.com/milaboratory/mixcr/issues?utf8=✓&q=)  
 - [ ] Inspection of raw alignments with [exportAlignmentsPretty](http://mixcr.readthedocs.io/en/master/export.html#exporting-well-formatted-alignments-for-manual-inspection) shows that data has the expected architecture, and sample preparation artefacts are not the reason of the problem (if this is the matter of the issue)

## Expected Result

*A description of what you wanted to happen*

## Actual Result

```
Writing pre-clones: progress unknown
Writing pre-clones: 2.2%
Writing pre-clones: 12.3%  ETA: 00:00:51
Writing pre-clones: 22.5%  ETA: 00:00:46
Writing pre-clones: 33.9%  ETA: 00:00:35
Writing pre-clones: 44.5%  ETA: 00:00:31
Writing pre-clones: 56.1%  ETA: 00:00:23
Writing pre-clones: 66.5%  ETA: 00:00:19
Writing pre-clones: 78.1%  ETA: 00:00:11
Writing pre-clones: 89.6%  ETA: 00:00:05
Writing pre-clones: 9.3%
Writing pre-clones: 84.3%  ETA: 00:00:00
Initialization: progress unknown
Assembling initial clonotypes: 96.2%
4.3.2; built=Wed Apr 12 02:35:07 CST 2023; rev=123d699964; lib=repseqio.v2.2
picocli.CommandLine$ExecutionException: Error while running command assemble java.lang.RuntimeException: Missing event detected.
        at com.milaboratory.mixcr.cli.Main.registerExceptionHandlers$lambda-13(SourceFile:322)
        at picocli.CommandLine.execute(CommandLine.java:2088)
        at com.milaboratory.mixcr.cli.Main.main(SourceFile:102)
Caused by: java.lang.RuntimeException: Missing event detected.
        at com.milaboratory.o.iX.a(SourceFile:59)
        at com.milaboratory.o.jd$c.accept(SourceFile:1475)
        at cc.redberry.pipe.blocks.FilteringPort.take(FilteringPort.java:65)
        at cc.redberry.pipe.blocks.O2ITransmitter.run(O2ITransmitter.java:63)
        at java.base/java.lang.Thread.run(Thread.java:829)
```

## Exact MiXCR commands 

`mixcr assemble -f --high-compression -Xmx128g --write-alignments --sort-by-sequence --report logs/E09-UQ03-UT03.assemble.report trim_mixcr/E09-UQ03-UT03.refined.vdjca trim_mixcr/E09-UQ03-UT03.clna &>> logs/E09_mixcr.info.log`

## MiXCR report files 

```
======================================
Analysis date: Wed Apr 12 15:51:24 CST 2023
Input file(s): trim_mixcr/E09-UQ03-UT03.refined.vdjca
Output file(s): trim_mixcr/E09-UQ03-UT03.clna
Version: 4.3.2; built=Wed Apr 12 02:35:07 CST 2023; rev=123d699964; lib=repseqio.v2.2
Command line arguments: assemble -f --high-compression --write-alignments --sort-by-sequence --report logs/E09-UQ03-UT03.assemble.report trim_mixcr/E09-UQ03-UT03.refined.vdjca trim_mixcr/E09-UQ03-UT03.clna
Analysis time: 75.6m
Final clonotype count: 53419
Reads used in clonotypes, percent of total: 2293112 (19.27%)
Average number of reads per clonotype: 42.93
Reads dropped due to the lack of a clone sequence, percent of total: 53864 (0.45%)
Reads dropped due to a too short clonal sequence, percent of total: 0 (0%)
Reads dropped due to low quality, percent of total: 0 (0%)
Reads dropped due to failed mapping, percent of total: 258 (0%)
Reads dropped with low quality clones, percent of total: 0 (0%)
Reads used in clonotypes before clustering, percent of total: 2293985 (19.28%)
Number of reads used as a core, percent of used: 2293877 (100%)
Mapped low quality reads, percent of used: 108 (0%)
Reads clustered in PCR error correction, percent of used: 873 (0.04%)
Reads pre-clustered due to the similar VJC-lists, percent of used: 0 (0%
Clonotypes dropped as low quality: 0
Clonotypes eliminated by PCR error correction: 31
Clonotypes pre-clustered due to the similar VJC-lists: 0
Clones dropped in post filtering: 0 (0%)
Reads dropped in post filtering: 0.0 (0%)
Alignments filtered by tag prefix: 981 (0.01%)
IGH chains: 53416 (99.99%)
IGH non-functional: 1409 (2.64%)
IGK chains: 3 (0.01%)
IGK non-functional: 0 (0%)
Pre-clone assembler report:
  Number of input groups: 314783
  Number of input groups with no assembling feature: 13
  Number of input alignments: 9739637
  Number of alignments with assembling feature: 9685773 (99.45%)
  Number of output pre-clones: 123991
  Number of pre-clonotypes per group:
    0: + 190792 (60.61%) = 190792 (60.61%)
    1: + 123965 (39.38%) = 314757 (100%)
    2: + 13 (0%) = 314770 (100%)
  Number of assembling feature sequences in groups with zero pre-clonotypes: 5116744
  Number of dropped pre-clones by tag suffix conflict: 0
  Number of dropped alignments by tag suffix conflict: 0
  Number of core alignments: 2293423 (23.55%)
  Discarded core alignments: 7392350 (322.33%)
  Empirically assigned alignments: 820 (0.01%)
  Empirical assignment conflicts: 0 (0%)
  Tag+VJ-gene empirically assigned alignments: 820 (0.01%)
  VJ-gene empirically assigned alignments: 0 (0%)
  Tag empirically assigned alignments: 0 (0%)
  Number of ambiguous groups: 13
  Number of ambiguous V-genes: 9
  Number of ambiguous J-genes: 2
  Number of ambiguous tag+V/J-gene combinations: 11
  Ignored non-productive alignments: 0 (0%)
  Unassigned alignments: 7445223 (76.44%)
======================================
```

**Comment by PoslavskySV** [comment]
Hi,

can you please paste all MiXCR commands used starting from the raw FASTQ files? And corresponding reports.

**Comment by omegahh** [comment]
Before assemble, they are:

```
mixcr align -f --high-compression -t 24 -Xmx128g --species hsa --library imgt --preset generic-bcr-amplicon-umi --rna --tag-pattern "^cagtggtatcaacgcagagt(UMI:NNNNTNNNNTNNNN)tcttgggg(R1:*)\^attgggcagccctgatt(R2:*) || ^attgggcagccctgatt(R1:*)\^cagtggtatcaacgcagagt(UMI:NNNNTNNNNTNNNN)tcttgggg(R2:*)" --floating-left-alignment-boundary --floating-right-alignment-boundary C --not-aligned-R1 trim_mixcr/E09-UQ03-UT03.NoAln_R1.fastq.gz --not-aligned-R2 trim_mixcr/E09-UQ03-UT03.NoAln_R2.fastq.gz trim_demux/E09-UQ03-UT03_R1.fastq.gz trim_demux/E09-UQ03-UT03_R2.fastq.gz trim_mixcr/E09-UQ03-UT03.vdjca &> logs/E09_mixcr.info.log

mixcr refineTagsAndSort -Xmx128g trim_mixcr/E09-UQ03-UT03.vdjca trim_mixcr/E09-UQ03-UT03.refined.vdjca &>> logs/E09_mixcr.info.log
```

**Comment by omegahh** [comment]
Is there any clue for debugging this? Should I provide more information about it? Looking forward to your reply:)

**Comment by PoslavskySV** [comment]
Yes, can you please provide full reports? Also, if it is possible to share raw data so that we can reproduce it on our end that will help us greatly to fix

**Comment by omegahh** [comment]
Yes, I am pleasure to share raw data with you, but this error happens occasionally. Sometime it fails, while sometime it passes.
We have a HPC cluster based on slurm.  Each node (a computer has 48 cores and 376GB memory). I run a mixcr job with 24 threads and 160GB memory, and two job simultaneously in one single node. 

Last time, The sample `E05` failed. The execution code is 
[E05_mixcr.exec.log](https://github.com/milaboratory/mixcr/files/11233505/E05_mixcr.exec.log)

And the whole report is
[E05_mixcr.info.log](https://github.com/milaboratory/mixcr/files/11233512/E05_mixcr.info.log)

**Comment by PoslavskySV** [comment]
Could you please remove option "--high-compression" and try to re-run? Looks like it is the source of a problem.

**Comment by dbolotin** [comment]
Hi, we are looking into the problem. "--high-compression" seems not to be the problem after deeper investigation. The exception is a result of a fail-safe assertion triggered due to some unexpected interplay between events in two threads processing the data. I hope I will be able to reconstruct what happened even without data and send you a fixed version today.

**Comment by dbolotin** [comment]
Hi again! Can you please try [this pre-release build](https://cdn.milaboratory.com/software/mixcr/mixcr-4.3.2-3-mapping-buffer-feed66460b17da9fa8d28dbc585111d0d43b8d04.zip) this should fix the problem. My guess is that this have something to do with somehow unusual thread scheduler bahaviour on the cluster you run mixcr on, instead we would catched such behaviour much earlier...

**Comment by omegahh** [comment]
I tried this pre-release and all my job succeed. Thank you for doing this!

**Comment by omegahh** [comment]
Sorry for bothering again. I am just wondering, does the updated release include this fix? Because I am experiencing the unexpected random crash again, but without any prompt this time.
