### ISSUE TITLE
Tag pattern for custom BCR protocol help

### ISSUE THREAD

**Issue by liisapomerants** [milaboratory/mixcr#1072]
We have BCR Chudakov protocol data (Turchaninova et al 2016) (with following modifications, if relevant: in the second PCR instead of sample barcodes in the primers, we added illumina overhangs to the primers and then ligated nextera xt indexes as a separate step) and used this pattern with minnn, but have trouble translating that into mixcr 4 pattern. We've used the mixcr-3 before and it worked well with minnn, but we have to use the mixcr 4 for better analysis. Could you please help with that?

The MiNNN (v10.1) pattern we have used before is here:
--pattern "AGTGGTATCAACGCAGAG(UMI:TNNNNTNNNNTNNNNT)CTT\*" 

## Checklist before submitting the issue:

 - [ ] The issue is strongly related to the MiXCR software
 - [ ] The issue can be reproduced with [the most recent version](https://github.com/milaboratory/mixcr/releases) of MiXCR
 - [x] There is no answer to the question in the [official documentation](http://mixcr.readthedocs.io/) and there is no duplicate issue in the [bug tracker](https://github.com/milaboratory/mixcr/issues?utf8=✓&q=)  
 - [ ] Inspection of raw alignments with [exportAlignmentsPretty] (http://mixcr.readthedocs.io/en/master/export.html#exporting-well-formatted-alignments-for-manual-inspection) shows that data has the expected architecture, and sample preparation artefacts are not the reason of the problem (if this is the matter of the issue)

## Expected Result

*A description of what you wanted to happen*

## Actual Result

- A general MiXCR error.

## Exact MiXCR commands 

`bin/mixcr-4.3.2/mixcr analyze generic-bcr-amplicon-umi \
                        --species hsa \
                        --rna \
                        --tag-pattern "AGTGGTATCAACGCAGAG(UMI:TNNNNTNNNNTNNNNT)CTT\*"
                        --rigid-left-alignment-boundary \
                        --floating-right-alignment-boundary C \
                        filename_R1_001.fastq.gz
                        filename_R1_001.fastq.gz
                        filename `
                        
## MiXCR report files 

*Paste here content of the report files produced by MiXCR (enclose it with triple ```` ``` ````  for better formatting)*

**Comment by mizraelson** [comment]
Hi, the correct pattern should be:

`^agtggtatcaacgcagag(UMI:tNNNNtNNNNtNNNNt)ctt(R1:*)\^(R2:*)`

I have also used lowercase letters to allow fuzzy matching as it helps in most cases.

Let me know if it helps. Also, is UMI always in the R1?

**Comment by liisapomerants** [comment]
Hi, 
thank you, the pattern seems to be correct. And yes, I think the UMI is in the R1 always, since the protocol we used put it in 5' end. But mixcr-4-3-2 still doesn't seem to be working - I used the same command i sent previously in a bash script: 

```   bash
for fn1 in files/SV01-1*_R1_001.fastq.gz
do
        fn2=${fn1/R1/R2} #string replace R1 R2
        bn=$(basename -- $fn1)
        mixcr_result=${bn/_*/}
        echo $fn1 $fn2 $mixcr_result
        bin/mixcr-4.3.2/mixcr analyze generic-bcr-amplicon-umi \
                --species hsa \
                --rna \
                --floating-left-alignment-boundary \
                --rigid-left-alignment-boundary C \
                --tag-pattern "^agtggtatcaacgcagag(UMI:tNNNNtNNNNtNNNNt)ctt(R1:*)\^(R2:*)" \
                --assemble-clonotypes-by {CDR1Begin:FR4End} \
                $fn1 $fn2 mixcr4_out/$mixcr_result
        bin/mixcr-4.3.2/mixcr exportClones mixcr4_out/$mixcr_result.clns mixcr4_out/$mixcr_result.tsv \  -f mixcr4_out/$mixcr_$
        bin/mixcr-4.3.2/mixcr exportQc align mixcr4_out/$mixcr_result.clns mixcr4_out/$mixcr_result.alignQc.png
done 

```
- It says in the error:

```
positional parameter at index 1 (([file_I1.fastq[.gz] [file_I2.fastq[.gz]]] file_R1.fastq[.gz] [file_R2.fastq[.gz]]|file.(fasta|bam|sam)) output_prefix) requires at least 2 values, but only 1 were specified: [ ]

.../slurm_script: line 26: --floating-left-alignment-boundary: command not found
``` 
I don't understand why it's not working.

**Comment by mizraelson** [comment]
Hi,
In the original command you specified:

```
--rigid-left-alignment-boundary \ --floating-right-alignment-boundary C 
```

But here I see you used another parameters:

```

--floating-left-alignment-boundary \
--rigid-left-alignment-boundary C \
```

The last one is incorrect as you specify left boundary twice.

Also, there is no need to run `exportClones` after as it is already a part of `mixcr analyze` pipeline.
