### ISSUE TITLE
Analyze mix-ins add multiple export fields.

### ISSUE THREAD

**Issue by weshorton** [milaboratory/mixcr#1075]
Hello, I have a quick question about how to modify the output for `mixcr analyze`. In previous versions of mixcr, I was able to submit a presets file that contained all of the other export fields that I wanted to include. For example:

```
cmd="/usr/bin/java -Xmx15g -jar /path/to/mixcr-3.0.3/mixcr.jar analyze amplicon \
        -s $SPECIES \
        --starting-material dna \
        --5-end v-primers \
        --3-end j-primers \
        --adapters adapters-present \
        --report $REPORTDIR/$REPORT \
        --receptor-type trb \
        --region-of-interest CDR3 \
        --verbose \
        --force-overwrite \
        --only-productive  \
        --align \"-OsaveOriginalReads=true --verbose\" \
        --export \"--preset-file $PRESET --verbose\" \
        $FASTQ \
        $EXPORT"
```

In this instance, the `--export` argument is pointing to a preset file full of export fields:

```
-cloneId
-count
-fraction
-vHit
-dHit
-jHit
-vGene
-dGene
-jGene
-vHitScore
-dHitScore
-jHitScore
-vAlignment
-dAlignment
-jAlignment
-vBestIdentityPercent
-dBestIdentityPercent
-jBestIdentityPercent
-nFeature CDR3
-aaFeature CDR3
-qFeature CDR3
-minFeatureQuality CDR3
-avrgFeatureQuality CDR3
-vHits
-dHits
-jHits
-vGenes
-dGenes
-jGenes
```

I am currently running this command:

```
cmd1="/path/to/mixcr-4.3.0/mixcr analyze generic-tcr-amplicon \
        --species mmu \
        --dna \
        --floating-left-alignment-boundary \
        --floating-right-alignment-boundary J \
        --export-productive-clones-only \
        $FASTQ \
        $EXPORT\_prod"
```

The [documentation for analyze](https://mixcr.com/mixcr/reference/mixcr-analyze/#command-line-options) as well as issue #977 indicate that other fields can be prepended or appended for either alignments or clones using:

```
[--prepend-export-clones-field <field> [<param>...]]...
[--append-export-clones-field <field> [<param>...]]...
[--prepend-export-alignments-field <field> [<param>...]]...
[--append-export-alignments-field <field> [<param>...]]... 
```

**Is it possible to provide a file containing all of these fields as in version 3, or do I have to specify each one in my analyze command?** Thanks for any help!

**Comment by PoslavskySV** [comment]
Hi Wes,

Suppose you have files:

**file: export.txt:**
```
-uniqueTagCount Molecule
-uniqueTagFraction Molecule
-nFeature CDR2
-nMutations CDR2
-aaMutations CDR2
```

Then you can do export from .clns using these files in the following way:

    mixcr exportClones --drop-default-fields @export.txt clones.clns clones.tsv

(you can also remove default export from analyze with `--remove-step exportClones`).


If you want to incorporate this into analyze, than you can do:

**file: export.txt:**
```
--prepend-export-clones-field -uniqueTagCount Molecule
--prepend-export-clones-field -uniqueTagFraction Molecule
--prepend-export-clones-field -nFeature CDR2
--prepend-export-clones-field -nMutations CDR2
--prepend-export-clones-field -aaMutations CDR2
```

and use:

  mixcr analyze <...> --drop-default-fields @export.txt clones.clns clones.tsv 


Let me know how it works.

**Comment by weshorton** [comment]
Sweet! I think that `mixcr analyze` command is what I'm looking for. Could you please point me to where the `@` flag for referencing a config file is explained in the docs? 

Also, is it possible to just add these new fields, without the `--drop-default-fields`?

**Comment by weshorton** [comment]
In case anyone else is interested in running this. I chose the analyze option that was listed above. 

1. I created a file called 4.3_analyzeExportPresets.txt and populated it with multiple lines of `--append-export-clones-field <field> [<param>...]` :

```
head 4.3_analyzeExportPresets.txt
--append-export-clones-field -cloneId
--append-export-clones-field -count
--append-export-clones-field -fraction
--append-export-clones-field -vHit
--append-export-clones-field -dHit
--append-export-clones-field -jHit
--append-export-clones-field -vGene
--append-export-clones-field -dGene
--append-export-clones-field -jGene
--append-export-clones-field -vHitScore
```

1. I placed this file into the same directory where I am running the mixcr command
2. I ran this command:

```
cmd1="/path/to/mixcr-4.3.0/mixcr analyze generic-tcr-amplicon \
        -Xmx32g \
        --species mmu \
        --dna \
        --floating-left-alignment-boundary \
        --floating-right-alignment-boundary J \
        --export-productive-clones-only \
        /path/to/fastqFileS1.fastq \
        S1_prod \
        @4.3_analyzeExportPresets.txt"
```

This produces an export clones file called `S1_prod.clones_TRB.tsv` (along with the other standard output files). And this file has the standard output columns as well as those that I specified in my preset file. If you specify an output field in your preset file that is already part of the default output, it will be output in the default location and won't be output twice. 

Also, I tried putting `@4.3_analyzeExportPresets.txt` after the other arguments and before the fastq input, and that gave me an error. I didn't try putting it anywhere else after I ran it successfully as the last argument.

```
mixcr analyze generic-tcr-amplicon \
        -Xmx32g \
        --species mmu \
        --dna \
        --floating-left-alignment-boundary \
        --floating-right-alignment-boundary J \
        --export-productive-clones-only \
        @4.3_analyzeExportPresets.txt
        /path/to/fastqFileS1.fastq \
        S1_prod \
```

So I believe the answer to my above questions are:

1. Use @ to reference files in the same working directory as where you're running the command
2. No you don't have to remove the default output columns if you just want to add a few columns to supplement the default output.

**Comment by PoslavskySV** [comment]
Thank you for detailed guide! You can use '@' for any options, this just expands the content of the file into the command args (unfortunately we don't have docs for that).
