### ISSUE TITLE
About the result of the alignment file from exportAlignments function

### ISSUE THREAD

**Issue by liuweiqing201709** [milaboratory/mixcr#1078]
## Checklist before submitting the issue:

 - [x] The issue is strongly related to the MiXCR software
 - [x] The issue can be reproduced with [the most recent version](https://github.com/milaboratory/mixcr/releases) of MiXCR
 - [x] There is no answer to the question in the [official documentation](http://mixcr.readthedocs.io/) and there is no duplicate issue in the [bug tracker](https://github.com/milaboratory/mixcr/issues?utf8=✓&q=)  
 - [x] Inspection of raw alignments with [exportAlignmentsPretty](http://mixcr.readthedocs.io/en/master/export.html#exporting-well-formatted-alignments-for-manual-inspection) shows that data has the expected architecture, and sample preparation artefacts are not the reason of the problem (if this is the matter of the issue)

## Expected Result

*A description of what you wanted to happen*

I get the result record like the following example:

V350146850L3C001R0010005626|||CB:Z:10700_11122|||UR:Z:GACGATGGCG|||UY:Z:F>A=;F)F5D      0       TRAV27*01        TRAJ54*01                :::::::::43:-1:52:::::56:0:85:116::     235|273|294|14|52||190.0                20|80|80|56|116|SG28CSG39ASG55ASC64G|244.0                TRAV27          TRAJ54          TRAV27          TRAJ54           TGTGCAGGACCCTTAATTCAGCGAGCCCAGAAACTGGTATTT       GGCCAAAGAACCAGGGTGACTATCAACCCAA                                  CAGPLIQRAQKLVF   GQRTRVTINP_     CTATACATCAGATTCCCAGCCTGGTGATACAGGCCTCTACCTCTGTGCAGGACCCTTAATTCAGCGAGCCCAGAAACTGGTATTTGGCCAAAGAACCAGGGTGACTATCAACCCAAAAATTCCAAAACCTGATCCTTCCGTGGTACCACC

then, 
1. In Vgene targetLength is 294, but the length of the TRAV27*01 is 274.
2. In the Jgene,  targeTo and targetLength is 20 and 80, but the length of the TRAJ54*01 is 60.

I feel weird. What's the consideration about the length of the target gene output. 

Thank you for your answer.

**Comment by liuweiqing201709** [comment]
2. There is anther question,  the "TRBD1\*01" mapped to target, but the TRBD1\*01 sequence is "GGGACAGGGGGC" , What's the matter with this alignment? 

<img width="854" alt="image" src="https://user-images.githubusercontent.com/32123540/233586842-5c04b917-1629-423f-b2b9-faad76a2898f.png">

**Comment by mizraelson** [comment]
Hi, can you please share the exact commands you used ?

**Comment by liuweiqing201709** [comment]
> Hi, can you please share the exact commands you used ?

Hi,  Mizraelson
I used three function here, 1.align,  2. exportAlignments, 3.exportAlignmentsPretty
 
Step1. align function 
mixcr align  \
    -f \
    --verbose \
    --library my_library \
    --species 9606 \
    --report human.report \
    --threads 8 \
    --OsaveOriginalReads=true \
    --not-aligned-R1 Y00061C3_V350146850_L03_read_1.clean.part_001.unmap \
    Y00061C3_V350146850_L03_read_1.clean.part_001.fq.gz \
    ./Y00061C3_V350146850_L03_read_1.clean.part_001.vdjca

Step2. exportAlignments function
mixcr exportAlignments \
    --force-overwrite 
    --preset-file exportAlignments.field.txt \
    ./D01862B1_V300111058_L03.1.alignments.vdjca \
    ./D01862B1_V300111058_L03.1.align2Ref.table.tsv 

Step3. exportAlignmentsPretty function
mixcr exportAlignmentsPretty \
    Y00061C3_V350146850_L03_read_1.clean.part_001.vdjca \
    Y00061C3_V350146850_L03_read_1.clean.part_001.preset-file.pretty.tsv

**Comment by mizraelson** [comment]
Thank you. And what's the origin of the library you use? Can you share the file with us to check, because it seems the issue might be in it. It is rather alarming that there is a TRBD gene in your alignment in between TRAV and TRAJ.

You can send it to us via email:

support@milaboratories.com

**Comment by mizraelson** [comment]
Thank you for sharing the data. Can you please confirm the issue persists with the latest version of MiXCR since lots of bugs have been addressed. Judging by the command you shared, you use version 3.X, while the latest one is 4.3.2.
