### ISSUE TITLE
Whole Genome DNA Seq

### ISSUE THREAD

**Issue by seongguheo** [milaboratory/mixcr#1094]
Hi,

Is it possible to analyze WGS in Mixcr v4.3.2?
Please post an example script, if possible.

Thank you for your work!
Luke

**Comment by PoslavskySV** [comment]
Hi, 

Yes, of course this is possible. You can follow [this instruction](https://mixcr.com/mixcr/reference/overview-built-in-presets/#exome-data) and use this command:

```
mixcr analyze exome-full-length \
    --species hsa \
      input_R1.fastq.gz \
      input_R2.fastq.gz \
      result
```

**Comment by wbvguo** [comment]
Hi, I the `exome-full-length` seems not being supported in version `v4.4.2`, should we simply use `exome-seq`?
