### ISSUE TITLE
Run 10X VDJ hashed data

### ISSUE THREAD

**Issue by royfrancis** [milaboratory/mixcr#1099]
My 10X VDJ fastq data for TCR looks like this:

```
PBMC_1_3_1_TCR_S5_L001_I1_001.fastq.gz
PBMC_1_3_1_TCR_S5_L001_R2_001.fastq.gz
PBMC_1_3_1_TCR_S5_L002_R1_001.fastq.gz
PBMC_1_3_1_TCR_S5_L001_I2_001.fastq.gz
PBMC_1_3_1_TCR_S5_L002_I1_001.fastq.gz
PBMC_1_3_1_TCR_S5_L002_R2_001.fastq.gz
PBMC_1_3_1_TCR_S5_L001_R1_001.fastq.gz
PBMC_1_3_1_TCR_S5_L002_I2_001.fastq.gz
```

This is one library with three individuals hashed and pooled together. 

The mixcr [example](https://mixcr.com/mixcr/reference/overview-built-in-presets/#10xgenomics) is like this:

```
mixcr analyze 10x-vdj-tcr \
     --species hsa \
     sample_R1.fastq.gz \
     sample_R2.fastq.gz \
     sample_result
```

Just wondering how to run the program with these files (specify indices and multiple lanes). On cellranger, the output counts are dehashed using a separate software.

**Comment by Alex-Davydov** [comment]
Hi,
To begin, you'll need to create a sample table in tab-delimited format, following the example provided below:


| Sample | TagPattern | SAMPLEI1 | SAMPLEI2 |
| --- | --- | --- | --- |
| Sample1 | | ATGCCGGA | CTGCTTGA |
| Sample2 | | CTTGTTCA | ATCCGGTT |

In the table, the first column represents the sample name, the second column is left empty, the third column contains the I1 (i7 index) sequence, and the fourth column contains the I2 (i5 index) sequence.
Next, you can use the following command:
```
mixcr analyze 10x-vdj-tcr \
      --species hs \
      --sample-table sample_table.tsv \
      --tag-pattern "^(CELL:N{16})(UMI:N{10})\^(R2:*)\(SAMPLEI1:*)\(SAMPLEI2:*)" \
      --split-by-sample \
      PBMC_1_3_1_TCR_S5_L{{n}}_R1_001.fastq.gz \
      PBMC_1_3_1_TCR_S5_L{{n}}_R2_001.fastq.gz \
      PBMC_1_3_1_TCR_S5_L{{n}}_I1_001.fastq.gz \
      PBMC_1_3_1_TCR_S5_L{{n}}_I2_001.fastq.gz \
      output/
```
In this command, you need to replace `sample_table.tsv` with the filename of your sample table. The `--tag-pattern` option allows you to override the 10x pattern from preset by adding your index files to the pattern (I1 and I2). Make sure the group names in the pattern match the names of the third and fourth columns of your sample table. Additionally, the `--split-by-sample` option is necessary to split the resulting files by sample. The `_L{{n}}_` in the fastq file names signifies that MiXCR will automatically concatenate lane 1 and lane 2.

**Comment by royfrancis** [comment]
Thanks for the quick reply. Now I get this error:

`Unmatched arguments from index 14: 'PBMC_1_3_1_TCR/PBMC_1_3_1_TCR_S5_L{{n}}_I2_001.fastq.gz', 'PBMC_1_3_1/'
`

My script (**mixcr.sh**) looks like this:

```
prefix="${1/_TCR/}"

singularity run \
--bind $PWD:/work \
--env MI_LICENSE_FILE="mixcr-license.txt" \
mixcr.sif \
analyze 10x-vdj-tcr \
--threads 4 \
--species hsa \
--sample-table mixcr-samples.tsv \
--tag-pattern "^(CELL:N{16})(UMI:N{10})\^(R2:*)\(SAMPLEI1:*)\(SAMPLEI2:*)" \
--split-by-sample \
${prefix}_TCR/${prefix}_TCR_S5_L{{n}}_R1_001.fastq.gz \
${prefix}_TCR/${prefix}_TCR_S5_L{{n}}_R2_001.fastq.gz \
${prefix}_TCR/${prefix}_TCR_S5_L{{n}}_I1_001.fastq.gz \
${prefix}_TCR/${prefix}_TCR_S5_L{{n}}_I2_001.fastq.gz \
${prefix}/
```

**mixcr-samples.tsv** looks like this:

```
Sample	TagPattern	SAMPLEI1	SAMPLEI2
PBMC_1_3_1		TCGTCAAGAT	CCTGAGTTGC
PBMC_1_3_2		GAATTGGTTA	CTACTAGAGT
PBMC_1_3_3		CGTCCACCTG	GTCATGAATG
PBMC_4		GAGACGCACG	ATGTTCATAG
```

The command is run like this: `bash mixcr.sh PBMC_1_3_1_TCR`. 

And the `PBMC_1_3_1_TCR` directory contains:

```
PBMC_1_3_1_TCR_S5_L001_I1_001.fastq.gz
PBMC_1_3_1_TCR_S5_L001_R2_001.fastq.gz
PBMC_1_3_1_TCR_S5_L002_R1_001.fastq.gz
PBMC_1_3_1_TCR_S5_L001_I2_001.fastq.gz
PBMC_1_3_1_TCR_S5_L002_I1_001.fastq.gz
PBMC_1_3_1_TCR_S5_L002_R2_001.fastq.gz
PBMC_1_3_1_TCR_S5_L001_R1_001.fastq.gz
PBMC_1_3_1_TCR_S5_L002_I2_001.fastq.gz
```

**Comment by Alex-Davydov** [comment]
Which version of MiXCR do you use? This functionality is available in MiXCR v4.2 or later.

**Comment by royfrancis** [comment]
I am running the docker image from `ghcr.io/milaboratory/mixcr/mixcr:latest` through singularity.

```
MiXCR v4.3.2 (built Tue Apr 11 18:35:22 UTC 2023; rev=123d699964; branch=no_branch; host=fv-az451-814)
RepSeq.IO v1.8.0-21-master (rev=5521c5842b)
MiLib v2.4.0-7-master (rev=acea8397fe)
Built-in V/D/J/C library: repseqio.v2.2
```

**Comment by Alex-Davydov** [comment]
Hi,
This is a solution to the problem. Here are the details:
Docker image: `ghcr.io/milaboratory/mixcr/mixcr:4.3.2-64-develop`
Command:
```
mixcr analyze 10x-vdj-tcr \
      --species hs \
      --sample-table sample_table.tsv \
      --tag-pattern "^(SAMPLEI1:*)\^(SAMPLEI2:*)\^(CELL:N{16})(UMI:N{10})\^(R2:*)" \
      --split-by-sample \
      PBMC_1_3_1_TCR_S5_L{{n}}_{{IR}}_001.fastq.gz \
      output/
```
I hope this resolves the issue. If you have any further questions or require additional assistance, please let me know.

**Comment by royfrancis** [comment]
Thanks! I updated the docker image, license and script.
I get the same error: 

```
Unmatched arguments from index 14: 'PBMC_1_3_1_TCR/PBMC_1_3_1_TCR_S5_L{{n}}_{{IR}}_001.fastq.gz', 'PBMC_1_3_1/'
```

**Comment by PoslavskySV** [comment]
Hi, could you please try from the command line? We just checked and the command works correctly, so need to check that the issue is not related to bash or smth
