### ISSUE TITLE
could mixcr analyze target capture sequencing data?

### ISSUE THREAD

**Issue by asaki1986** [milaboratory/mixcr#1110]
We've designed hundreds of 120bp probe to capture all the genes across BCR/TCR genes, using 150PE on novaseq platform.

Can I use MIXCR to analyze these data, and which command should I use?

Best,
Junfeng

**Comment by PoslavskySV** [comment]
Hi Junfeng,

Of course, you can use [this preset](https://mixcr.com/mixcr/reference/overview-built-in-presets/#generic-bcr-amplicon) for both T and B cells.
