### ISSUE TITLE
Java version error (MixCR version 4.3.2)

### ISSUE THREAD

**Issue by yutito** [milaboratory/mixcr#1112]
Hi

I am trying to download MixCR the latest version (version 4.3.2).
Here is the command;

unzip mixcr-4.3.2.zip
Archive:  mixcr-4.3.2.zip
  inflating: mixcr
  inflating: LICENSE
  inflating: mixcr.jar

./mixcr -v
Wrong version of java. Please use Java 7 or higher.

I got this error message. What is wrong? 
Thanks in advance.

Yuta

**Comment by PoslavskySV** [comment]
Hi,

Could you please paste the result of `java -version` here?

**Comment by yutito** [comment]
Thank you for your reply.
It is working now.
Thank you.
