### ISSUE TITLE
Link of Alignment-file and Clone-file

### ISSUE THREAD

**Issue by 3sevieria** [milaboratory/mixcr#113]
I understand the mapping between initial reads and final clonotypes. But I want to know the mapping between __Aligned sequence__ and clones.

**Comment by dbolotin** [comment]
Could you please explain in some more details desired output/type of information you want to get from MiXCR? If I get you right you want to export alignments for the specified clonotype? Or you just want some kind of id to id mapping?

**Comment by 3sevieria** [comment]
sorry, i mean the latter.

the map such as 
clone_id -> [seq_id1, seq_id2, ...., seq_idN] .

**Comment by PoslavskySV** [comment]
@3sevieria did you look into these docs https://mixcr.readthedocs.io/en/latest/export.html#exporting-reads-aggregated-by-clones ? From your last answer it seems that all you need is already in MiXCR. You can pass the option `--index` and then retrieve `clone -> readId` mapping in e.g. the following way:


    mixcr assemble --index index_file alignments.vdjca output.clns
    mixcr exportClones -p min -readIds index_file clones.clns clones.txt


which will give you smth like 

    Clone ID	Clone count	Best V hit	...	Reads
    0	7213	IGHV4-34*00	...	56,74,92,96,101,119,169,183...
    1	2951	IGHV2-23*00	...	46,145,194,226,382,451,464...
    2	2269	IGHV4-34*00	...	58,85,90,103,113,116,122,123...
    ...	 	...	...	


If you need something more, could you please explain it in more detail?

**Comment by 3sevieria** [comment]
thank you!  That works well.
