### ISSUE TITLE
No JAR when installing

### ISSUE THREAD

**Issue by mtutert** [milaboratory/mixcr#115]
Hi, I have installed the program mixcr however when I run the command "mixcr" I get the output of "No jar." Is there anything I am doing wrong?

Thanks.

**Comment by dbolotin** [comment]
By what means did you install mixcr? Using brew, or zip package? OS?
Can you please provide some more details.

**Comment by joonlee3** [comment]
I downloaded and unzipped the zip package. I got the same message "No jar."

**Comment by dbolotin** [comment]
Please provide steps to reproduce the problem.

I just tested latest release and it seems to work:
```
> wget https://github.com/milaboratory/mixcr/releases/download/v1.8.1/mixcr-1.8.1.zip
> unzip mixcr-1.8.1.zip
> cd mixcr-1.8.1
> ./mixcr -v
MiXCR v1.8.1 (built Wed Jun 29 11:35:12 MSK 2016; rev=d7c1254; branch=hotfix/v1.8.1)
Components:
MiLib v1.5-SNAPSHOT (rev=27a3ea6; branch=develop)
```

I am on Mac OS X, but script also should work for Linux and FreeBSD.

**Comment by joonlee3** [comment]
Thanks. It is working now.

**Comment by dbolotin** [comment]
)) Good.
