### ISSUE TITLE
Understanding gene usage

### ISSUE THREAD

**Issue by benjytan88** [milaboratory/mixcr#1153]
Hi MiXCR developers,
I wanted to ask what is the meaning of multiple TRBV genes detected in a sample? For example, what is the meaning of TRBV3-1, TRBV14, TRBV3-2, TRBV4-2 in sample K169_N1t1 in the table below? 

![Screenshot 2023-06-15 at 15 22 45](https://github.com/milaboratory/mixcr/assets/24598265/04887a1b-789b-4b12-839f-36e9a062c6d9)

**Comment by PoslavskySV** [comment]
Hi,  could you please elaborate how did you produce this table? It does not look like output from MiXCR.
