### ISSUE TITLE
Error when running exportAlignmentsPretty on empty file

### ISSUE THREAD

**Issue by bbimber** [milaboratory/mixcr#118]
Hello,

We run MiXCR as part of a pipeline.  If the user selects the 'export alignments' option, we include exportAlignmentsPretty.  If no alignments are found, align/assemble outputs an empty file (as it should).  However, if you try to run exportAlignmentsPretty on the output, it fails with an error like: 

18 Jul 2016 05:28:30,668 DEBUG:     Exception in thread "main" java.lang.RuntimeException: Unsupported file format; .vdjca file of version MiXCR.CLNS.V04 while you are running MiXCR MiXCR.VDJC.V07
18 Jul 2016 05:28:30,711 DEBUG:         at com.milaboratory.mixcr.basictypes.VDJCAlignmentsReader.init(VDJCAlignmentsReader.java:137)
18 Jul 2016 05:28:30,733 DEBUG:         at com.milaboratory.mixcr.basictypes.VDJCAlignmentsReader.take(VDJCAlignmentsReader.java:229)
18 Jul 2016 05:28:30,766 DEBUG:         at com.milaboratory.mixcr.basictypes.VDJCAlignmentsReader.take(VDJCAlignmentsReader.java:53)
18 Jul 2016 05:28:30,800 DEBUG:         at cc.redberry.pipe.CUtils$OPIterator.hasNext(CUtils.java:420)
18 Jul 2016 05:28:30,834 DEBUG:         at com.milaboratory.mixcr.cli.ActionPrettyAlignments.go(ActionPrettyAlignments.java:81)
18 Jul 2016 05:28:30,866 DEBUG:         at com.milaboratory.cli.JCommanderBasedMain.main(JCommanderBasedMain.java:147)
18 Jul 2016 05:28:30,900 DEBUG:         at com.milaboratory.mixcr.cli.Main.ma

I can understand why this happens; however, it would be a nice feature if exportAlignmentsPretty could detect the empty file and not throw the exception.

**Comment by dbolotin** [comment]
Sorry for such a late response.

It looks like you are trying to export alignments from *.clns file (not *.vdjca).

I just checked, mixcr works as expected (without exceptions) with empty files: align, assemble, exportAlignmentsPretty, exportAlignments, exportClones. Except it doesn't output header line in case of exportAlignments and exportClones.

**Comment by bbimber** [comment]
yes, thanks for the reply.  i saw this error elsewhere in our code and corrected it.  should have caught it before opening the issue.
