### ISSUE TITLE
importFromIMGT doesnt work (problem with pup command)

### ISSUE THREAD

**Issue by SolaimanR** [milaboratory/mixcr#122]
Hey,

running mixcr importFromIMGT starts the script. I get to agree to the IMGT terms. Then it will ask me to select a species. However, it shows me an error before giving me the species options that goes:

`path/to/importFromIMGT.sh: line 43: path/to/pup: cannot execute binary file: Exec format error`

Then it continues, however does not give me any species to select from, it is just blank like this:

```
Available species:
Please select species (e.g. '5' for ):
```

Is this a 32-bit/64-bit problem? I run Ubuntu 14.04 LTS 64-bit.

**Comment by dbolotin** [comment]
Sorry for the late response.

Please see this issue: #106
