### ISSUE TITLE
How to tell the difference between TCRa, TCRb and BCR?

### ISSUE THREAD

**Issue by innagsc** [milaboratory/mixcr#123]
Hi, I ran the 3 steps of the MiXCR, and I have the output file clones.txt. 
Is there a way to identify TCRa, TCRb and BCR CDR3 sequences?

Thanks!

**Comment by dbolotin** [comment]
You can separately export each type of molecules:

```
mixcr exportClones -l TRA clones.clns clones.TRA.txt
mixcr exportClones -l TRA clones.clns clones.TRA.txt
```

**Comment by innagsc** [comment]
When I run the 3 steps of the MiXCR with the default parameter of -l (to include BCR, TCRa and TCB), I get 673 clones in the clone file. However, when I run the 3 steps on each loci separately (indicating -l TRA, TRB or IGH in the alignment step and exporting step) I get a higher number of clones, 719 clones. What could be the reason for this?

Thanks!

**Comment by dbolotin** [comment]
It is only a guess, but maybe some TRB clones were misinterpreted as TRA or something like this. I recommend to always run analysis on all loci at once, and separate results by loci only on the final export stage (using `-l`, `--filter-locus` see [here](http://mixcr.readthedocs.io/en/latest/export.html#command-line-parameters)).

You can send me your files (bolotin.dmitriy [at] gmail.com) and I will tell you exact reason of this behaviour. Please also provide exact commands you used.
