### ISSUE TITLE
Unwanted targetQualities field on export

### ISSUE THREAD

**Issue by LukeHebert** [milaboratory/mixcr#1242]
## Expected Result

The export command below should not generate a .tsv file that includes a `targetQualities` column.

## Actual Result

The command generated a .tsv that does include a `targetQualities` column.

## Exact MiXCR commands 

`mixcr-4.3.2/mixcr -Xmx30g exportAlignments -f -targetSequences -readIds -vGene -dGene -jGene -cGene -nFeature FR1 -nFeature CDR1 -nFeature FR2 -nFeature CDR2 -nFeature FR3 -nFeature CDR3 -nFeature FR4 -aaFeature FR1 -aaFeature CDR1 -aaFeature FR2 -aaFeature CDR2 -aaFeature FR3 -aaFeature CDR3 -aaFeature FR4 -vBestIdentityPercent -dBestIdentityPercent -jBestIdentityPercent -cBestIdentityPercent -positionOf CBegin -positionOf CExon1End -positionOf CEnd myfile.vdjca myfile.tsv`

**Comment by PoslavskySV** [comment]
Hi,

You need to add `--drop-default-fields` option to remove default columns from the export.

**Comment by LukeHebert** [comment]
Thank you!

Luke
