### ISSUE TITLE
Error while running command align,  Illegal number of elements for merging.

### ISSUE THREAD

**Issue by weizhiting** [milaboratory/mixcr#1243]
## Checklist before submitting the issue:

 - [x] The issue is strongly related to the MiXCR software
 - [x] The issue can be reproduced with [the most recent version](https://github.com/milaboratory/mixcr/releases) of MiXCR
 - [x] There is no answer to the question in the [official documentation](http://mixcr.readthedocs.io/) and there is no duplicate issue in the [bug tracker](https://github.com/milaboratory/mixcr/issues?utf8=✓&q=)  
 - [x] Inspection of raw alignments with [exportAlignmentsPretty](http://mixcr.readthedocs.io/en/master/export.html#exporting-well-formatted-alignments-for-manual-inspection) shows that data has the expected architecture, and sample preparation artefacts are not the reason of the problem (if this is the matter of the issue)

## Expected Result

When using the lastest version of mixcr (4.3.2) analyzing my tumor samples, one of them report an error,  "picocli.CommandLine$ExecutionException: Error while running command align java.lang.RuntimeException: java.lang.IllegalArgumentException: Illegal number of elements for merging.".   

 please help me and how can i fix it. Thanks!

## Actual Result

`picocli.CommandLine$ExecutionException: Error while running command align java.lang.RuntimeException: java.lang.IllegalArgumentException: Illegal number of elements for merging.`

## Exact MiXCR commands 

`mixcr             align   --preset    rnaseq-cdr3    --threads  30    --species  hsa   -f  --rna   -Xmx100g     145Aligned.sortedByCoord.out.bam        alignments.vdjca`

## MiXCR report files 

`Alignment: 0%
4.3.2; built=Wed Apr 12 02:35:07 CST 2023; rev=123d699964; lib=repseqio.v2.2
picocli.CommandLine$ExecutionException: Error while running command align java.lang.RuntimeException: java.lang.IllegalArgumentException: Illegal number of elements for merging.
	at com.milaboratory.mixcr.cli.Main.registerExceptionHandlers$lambda-13(SourceFile:322)
	at picocli.CommandLine.execute(CommandLine.java:2088)
	at com.milaboratory.mixcr.cli.Main.main(SourceFile:102)`

**Comment by PoslavskySV** [comment]
Hi, 

this is a known bug when starting from BAM. As a workaround, I recommend starting from raw _fastq_ files for now.

**Comment by weizhiting** [comment]
OK， thanks for your reply!
