### ISSUE TITLE
What are the individual mixcr commands of a Built-in preset?

### ISSUE THREAD

**Issue by MathildeFogPerez** [milaboratory/mixcr#1247]
Hi,

I'm using the latest developement version of Mixcr (MiXCR v4.4.1-6-develop) and trying to use one of your built-in preset 

`mixcr analyze bd-sc-xcr-rhapsody-full-length    --species human     sample_R1.fastq.gz     sample_R2.fastq.gz     sample_result`

I have an issue with the memory heapspace at the 'mixcr extend' step and I would like not to run everything from the beginning and use  the single mixcr command to finish the analysis.

I know it starts with :
mixcr align
mixcr refineTagsAndSort
mixcr assemblePartial
mixcr extend

I would guess the next command to be:
mixcr assemble \
      sample1_result.par.vdjca \
      sample1_result.clna

mixcr assembleContigs \
      sample1_result.clna \
      sample1_result.clns 

mixcr exportClones \
      sample1_result.clns \
      sample1_result.tsv 

Is it correct?

thanks!
Mathilde

**Comment by mizraelson** [comment]
Hi, yes, that's correct!
