### ISSUE TITLE
--drop-default-fields for analyze

### ISSUE THREAD

**Issue by naviret** [milaboratory/mixcr#1249]
Hi!

I'm having trouble using the --drop-default-fields parameter for my analyze pipeline. I'm wondering if this is still supported. 

IMPORTANT: MiXCR will use at most 12000MB of RAM,
           use -Xmx to change automatically set heap size (i.e. -Xmx50g to set heap size to 50 Gb)
4.4.1; built=Thu Jul 06 13:36:41 EDT 2023; rev=f7cd556c6c; lib=repseqio.v3.0.1
Unknown option: '--drop-default-fields'

**Comment by mizraelson** [comment]
Hi, can you please share the exact command you are running.

**Comment by naviret** [comment]
Hi yes of course:

```
mixcr analyze generic-amplicon \
    --species hs \
    --rna \
    --floating-left-alignment-boundary \
    --floating-right-alignment-boundary C \
    --drop-non-CDR3-alignments \
    --assemble-contigs-by VDJRegion \
    --drop-default-fields \
    --export-productive-clones-only \
    --impute-germline-on-export \
    --append-export-clones-field -cloneId \
    --append-export-clones-field -readCount \
    --append-export-clones-field -aaFeatureImputed VDJRegion \
    --append-export-clones-field -nFeatureImputed VDJRegion \
    SRR8235277_R1.fastq \
    SRR8235277_R2.fastq \
```

This is an image of the stdout I get from running the command:
<img width="695" alt="image" src="https://github.com/milaboratory/mixcr/assets/111366578/cebc94af-61b3-4bef-a36d-b4909d8757e5">

I'm running Mac OS Ventura 13.4 and these are my MiXCR specifications:

```
MiXCR v4.4.1 (built Thu Jul 06 13:36:41 EDT 2023; rev=f7cd556c6c; branch=no_branch; host=fv-az256-153)
RepSeq.IO v2.1.0 (rev=23cc1c7368)
MiLib v3.1.0 (rev=1e98a48ccd)
Built-in V/D/J/C library: repseqio.v3.0.1
```

Thanks so much for your help!

-Ivan

**Comment by mizraelson** [comment]
Hi,
You are right; that is a mistake in our docs that I will fix right away. `--drop-default-fields` is a parameter of the `mixcr exportClones` function and is not callable from `mixcr analyze`. You can just omit it, and everything will work. If you want to use it, you can run `mixcr exportClones` on a `clns` file generated by `mixcr analyze`.
Sincerely,
Mark
