### ISSUE TITLE
Output 

### ISSUE THREAD

**Issue by bshim181** [milaboratory/mixcr#1261]
Hello, when looking at the mixcr report, I find two TCR repertoires with exactly identical CDR3 amino acid sequences and 1 mismatch in CDR3 nt sequences. These two occurrences have equal V and J segments. 

I was wondering why they have not been clustered into a single clonotype when I have specified assemble gene feature parameter to CDR3 and 2 mismatches or 1 indels are allowed. 

<img width="990" alt="Screenshot 2023-07-26 at 3 50 19 PM" src="https://github.com/milaboratory/mixcr/assets/53489568/db13cd2c-eab6-4043-92bd-abff91483906">

**Comment by mizraelson** [comment]
Hi,
Could you please provide the exact command you used?

To address your question, we should initially examine the alignments that support each clone. This can be done using the `mixcr exportAlignments input.vdjca output.tsv` command. It's likely that there was a comparable number of reads supporting each variant, cause clustering only happens if one clone has a significantly lower count. 

Sincerely,
Mark

**Comment by bshim181** [comment]
I basically used generic-amplicon preset set-ups and made only changes during exportClone parameters (I believe generic-amplicon by default clusters by CDR3 sequences with max mutations allowed being 2 nt mismatches or 1 indels but not both).

**Comment by bshim181** [comment]
I was wondering since these clonotypes have identical CDR3 seq (with 1 difference in nt) and also identical V and J segments, does it make sense to combine or cluster these clonotypes together? 

<img width="872" alt="Screenshot 2023-07-27 at 10 07 03 AM" src="https://github.com/milaboratory/mixcr/assets/53489568/7653728d-fe11-44d1-adbc-323a213808dc">

<img width="870" alt="Screenshot 2023-07-27 at 10 07 24 AM" src="https://github.com/milaboratory/mixcr/assets/53489568/5d1c9473-0032-4d60-a34b-34af80ed182f">

The read count comparison is 284 vs 5. What is the threshold for valid number of reads that support each variant?

**Comment by mizraelson** [comment]
The determination process is somewhat more complex than simply examining the number of reads. Initially, the sequencing quality of the nucleotide is considered. Subsequently, a negative binomial distribution is applied to ascertain if this nucleotide might be the result of an error, accounting for both the read proportion of the clones and the quality of the sequencing.
