### ISSUE TITLE
Skip Steps 

### ISSUE THREAD

**Issue by bshim181** [milaboratory/mixcr#1263]
Hello, 

I know there are features to skip steps during MIXCR Analysis. I was wondering if there is a feature to skip one of the steps conducted during Assembly. I would like to keep track of the clone that gets discarded during the pre-cloning steps and the list of UMIs that collide. Is it possible to set the pre-cloning step parameter to null and proceed with other assembly steps?

**Comment by mizraelson** [comment]
Hi,

Yes, it is possible. The clones will be assembled without taking UMIs into account, and then MiXCR will add UMI clone count accordingly. You can add the following parameter for that behavior: `-Massemble.consensusAssemblerParameters=null`.

Here's the corrected code:

```
mixcr analyze generic-amplicon-with-umi \
--species hsa \
--library imgt \
--rna \
--rigid-left-alignment-boundary \
--floating-right-alignment-boundary C \
--tag-pattern '^(R1:*)\^(UMI:N{7})' \
-Massemble.consensusAssemblerParameters=null \
${R1_file} \
${R2_file} \
/mixcr_OUTPUT/${filename_woExt}/${filename_woExt}
```

To compare the lists of UMI sequences, you should first preserve alignments during assembly. You can use `-Massemble.clnaOutput=true` in the analyze command.

```
mixcr analyze generic-amplicon-with-umi \
--species hsa \
--library imgt \
--rna \
--rigid-left-alignment-boundary \
--floating-right-alignment-boundary C \
--tag-pattern '^(R1:*)\^(UMI:N{7})' \
-Massemble.clnaOutput=true \
${R1_file} \
${R2_file} \
/mixcr_OUTPUT/${filename_woExt}/${filename_woExt}
```

Afterwards, you will have a .clna file which you can use to export alignments with UMI sequences and clone IDs corresponding to the clonotype table. Alignments with a clone ID of -1 are those that were filtered out.

```
mixcr exportAlignments -cloneId -tags Molecule input.clna output.tsv
```

Also, please use the [latest development version](https://link.milaboratory.com/software/mixcr/mixcr-develop.zip) as it has important fixes.

Sincerely,
Mark

**Comment by bshim181** [comment]
Thank you so much
