### ISSUE TITLE
Problem with importFromIMGT

### ISSUE THREAD

**Issue by obricard** [milaboratory/mixcr#127]
Hello 
I have a problem to import loci when I execute importFromIMGT.
Thanks for your help.
Here is a copy paste of my terminal 

M-75-3-56-17-2035:mixcr-1.8.2 OBricard$ /Users/OBricard/Desktop/NGS/tools/mixcr-1.8.2/mixcr importFromIMGT
Starting importFromIMGT.sh script
/Users/OBricard/Desktop/NGS/tools/mixcr-1.8.2/mixcr
MiXCR v1.8.2 (built Sun Jul 31 21:45:51 CEST 2016; rev=8d7653a; branch=hotfix/1.8.2)
Components: 
MiLib v1.5-SNAPSHOT (rev=6fb25d3; branch=UNKNOWN)
By using this script you agree to the terms of use of IMGT website. (see http://www.imgt.org/ for details).
Press ENTER to continue or other key to exit...
Available species:
(0) Bos taurus
(1) Camelus dromedarius
(2) Canis lupus familiaris
(3) Cercocebus atys
(4) Danio rerio
(5) Homo sapiens
(6) Macaca fascicularis
(7) Macaca mulatta
(8) Macaca nemestrina
(9) Mus
(10) Mus cookii
(11) Mus minutoides
(12) Mus musculus
(13) Mus pahari
(14) Mus saxicola
(15) Mus spretus
(16) Oncorhynchus mykiss
(17) Ornithorhynchus anatinus
(18) Oryctolagus cuniculus
(19) Ovis aries
(20) Papio anubis anubis
(21) Rattus norvegicus
(22) Rattus rattus
(23) Sus scrofa
(24) Vicugna pacos
Please select species (e.g. '5' for Homo sapiens): 5
You selected: Homo sapiens.
Please enter a list of common species names for Homo sapiens delimited by ':' to be used in -s option in 'mixcr align ...' (e.g. 'hsa:hs:homosapiens:human'): hsa:hs:homosapiens:human
Getting taxonId for Homo sapiens from NCBI... XPath set is empty
OK. TaxonId=
Creating directory for downloaded files (./imgt_downloads/)
Downloading files:
./imgt_downloads/Homo_sapiens_IGHV.fasta successfully downloaded.
./imgt_downloads/Homo_sapiens_IGHD.fasta successfully downloaded.
./imgt_downloads/Homo_sapiens_IGHJ.fasta successfully downloaded.
./imgt_downloads/Homo_sapiens_IGKV.fasta successfully downloaded.
./imgt_downloads/Homo_sapiens_IGKJ.fasta successfully downloaded.
./imgt_downloads/Homo_sapiens_IGLV.fasta successfully downloaded.
./imgt_downloads/Homo_sapiens_IGLJ.fasta successfully downloaded.
./imgt_downloads/Homo_sapiens_TRAV.fasta successfully downloaded.
./imgt_downloads/Homo_sapiens_TRAJ.fasta successfully downloaded.
./imgt_downloads/Homo_sapiens_TRBV.fasta successfully downloaded.
./imgt_downloads/Homo_sapiens_TRBD.fasta successfully downloaded.
./imgt_downloads/Homo_sapiens_TRBJ.fasta successfully downloaded.
./imgt_downloads/Homo_sapiens_TRDV.fasta successfully downloaded.
./imgt_downloads/Homo_sapiens_TRDD.fasta successfully downloaded.
./imgt_downloads/Homo_sapiens_TRDJ.fasta successfully downloaded.
./imgt_downloads/Homo_sapiens_TRGV.fasta successfully downloaded.
./imgt_downloads/Homo_sapiens_TRGJ.fasta successfully downloaded.
Importing loci:
IGH
/Users/OBricard/Desktop/NGS/tools/mixcr-1.8.2/mixcr importSegments -f -s :hsa:hs:homosapiens:human -l IGH -r report_Homo_sapiens_IGH.txt -v ./imgt_downloads/Homo_sapiens_IGHV.fasta -d ./imgt_downloads/Homo_sapiens_IGHD.fasta -j ./imgt_downloads/Homo_sapiens_IGHJ.fasta
Error: Malformed species name.
IGK
/Users/OBricard/Desktop/NGS/tools/mixcr-1.8.2/mixcr importSegments -f -s :hsa:hs:homosapiens:human -l IGK -r report_Homo_sapiens_IGK.txt -v ./imgt_downloads/Homo_sapiens_IGKV.fasta -j ./imgt_downloads/Homo_sapiens_IGKJ.fasta
Error: Malformed species name.
IGL
/Users/OBricard/Desktop/NGS/tools/mixcr-1.8.2/mixcr importSegments -f -s :hsa:hs:homosapiens:human -l IGL -r report_Homo_sapiens_IGL.txt -v ./imgt_downloads/Homo_sapiens_IGLV.fasta -j ./imgt_downloads/Homo_sapiens_IGLJ.fasta
Error: Malformed species name.
TRA
/Users/OBricard/Desktop/NGS/tools/mixcr-1.8.2/mixcr importSegments -f -s :hsa:hs:homosapiens:human -l TRA -r report_Homo_sapiens_TRA.txt -v ./imgt_downloads/Homo_sapiens_TRAV.fasta -j ./imgt_downloads/Homo_sapiens_TRAJ.fasta
Error: Malformed species name.
TRB
/Users/OBricard/Desktop/NGS/tools/mixcr-1.8.2/mixcr importSegments -f -s :hsa:hs:homosapiens:human -l TRB -r report_Homo_sapiens_TRB.txt -v ./imgt_downloads/Homo_sapiens_TRBV.fasta -d ./imgt_downloads/Homo_sapiens_TRBD.fasta -j ./imgt_downloads/Homo_sapiens_TRBJ.fasta
Error: Malformed species name.
TRG
/Users/OBricard/Desktop/NGS/tools/mixcr-1.8.2/mixcr importSegments -f -s :hsa:hs:homosapiens:human -l TRG -r report_Homo_sapiens_TRG.txt -v ./imgt_downloads/Homo_sapiens_TRGV.fasta -j ./imgt_downloads/Homo_sapiens_TRGJ.fasta
Error: Malformed species name.
TRD
/Users/OBricard/Desktop/NGS/tools/mixcr-1.8.2/mixcr importSegments -f -s :hsa:hs:homosapiens:human -l TRD -r report_Homo_sapiens_TRD.txt -i -v ./imgt_downloads/Homo_sapiens_TRDV.fasta -d ./imgt_downloads/Homo_sapiens_TRDD.fasta -j ./imgt_downloads/Homo_sapiens_TRDJ.fasta
Error: Malformed species name.

Operation executed successfully.
See report*.txt files created in current folder for details.

To use imported segments invoke mixcr with the following parameters:
mixcr align --library local -s hsa ...

**Comment by dbolotin** [comment]
Please, try to run the command once again, looks like some problems with NCBI server to resolve the species name.

**Comment by dbolotin** [comment]
Did this resolve the issue?

**Comment by obricard** [comment]
No I tried to re-run the command several times the last days but I still get the same message.
I tried to run mixcr with human RNAseq data without proper segment importation and it worked pretty well. Are the human reference sequences prepack somewhere in the mixcr zip folder ?

**Comment by dbolotin** [comment]
Hi, sorry for the late response. With new [MiXCR 2.0](https://github.com/milaboratory/mixcr/releases/latest) (just released), there is no more need to import IMGT library. Please see [here](http://mixcr.readthedocs.io/en/latest/importSegments.html).

**Comment by dbolotin** [comment]
Sorry, just noticed the second part of your post. Yes, MiXCR comes with it's own built-in referenced, based on latest genome assembly (see this [repository](https://github.com/repseqio/library)).
