### ISSUE TITLE
Single Read Supported UMIs. 

### ISSUE THREAD

**Issue by bshim181** [milaboratory/mixcr#1288]
During the refiningTagsAndSort step or during the assembly step, is there feature to drop UMIs that are only supported by one read? I wanted to enforce a stronger quality restriction. Thank you.

**Comment by mizraelson** [comment]
During the refineTagsAndSort step, MiXCR automatically sets the threshold based on the distribution.

You can manually adjust it by adding the following parameters to the analyze command:
```
-M refineTagsAndSort.parameters.postFilter=null \
-M assemble.consensusAssemblerParameters.assembler.minRecordsPerConsensus=2 \
```

This will only use UMIs covered by more than two reads.

**Comment by bshim181** [comment]
Hello, in the tagCount list, UMIs with one reads seems to still appear in the exported clone output. Is this an unexpected behavior?

<img width="1267" alt="Screenshot 2023-08-02 at 9 29 07 AM" src="https://github.com/milaboratory/mixcr/assets/53489568/54eaa73c-d4c5-487b-b081-344d1cd3b79b">

**Comment by mizraelson** [comment]
The threshold is applied to all data. Is there a chance that you have the same UMI in other clones?

**Comment by bshim181** [comment]
There is high chance barcode collision at the moment since our UMI is pretty short. 
It was a mistake related to the fact that I turned off the consensusAssembler parameters off because of high probability of barcode colllision. Is there a way to modify the tagCounts list without touching the consensusAssembler params?

**Comment by mizraelson** [comment]
Then it makes sense since these UMIs are most likely covered by more than 1 read with different CDR3s.

**Comment by mizraelson** [comment]
What do you mean by modifying tagCounts list?

**Comment by mizraelson** [comment]
I will close the issue for now. Feel free to reopen if needed.
