### ISSUE TITLE
Question: Can MiXCR analize or align .fasta file sequences?

### ISSUE THREAD

**Issue by gvaleman** [milaboratory/mixcr#1289]
I'm trying to perform B cell sequence alignment (VH region) using MiXCR  (10x genomic sequencing), according to the documentation I've read, it requires raw fastq.gz reads. I have fasta files of the VH region.

Is there a way to perform sequence alignment (or analize) using fasta format sequences?

**Comment by mizraelson** [comment]
Hi,
Could you provide more details about the origin of the FASTA files? While it's technically possible to use FASTA files, there are a couple of points you should keep in mind:

- MiXCR relies heavily on quality scores at many stages of the pipeline.
- The 10x Genomics protocol requires the presence of two reads. The forward read contains the cell and UMI barcodes, while the reverse read carries the payload.

Please share more details so I can provide a more precise answer.

**Comment by gvaleman** [comment]
Hi!
Thank you for your response.

I am using the all_contig_annotations file from the 10x Genomics cellranger vdj pipeline. This file contains the nucleotide sequence of the B cell receptor (VH). As I mentioned, I understand that using the preset for 10x Genomics, MiXCR requires paired reads in fastq.gz format. However, since I have the nucleotide sequences in fasta format, is it possible to use them as input for alignment or analysis in MiXCR?

**Comment by mizraelson** [comment]
Yes, you can use Fasta files for alignment. I would suggest using generic-amplicon preset as there are no barcodes in the data.

**Comment by gvaleman** [comment]
Thank you very much, your prompt response and feedback are very helpful.
Greetings!
