### ISSUE TITLE
How to continue with mixcr output results?

### ISSUE THREAD

**Issue by A-legac45** [milaboratory/mixcr#1290]
Hello, 

I run mixcr on my sample TCR MIXCr bulk from milaboratories and I got my different clones_trad.tsv or clones_trb.tsv files

Is there any king of filtering, QC to apply on this files

targetquelities colomn [[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[ or some like that NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN ( 1 uniqueMoleculeCount)

minQualCDR3

refPoints

the qc files graph are the following 
[chainUsage.pdf](https://github.com/milaboratory/mixcr/files/12249204/chainUsage.pdf)
[alignQc.pdf](https://github.com/milaboratory/mixcr/files/12249206/alignQc.pdf)

Thanks for your output

**Comment by mizraelson** [comment]
Your plots appear to be in good shape. The 'analyze' command incorporates all the filtering and correction steps. Unless something seems off, there shouldn't be a need for further filtering.

In addition, could you please share the tags qc plot? You can do this using the `mixcr exportQc tags input.clns output.pdf` command.

**Comment by A-legac45** [comment]
[output.pdf](https://github.com/milaboratory/mixcr/files/12249330/output.pdf)
yes of course here it is. 

Should I consider the chain with 1 uniqueMoleculeCount which have NNNN

<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:////Users/alegac/Library/Group%20Containers/UBF8T346G9.Office/TemporaryItems/msohtmlclip/clip.htm">
<link rel=File-List
href="file:////Users/alegac/Library/Group%20Containers/UBF8T346G9.Office/TemporaryItems/msohtmlclip/clip_filelist.xml">
<style>

</style>
</head>

<body link="#0563C1" vlink="#954F72">



readCount | readFraction | uniqueMoleculeCount | uniqueMoleculeFraction
-- | -- | -- | --
5036783.0 | 0.129100372571994 | 17540 | 0.06278771737651868



</body>

</html>
 <html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:////Users/alegac/Library/Group%20Containers/UBF8T346G9.Office/TemporaryItems/msohtmlclip/clip.htm">
<link rel=File-List
href="file:////Users/alegac/Library/Group%20Containers/UBF8T346G9.Office/TemporaryItems/msohtmlclip/clip_filelist.xml">
<style>

</style>
</head>

<body link="#0563C1" vlink="#954F72">



2182.0 | 5.592796293826653E-5 | 1 | 3.5796874216943377E-6
-- | -- | -- | --




</body>

</html>
I would like to compare my bulck with my sc10x output can I just merge them by the cdr3 nt chain

**Comment by mizraelson** [comment]
The plots seem to be in decent shape. There may be some room for improvement in a few samples. The goal is to set a threshold between the two peaks on the plot. But for now, I would recommend proceeding with the analysis.

To compare the samples, you could merge the CDR3s since you wouldn't anticipate any hypermutations in T cells. However, keep in mind that the 10x preset assumes assembly by the longest possible feature. This means that in some rare cases (allelic variations or mutations) two clones may carry an identical CDR3 sequence.

**Comment by mizraelson** [comment]
The quality score for 'N' is actually quite high. According to the table, this UMI is supported by 2128 reads, which is a very substantial number.

**Comment by A-legac45** [comment]
Thanks a lot for your advice

**Comment by A-legac45** [comment]
Just for later could you let me know which sample and how to perform the improvement you are speaking about. For those sample I run the following command pkgs/mixcr-4.4.1-0/bin/mixcr -Xmx15g analyze milab-human-rna-tcr-umi-multiplex

**Comment by mizraelson** [comment]
You can add the following parameters:
```
-MrefineTagsAndSort.parameters.postFilter=null \
-Massemble.consensusAssemblerParameters.assembler.minRecordsPerConsensus=15 \
```
Where, 15 is the Reads/UMI threshold for correction. You may try to move it a bit to the right (red line on the tags QC plots that you have shared), but after giving it a second look, I wouldn't change it.

**Comment by A-legac45** [comment]
ok thanks but just one more question In my clones_trad.tsv files I have 

<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:////Users/alegac/Library/Group%20Containers/UBF8T346G9.Office/TemporaryItems/msohtmlclip/clip.htm">
<link rel=File-List
href="file:////Users/alegac/Library/Group%20Containers/UBF8T346G9.Office/TemporaryItems/msohtmlclip/clip_filelist.xml">
<style>

</style>
</head>

<body link="#0563C1" vlink="#954F72">



cloneId | readCount | readFraction | uniqueMoleculeCount | uniqueMoleculeFraction | targetSequences | targetQualities | allVHitsWithScore
-- | -- | -- | -- | -- | -- | -- | --




</body>

</html>

<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:////Users/alegac/Library/Group%20Containers/UBF8T346G9.Office/TemporaryItems/msohtmlclip/clip.htm">
<link rel=File-List
href="file:////Users/alegac/Library/Group%20Containers/UBF8T346G9.Office/TemporaryItems/msohtmlclip/clip_filelist.xml">
<style>

</style>
</head>

<body link="#0563C1" vlink="#954F72">



94146 | 2.0 | 3.3840061749991076E-8 | 1 | 3.633945410872038E-6 | TGTGCAGGCTTCGATCAAACTGGGGCAAACAGCCTCTTCTTT | NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN | TRAV27*00(511)
-- | -- | -- | -- | -- | -- | -- | --
101666 | 2.0 | 3.3840061749991076E-8 | 1 | 3.633945410872038E-6 | TGTGCAATGAGCGACACTAACTTTGGAAATGAGAAATTAACCTTT | LNNNNNNNLNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN | TRAV12-3*00(620)
109965 | 2.0 | 3.3840061749991076E-8 | 1 | 3.633945410872038E-6 | TGCATCGTCCTTTTTGGAAATGAGAAATTAACCTTT | NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNMN | TRAV26-1*00(555)
112200 | 2.0 | 3.3840061749991076E-8 | 1 | 3.633945410872038E-6 | TGCAGCTATAAATTGATCTTC | NNNNNNNNNNNNNNNNNNNNN | TRAV19*00(480)
36069 | 1.0 | 1.6920030874995538E-8 | 1 | 3.633945410872038E-6 | TGTGTGGTGAACATGGATGGCCAGAAGCTGCTCTTT | FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF | TRAV12-1*00(670)
38250 | 1.0 | 1.6920030874995538E-8 | 1 | 3.633945410872038E-6 | TGTGCTTTCATGAAGATGAGTAATTATGGAGGAAGCCAAGGAAATCTCATCTTT | FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF | TRAV38-1*00(600)
39525 | 1.0 | 1.6920030874995538E-8 | 1 | 3.633945410872038E-6 | TGTGCTTATGAAGAGGGTAATGCAGGCAACATGCTCACCTTT | FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF | TRAV38-2DV8*00(540)
43912 | 1.0 | 1.6920030874995538E-8 | 1 | 3.633945410872038E-6 | TGTGCTCTGAGTCCCAGAAACAGTGCCAGACTCATGTTT | FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF | TRAV9-2*00(510)
45086 | 1.0 | 1.6920030874995538E-8 | 1 | 3.633945410872038E-6 | TGTGCTCTGAGTGATCACGACGGATCTGAAAAGCTGGTCTTT | FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF | TRAV9-2*00(570)



</body>

</html>


<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:////Users/alegac/Library/Group%20Containers/UBF8T346G9.Office/TemporaryItems/msohtmlclip/clip.htm">
<link rel=File-List
href="file:////Users/alegac/Library/Group%20Containers/UBF8T346G9.Office/TemporaryItems/msohtmlclip/clip_filelist.xml">
<style>

</style>
</head>

<body link="#0563C1" vlink="#954F72">



112813 | 10.0 | 1.6920030874995539E-7 | 1 | 3.633945410872038E-6 | AAGACCAGTTCTATTTT | NNNNNNNNNNNNNNNNN | TRAV27*00(460) | TRAJ49*00(447,1) | TRAC*00(155,6) | 338\|338\|368\|0\|0\|\|0.0 | 31\|45\|76\|3\|17\|\|140.0 | AAGACCAGTTCTATTTT | 45 | KTS_YF | :::::::::0:-10:0:::::3:-11:17:::
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
23033 | 9.0 | 1.5228027787495985E-7 | 2 | 7.267890821744076E-6 | TGTGCCGTCTTAGCATCAGGAGGAAGCTACATACCTACATTT | [[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[ | TRAV12-2*00(597,6) | TRAJ6*00(600,4) | TRAC*00(60,4) | 350\|358\|383\|0\|8\|\|80.0 | 21\|51\|82\|12\|42\|\|300.0 | TGTGCCGTCTTAGCATCAGGAGGAAGCTACATACCTACATTT | 58 | CAVLASGGSYIPTF | :::::::::0:-5:8:::::12:-1:42:::



</body>

</html>

Should I delete all the lines which are below 10 reads?

**Comment by mizraelson** [comment]
Certainly not, those a perfectly valid results.

**Comment by mizraelson** [comment]
Of course these don't contribute to the top abundant clonotypes, but I wouldn't cut it.
