### ISSUE TITLE
exom-full-length or exome-seq in capture-based NGS data with mixcr-4.4.1?

### ISSUE THREAD

**Issue by xmy1990** [milaboratory/mixcr#1292]
## Checklist before submitting the issue:

 - [ ] The issue is strongly related to the MiXCR software
 - [ ] The issue can be reproduced with [the most recent version](https://github.com/milaboratory/mixcr/releases) of MiXCR
 - [ ] There is no answer to the question in the [official documentation](http://mixcr.readthedocs.io/) and there is no duplicate issue in the [bug tracker](https://github.com/milaboratory/mixcr/issues?utf8=✓&q=)  
 - [ ] Inspection of raw alignments with [exportAlignmentsPretty](http://mixcr.readthedocs.io/en/master/export.html#exporting-well-formatted-alignments-for-manual-inspection) shows that data has the expected architecture, and sample preparation artefacts are not the reason of the problem (if this is the matter of the issue)

## Expected Result

*A description of what you wanted to happen*

## Actual Result

*A description of what actually happened*

## Exact MiXCR commands 

*Paste here __exact__ MiXCR commands you used (enclose it with single `` ` ``  for better formatting)*

## MiXCR report files 

*Paste here content of the report files produced by MiXCR (enclose it with triple ```` ``` ````  for better formatting)*

Thank you very much at first!

With capture-based NGS data, what should I use :

mixcr analyze exom-full-length(https://vdj.online/) ?
or
mixcr analyze exome-seq (https://mixcr.com/mixcr/reference/overview-built-in-presets/#exome-data) ?

**Comment by mizraelson** [comment]
Hi. The 'exom-full-length' preset was deprecated in the latest version. I suggest using 'exome-seq'. The difference between the two is that the full-length preset filters out all clone sequences that do not cover the full VDJRegion, while 'exome-seq' does not filter anything but provides the longest possible contig for every clone. To mimic the behavior of the deprecated preset, you can add the following parameter if needed:

`--assemble-contigs-by VDJRegion`

**Comment by xmy1990** [comment]
Thanks for your kind answer @mizraelson.

 But I have a new issue,  all readCount in the *.tsv result file are very small (from 1 to 3), is that right ?
 
My data is capture-based NGS data  based on exome-seq.

My mixcr-4.4.1 script is :
mixcr analyze exome-seq \
    --species hsa \
      test.bam \
      test

ref from here: https://mixcr.com/mixcr/reference/overview-built-in-presets/#exome-data
Any misused analysis settings ?

**Comment by mizraelson** [comment]
If your data is from a bulk, non-enriched exome-seq, then it's quite reasonable that only a small number of reads would align to the TCR/BCR reference (and every clone is covered by only a few reads). This is consistent with the nature of exome sequencing, where only specific regions of the genome are targeted, and the TCR/BCR segments may not be the primary focus.
