### ISSUE TITLE
MiXCR supports detection of incomplete/special recombinations?

### ISSUE THREAD

**Issue by linxianzu1995** [milaboratory/mixcr#1295]
![image](https://github.com/milaboratory/mixcr/assets/43058344/dc3be335-c862-4cc0-bc94-28aa011e02df)
URL: https://www.vidjil.org/doc/libraries-recombinations/#analyzed-human-immune-recombinations-in-vidjil
Hi， vidjil supports incomplete/special recombinations, such as IGH+(Dh-Jh)。I want to try to use MiXCR to analyzeincomplete/special recombinations, but I don't know if MiXCR supports it, so I want to check if MiXCR supports the analysis of incomplete/special recombinations.

**Comment by mizraelson** [comment]
Hi, 
We are actively working on implementing this feature, and it will be available soon.

**Comment by linxianzu1995** [comment]
Hi, when are this feature expected to be available?

**Comment by linxianzu1995** [comment]
> Hi, We are actively working on implementing this feature, and it will be available soon.

Hi, when are this feature expected to be available?

**Comment by mizraelson** [comment]
Hi,
Can you please contact our support on [support@milaboratories.com](mailto:support@milaboratories.com)
