### ISSUE TITLE
mixcr downsample error: "Require clnx file type, got ./clns"

### ISSUE THREAD

**Issue by jvpon** [milaboratory/mixcr#1299]
Dear mixcr people,

After running
`mixcr analyze takara-mouse-tcr-cdr3`
I have only .clns files, which I link to the folder ./clns

I'd like to obtain normalized read counts for clonotypes.

I am trying to run
`mixcr downsample \
     --chains TRA,TRB \
     --downsampling count-reads-auto \
     --only-productive \
     --summary summary.tsv \
     ./clns
`
and get an error
`Require clnx file type, got ./clns`

Thanks,

Julia

**Comment by mizraelson** [comment]
Hi,
if you have `.clns` files in the `clns` folder the command should be:

```
mixcr downsample \ 
--chains TRA,TRB \ 
--downsampling count-reads-auto \
--only-productive \
--summary summary.tsv \
 ./clns/*.clns 
```
