### ISSUE TITLE
Secure File Transfer

### ISSUE THREAD

**Issue by bshim181** [milaboratory/mixcr#1306]
Hello, 

This is regarding the rhTCR protocol. We have prepared a mouse single cell and bulk dataset which you guys can reference to build   the preset. We were wondering what would be the most convenient way to transfer the data over. Thank you.

**Comment by mizraelson** [comment]
Hi,

Please write to our support email: [support@milaboratories.com](mailto:support@milaboratories.com). We can prepare a dedicated secured SFTP server for you to upload the data, or you can share it in some other way that you prefer.

Best regards,
Mark
