### ISSUE TITLE
ERROR: Sample tag does not work without sample table

### ISSUE THREAD

**Issue by ElisaRosatiScalchi** [milaboratory/mixcr#1333]
We have multiple samples from the same patient in different fastq files. We want to run them all together and obtain the sample tag in the output clonotype table. 

## Expected Result

I aim at obtaining a clonotype table with a tag column indicating the original sample.

## Actual Result

Error: "Sample tag does not work without sample table"
But also with sample table I do not manage to make it work. In the documentation there is this example:
``
mixcr analyze rnaseq-cdr3 sample{{SAMPLE0:n}}_{{R}}.fastq.gz
``
where the sample tag is provided without sample table. 
How is the SAMPLE tag supposed to work? Should it work without the sample table? 
And if the sample table is necessary is it possible to get a template? As the only example provided includes several plates which is not applicable to our case.

## Exact MiXCR commands 

Version in use: MiXCR v4.3.2

`MIXCR="/softwares/mixcr/mixcr -Xmx50g"`
`FASTQ_DIR='test_mixcr'`
`fastq_input=${FASTQ_DIR}/{{SAMPLE0:a}}_S{{n}}_{{R}}_001.fastq.gz`
`output_folder='clonotype_tables'`
`#RUN MIXCR`
`$MIXCR analyze takara-human-tcr-V2-full-length --threads 16 $fastq_input $output_folder`

**Comment by mizraelson** [comment]
Hi, 
There are two options:

1) Add the `--infer-sample-table` and `--split-by-sample` parameters. With these, samples will be processed concurrently, but separate output files will be generated for each sample.
```
mixcr analyze takara-human-tcr-V2-full-length \
	--infer-sample-table \
	--split-by-sample \
	{{SMPL:a}}_{{R}}.fastq.gz \
	out 
```

2)  If you prefer a single clonotype table that consolidates all clones from all samples, you'll need to modify the preset to incorporate the SMPL tag. While we plan to streamline this process in our upcoming update, I've attached a modified preset file for your convenience. Extract the .yaml file from the zipped folder and place it in the directory from which you'll be running `mixcr`. Alternatively, you can also move it to `~/.mixcr/presets/`.

Subsequently, execute:
```
mixcr analyze local:takara-human-tcr-V2-full-length-multiplex \
	--infer-sample-table \
	--dont-split-by-sample \
	--prepend-export-clones-field -tags Sample \
	{{SMPL:a}}_{{R}}.fastq.gz \
	out 
```

This will produce a single clonotype table for each chain, inclusive of a SMPL column.

For further insights, consider the [exportClonesOverlap](https://mixcr.com/mixcr/reference/mixcr-exportClonesOverlap/) function. This returns a table showcasing all clones along with their occurrence count across each sample (.clns) file.

I also advise updating MiXCR to its latest version for optimal results.

Sincerely,
Mark

[takara-human-tcr-V2-full-length-multiplex.yaml.zip](https://github.com/milaboratory/mixcr/files/12527892/takara-human-tcr-V2-full-length-multiplex.yaml.zip)

**Comment by ElisaRosatiScalchi** [comment]
Hi @mizraelson,

thanks for your answer. Your option 1 is working good indeed. 
One further question would be if the  _--split-by-sample_ option does influence the sample count of MIXCR license. Meaning if I run 4 samples from the same patient together and use  _--split-by-sample_ does that count as 1 MIXCR sample or 4 for licensing purposes?

**Comment by mizraelson** [comment]
Hi Elisa,

The option `--split-by-sample` does not affect the sample count. If you have sample tags, then regardless of whether this option is used, samples will be counted by the number of sample tag values. To process such data as a single sample, you would need to remove the sample tag entirely. However, by doing so, you will not be able to identify which data came from which sample. If you have any further questions related to this, please feel free to contact us at [support@milaboratories.com](mailto:support@milaboratories.com).

Sincerely,
Mark
