### ISSUE TITLE
mixcr align tissue

### ISSUE THREAD

**Issue by jiepan1** [milaboratory/mixcr#1402]
TRAV14DV4*00
TRAV12-3*00
TRAV26-1*00
TRAV2*00
TRAV12-3*00
TRAV14DV4*00
TRAV14DV4*00
TRAV2*00
TRAV26-2*00
TRAV3*00
TRAV26-2*00
TRAV12-1*00
TRAV35*00
TRAV39*00
TRAV9-2*00
TRAV14DV4*00
TRAV27*00
TRAV14DV4*00
TRAV19*00
TRAV16*00
TRAV27*00
TRAV12-2*00
TRAV17*00
TRAV19*00
TRAV19*00
TRAV3*00
TRAV14DV4*00

These are mixcr results' TRA genes，why ?  The correct TRAV genes is  [TRAV1-1*01]

**Comment by mizraelson** [comment]
Hi,
Can you please provide more information: What command did you use, what data you applied it to, what read sequence you refer to?

Sincerely,
Mark

**Comment by jiepan1** [comment]
The command would be:
mixcr align -p irepertoire-human-rna-repseq-plus \
 -s hsa \
 -OvParameters.geneFeatureToAlign=VTranscript \
-t 60 \
-OsaveOriginalReads=true\
/home/panjie/projects/center/xiatian/20231023/CP2020112300069/H101SC23101467/RSHD01204/X101SC23101467-Z01/X101SC23101467-Z01-J001/00.CleanData/20231009-PaTCR/20231009-PaTCR_2.clean.fq.gz  2.vdjca

mixcr exportAlignments -readIds -descrR1 ./2.vdjca -f ./id_2.tsv

Thank you in advance.

**Comment by mizraelson** [comment]
What target sequence do you see in the alignments that raises concerns?

**Comment by jiepan1** [comment]
Sorry, I can't understand what you mean.
I run this command:
mixcr align -p irepertoire-human-rna-repseq-plus\
                                                                     -s hsa\
-OvParameters.geneFeatureToAlign=VTranscript\
                                                                     -t 60 \
                                     -OsaveOriginalReads=true\
/home/panjie/projects/center/xiatian/20231023/CP2020112300069/H101SC23101467/RSHD01204/X101SC23101467-Z01/X101SC23101467-Z01-J001/00.CleanData/20231009-PaTCR/20231009-PaTCR_2.clean.fq.gz 2.vdjca

mixcr exportAlignments -readIds -descrR1 ./2.vdjca -f ./id_2.tsv


But the following results were obtained:
#################################
allVHitsWithScore | allJHitsWithScore | aaSeqCDR3
-- | -- | --
TRAV14DV4*00 | TRAJ38*00 | CAMRGGSGNNRKLIW
TRAV2*00 | TRAJ31*00 | CAVAEGRLMF
TRAV26-1*00 | TRAJ50*00 | CIVRKTSYDKVIF
TRAV12-3*00 | TRAJ34*00 | CAMSAYNTDKLIF
TRAV26-2*00 | TRAJ39*00 | CILRGYNNAGNMLTF
TRAV14DV4*00 | TRAJ58*00 | CAMSQETSGSRLTF
TRAV35*00 | TRAJ38*00 | CAGLYNAGNNRKLIW
TRAV26-2*00 | TRAJ32*00 | CILRGYGGATNKLIF
TRAV9-2*00 | TRAJ3*00 | CALSSASKIIF
TRAV39*00 | TRAJ42*00 | CAGPNYGGSQGNLIF
TRAV26-1*00 | TRAJ49*00 | CIVRPPNTGNQFYF
TRAV16*00 | TRAJ11*00 | CALRNSGYSTLTF
TRAV27*00 | TRAJ37*00 | CAGYGSSNTGKLIF
TRAV8-4*00 | TRAJ10*00 | CAVSEGGGNKLTF
TRAV2*00 | TRAJ20*00 | CAVEGYDYKLSF
TRAV35*00 | TRAJ37*00 | CAGHGSSNTGKLIF
TRAV12-1*00 | TRAJ43*00 | CVVNLVRF
TRAV26-1*00 | TRAJ31*00 | CIVRNNNARLMF
######################################
So What I'm wondering is why the name of the V gene is in the form of *00, The correct V gene name form is TRAV8-4*01.

**Comment by mizraelson** [comment]
Is your question related to allele number? Like, why all alleles are *00 and not *01/*02/...?

**Comment by jiepan1** [comment]
Yes, Thanks
now, my question is how use IMGT reference instead of MiXCR build-in reference to see allelic variants?

**Comment by mizraelson** [comment]
Due to a number of reasons discussed [here](https://github.com/milaboratory/mixcr/discussions/1311) MiXCR employs a distinct and more accurate method to infer allelic variants using a dedicated [`mixcr findAlleles`](https://mixcr.com/mixcr/reference/mixcr-findAlleles/) command.

#1311

**Comment by jiepan1** [comment]
thank you! that clarifies a lot. I'll close this issue now.
