### ISSUE TITLE
No preset with name "kAligner2".

### ISSUE THREAD

**Issue by Angieiscute** [milaboratory/mixcr#1417]
Hi,

App version: 4.5.0;

When I employ the following command:
`mixcr align --rna --preset generic-bcr-amplicon --species hsa
`
A warning is raised:
```
WARNING: Preset generic-bcr-amplicon is deprecated. The preset is deprecated. Please use generic-amplicon.
```
Subsequently, I attempted to utilize:

`mixcr align --rna --preset generic-amplicon --preset kAligner2 --species hsa
`

This resulted in an error:
```
option '--preset' (<preset>) should be specified only once.
```

Hence, if I want to apply kAligner2 for BCR analysis, what are the correct options to use?

Thanks!

**Comment by mizraelson** [comment]
We have updated our `kAligner2` to accommodate both TCR and BCR data. As a result, we have replaced `generic-bcr-amplicon` and `generic-tcr-amplicon` with `generic-amplicon`. So there is no need to specify `kAligner2` separately.
