### ISSUE TITLE
exportAirr clone_id

### ISSUE THREAD

**Issue by Januaryyiyue** [milaboratory/mixcr#1419]
## Checklist before submitting the issue:

 - [x] The issue is strongly related to the MiXCR software
 - [ ] The issue can be reproduced with [the most recent version](https://github.com/milaboratory/mixcr/releases) of MiXCR
 - [x] There is no answer to the question in the [official documentation](http://mixcr.readthedocs.io/) and there is no duplicate issue in the [bug tracker](https://github.com/milaboratory/mixcr/issues?utf8=✓&q=)  
 - [x] Inspection of raw alignments with [exportAlignmentsPretty](http://mixcr.readthedocs.io/en/master/export.html#exporting-well-formatted-alignments-for-manual-inspection) shows that data has the expected architecture, and sample preparation artefacts are not the reason of the problem (if this is the matter of the issue)

## Expected Result

While using MiXCR exportAirr, I want to specify which fields to get, for example the clond_id field. But I do not know how to specify it.

## Actual Result

There is no field called clone_id in the output

## Exact MiXCR commands 

```
mixcr exportAirr --target -1 /path/to/assembly/file.clns /path/to/result/file.tsv
```

**Comment by mizraelson** [comment]
Hi,
Currently we support only a fixed set of columns for AIRR export. We will add `clone_id` field upon your request in the upcoming release.

**Comment by mizraelson** [comment]
The field has been added in the latest develop version #1433.
