### ISSUE TITLE
Low alignment rate when using fastq generated from bamtofastq

### ISSUE THREAD

**Issue by malonzm1** [milaboratory/mixcr#1427]
Hi,

I had to use cellranger's bamtofastq function for some bam files. Then I used the resulting fastq files for clonotype detection with mixcr. I noticed that the alignment rate was very low (from less than 1% to around 3%). Any thoughts?

Thanks and good day.

**Comment by mizraelson** [comment]
Its hard to say without knowing the wet-lab details. What cells were used for the sample preparation ? If it is a 10x data - what kit was used? 5' 10x VDJ end? What command did you use for MiXCR analysis? Can you share the report files generated by MiXCR?
