### ISSUE TITLE
alpha and beta chain dimers from mixcr

### ISSUE THREAD

**Issue by malonzm1** [milaboratory/mixcr#1442]
Hi,

I've used mixcr with many samples from a huge scRNAseq dataset. In each case, for TCRs, I only get either alpha or beta chain in a cell and never both as a dimer. Any thoughts?

Thanks and good day.

Br,

**Comment by mizraelson** [comment]
Hi,

It's impossible to provide a definitive answer without knowing specific details about your experimental protocol, the MiXCR commands you've used, the reports you've obtained, and without a closer examination of the raw data. The effectiveness and outcomes of T-cell receptor (TCR) analysis in single-cell RNA sequencing (scRNA-seq) data can vary significantly based on various factors.

To better understand and address the issue you're experiencing, please provide more information about the following:

1) Experimental Protocol: Describe the scRNA-seq protocol you used, including any details about cell isolation, library preparation, and sequencing technologies.

2) MiXCR Commands: Share the specific MiXCR commands or parameters you employed for TCR analysis.

3) Reports: Provide any relevant reports or output generated by MiXCR during your analysis.

4) Raw Data: If possible, share a sample of the raw data or data processing steps to help identify potential issues.

Best regards
