### ISSUE TITLE
QC ALERT 

### ISSUE THREAD

**Issue by drosop** [milaboratory/mixcr#1446]
Dear MiXCR team,

I have run the mouse BCR sequencing using Takara SMARTer® Mouse BCR IgG H/K/L Profiling Kit and did analysis using the MiXCR preset mixcr analyze takara-mouse-rna-bcr-smarter using MiXCR v4.5.0. Also, There was very low adaptor content, so I didnt do trimming before.

In the output, I have alerts for :

   Successfully aligned reads:                                     97.67% [OK]
   Off target (non TCR/IG) reads:                                 1.8%   [OK]
   Reads with no V or J hits:                                          0.49%  [OK]
   **Overlapped paired-end reads:                                  32.07% [ALERT]
   Reads used in clonotypes:                                         19.68% [ALERT]
   Alignments that do not cover VDJRegion:                68.03% [ALERT]**
   Alignments dropped due to low sequence quality:   0.0%   [OK]
   Clones dropped in post-filtering:                                0.0%   [OK]
   Alignments dropped in clones post-filtering:             0.0%   [OK]

However, the alignment rate is good. Is this report fine? What can be the reason for low number of reads used in clonotypes or VDJ regions? 

Thank you,

**Comment by MiLaboratoriesSupport** [comment]
​Hi,  
My guess is that you used a shorter reads' length (150+150?) which was not enough to cover the whole VDJRegion. By default MiXCR tries to assemble the full-length receptor sequence for this protocol. If that is the case, you may add `--assemble-clonotypes-by CDR3` parameter, to assemble clones by CDR3 region only.  ​   

Sincerely,
Mark
