### ISSUE TITLE
picocli.CommandLine$ExecutionException: Error while running command refineTagsAndSort java.lang.IllegalStateException: Check failed.

### ISSUE THREAD

**Issue by malonzm1** [milaboratory/mixcr#1450]
Hi,

Any ideas what could cause this error `picocli.CommandLine$ExecutionException: Error while running command refineTagsAndSort java.lang.IllegalStateException: Check failed.`?

[mixcr2_GSE125527_1.txt](https://github.com/milaboratory/mixcr/files/13496924/mixcr2_GSE125527_1.txt)

The command used was: `'mixcr -Xmx1000g analyze 10x-sc-xcr-vdj -s hsa --rna --threads 4 --force-overwrite %s %s %s/%s'%(infile1,infile2,outdir,srr)`.

Thanks and good day.

**Comment by dbolotin** [comment]
Hi! Thanks for reporting! We isolated the problem and will fix it today. It will be published with the new release next week. We will post a pre-release version here. For this rare situation to emerge your data most probably should consist exclusively from some unusual sequence: very short or consisting from only one nucleotide, like `AAAAAAA...`.

**Comment by malonzm1** [comment]
Thanks!

**Comment by mizraelson** [comment]
The issue has been resolved in the latest [develop version](https://link.milaboratory.com/software/mixcr/mixcr-develop.zip).
