### ISSUE TITLE
Question about UMI information in the output files vdjca and clns

### ISSUE THREAD

**Issue by silvia1234567890** [milaboratory/mixcr#1468]
Hello,

for the alignment, I ran this code:

```
mixcr align --preset generic-amplicon \
> --library Scophthalmus_maximus-IGH.json \
> --species Scophthalmus_maximus \
> --rna \
> --rigid-left-alignment-boundary \
> --rigid-right-alignment-boundary C \
> -OsaveOriginalReads=true \
> seqs.fasta \
> alignments.vdjca
```
for the clonotype:
`mixcr assemble alignments.vdjca clones.clns`

and to export:
```
mixcr exportAlignments alignments.vdjca alignments.tsv
mixcr exportClones clones.clns clones.tsv
```

In my clonotype table there is no "UMI count" column, and when I want to check the barcode coverage statistics with:
`mixcr exportQc tags clones.clns tags.pdf`
it gives me this message in the terminal:
`No tag refinement report for clones.clns; did you run refineTagsAndSort command?`

My question is: is there any parameter i forgot to put in the mixcr align code to get this information?

Thank you in advance!

**Comment by mizraelson** [comment]
Hi,

The commands you used do not include UMI parsing and processing, which is why that information is not appearing in the output. Could you please share the library structure and the protocol used for your data so I can assist you with the appropriate set of commands.

Sincerely,
Mark
