### ISSUE TITLE
ERROR: File lock safeguard was triggered. Please report this error to support@milaboratories.com.

### ISSUE THREAD

**Issue by jingjing578** [milaboratory/mixcr#1493]
hi,
 When I run the mixcr , ERROR: File lock safeguard was triggered. Please report this error to support@milaboratories.com. occurred. How can I solve it 
Thank you

**Comment by mizraelson** [comment]
Hi,
Can you please share the MiXCR version and the command used.

**Comment by jingjing578** [comment]
> Hi, Can you please share the MiXCR version and the command used.

Hello, I have found the reason, it is a network problem, thank you

**Comment by EdGreen21** [comment]
@jingjing578 can you elaborate on the solution? What kind of network error, and how did you fix it?
