### ISSUE TITLE
exportClones error with Imputed

### ISSUE THREAD

**Issue by Angieiscute** [milaboratory/mixcr#1496]
Hi, 
I'm using the following command: 
` mixcr  exportClones -o -t --chains TRB -nFeatureImputed V5UTRGermline -nFeatureImputed L1 -nFeatureImputed L2 alignment.clns result.tsv`
However, it results in an error message as follows:

> Exporting clones: 0%
> Exporting clones: 11.8%  ETA: 00:00:07
> Exporting clones: 29.9%  ETA: 00:00:03
> java.lang.AssertionError: 
> [{false 0 123 150}, {true 1 47 51}, {false 1 0 2}]
> [{false 0 123 150}, {true 0 47 51}]
> 91441
>         at com.milaboratory.o.jO.m(SourceFile:588)
>         at com.milaboratory.o.BB.a(SourceFile:98)
>         at com.milaboratory.o.BB.a(SourceFile:105)
>         at com.milaboratory.o.jO.j(SourceFile:372)
>         at com.milaboratory.o.rB.invoke(SourceFile:1370)
>         at com.milaboratory.o.kQ.extractValue(SourceFile:55)
>         at com.milaboratory.mixcr.export.FieldWithParameters$create$2.invoke(SourceFile:316)
>         at com.milaboratory.mixcr.export.FieldWithParameters$create$2.invoke(SourceFile:315)
>         at com.milaboratory.o.kW.a(SourceFile:25)
>         at com.milaboratory.o.lv.put(SourceFile:40)
>         at com.milaboratory.mixcr.cli.CommandExportClones$Cmd$ExportClones.run(SourceFile:368)
>         at com.milaboratory.mixcr.cli.CommandExportClones$Cmd.run1$runExport(SourceFile:285)
>         at com.milaboratory.mixcr.cli.CommandExportClones$Cmd.run1(SourceFile:332)
>         at com.milaboratory.mixcr.cli.MiXCRCommandWithOutputs.run0(SourceFile:69)
>         at com.milaboratory.mixcr.cli.MiXCRCommand.run(SourceFile:37)
>         at picocli.CommandLine.executeUserObject(CommandLine.java:1939)
>         at picocli.CommandLine.access$1300(CommandLine.java:145)
>         at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2358)
>         at picocli.CommandLine$RunLast.handle(CommandLine.java:2352)
>         at picocli.CommandLine$RunLast.handle(CommandLine.java:2314)
>         at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2179)
>         at picocli.CommandLine$RunLast.execute(CommandLine.java:2316)
>         at com.milaboratory.mixcr.cli.Main.registerLogger$lambda-26(SourceFile:447)
>         at picocli.CommandLine.execute(CommandLine.java:2078)
>         at com.milaboratory.mixcr.cli.Main.main(SourceFile:98)

However, when I omit the export of the imputed L1 part (by excluding the `-nFeatureImputed L1` option), the export is successful. 

Do you have any insights into what might be causing this issue with this sample data? BTW, it's mouse data, if I use the human library to analyze the is no problem. 

Thanks!

Best,

Angie

**Comment by mizraelson** [comment]
Could you please specify the MiXCR version you used and the commands executed before `exportClones`? It's important to note that to successfully export a particular feature, it needs to be included in the clonotype assembly feature and must be at least partially covered.

I tested your command on 5'RACE data using MiXCR 4.6, employing the `--assemble-clonotypes-by VDJTranscript` option in the `mixcr analyze` command, and it functioned as expected.

Sincerely,
Mark

**Comment by mizraelson** [comment]
I will close the issue for now, feel free to reopen.
