### ISSUE TITLE
findAlleles with 10x single cell data

### ISSUE THREAD

**Issue by xiachenrui** [milaboratory/mixcr#1503]
## Checklist before submitting the issue:

 - [x] The issue is strongly related to the MiXCR software
 - [x] The issue can be reproduced with [the most recent version](https://github.com/milaboratory/mixcr/releases) of MiXCR
 - [x] There is no answer to the question in the [official documentation](http://mixcr.readthedocs.io/) and there is no duplicate issue in the [bug tracker](https://github.com/milaboratory/mixcr/issues?utf8=✓&q=)  
 - [x] Inspection of raw alignments with [exportAlignmentsPretty](http://mixcr.readthedocs.io/en/master/export.html#exporting-well-formatted-alignments-for-manual-inspection) shows that data has the expected architecture, and sample preparation artefacts are not the reason of the problem (if this is the matter of the issue)

## Expected Result

I follow your tutorial on B cell lineage at https://mixcr.com/mixcr/guides/b-cell-lineages-webinar/#quality-control using my 10x single cell VDJ seq data. I could run `mixcr analyze 10x-sc-xcr-vdj`. But  I can not run `findAlleles` function successfully.  

## Actual Result

Not sure

## Exact MiXCR commands 

```
mixcr findAlleles \               
    --report mixcr_CZC_bcr/DCh.findAlleles.report.txt \
    --export-alleles-mutations mixcr_CZC_bcr/DCh_alleles.tsv \
    --export-library mixcr_CZC_bcr/DCh_alleles.json \
    --output-template {file_dir_path}/{file_name}.reassigned.clns \
    mixcr_CZC_bcr/*.clns
```

## MiXCR report files 
```
App version: 4.6.0; built=Sat Dec 09 19:48:42 UTC 2023; rev=c9fafa41fe; lib=repseqio.v4.0
Some of the inputs were processed by `assembleContigs` or `analyze` without `--assemble-contigs-by` option: mixcr_CZC_bcr/mixcr_CZC_bcr.contigs.clns, mixcr_CZC_bcr/mixcr_CZC_bcr.grouped.clns
```

**Comment by mizraelson** [comment]
Please add `--assemble-contigs-by VDJRegion` to your `mixcr analyze` command. 

This will fix the error.
