### ISSUE TITLE
Need help with converting old codes to newer version

### ISSUE THREAD

**Issue by wwang86** [milaboratory/mixcr#1505]
Hi, I am really new to MiXCR and have no experience with bio-informatic analysis. I have a code from our previous lab member which was used for ver 3.0.13. I want to see if anyone can help me update the code to be used on ver 4.6.0. 

`mixcr analyze amplicon -s mmu --starting-material rna --5-end v-primers --3-end j-primers --adapters adapters-present --assemble "-OassemblingFeatures=[VDJRegion]" --export "-p fullImputed" Input_R1.fastq.gz Input_R2.fastq.gz output`

**Comment by mizraelson** [comment]
Hi,
So the updated code will look like this:

```
mixcr analyze generic-amplicon \
    --species mmu \
    --rna \
    --floating-left-alignment-boundary \
    --floating-right-alignment-boundary J \
    --assemble-clonotypes-by "VDJRegion" \
    --impute-germline-on-export \
      input_R1.fastq.gz \
      input_R2.fastq.gz \
      result
```
