### ISSUE TITLE
Alignment and mutations encoding Example

### ISSUE THREAD

**Issue by RodenLuo** [milaboratory/mixcr#151]
Anyone also confused by the following example in Doc [Appendix](http://mixcr.readthedocs.io/en/latest/appendix.html)?

From what the appendix has described and my understanding, the first result should be: 
`2|17|19|3|18||75.0` and the second should be: `2|17|19|3|18|DG7SC9TI13C|41.0`. (The first three numbers are changed from `0|15|17` to `2|17|19`) 

> Example:
> Consider the following BLAST-like alignments encoded in MiXCR notation:
> 
> -  Alignment without mutation
> 
>       <pre style="font-size: 11px">
>       target = TTGTGCTGACAGATACCCC
>       query  = CGAGTGCTGACAGATACCGTCGATGCT
>       
>       BLAST like alignment:
>       2 GTGCTGACAGATACC 16
>         |||||||||||||||
>       3 GTGCTGACAGATACC 17
>       
>       MiXCR alignment:
>       0|15|17|3|18||75.0
>       </pre>
> 
> subsequence from ``target`` (from nucleotide 0 to nucleotide 15) was
> found to be identical to susequence from ``query`` (from nucleotide 3 to
> nucleotide 18).
> 
> -  Alignment with mutation
> 
>       <pre style="font-size: 11px">
>       target = TTGTGCTGACAGATACCCC
>       query  = CGAGTGCTATAGACTACCGTCGATGCT
>       
>       BLAST like alignment:
>       2 GTGCTGACAGA-TACC 16
>         ||||| | ||| ||||
>       3 GTGCT-ATAGACTACC 17
>       
>       MiXCR alignment:
>       0|15|17|3|18|DG7SC9TI13C|41.0
>       </pre>
> 
> so, to obtain subseqeunce from **query sequence** from 3 to 18 we need
> to apply the following mutations to subsequence of **target sequence**
> from 2 to 16: - deletion of ``G`` at position ``7`` - substitution of
> ``C`` at position ``9`` to ``T`` - insertion of ``C`` before at position``13``

**Comment by rhilker** [comment]
I found another confusing thing in the mutation example: The alignment score 41.0
The alignment has `13 matches, 1 mismatch, 1 insertion and 1 deletion`. With the default alignment scoring, shouldn't it be 
`5*13 = 65` for 13 matches
`-9` for mismatch
`-12` and `-12` for both insertion and deletion
giving:
`65 - 33 = 32`? Or did I overlook something?
