### ISSUE TITLE
OassemblingFeatures

### ISSUE THREAD

**Issue by suntaosimon** [milaboratory/mixcr#160]
I noticed the Version 2.0 has been released, I have upgraded already and tried to assemble CDR2 only by using “OassemblingFeatures="[CDR2]”” without include CDR3. It seems like this feature is still not available because it gives me an error message: Exception in thread "main" java.lang.ArrayIndexOutOfBoundsException: -1

Just wanna confirm that V2.0 did not remove the limit for assemblingFeatures to include CDR3, right?

Thank you very much!

**Comment by dbolotin** [comment]
Hi @suntaosimon ,

Yes, I confirm, this feature is still not available, by now assemblingFeatures must cover CDR3. We are working on this issue.

All the best,
Dmitry.
