### ISSUE TITLE
UMI-based error correction 

### ISSUE THREAD

**Issue by bshim181** [milaboratory/mixcr#1635]
This is a UMI distribution I see for one of my samples. I was wondering what parameters are suggested to modify to relax level of UMI filtering conducted here (possibly lower the UMI filtering threshold by 3 reads per UMI rather than 10 shown on this graph)

<img width="954" alt="Screenshot 2024-04-29 at 10 58 07 AM" src="https://github.com/milaboratory/mixcr/assets/53489568/2997e698-28ed-42b3-8931-054b4c4567a9">

**Comment by mizraelson** [comment]
Hi, I would first check the `refineTagsAndSort` report to see the percentage of reads that are being filtered out. To manually set the UMI filter, you can use the following parameters with the `mixcr analyze` command:

```
-M.refineTagsAndSort.parameters.postFilter=null
-M.assemble.consensusAssemblerParameters.assembler.minRecordsPerConsensus=3
```
