### ISSUE TITLE
RefineTagsAndSort 

### ISSUE THREAD

**Issue by bshim181** [milaboratory/mixcr#1646]
This is an example image and explanation posted on MiXCR website. I could not fully comprehend what the threshold was accomplishing. 
<img width="769" alt="Screenshot 2024-05-07 at 3 21 33 PM" src="https://github.com/milaboratory/mixcr/assets/53489568/dc8b9d68-ed01-4ccb-afda-5fdf70b5b9ff">

In general, during refineTagsAndSort, it seems to correct huge proportion of artificial barcode generated as a artifact of sequencing error. 
<img width="770" alt="Screenshot 2024-05-07 at 3 29 22 PM" src="https://github.com/milaboratory/mixcr/assets/53489568/c8511fca-3408-4ad1-baf6-6fbfc516e205">

Previously I assumed that MiXCR discards barcodes with read evidences lower than the threshold, but based on the refineTagsAndSort reports for my samples, that seems to be not the case. Rather it corrects the UMIs and most of the reads are retained. In this case, what is the threshold accomplishing? Are UMIs under that threshold corrected and converged into UMIs over that threshold?

**Comment by mizraelson** [comment]
MiXCR does both. It first corrects the errors in the UMI sequence and then applies the threshold.
