### ISSUE TITLE
For detection of somatic hypermutation (SHM) ?

### ISSUE THREAD

**Issue by xmy1990** [milaboratory/mixcr#1648]
Hi,
Which parameters should I use to detect somatic hypermutation (SHM) in the command "mixcr analyze exome-seq".

or can I use  "mixcr analyze exome-seq" to detect somatic hypermutation (SHM).

Thanks

**Comment by mizraelson** [comment]
Hi, could you specify what type of output you're looking for? By default, MiXCR provides the sequence of all regions that were covered for each clone. If necessary, you can customize the output to include additional columns, such as the number of mutations in a specific region or the mutations themselves.

You can find a complete list of all possible output columns in our [documentation](https://mixcr.com/mixcr/reference/mixcr-export/#common-fields).
