### ISSUE TITLE
Somatic hypermutation analysis

### ISSUE THREAD

**Issue by pbpayal** [milaboratory/mixcr#1656]
How to do somatic hypermutation analysis between two sample sets (3 samples per cohort) Can we do somatic hypermutation analysis from https SMARTer Mouse TCR a/b Profiling Kit? I came across "B cell lineage tracing" page. 

How to create a diagram for mutation frequencies between two cohorts( no timepoints)?

**Comment by mizraelson** [comment]
Do you expect somatic hypermutations to be present in TCRs?
