### ISSUE TITLE
Error exportPlots shmTrees - Duplicate library: repseqio.v4.0_with_found_alleles:10090

### ISSUE THREAD

**Issue by pbpayal** [milaboratory/mixcr#1666]
## Error while running exportPlots shmTrees

`mixcr exportPlots shmTrees -m metadata_part1.tsv --node-color condition  --ids 1424 part1_trees.shmt Mutant_shm_trees_1424.pdf`

**_Error while running command shmTrees java.lang.RuntimeException: Duplicate library: repseqio.v4.0_with_found_alleles:10090_**

Attached metadata file.
[metadata_part1.txt](https://github.com/milaboratory/mixcr/files/15391321/metadata_part1.txt)

**Comment by mizraelson** [comment]
Hi, can you please try [the latest develop version](https://link.milaboratory.com/software/mixcr/mixcr-develop.zip). It looks like a bug we have already fixed.

**Comment by pbpayal** [comment]
Yes..it works when with the dev version. Thanks
