### ISSUE TITLE
library imgt requires exact version

### ISSUE THREAD

**Issue by fabioticconi** [milaboratory/mixcr#168]
I have this in my libraries folder: `imgt.201631-4.sv1.json`

If I do `mixcr align --library imgt` it fails (at least for the species I've tried it in, mouse). If I do `mixcr align --library imgt.201631-4.sv1` it works.

So I think there's a bug in the code that parses for the filename. Note how that's exactly how the file looks after downloading it from here https://github.com/repseqio/library-imgt/releases and gunzipping it.

Or the documentation here is wrong and we can't use simply `imgt` to get the newest version: http://mixcr.readthedocs.io/en/latest/importSegments.html

**Comment by dbolotin** [comment]
Thanks for reporting! This [bug](https://github.com/milaboratory/mixcr/issues/137#issuecomment-251207150) is already fixed in 2.0.1. We will release it somewhere this week.
