### ISSUE TITLE
How to perform MiXCR on my spatial TCR data

### ISSUE THREAD

**Issue by yuyuleung** [milaboratory/mixcr#1684]
### Discussed in https://github.com/milaboratory/mixcr/discussions/1683

<div type='discussions-op-text'>

<sup>Originally posted by **yuyuleung** June  5, 2024</sup>
Hello, 

I wanna perform MiXCR analysis on my spatial TCR data, where multiple barcodes are assigned to a spatial spot (looked as a single cell). 

My .fq files are in the following format:
read1.fq: 20bp (barcode)
read2.fq: 90bp (mRNA)

Besides, I have also generated a barcodeTranslate file, where which barcodes can be assigned to which cells are clarified. 
Like:
spot1 CAACAAACAAAAATACTATATTAAC
spot1 CAACAAACATAAATACAATATTAAC
spot2 TACAACTGAAAATAATTATCATACC
spot2 TACAACTGAATATAATTATCATACG
...

How can I specify/define my multiple barcode sequences as a single cell to analyze? 

Thank you. 
Yuyu
</div>

**Comment by mizraelson** [comment]
I am gonna close this issue, the discussion is in #1683.
