### ISSUE TITLE
findAlleles get empty clone data

### ISSUE THREAD

**Issue by liu9756** [milaboratory/mixcr#1697]
Hi ! I would like to run findAlleles to continue the analysis of SHM. However, when I run the findAlleles command with my own data which generated from analysis, no clone information is detected in by findAlleles. I am sure the data indeed contain the clone information, so please help to check if my command is correct. Thanks!

user@user-Precision-3660:/media/user/Elements/Data_Ye_Liu/scRNA/mouse/ZSG_BCR/S6_MIXC_result_kit2$ mixcr findAlleles -OfilterForDataWithUmi.useClonesWithCountGreaterThen=0       --report DCh.findAlleles.report.txt       --export-alleles-mutations DCh_alleles.tsv       --export-library DCh_alleles.json       --output-template S6.reassigned.clns       *.clns
IMPORTANT: MiXCR will use at most 6373MB of RAM,
           use -Xmx to change automatically set heap size (i.e. -Xmx50g to set heap size to 50 Gb)
WARNING: unnecessary override -OuseClonesWithCountGreaterThen=0 with the same value.
Step 1 of 7: count diversity for dataset: progress unknown
Step 2 of 7: grouping by the same J gene: progress unknown
Step 2 of 7: Searching for J alleles: progress unknown
Step 3 of 7: grouping by the same V gene: progress unknown
Step 4 of 7: grouping by the same J gene: progress unknown
Step 5 of 7: grouping by the same V gene: progress unknown
Step 6 of 7: removing unnecessary genes: progress unknown
Step 7 of 7: realigning mouse_S6.clns: progress unknown
============== FindAlleles Report ==============
Analysis time: 311ms
Clones score delta stats:
	size: 0
	sum: 0.0
	min: NaN
	max: NaN
	avg: NaN
	quadratic mean: NaN
	std deviation: NaN
Clones count with no change of score: 0
Clones count with negative score change: 0
Found alleles on first try: 0
Zygotes: {}
Not enough information for allele search: []
Found alleles: 0
	De novo alleles: 0
	Known variant from library: 0
	Not enough info for search, but aligned on known allele: 0
Not changed genes: 0
	Not changed after search: 0
	No clones to search: 0
	Have clones to search, but not enough info for search and can't be aligned on known variant: 0
Removed genes: 617
	No top hits in result files: 0
	No top hits in source files: 0
	Can be aligned on other gene: 0
	Not represented in source files: 617
Found alleles that don't fit well to data: {}

**Comment by mizraelson** [comment]
Hi, do you see the clones in the table before you run the findAlleles function?

**Comment by liu9756** [comment]
Actually not, when I run analysis, the assembleContigs step also detect 0 clones which is also weird:
Analysis date: Tue May 28 14:45:00 EDT 2024
Input file(s): ./result.clna
Output file(s): ./result.contigs.clns
Version: 4.3.2; built=Tue Apr 11 14:35:07 EDT 2023; rev=123d699964; lib=repseqio.v2.2
Command line arguments: assembleContigs --report ./result.assembleContigs.report.txt --json-report ./result.assembleContigs.report.json ./result.clna ./result.contigs.clns
Analysis time: 8.69m
Initial clonotype count: 336
Final clonotype count: 336 (100%)
Canceled assemblies: 0 (0%)
Number of premature termination assembly events, percent of number of initial clonotypes: 0.0 (0%)
Longest contig length: 615
Clustered variants: 0 (0%)
Reads in clustered variants: 0.0 (0%)
Reads in divided (newly created) clones: 0.0 (0%)
Clones with ambiguous letters in splitting region: 0 (0%)
Reads in clones with ambiguous letters in splitting region: 0.0 (0%)
Average number of ambiguous letters per clone with ambiguous letters in splitting region: NaN

**Comment by mizraelson** [comment]
Can you please try running the analysis with the [latest develop version](https://link.milaboratory.com/software/mixcr/mixcr-develop.zip). If you still see the issue, would it be possible to share the clns file? You can send it to support@milaboratories.com

**Comment by mizraelson** [comment]
Hi, do you still see this issue?

**Comment by liu9756** [comment]
Hi! I am trying to run the latest version on remote server, but it said I don't have permission

**Comment by mizraelson** [comment]
What error do you see? Is it a server message or a MiXCR error message?

**Comment by liu9756** [comment]
Actually when I try to run the latest version, it said [liu9756@owens-login04 mixcr]$ mixcr
Error: A JNI error has occurred, please check your installation and try again
Exception in thread "main" java.lang.UnsupportedClassVersionError: com/milaboratory/mixcr/cli/Main has been compiled by a more recent version of the Java Runtime (class file ver
sion 55.0), this version of the Java Runtime only recognizes class file versions up to 52.0
        at java.lang.ClassLoader.defineClass1(Native Method)
        at java.lang.ClassLoader.defineClass(ClassLoader.java:756)
        at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
        at java.net.URLClassLoader.defineClass(URLClassLoader.java:473)
        at java.net.URLClassLoader.access$100(URLClassLoader.java:74)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:369)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:363)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(URLClassLoader.java:362)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:352)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
        at sun.launcher.LauncherHelper.checkAndLoadMain(LauncherHelper.java:621)

**Comment by mizraelson** [comment]
what command do you try to run and what Java version do you have?

**Comment by liu9756** [comment]
Thanks! I update Java and it now successfully running!

**Comment by liu9756** [comment]
I use the latest version to run the analysis , but the assemble still display 0% clones, I will send the necessary files to the email.===================== report: assemble =====================
Analysis time: 306ms
Final clonotype count: 0
Reads used in clonotypes, percent of total: 0 (0%)
Average number of reads per clonotype: NaN
Reads dropped due to the lack of a clone sequence, percent of total: 1876 (0%)
Reads dropped due to a too short clonal sequence, percent of total: 0 (0%)
Reads dropped due to low quality, percent of total: 0 (0%)
Reads dropped due to failed mapping, percent of total: 0 (0%)
Reads dropped with low quality clones, percent of total: 0 (0%)
Aligned reads processed: 0
Reads used in clonotypes before clustering, percent of total: 0 (0%)
Number of reads used as a core, percent of used: 0 (NaN%)
Mapped low quality reads, percent of used: 0 (NaN%)
Reads clustered in PCR error correction, percent of used: 0 (NaN%)
Reads pre-clustered due to the similar VJC-lists, percent of used: 0 (NaN%)
Clonotypes dropped as low quality: 0
Clonotypes eliminated by PCR error correction: 0
Clonotypes pre-clustered due to the similar VJC-lists: 0
Clones dropped in post filtering: 0 (NaN%)
Reads dropped in post filtering: 0.0 (0%)
Alignments filtered by tag prefix: 0 (0%)
Pre-clone assembler report:
  Number of input groups: 375
  Number of input groups with no assembling feature: 375
  Number of input alignments: 1876
  Number of alignments with assembling feature: 0 (0%)
  Number of output pre-clones: 0
  Number of pre-clonotypes per group:  
  Number of assembling feature sequences in groups with zero pre-clonotypes: 0
  Number of dropped pre-clones by tag suffix conflict: 0
  Number of dropped alignments by tag suffix conflict: 0
  Number of core alignments: 0 (0%)
  Discarded core alignments: 0 (NaN%)
  Empirically assigned alignments: 0 (0%)
  Empirical assignment conflicts: 0 (0%)
  Tag+VJ-gene empirically assigned alignments: 0 (0%)
  VJ-gene empirically assigned alignments: 0 (0%)
  Tag empirically assigned alignments: 0 (0%)
  Number of ambiguous groups: 0
  Number of ambiguous tag+V/J-gene combinations: 0
  Ignored non-productive alignments: 0 (0%)
  Unassigned alignments: 0 (0%)

**Comment by mizraelson** [comment]
I will close this issue as it is directly connected to the #1713
