### ISSUE TITLE
--diff-loci or --allow-chimeras

### ISSUE THREAD

**Issue by Kinoubi** [milaboratory/mixcr#171]
Hi,

I want to try differents loci, but commands doesn't work....I need a little help please :)
I am working with the 2.0 version of MiXCR

Thanks !

**Comment by PoslavskySV** [comment]
Hi,

`--diff-loci` is now deprecated, use `--allow-chimeras` instead. With this option alignments of V and J allowed to be of different loci (e.g. TRBV and TRAJ). Which particular command doesn't work?

**Comment by Kinoubi** [comment]
Hi,


Thank you for the answer.


If I write : mixcr align {other options} --allow-chimeras {file R1} {file R2} {output}


It writes that '--allow-chimeras' is an unkonw options...


Karine

________________________________
De : PoslavskySV <notifications@github.com>
Envoyé : jeudi 10 novembre 2016 20:18
À : milaboratory/mixcr
Cc : Kinoubi; Author
Objet : Re: [milaboratory/mixcr] --diff-loci or --allow-chimeras (#171)


Hi,

--diff-loci is now deprecated, use --allow-chimeras instead. With this option alignments of V and J allowed to be of different loci (e.g. TRBV and TRAJ). Which particular command doesn't work?

-

**Comment by PoslavskySV** [comment]
Sorry, the correct option is `-OallowChimeras=true`:

     mixcr align {other options} -OallowChimeras=true {file R1} {file R2} {output}

I will now fix the docs. Thanks for reporting issue!

**Comment by Kinoubi** [comment]
I tried this one too, but I have forgot the big "C" for chimeras. It works now.


Thank you so much


________________________________
De : PoslavskySV <notifications@github.com>
Envoyé : mardi 15 novembre 2016 12:07
À : milaboratory/mixcr
Cc : Kinoubi; Author
Objet : Re: [milaboratory/mixcr] --diff-loci or --allow-chimeras (#171)


Sorry, the correct option is -OallowChimeras=true:

 mixcr align {other options} -OallowChimeras=true {file R1} {file R2} {output}


I will now fix the docs. Thanks for reporting issue!

-
