### ISSUE TITLE
QIAgen Targeted library

### ISSUE THREAD

**Issue by GabyBG** [milaboratory/mixcr#1728]
Hello,

Thank you so much for mixer, it has proven to be a very valuable package for my Immune repertoire analysis. 
I am currently working with QIAseq Targeted RNA Panel TCR Library Kit, I tried running mixcr version 4.6 👍 

```
mixcr analyze qiagen-human-rna-tcr-umi-qiaseq fastq.R1.fastq.gz  fastq.R2.fastq.gz
```

Very few reads aligned and it could be because the configuration of the library might be a little different. According to the vendor the library has phasing on both ends. 
Are there any plans to dd the targetedRNA Panel TCR  library kit configuration? or is it something I missed in the documentation? When comparing the results from the pipeline described above vs the Qiagen analysis tool, the results are very different.

Thank you so much for your help!

<img width="683" alt="image" src="https://github.com/user-attachments/assets/dc4e184c-18cc-4ade-b9cd-1c6f5e8dec13">

**Comment by mizraelson** [comment]
Hi,
Can you share the align report here?
