### ISSUE TITLE
Failure to start program on Centos Linux Distribution

### ISSUE THREAD

**Issue by jacobhurst** [milaboratory/mixcr#173]
free -m | head -n 3 

within the mixcr wrapper produces different ouput to Ubuntu:-

             total        used        free      shared  buff/cache   available
Mem:           7566         236        3142          24        4187        7020
Swap:             0           0           0

maxMb gets set to -100 as a result. 

Suggested action:- simplify overly complex script.

**Comment by dbolotin** [comment]
Thanks for reporting! Will fix it this weekend.

**Comment by dbolotin** [comment]
On what version of CentOS do you see this problem?

I just tested on CentOS 7, and `free -m | head -n 3` produces the same result as in Ubuntu.

**Comment by dbolotin** [comment]
Also tested on Scientific Linux 6.4, same result as on Ubuntu.

**Comment by jacobhurst** [comment]
Hi,
I'm using Centos 7.2 wondered if "available" was a better option? the machine is an AWS compute node configured without swap.
best wishes
Jake

**Comment by dbolotin** [comment]
Thanks!

There are lots of images with Centos 7.2, can you please provide exact AMI id.

Seems that `free` command now have new output format, I will research the meaning of new fields, and if `available` means "maximal amount of memory available for allocation" I will go with it.

**Comment by jacobhurst** [comment]
AMI ami-5fd7133f

best wishes
Jake

**Comment by dbolotin** [comment]
Fixed.

Here is the link to the fixed version:
http://files.milaboratory.com/mixcr/mixcr-2.0.3-SNAPSHOT.zip

2.0.3 will be released somewhere in the end of the next week.

I decided that `free` column is more conservative.

All the best!

P.S. Thanks for pointing to Alces Flight Compute, looks interesting.
