### ISSUE TITLE
Han el all preset

### ISSUE THREAD

**Issue by alexell22** [milaboratory/mixcr#1733]
Hi! 

I am using the Han et all preset (han-et-al-2014) , with mixcr-4.3. I am facing several issues:

1. Low coverage of the plates (I have 20 plates in total, 5 sorted cells in each well, library prep is done the same way as discussed in the paper, and currently libraries are resequenced). However, I am getting quite a similar outcome with the specified preset (~50%). What could be the reason behind it, if not the library prep? 
2.  Some Plate barcodes could not be found in the processed data (plate is missing), however are present in the unprocessed data (with the required seq, as well in the ROW and Column). Is it possible to check the builtin:han-2014-cell3-plate? Or what can be also done in that case? 

Thank you!

**Comment by mizraelson** [comment]
Hi,
1) The preset is optimized to work with datasets with one cell per well as was done in the original publication.
2) Can you share the report files? 
3) I am attaching the list of the plate barcodes build into the preset.
[han-2014-cell3-plate.txt](https://github.com/user-attachments/files/16482563/han-2014-cell3-plate.txt)

**Comment by alexell22** [comment]
Sure!
[result.align.report.txt](https://github.com/user-attachments/files/16482580/result.align.report.txt)
[result.assemble.report.txt](https://github.com/user-attachments/files/16482581/result.assemble.report.txt)
[result.qc.txt](https://github.com/user-attachments/files/16482582/result.qc.txt)
[result.refine.report.txt](https://github.com/user-attachments/files/16482583/result.refine.report.txt)

Thank you for the list!

**Comment by mizraelson** [comment]
Did you use the same primers as in the paper?

**Comment by alexell22** [comment]
Yes, the same (1st, 2nd reaction and barcoding). We did not include the phenotyping ones, just for TCRs.

**Comment by mizraelson** [comment]
From the reports, I see you are using MiXCR v4.6 not 4.3

Here is the pattern from the preset:
```
 ^NN(CELL3PLATE:N{5})ga(CELL1ROW:N{5})ccagggttttcccagtcacgac(R1:*) \
 ^NN(CELL2COLUMN:N{5})gtcactggatttagagtctctcag(R2:*) |
 ^NN(CELL2COLUMN:N{5})gagatctctgcttctgatggctc(R2:*)
 ```
According to the reports, the main issue is that this pattern wasn't matched:

`Alignment failed: absent barcode: 4197136 (94.79%)`

Do you see these primer sequences in your data? If you can share the FASTQ files, I can take a look.
