### ISSUE TITLE
Pre-Clonotypes

### ISSUE THREAD

**Issue by bshim181** [milaboratory/mixcr#1735]
Hello, 

I am running in to issues where there are large number of zero pre-clonotypes groups. I am looking at different replicates for the sample run and it varies from 65% to high 80 range. What might be the cause for this?

The reads have 12 bp UMI with around 500,000 reads in total. It demonstrates about 95% alignment rate. 

<img width="792" alt="Screenshot 2024-08-05 at 2 04 37 PM" src="https://github.com/user-attachments/assets/12bffdfa-623f-4b8b-af8e-510caf203e70">

**Comment by mizraelson** [comment]
This means that for the majority of UMI groups, there are multiple clones marked with the same UMI sequence.
