### ISSUE TITLE
Missing Documentation on MIXCR output

### ISSUE THREAD

**Issue by alvinwt** [milaboratory/mixcr#175]
Hi, 

I am looking for more information on how to interpret the output of MIXCR especially in the context of using RNA-seq data. It would be useful to have more documentation describing the output. Particularly, information about how reliable the output is with regards, the number of clones, reads mapping to each clone and the depth of sequencing is useful. 

As I am using rather old data, I am unsure if the small number of clones, small number of chains are indicating that the sequencing coverage is insufficient and unable to detect the TCR sequences. There were just 3 TRA chains and 5 TRB chains with 1 clone count each.

Is there a way to tell if the coverage is insufficient and should not be used for TCR profiling? These points would be very helpful in the documentation.

**Comment by dbolotin** [comment]
Hi @alvinwt,

more extensive documentation for RNA-Seq is coming. We are currently working on describing this functionality in more details. Thanks for pointing on results interpretation topic, it definitely deserves additional coverage.

Please post here report files from all analysis steps (`align`, `assemblePartial` and `assemble`), this way I can tell you with more confidence, if there are any analysis glitches. What is the library structure? paired-end/single-end? read length?

In general it is pretty common to see samples with very low TCR content, even without any TCR rearrangements.

As an additional validation source you can use expression levels of TRBC1/2 and TRAC gene.

P.S. current development version of MiXCR 2.1.0 has several improvements for RNA-Seq analysis, it is still in development, and may contain bugs, but if you are interested I can publish pre-release binary and post here a link. This version will be officially released only in the very end of December or in January.
