### ISSUE TITLE
Missing tsv files in MiXCR 4.7.0 output for 10X GEX pipeline

### ISSUE THREAD

**Issue by genome2020** [milaboratory/mixcr#1778]
Hi,

I just ran latest version (4.7.0) of MiXCR on my 10X 5' GEX data. However, I am missing several .tsv files that were present when I ran older version of MiXCR on the same data. Specifically the following files are missing.

S48.clone.groups_mixed.tsv
S48.clone.groups_TRAB.tsv
S48.clone.groups_TRGD.tsv

The command I used is:

mixcr -Xmx100g analyze 10x-sc-5gex --threads 16 --species hsa S48_R1_001.fastq.gz S48_R2_001.fastq.gz S48

Could you please help with the issue? Thanks!

**Comment by mizraelson** [comment]
Hi, what files did you get in the output?
