### ISSUE TITLE
Alignment read counts by sample when using input file name expansion

### ISSUE THREAD

**Issue by benjytan88** [milaboratory/mixcr#1783]
Hi MiXcR team, 
I'm using MiXcR to analyze multiple samples of BCR data, so I am using file name expansion for it. My FASTQ files look like this with the sample name at the front.

```
LN1_R1_001.fastq.gz
LN1_R2_001.fastq.gz
LN2_R1_001.fastq.gz
LN2_R2_001.fastq.gz
SC1_R1_001.fastq.gz
SC1_R2_001.fastq.gz
SC2_R1_001.fastq.gz
SC2_R2_001.fastq.gz
```

My command to run MiXcR is as follows: 
`mixcr analyze --output-not-used-reads --split-by-sample neb-mouse-rna-xcr-umi-nebnext ./FASTQs/{{a}}_{{R}}_001.fastq.gz ./OUTPUT/`

Upon completion, when I checked the QC, all of them have the same number of reads sequenced and % successfully aligned reads. When I generate the alignment reports using this command, all my barplots have the same distribution. 

`mixcr exportQc align ./OUTPUT/*.vdjca ./REPORT/alignQC.pdf`

 I believe this shows the total sequences aligned for all samples together, but I wanted is the QC for each individual sample. Could you please guide on how can I get this? Am I missing any parameters in my command? 

Thank you.

**Comment by mizraelson** [comment]
Hi,
When you use `{{a}}_{{R}}_001.fastq.gz`, it merges everything together and processes it as a single sample.
If you want to process the samples separately, you can use:
`{{SMPL:a}}_{{R}}_001.fastq.gz`.
