### ISSUE TITLE
Different alignment rates for MiXCR analyze and MiXCR align

### ISSUE THREAD

**Issue by Januaryyiyue** [milaboratory/mixcr#1793]
Hi,

I previously used MiXCR4.1.2 align, assemble, etc. separately and get an alignment log like this:
```
Total sequencing reads: 11689853
Successfully aligned reads: 10588551 (90.58%)
...
```
When I repeat the analysis with MiXCR analyze, my log file looks like this:
```
Total sequencing reads: 12150553
Successfully aligned reads: 202393 (1.67%)
...
```
The alignment rates are significantly different, but the resulting clones are almost the same.

Is there a reason why this is the case? If e.g., a previous alignment rate of 50% would be considered acceptable, what percentage should I expect from the new alignment rate?

Thank you!

**Comment by mizraelson** [comment]
Hi, can you share the exact commands?
