### ISSUE TITLE
Multiple clones per cell barcode

### ISSUE THREAD

**Issue by SirKuikka** [milaboratory/mixcr#1794]
Hi, 

I have a simple question. I am looking at the .clones.tsv output for the single-cell Mixcr workflow, and there are often multiple clones per cell barcode. Should I just use the first one with the most reads/UMIs if I want to assign a clone identity to each cell barcode?

![image](https://github.com/user-attachments/assets/1bb4ae45-5038-49e7-b9bd-2fd6356b642c)

![image](https://github.com/user-attachments/assets/95319aaf-26fc-4997-8aa6-c82e61bf0316)

**Comment by mizraelson** [comment]
Hi, what MiXCR version and command do you use?
