### ISSUE TITLE
Error : mixcr line 215: 20652 Killed  $java -Dmi.license.file="$dir/mi.license" -D${app}.path="$dir" -D${app}.command=${app} "${javaArgs[@]}" -jar "$jar" "${appArgs[@]}"

### ISSUE THREAD

**Issue by liu9756** [milaboratory/mixcr#1815]
Hi! I use `mixcr analyze 10x-sc-xcr-vdj` command to process my files, however, in refineTagsAndSort section, I am informed that `/users/PAS2177/liu9756/mixcr/mixcr: line 215: 20652 Killed                  $java -Dmi.license.file="$dir/mi.license" -D${app}.path="$dir" -D${app}.command=${app} "${javaArgs[@]}" -jar "$jar" "${appArgs[@]}"`

The following is the command output:

>`  Average R1 nucleotides trimmed right: 8.506156640558773E-6
Tag parsing report:
  Execution time: 0ns
  Total reads: 205850900
  Matched reads: 205850900 (100%)
  Projection +R1 +R2: 205850900 (100%)
  For variant 0:
    For projection +R1 +R2:
      CELL:Left position: 0
      UMI:Left position: 16
      CELL:Right position: 16
      UMI:Right position: 26
      R2:Left position: 0
      Variants: 0
      Cost: 0
      CELL length: 16
      UMI length: 10
      R2 length: 101
>>>>>>>>>>>>>>>>> mixcr refineTagsAndSort <<<<<<<<<<<<<<<<<
Running:
mixcr refineTagsAndSort --report results_10x.refine.report.txt --json-report results_10x.refine.report.json results_10x.vdjca results_10x.refined.vdjca
Correction will be applied to the following tags: CELL, UMI
Sorting will be applied to the following tags: CELL, UMI
The following whitelist will be used for CELL: WhitelistFromAddress(address=builtin:737K-august-2016)
Initialization: progress unknown
Initialization: 0.9%
Initialization: 11%  ETA: 00:03:24
Initialization: 21.5%  ETA: 00:10:16
Initialization: 22.6%  ETA: 03:37:25
Initialization: 25.2%  ETA: 01:35:36
Initialization: 27.4%  ETA: 01:18:30
Initialization: 28.8%  ETA: 01:56:00
/users/PAS2177/liu9756/mixcr/mixcr: line 215: 20652 Killed                  $java -Dmi.license.file="$dir/mi.license" -D${app}.path="$dir" -D${app}.command=${app} 
"${javaArgs[@]}" -jar "$jar" "${appArgs[@]}"
[liu9756@owens-login04 NEW_BCR_S7]$ 
`

**Comment by mizraelson** [comment]
How much memory did you use? It seems like the process was killed due to the lack of RAM.

**Comment by liu9756** [comment]
100G

**Comment by liu9756** [comment]
I will try 200G

**Comment by mizraelson** [comment]
Sometimes for a very large datasets 100G might not be enough. Let's see if 200G will do.

**Comment by mizraelson** [comment]
Did it work?

**Comment by mizraelson** [comment]
I am gonna close it for now. Feel free to reopen.
