### ISSUE TITLE
picocli.CommandLine$ExecutionException: Error while running command align java.lang.RuntimeException: Failed to override some parameter.   

### ISSUE THREAD

**Issue by Dingchunyuan** [milaboratory/mixcr#1819]
## Checklist before submitting the issue:

 - [√] The issue is strongly related to the MiXCR software
 - [√] The issue can be reproduced with [the most recent version](https://github.com/milaboratory/mixcr/releases) of MiXCR
 - [√] There is no answer to the question in the [official documentation](http://mixcr.readthedocs.io/) and there is no duplicate issue in the [bug tracker](https://github.com/milaboratory/mixcr/issues?utf8=✓&q=)  
 - [√] Inspection of raw alignments with [exportAlignmentsPretty](http://mixcr.readthedocs.io/en/master/export.html#exporting-well-formatted-alignments-for-manual-inspection) shows that data has the expected architecture, and sample preparation artefacts are not the reason of the problem (if this is the matter of the issue)

Hello,

I am writing to seek your assistance regarding an issue I encountered while running MixCR. I attempted to modify certain parameters, but unfortunately, an error occurred during the process.

Could you please provide guidance on how to correctly adjust these parameters to avoid such errors? 

Thank you for your support.

## Exact MiXCR commands 
  `mixcr align \
    --species hsa \
    --library imgt \
    -f \
     -p generic-amplicon-with-umi \
    -OvParameters.geneFeatureToAlign="VTranscriptWithP " \
    -OallowNoCDR3PartAlignments=true \
    -OallowPartialAlignments=true \
    -OallowPartialAlignments=true \
    --keep-non-CDR3-alignments \
    --rigid-left-alignment-boundary  \
    --floating-right-alignment-boundary C\
    --tag-pattern "^(R1:*)\\^(UMI:N{{16}})(R2:*)" \
    --report results/FT100053139_L01_S009.report.txt \
    --json-report results/FT100053139_L01_S009.report.json \
    --assemble-clonotypes-by CDR3 \
    --rna \
    -OvParameters.relativeMinScore=0.7 \
    -OjParameters.relativeMinScore=0.7 \
    -OcParameters.relativeMinScore=0.7 \
    -OvParameters.absoluteMinScore=30 \
    -OjParameters.absoluteMinScore=30 \
    -OcParameters.absoluteMinScore=30 \
	/public/home/dingchunyuan/TCR/Rawdata/G99/FT100053139_100bp/FT100053139_L01_S009_1.fq.gz \
    /public/home/dingchunyuan/TCR/Rawdata/G99/FT100053139_100bp/FT100053139_L01_S009_2.fq.gz \
    ./results/FT100053139_L01_S009.vdjca `
ERROR info
```picocli.CommandLine$ExecutionException: Error while running command align java.lang.RuntimeException: Failed to override some parameter.   ```

**Comment by mizraelson** [comment]
Hi, what kind of protocol do you have? What is the structure of the cDNA library?
