### ISSUE TITLE
local preset

### ISSUE THREAD

**Issue by Dingchunyuan** [milaboratory/mixcr#1824]
## Checklist before submitting the issue:

 - [√ ] The issue is strongly related to the MiXCR software
 - [ √] The issue can be reproduced with [the most recent version](https://github.com/milaboratory/mixcr/releases) of MiXCR
 - [√ ] There is no answer to the question in the [official documentation](http://mixcr.readthedocs.io/) and there is no duplicate issue in the [bug tracker](https://github.com/milaboratory/mixcr/issues?utf8=✓&q=)  
 - [ ] Inspection of raw alignments with [exportAlignmentsPretty](http://mixcr.readthedocs.io/en/master/export.html#exporting-well-formatted-alignments-for-manual-inspection) shows that data has the expected architecture, and sample preparation artefacts are not the reason of the problem (if this is the matter of the issue)

Hello,

I would like to ask where I should place the file if I need to set up local presets. Are there any naming requirements for this file?

I have tried placing it in the path where mixcr and micr.jar are located, the path set by the fq file, and using bashrc to set environment variables, but all attempts have failed. Below is my code.
![image](https://github.com/user-attachments/assets/306c33d6-f1fa-4715-b60c-db16fdb2ff04)
![image](https://github.com/user-attachments/assets/cbbb6651-a875-40cb-93be-80fdb60288d7)

Thank you for your assistance.

**Comment by mizraelson** [comment]
Hi, you can put it either inside the directory you run mixcr from or in ~/.mixcr/presets folder.

Then run as:

```
mixcr analyze local:preset_dcy ...
```
