### ISSUE TITLE
Export column names

### ISSUE THREAD

**Issue by mikessh** [milaboratory/mixcr#184]
This may seem annoying but output column naming needs some refactoring. For example:

![image](https://cloud.githubusercontent.com/assets/6215797/21454310/8755f670-c928-11e6-8ab1-7a1f2ae24b50.png)

as you see using spaces and ``sequence(s)`` is not a very good idea. I suggest snake case.

**Comment by dbolotin** [comment]
Try -s option on export.

**Comment by mikessh** [comment]
Good, maybe make this setting default? I mean I get lots of clonotype tables made using MIXCR from other people and they all have this format.. :)

**Comment by dbolotin** [comment]
Sounds reasonable.

**Comment by dbolotin** [comment]
Fixed in 65d6115b7460e956d06c3b67fb454311e78e24c4
