### ISSUE TITLE
Persisting "Writing clones" during assemble

### ISSUE THREAD

**Issue by lordim** [milaboratory/mixcr#1847]
Hello,

I'm currently trying to test run the `mixcr analyze 10x-sc-xcr-vdj` preset on a pair of reads, and the execution was running fine until it reached the assemble stage, where it continued to print "Writing Clones" at the same percentage:

![image](https://github.com/user-attachments/assets/12a7f9ee-3516-44ee-a151-9e50db3dc5ed)

Does this mean that the pipeline is still running, or does it mean that it's at a dead end? Each of the read files is around 1GB, so it should not take too long, but the "Writing Clones" has been going on for a few hours now.

**Comment by mizraelson** [comment]
Hi, can you please try [the latest develop version](https://link.milaboratory.com/software/mixcr/mixcr-develop.zip) and let me know if it solved the issue.

**Comment by lordim** [comment]
Hello, is there a way to install it through CLI? I'm working on a remote server. Also, mine seems to be a pretty recent version, unless the version you mentioned is even newer:

<img width="833" alt="image" src="https://github.com/user-attachments/assets/1c61aedc-06e9-47f7-85a0-e98d1d30cd5a">

**Comment by mizraelson** [comment]
Yes, you can download it, unzip and just use as `java -jar /path/to/mixcr.jar analyze ...`

**Comment by mizraelson** [comment]
Hi, did it help?

**Comment by lordim** [comment]
Hello, yes, I think it seems to work for now! I'll post another issue if some other error pops up. Thank you!

**Comment by liel-cohen** [comment]
I have the same issue, running the analyze command:

`nice -n 8 mixcr -Xmx200g analyze 10x-sc-xcr-vdj --use-local-temp -s hsa O_1{{a}}_L{{n}}_{{R}}_001.fastq.gz ~/folder/
`

Running the command using this dev version worked perfectly (results that look good within 2 days):

`MiXCR v4.7.0-104-develop (built Fri Sep 27 14:22:11 PDT 2024; rev=8b1ab7f480; branch=develop; host=fv-az1249-2)
RepSeq.IO v2.5.0 (rev=06fa1852ee)
MiLib v3.5.0-3-mitool-tag-types (rev=7d638011d4)
Built-in V/D/J/C library: repseqio.v5.1`

Running the command using the main version (see below) gets stuck on "Writing clones: 15%" for more than a week. I tries it multiple times with and without --use-local-temp, and it always gets stuck at the same point (15%). File _clones.clna_ is the last one created a few hours after the run started, it has 43.15kb, and remains that way.

`MiXCR v4.7.0 (built Wed Aug 07 12:19:48 PDT 2024; rev=976ba14139; branch=no_branch; host=fv-az1019-185)
RepSeq.IO v2.5.0 (rev=06fa1852ee)
MiLib v3.5.0 (rev=b6cfcdc2af)
Built-in V/D/J/C library: repseqio.v5.1`
