### ISSUE TITLE
Mixcr built in reference

### ISSUE THREAD

**Issue by pbpayal** [milaboratory/mixcr#1858]
What's the builtin reference for Mixcr ? Is it IMGT? 

The link - "gene library" mentioned here isn't working. So wanted to check.
> The built-in reference [gene library](http://github.com/repseqio/library) of V-, D-, J- and C- segments is thoroughly compiled for every available species using the data specifically obtained from multiple dedicated sequencing runs as well as from hundreds of other experiments. At the same time MiXCR supports using of [external libraries](https://mixcr.com/mixcr/guides/external-libraries/) or even to assemble a [custom library](https://mixcr.com/mixcr/guides/create-custom-library/) from scratch.

**Comment by mizraelson** [comment]
Hi, MiXCR uses its own reference by default, not IMGT. We manually create and keep it up to date.
