### ISSUE TITLE
What do asterisks and underscores mean in the AA.Seq.CDR3 output?  

### ISSUE THREAD

**Issue by DanteBortone** [milaboratory/mixcr#204]
My AA.Seq.CDR3 output shows an occasional asterisk and/or underscore for some of the assembled and exported clones(eg. CAR*CG_YEQYF).  What do these symbols mean? 

Apologies if I overlooked this description in the docs.

**Comment by dbolotin** [comment]
Sorry, this important topic is really not described in the docs.

The rules are the following:

- If gene feature is known to have left and right bounds to point to the first nucleotide in a triplet.
*Like `CDR3`, where it's first position point to the first nucleotide in triplet that encodes conserved `Cys`, and the next position after the last nucleotide (right boundary is exclusive) points to the first nucleotide in triplet encoding next amino acid after conserved `Phe`.*

    The following translation rule applies:

        ATT AG  ACA
         I   _   T

    Basically, amino acids are translated starting from both sides simultaneously. If at the end of the procedure both sides stopped in the same place, resulting sequence will be a normal in-frame a.a. sequence (without any `_` symbols). If one or two nucleotides are left, an **incomplete codon symbol** (`_`) is added between left and right translated parts.

    For example `_` symbol can be used to determine if `CDR3` and consequently the whole gene is out-of-frame.

- If only one boundary (left or right) is known to be linked with reading frame, this boundary is used as translation origin.
*E.g. for `JCDR3Part` only right point is known to be anchored between triplets.*

    In this case you can see `_` symbol on the opposite relative to translation origin side of the sequence.

    Translation from right side:

       AT GTC ACA
       _   V   T

    Translation from left side:

        ATT AGA CA
         I   R   _


Hope this clarifies the situation, if not, please let me know.

Just created an issue to add this description to docs: #205

Thanks for pointing on this problem!

**Comment by dbolotin** [comment]
`*` symbol denotes stop codon

**Comment by DanteBortone** [comment]
Thank you for the quick and thorough response.

**Comment by lhhaoliu** [comment]
Thanks for the explanation, should these CDR3s considered productive or not? I assume they should be considered un-productive?

> Sorry, this important topic is really not described in the docs.
> 
> The rules are the following:
> 
> * If gene feature is known to have left and right bounds to point to the first nucleotide in a triplet.
>   _Like `CDR3`, where it's first position point to the first nucleotide in triplet that encodes conserved `Cys`, and the next position after the last nucleotide (right boundary is exclusive) points to the first nucleotide in triplet encoding next amino acid after conserved `Phe`._
>   The following translation rule applies:
>   ```
>     ATT AG  ACA
>      I   _   T
>   ```
>   
>   
>   Basically, amino acids are translated starting from both sides simultaneously. If at the end of the procedure both sides stopped in the same place, resulting sequence will be a normal in-frame a.a. sequence (without any `_` symbols). If one or two nucleotides are left, an **incomplete codon symbol** (`_`) is added between left and right translated parts.
>   For example `_` symbol can be used to determine if `CDR3` and consequently the whole gene is out-of-frame.
> * If only one boundary (left or right) is known to be linked with reading frame, this boundary is used as translation origin.
>   _E.g. for `JCDR3Part` only right point is known to be anchored between triplets._
>   In this case you can see `_` symbol on the opposite relative to translation origin side of the sequence.
>   Translation from right side:
>   ```
>    AT GTC ACA
>    _   V   T
>   ```
>   
>   
>   Translation from left side:
>   ```
>     ATT AGA CA
>      I   R   _
>   ```
> 
> Hope this clarifies the situation, if not, please let me know.
> 
> Just created an issue to add this description to docs: #205
> 
> Thanks for pointing on this problem!

**Comment by PoslavskySV** [comment]
@lhhaoliu Yes, we typically consider out-of-frame CDR3s and CDR3s with stop codons as non productive

**Comment by lhhaoliu** [comment]
> @lhhaoliu Yes, we typically consider out-of-frame CDR3s and CDR3s with stop codons as non productive

Thanks
