### ISSUE TITLE
MIXCR installation manually

### ISSUE THREAD

**Issue by suntaosimon** [milaboratory/mixcr#210]
I used to use brew  to install and update mixcr but found the update is slower than install manually. so I tried to install manually by following command, 

> wget https://github.com/milaboratory/mixcr/releases/download/v2.1/mixcr-2.1.zip
> unzip mixcr-2.1.zip
> cd mixcr-2.1
> mixcr -v

but "mixcr"command is not working. 

I want to know if once you used brew you can not switch to manual installation?

Thanks!

**Comment by dbolotin** [comment]
Sorry, just updated homebrew repo. You can now upgrade MiXCR using it.

Please post here error message that you see with manually installed MiXCR ?

To run mixcr from current folder you should add `./` before the script name, instead shell will look into PATH folder to find the executable file.

You can unlink mixcr installed using brew like this:
```
brew unlink mixcr
```

**Comment by dbolotin** [comment]
Connected to #211
