### ISSUE TITLE
Options for multiple mixcr calls with different parameters

### ISSUE THREAD

**Issue by dbolotin** [milaboratory/mixcr#225]
If user is able to run several mixcr commands in one go this will:

* simplify life for everyone
* speedup analysis because there will be no JVM startup overhead, and subsequent mixcr calls will be executed using JIT compiled/optimized code

One of use-cases is analysis of huge number of input files.

Options:

* piped commands

  ```
  cat commands.txt | mixcr !
  ```
  and all possible variations you can imagine with piping

* `parallel`-like interface:
  ```
  mixcr assemble {} {.}.clns ::: *.vdjca
  ```
  or even
  ```
  mixcr align {R}_R1.fastq.gz {R}_R2.fastq.gz {R}.vdjca ::: *_R1.fastq.gz
  ```
  and cartesian product
  ```
  mixcr exportClones -c {1} {2} {2.}.{1}.txt ::: *.clns ::: TRA TRB TRD TRG
  ```

Not sure if it is worth doing it, after reading this http://openjdk.java.net/jeps/295 .

**Comment by PoslavskySV** [comment]
https://mixcr.readthedocs.io/en/master/analyze.html
