### ISSUE TITLE
exportClone doesn't export any mutation

### ISSUE THREAD

**Issue by marijazmf** [milaboratory/mixcr#229]
Dear developers,

Congratulation for great job. The tool is very good. I have small issue during exporting clones. I am not sure  how to export mutations. I am doing analysis of data obtained using 5’RACE-based amplification protocols and I followed alignment and assembling procedure like it's described in [documentation](http://mixcr.readthedocs.io/en/latest/quickstart.html#analysis-of-data-obtained-using-5-race-based-amplification-protocols).  My issue is how to export mutations from clone file? Which genomic feature to use? I tried some of them but I got only "-" everywhere. 

Thanks in advance.
Best,
Marija

**Comment by PoslavskySV** [comment]
Dear Marija, 

can you paste here exact commands that you tried?

**Comment by marijazmf** [comment]
I tried several commands:
`mixcr exportClones --chains IGH clones.clns clones.txt`
`mixcr exportClones -nMutations VTranscript clones.clns clones.txt`

but it didint work.

Best,
Marija

**Comment by PoslavskySV** [comment]
As I see you use `VTranscript` feature to extract mutations, that is why you have no any results. If you use standard pipeline, clones are assembled (`mixcr assemble ...`) by CDR3 region, and only information about CDR3 region is available for output at `exportClones` step. So you can do e.g.

```
 mixcr exportClones -p all -nMutations GermlineVCDR3Part clones.clns clones.txt
```
this will add the last column to the standard output. We [plan](https://github.com/milaboratory/mixcr/issues/48) to implement assembling of out-of-clonal-sequence regions (basically everything up- and down- stream clonal sequence) soon, after that it will be possible to extract information from other than clonal sequence regions.

Now  you can export mutations from the raw alignments:
```
 mixcr exportAlignments -p all -nMutations VTranscript alignments.vdjca alignments.txt
```
-- this should give you results. And even better option available If your reads does not cover whole VTranscript:

```
mixcr exportAlignments \
         -nMutationsRelative FR1 VTranscript \
         -nMutationsRelative CDR1 VTranscript \
         -nMutationsRelative FR2 VTranscript \
         -nMutationsRelative CDR2 VTranscript \
         -nMutationsRelative FR3 VTranscript \
          your_data.vdjca output.txt
```

etc.

**Comment by marijazmf** [comment]
Thank you very much for your help. 
Best,
Marija
