### ISSUE TITLE
cloneId is not sequential?

### ISSUE THREAD

**Issue by suntaosimon** [milaboratory/mixcr#232]
e.g. 0,1,3,4,5,7,9,....
Because this has xcluded out of frames and sequences containing stop codons during exporting?

Thanks!

**Comment by dbolotin** [comment]
Yes, this is one of the reasons.

Generally, ids are not guaranteed to be sequential. And id assignment algorithm may change in the future.
The only guarantee about `cloneId`s are that they are unique, and  that they are the same as ids provided in `exportAlignments` `-cloneId <index_file>` column (see [here](http://mixcr.readthedocs.io/en/latest/export.html#available-fields)).
