### ISSUE TITLE
Data preprocessing and quality trimming

### ISSUE THREAD

**Issue by marijazmf** [milaboratory/mixcr#233]
Dear developer,

I am doing analysis of data obtained using 5’RACE-based amplification protocols. My main concern is should I  do some quality filtering before I run MiXCR pipeline (for ex. remove reads shorter than 150 bases, low quality reads ...)?
I tried with and without filtering, but in the case of trimmed data a lot of reads are unsuccessfully aligned.

  
![image](https://cloud.githubusercontent.com/assets/19795043/24710513/9e973222-1a1d-11e7-82c6-a14dce226dd2.png)

Thanks in advance.
Best,
Marija

**Comment by chudakovdm** [comment]
You could trim also the very bad positions. 

  PLaying with MiXCR quality filers may help you to extract more


>Среда,  5 апреля 2017, 17:34 +03:00 от marijazmf <notifications@github.com>:
>
>Dear developer,
>I am doing analysis of data obtained using 5’RACE-based amplification protocols. My main concern is should I  do some quality filtering before I run MiXCR pipeline (for ex. remove reads shorter than 150 bases, low quality reads ...)?
>I tried with and without filtering, but in the case of trimmed data a lot of reads are unsuccessfully aligned.
>Thanks in advance.
>Best,
>Marija
>—
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly,  view it on GitHub , or  mute the thread .


Dmitriy Chudakov, PhD, DSc.
Head of Genomics of Adaptive Immunity lab, Institute of Bioorganic Chemistry, Moscow, Russia 
Head of research group Adaptive Immunity, CEITEC, Masaryk University, Brno, Czech Republic

**Comment by chudakovdm** [comment]
PS: full length ananlysis with 5'RACE is not always good. I would concentrate on CDR3 with TCRs. 


>Среда,  5 апреля 2017, 17:34 +03:00 от marijazmf <notifications@github.com>:
>
>Dear developer,
>I am doing analysis of data obtained using 5’RACE-based amplification protocols. My main concern is should I  do some quality filtering before I run MiXCR pipeline (for ex. remove reads shorter than 150 bases, low quality reads ...)?
>I tried with and without filtering, but in the case of trimmed data a lot of reads are unsuccessfully aligned.
>Thanks in advance.
>Best,
>Marija
>—
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly,  view it on GitHub , or  mute the thread .


Dmitriy Chudakov, PhD, DSc.
Head of Genomics of Adaptive Immunity lab, Institute of Bioorganic Chemistry, Moscow, Russia 
Head of research group Adaptive Immunity, CEITEC, Masaryk University, Brno, Czech Republic

**Comment by PoslavskySV** [comment]
Already implemented.
