### ISSUE TITLE
Segment family output problems in exportAlignments

### ISSUE THREAD

**Issue by mikessh** [milaboratory/mixcr#246]
``-dGenes`` returns ``TRBD1`` which is OK, but ``-dFamilies`` returns ``TRBD1*00``, i.e. goes back to the allele level

**Comment by mikessh** [comment]
Same with V(?), e.g. ``TGCAGCAAGAAGACTCAGCTGCGTATCTCTGCACCAGCAGCCAAGGGGATCGCGGGGGGCCACTACAATGAGCAGTTCTTCGGGCCA`` returns TRBV1*00

**Comment by PoslavskySV** [comment]
Fixed via [repseqio 8668b23](https://github.com/repseqio/repseqio/commit/8668b23133dc8318ef3f4c255e100994f6e9bc3b)
