### ISSUE TITLE
Merged runs- different number of clones

### ISSUE THREAD

**Issue by innagsc** [milaboratory/mixcr#248]
I have a library that has been sequenced on a HiSeq rapid mode (2 lanes/runs). When I ran it through the MiXCR analysis for each run individually, I got the same number of clones for each sample. However, when I merged the Fastq files and ran it through the MiXCR analysis, there were some samples where I got more or fewer clones than for the individual runs. 

I will give an example:
Run1- sample4 -1854 clones
Run2- sample4 - 1854 clones
Merged run (concatenating the fastq files for each sample) - sample4 - 1851 clones

Any ideas?

Thank you in advance!

**Comment by dbolotin** [comment]
Sorry for the extremely delayed response. Such behaviour may be observed due to the error-correction algorithms applied on the assemble step. E.g. having the information combined from two samples, MiXCR manages to eliminate more artificial diversity.
