### ISSUE TITLE
Trim low quality letters on the end of reads ??

### ISSUE THREAD

**Issue by dbolotin** [milaboratory/mixcr#25]
Instead such low-qulity endings (with nearly random sequence) can lead to bad alignments with `j rightFloatingBound = false` ?

**Comment by mikessh** [comment]
I would not add such kind of options (trimming, adapter removal, etc) to the software, rather test them and put them as suggestion to corresponding (say, "data pre-processing") section of manual

**Comment by dbolotin** [comment]
Yes in general it should be done by external software. But with new default options presence of random tail could spoil alignment of J gene. Previous version was tolerant to this thing. So the reason here is to prevent substantial performance decrease on datasets where previous version worked successfully.

**Comment by dbolotin** [comment]
Experiments showed that this adverse effect is not the case in real data.
