### ISSUE TITLE
Connecting to github.com (github.com)|192.30.253.112|:443 failed.  I am using ubuntu 16.04

### ISSUE THREAD

**Issue by ala351970** [milaboratory/mixcr#250]

**Comment by ala351970** [comment]
I run the command in ubuntu 16.04 wget https://github.com/milaboratory/mixcr/releases/download/v1.8.1/mixcr-1.8.1.zip

but Connecting to github.com (github.com)|192.30.253.113|:443. failed?
any help

**Comment by mikessh** [comment]
Works fine for me. This has something to do with your connection to github

**Comment by ala351970** [comment]
how to fix that? I am connected to proxy

**Comment by mikessh** [comment]
don't know, try googling/checking at stackoverflow. this question is definitely out of scope of mixcr issue section, sorry

**Comment by dbolotin** [comment]
Also consider using recent version of MiXCR (2.1.3). Many enhancements and bug fixes were made since 1.8.1.
