### ISSUE TITLE
Java error on cluster - Wrong version...use Java 7 or above

### ISSUE THREAD

**Issue by c2b2pss** [milaboratory/mixcr#251]
I am trying to run mixcr on our cluster using java.  The env variables etc. for java are fine, and java -version shows

-bash-4.1$ java -version
java version "1.8.0_91"
Java(TM) SE Runtime Environment (build 1.8.0_91-b14)
Java HotSpot(TM) 64-Bit Server VM (build 25.91-b14, mixed mode)

But micr.jar always complains the version number is below 7.  I think the code for checking java version needs some tweaking...

Help!

**Comment by PoslavskySV** [comment]
How do you run MiXCR? What exact command you use?

**Comment by c2b2pss** [comment]
It is in a script as follows:

#!/bin/bash

#$ -cwd
#$ -j y
#$ -l mem=24G,time=3:15:15
#$ -S /bin/bash
#$ -N mixcr

source ~/.bash_profile
module load java
java -jar mixcr.jar align -p rna-seq -s hsa -OallowPartialAlignments=true AC25.fastq.bz2

**Comment by PoslavskySV** [comment]
As I see, you use PBS, so if you run on cluster, and you have a error with java version, it is definitely the case when the java version on the particular nodes is below 7. You can check it by enabling logs (e.g. `PBS -o path_to_my_log.log)` and adding `echo $(java -version)` to your pbs script.

**Comment by c2b2pss** [comment]
OK. Here is the log...ignore the file input error since I did not fix that.

java version "1.8.0_91"
Java(TM) SE Runtime Environment (build 1.8.0_91-b14)
Java HotSpot(TM) 64-Bit Server VM (build 25.91-b14, mixed mode)

Reference library: repseqio.v1.2:9606:1353156c3504ab36ef955667a3e344d1
Exception in thread "main" java.io.FileNotFoundException: AC25.fastq.bz2 (No such file or directory)
	at java.io.FileInputStream.open0(Native Method)
	at java.io.FileInputStream.open(FileInputStream.java:195)
	at java.io.FileInputStream.<init>(FileInputStream.java:138)
	at java.io.FileInputStream.<init>(FileInputStream.java:93)
	at com.milaboratory.core.io.sequence.fastq.SingleFastqReader.<init>(SingleFastqReader.java:65)
	at com.milaboratory.core.io.sequence.fastq.SingleFastqReader.<init>(SingleFastqReader.java:79)
	at com.milaboratory.mixcr.cli.ActionAlign$AlignParameters.createReader(ActionAlign.java:423)
	at com.milaboratory.mixcr.cli.ActionAlign.go(ActionAlign.java:175)
	at com.milaboratory.cli.JCommanderBasedMain.main(JCommanderBasedMain.java:155)
	at com.milaboratory.mixcr.cli.Main.main(Main.java:115)

**Comment by PoslavskySV** [comment]
So:
 1) if your java version < 7, MiXCR wouldn't run, since it is written in Java 7
 2) if your java version = 7 and you run MiXCR with "./mixcr ...", you will see the warning "Wrong version of java. Please use Java 7 or higher.", since Java 8 is much better and contains several important fixes (also we plan to fully migrate to Java8 in future)
 2) if your java version is >= 7 and you run MiXCR with "java -jar mixcr.jar ..." you will not see any warnings, and all will work fine with any Java >= 7

As far as I see from your last answer, your java version >= 8, and all works fine in your case (no warning "Wrong version of java. Please use Java 7 or higher" printed)

**Comment by c2b2pss** [comment]
Its working !!  Thanks for your immediate answers, much appreciated.

Actually, adding the "echo $(java -version)" to the script made the whole difference.....

Thanks again !

**Comment by c2b2pss** [comment]
One more thing: What about a reference file? I do not remember copying or downloading one on the server.  

Where is this stored "Reference library: repseqio.v1.2:9606:1353156c3504ab36ef955667a3e344d1"?
The libraries folder is empty.

Is mixcr calling out to a file online?

**Comment by PoslavskySV** [comment]
The built-in reference library is stored directly in the `mixcr.jar` file.
