### ISSUE TITLE
Clonal sequence quality

### ISSUE THREAD

**Issue by deryu** [milaboratory/mixcr#252]
Hello,

I ran mixcr and got the result files. 

I wonder some result columns.. try to find its meaning but i don't find. 

Here is my result.

Clone fraction | Clonal sequence quality(s) | All V hits | All D hits | All J hits | All C hits
0.970422691 | SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS | IGKV1-9*00(435.1),IGKV1-13*00(388.9),IGKV1-6*00(350.3) | IGKJ1*00(145.2) | IGKC*00(235)
0.022045028 | SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS | IGHV3-21*00(145.8),IGHV3-7*00(123) | IGHD3-16*00(37) | IGHJ4*00(119) | IGHG1*00(480.1),IGHG3*00(446)

I have two questions,
  1. In Clonal sequence quality, What is the meaning of the alphabet?
  2. What does the number in parentheses mean?

Please answer to me.
Thank you

**Comment by PoslavskySV** [comment]
Hi, 

1. `Clonal sequence quality(s)` is standard fastq quality in phred format
2. The number in parentheses is alignment score of corresponding hit
