### ISSUE TITLE
Are primers used for identifying the immunological chain (BCR/TCRa/TCRb)?

### ISSUE THREAD

**Issue by innagsc** [milaboratory/mixcr#253]
Hello,

Does anyone know how the MiXCR algorithm works? Does it look for the primers for assigning the immunological chain or does it look for the read sequence itself?

Thank you for your help :)

**Comment by PoslavskySV** [comment]
It looks for the read sequence itself and aligns it with the reference database of TRC/BCR genes. See 
[readthedocs.io](http://mixcr.readthedocs.io) and [original paper in Nature Methods](https://www.nature.com/nmeth/journal/v12/n5/full/nmeth.3364.html).
