### ISSUE TITLE
Add an option to export alignments in CIGAR format

### ISSUE THREAD

**Issue by mikessh** [milaboratory/mixcr#256]
subj. E.g. add ``-vAlignmentCigar``. I think we need soft clipping here

**Comment by javh** [comment]
The CIGAR specification we came up with for the AIRR standard is here:
http://airr-standards.readthedocs.io/en/latest/datarep/overview.html

Copy-paste for permanence:

Operator | Description
-- | --
= | An identical non-gap character.
X | A differing non-gap character.
M | A positional match in the alignment. This can be either an identical (=) or differing (x) non-gap character.
D | Deletion in the query (gap in the query).
I | Insertion in the query (gap in the reference).
S | Positions that appear in the query, but not the reference. Used exclusively to denote the start position of the alignment in the query. Should precede any N operators.
N | A space in the alignment. Used exclusively to denote the start position of the alignment in the reference. Should follow any S operators.

The use of either the =/X or M syntax is valid, but should be used consistently. While leading S and N operators are required, tailing S and N operators are optional.  S and N are the clipping operators we used to annotation both the `queryFrom` and `targetFrom` coordinates, respectively.
