### ISSUE TITLE
exportAlignments exception

### ISSUE THREAD

**Issue by bbimber** [milaboratory/mixcr#258]
Hello,

I've been running MiXCR for a while without issue on paired end input data.  I recently encountered an odd error when using exportAlignments.  I assume this indicates something like a single read pair in which only one of the two reads aligned?  My input data was paired end, and this file was created using 'mixcr align' with --save-description specified, so I'm not sure what caused the error.  The stack is below, I'm happy to send more detail if it helps.

```
02 Aug 2017 15:41:30,532 INFO :     /home/exacloud/lustre1/prime-seq/java/current/bin/java -Dmixcr.path=/home/groups/prime-seq/pipeline_tools/bin -Dmixcr.command=mixcr -XX:+AggressiveOpts -jar /home/groups/prime-seq/pipeline_tools/bin/mixcr.jar exportAlignments -f -vGene -dGene -jGene -cGene -vHit -dHit -jHit -cHit -vHitScore -dHitScore -jHitScore -cHitScore -readId -sequence -positionOf VEndTrimmed -positionOf JBeginTrimmed -positionOf CBegin -descrR1 -descrR2 /home/exacloud/lustre1/prime-seq/workDir/3c97a322-59fb-1035-9ae7-c8ba61884ab6/SequenceA.work/22436-Gag120-Clone-38_S6_L001_R1_001/Alignment/22436_Gag120-Clone-38.12.rhesus.align.vdjca.gz /home/exacloud/lustre1/prime-seq/workDir/3c97a322-59fb-1035-9ae7-c8ba61884ab6/SequenceA.work/22436-Gag120-Clone-38_S6_L001_R1_001/Alignment/22436_Gag120-Clone-38.12.rhesus.alignments.txt
02 Aug 2017 15:41:30,534 DEBUG: using path: /home/exacloud/lustre1/prime-seq/java/current/bin:/home/groups/prime-seq/pipeline_tools/bin/:/home/exacloud/lustre1/prime-seq/java/current/bin/:/state/partition2/opt/installed/sra-tools-2.8.0-2/bin:/opt/openmpi/bin:/usr/lib64/qt-3.3/bin:/usr/local/bin:/bin:/usr/bin:/opt/ganglia/bin:/opt/ganglia/sbin:/usr/java/latest/bin:/opt/rocks/bin:/opt/rocks/sbin:/opt/condor/bin:/opt/condor/sbin
02 Aug 2017 15:41:31,436 DEBUG:     Exporting alignments: 0%
02 Aug 2017 15:41:31,908 DEBUG:     Exception in thread "main" java.lang.IllegalArgumentException: Error for option '-descrR2':
02 Aug 2017 15:41:31,909 DEBUG:     No description available for second read: either re-run align action with --save-description option or don't use '-descrR2' in exportAlignments
02 Aug 2017 15:41:31,910 DEBUG:         at com.milaboratory.mixcr.export.FieldExtractors$25.extract(FieldExtractors.java:485)
02 Aug 2017 15:41:31,911 DEBUG:         at com.milaboratory.mixcr.export.FieldExtractors$25.extract(FieldExtractors.java:480)
02 Aug 2017 15:41:31,912 DEBUG:         at com.milaboratory.mixcr.export.FieldParameterless$1.extractValue(FieldParameterless.java:60)
02 Aug 2017 15:41:31,913 DEBUG:         at com.milaboratory.mixcr.export.InfoWriter.put(InfoWriter.java:82)
02 Aug 2017 15:41:31,914 DEBUG:         at com.milaboratory.mixcr.cli.ActionExportAlignments.go0(ActionExportAlignments.java:58)
02 Aug 2017 15:41:31,915 DEBUG:         at com.milaboratory.mixcr.cli.ActionExport.go(ActionExport.java:52)
02 Aug 2017 15:41:31,916 DEBUG:         at com.milaboratory.cli.JCommanderBasedMain.main(JCommanderBasedMain.java:155)
02 Aug 2017 15:41:31,917 DEBUG:         at com.milaboratory.mixcr.cli.Main.main(Main.java:115)
02 Aug 2017 15:41:31,938 WARN :     process exited with non-zero value: 1
02 Aug 2017 15:41:31,939 INFO : Failed to complete task 'org.labkey.sequenceanalysis.pipeline.SequenceAlignmentTask'
```

**Comment by bbimber** [comment]
Hi Dmitry - here's the file you requested.  let me know if there's anything else that would help.

[22436_Gag120-Clone-38.12.rhesus.align.vdjca.gz](https://github.com/milaboratory/mixcr/files/1200357/22436_Gag120-Clone-38.12.rhesus.align.vdjca.gz)

**Comment by dbolotin** [comment]
@bbimber can you please also share your segment library, I can't reproduce the problem without it.

**Comment by bbimber** [comment]
here you go.  this is just a JSON file renamed to .txt so github will accept it

[rhesus_v1.9.2.json.txt](https://github.com/milaboratory/mixcr/files/1496955/rhesus_v1.9.2.json.txt)

**Comment by dbolotin** [comment]
Can you please send me compiled library (`repseqio compile rhesus_v1.9.2.json rhesus_v1.9.2.compiled.json.gz`) to incorporate all sequences into it, this time I failed to reproduce the problem due to the absent `LT160002.fasta` file.
Another question, how many `assemblePartial` iteration have you performed for the `.vdjca` file?

**Comment by bbimber** [comment]
yes, good point.  compiled file attached.

we run assemblePartial twice.
[rhesus_v1.9.2.compile.json.gz](https://github.com/milaboratory/mixcr/files/1497352/rhesus_v1.9.2.compile.json.gz)

**Comment by dbolotin** [comment]
Are you sure the input was paired-end? All alignments in the file has only one target sequence, and I haven't found any evidence of `overlap` or `assemblePartial` events (that could possibly merge two reads and somehow mess with the description lines). Though, I am not 100% sure about this conclusion, and if you still think the data was paired-end, it would be great to have raw data (you can send me link by email) and exact pipeline of commands to reproduce this.

**Comment by bbimber** [comment]
Hi Dmitri - i have no idea how this happened, but you are exactly right.  we run all our data through a largely automated pipeline and somehow the first time through this sample was treated as single-end.  the unrelated issue about wildcards in sequence has been blocking me from retrying this sample since we first saw the error, but you are almost certainly right this would fix it.  Sorry for the bad error report.

**Comment by dbolotin** [comment]
No problem.
