### ISSUE TITLE
Lack of clones and droped but those could be aligned from BLAST(bug?)

### ISSUE THREAD

**Issue by suntaosimon** [milaboratory/mixcr#262]
Almost every sample has the same problem. 
From the report: Reads dropped due to the lack of a clone sequence: 174177 (45.95%). This percentage is always from 30%~50%. I have checked with the aligned sequence, as shows below(a typical sequence that drops due to lack of a clone), the highlighted position is always the same position that can not be mapped in 30%-50% of the sequences, then these sequences will be dropped (30%~50% sequences of each sample). 
![image](https://user-images.githubusercontent.com/3598340/28992042-eba86840-79c4-11e7-897b-3f356aaf4a3a.png)

But I use BLAST to align the bases from 0 to 79 and it can be mapped. 

![image](https://user-images.githubusercontent.com/3598340/28992044-04c130d2-79c5-11e7-93a9-893773cfe0f2.png)

Have checked with the TRBV20 sequence, GGTGCTGTCGTCTCTCAACATCCGAGCTGGGTTATCTGTAAGAGTGGAACCTCTGTGAAGATCGAGTGCCGTTCCCTGGACTTTCAGGCCACAACTATGTTTTGGTATCGTCAGTTCCCGAAACAGAGTCTCATGCTGAT_GGCAACTTCCAATGAGGGCTCCAAGGCCACATACGAGCAAGGCGTCGAGAAGGACAAGTT_TCTCATCAACCATGCAAGCCTGACCTTGTCCACTCTGACAGTGACCAGTGCCCATCCTGAAGACAGCAGCTTCTACATCTGCAGTGCTAGAGA
Looks like the unmapped site is in there and should be mapped.

The typical commands I used is,

```
align --chains ALL --species hsa --parameters rna-seq -OallowPartialAlignments=true -OvParameters.geneFeatureToAlign=VTranscript --report alignmentReport.log clean_R1.fastq.gz clean_R2.fastq.gz alignment.vdjca

assemble --report clonReport.log -ObadQualityThreshold=10 -OmaxBadPointsPercent=0.9 alignment.vdjca alignment.clns
```

Our protocols is RNA+5RACE. 

What could the issue be?

BTW, how to set floatingRightBound of J as false? 
-OvParameters.parameters.floatingRightBound=false means VJC are all false? how to set only J and C are false?

Thanks!

**Comment by PoslavskySV** [comment]
> BTW, how to set floatingRightBound of J as false?
-OvParameters.parameters.floatingRightBound=false means VJC are all false? how to set only J and C are false?

for J gene you can use
```
-OjParameters.parameters.floatingRightBound=false
```
and similarly for C gene. But I'm not sure it is worth doing in rna-seq mode (in fact I strongly suggest against it).

Regarding the missed alignments, they probably have too low score (very short V part), so you can try to adjust the scoring scheme if you really sure that you need this.
