### ISSUE TITLE
reconstruct full-length receptors?

### ISSUE THREAD

**Issue by dkoppstein** [milaboratory/mixcr#263]
Hi, quick question -- is it currently possible to reconstruct full-length receptors using MIXCR? I've tried doing doing this on RNA-seq data by using e.g. -nFeature FR1 when exporting the alignments, but can only get the CDR3 sequence. This is counterintuitive to me since the CDR3 is the least-defined region. 

I guess one could use Trinity on the read IDs aggregated clones, but I haven't tried that yet. Just wanted to ask if you guys already have a workflow for doing this. Thanks!

**Comment by dbolotin** [comment]
Hi. For now it is possible to assemble only CDR3 sequence from several disjoint sequences (as described [here](http://mixcr.readthedocs.io/en/latest/rnaseq.html)).

By default aligner discards sequences without CDR3 (or without CDR3 fragments with ` -OallowPartialAlignments=true`). It is possible to disable this filter with `-OallowNoCDR3PartAlignments=true` (not yet documented):
```
mixcr align -p rna-seq -OallowPartialAlignments=true -OallowNoCDR3PartAlignments=true input_R1.fastq.gz input_R2.fastq.gz output.vdjca
```
but they still will be ignored by `assemblePartial`, though you can use raw alignments from `exportAlignments`.

We have plans to implement functionality as you described. Assembling of wider than CDR3 sequences will be implemented in two ways: (i) by extending algorithm of `exportAlignments` (follow `custom_feature_assemblePartial` branch of this repo), and, also, (ii) additional exporting options that will make it possible to export original sequences for clones (as you mentioned) for software like Spades. But, unfortunately this features will be implemented not earlier than the end of autumn.

Hope this will help.

**Comment by dkoppstein** [comment]
Hi Dmitry, thanks for the reply. I recently joined a lab in Australia and we recently released an updated version of VDJPuzzle that can do BCR reconstruction using Trinity, so I just wanted to run MIXCR in parallel as a comparison if it can do the BCR reconstruction as well. We cited MIXCR in our preprint and use MiGMAP in the pipeline, so we really appreciate your software and look forward to the functionality you describe in MIXCR. 

Many thanks,
David

**Comment by dbolotin** [comment]
All base stuff is implemented, functionality work in development branch, a lot of technical issues still remains. Will be released with 2.2.

**Comment by sumetha** [comment]
Hi Dmitry,

I'm trying to use the development branch, I'm still not able to generate the full-length receptor. 

This is the command I'm using to get the alignment,
mixcr exportAlignmentsPretty  ai.vdjca a_PRETTY_ALIGNMENT_DETAIL.txt

And the alignment file looks like this;

>>> Read ids: 69786

                                 V><J CDR3><FR4                       
                 Q  Y  N  S  Y  P  R  T  F  G  G  G  T  K  L  E _     
    Quality     66666767777777776777275767767766625777767572267277    
    Target0   0 CAATATAACAGCTATCCTCGGACGTTCGGTGGAGGCACCAAGCTGGAAAT 49   Score
IGKV6-15*00 327 caatataacagctatcctc                                345  95
   IGKJ1*00  22                    ggacgttcggtggaggcaccaagctggaaat 52   155
    69786R0   0 caatataacagctatcctcggacgttcggtggaggcaccaagctggaaat 49  

I'm getting those reconstructed CDR3 regions , not the full receptor though.  Am i missing something > Should I be use someother option?

**Comment by dbolotin** [comment]
Hi,

please see this answer for the pipeline:
https://github.com/milaboratory/mixcr/issues/372#issuecomment-381033074

Please also note that this functionality is still under development. Hope, it will be finished by the end of June.

Best!
Dmitry.

**Comment by sumetha** [comment]
Thanks for the response Dmitry. I tried the binary and it worked. Now I have the full length clonal sequence.
