### ISSUE TITLE
MiXCR 2.1.5 lists more total reads than are present in fastq file

### ISSUE THREAD

**Issue by DanteBortone** [milaboratory/mixcr#265]
First of all, thank you so much for creating MiXCR.  It's done a lot of great work for us. We even tested it and found that it performed much better against TRUST.  Additionally, your documentation is outstanding. So thanks!

Now for my issue: When I look at the alignment logs the total sequencing reads listed is more than what is in the original fastq.  I reverted to 2.0.3 and this didn't happen.

When I look at the alignment log ----
Total sequencing reads: 55811

When I just look at how many lines are in the file -----
my_fastq.fastq | echo $((`wc -l`/4)) 
53398
FastQC output also agrees with the wc command for read count.

When I run an older version of MiXCR (2.0.3) ----
Total sequencing reads: 53398

I've tried both the basic command:
mixcr align -f \
    -r alignment_log.txt \
    -s hsa \
    -t 6 \
  R1_001.fastq.gz R2_001.fastq.gz alignment.vdjca

and more complicated calls:
mixcr align -f \
  --save-reads \
  --library imgt \
  --not-aligned-R1 unaligned_R1.fastq \
  --not-aligned-R2 unaligned_R2.fastq \
  -r alignment_log.txt \
  -c TRB \
  -s hsa \
  -t 6 \
  R1_001.fastq.gz R2_001.fastq.gz alignment.vdjca

...and have gotten the same problem with 2.1.5.

Even the reported successfully aligned reads (55503) is more than the total reads in the original fastqs.  Any thoughts?

Kind regards,
Dante

**Comment by DanteBortone** [comment]
I tested several versions to isolate where the total read count was off:
2.1.5: 55811 reads
2.1.1: 55811 reads
2.1: 55812 reads
2.0.4: 53398 reads
2.0.3: 53398 reads

Looks like the transition to 2.1 is where the problem occurred.

**Comment by dbolotin** [comment]
Sorry for delayed response. Thanks for reporting! This definitely looks like a bug, we'll look into it soon.
