### ISSUE TITLE
Keep presence of alignment and assembly report fields consistent

### ISSUE THREAD

**Issue by joltex** [milaboratory/mixcr#268]
Sometimes certain alignment and assembly report fields are missing. For example, "Alignment failed because of low total score" appears for some samples or sequencing runs but not for others. I assume this is because some samples have no reads failing alignment for this reason - they might be MiGEC / high quality reads for example.

This makes summarizing multiple samples or sequencing runs more troublesome. It would be better to always show these fields and give a value of '0' if the given sample had no reads falling into the given category.

**Comment by dbolotin** [comment]
Sorry for delayed response. Agree! We will add JSON report output option. In this case, it will be even possible to quick-summarise results with util like `jq`. Will it solve the problem for you?

**Comment by joltex** [comment]
Yes, I think a JSON report would be great. I generally parse all the individual report files for a sequencing run of many samples to generate a single report table.

**Comment by dbolotin** [comment]
Good! The plan now is to implement each report as single line JSON (like described [here](http://jsonlines.org/)), so you can specify the same file in several mixcr invocations, and each subsequent report will be added to it line by line.
