### ISSUE TITLE
Export field "BestJGene might be wrong

### ISSUE THREAD

**Issue by fabio-t** [milaboratory/mixcr#273]
Example to show what I mean:

| bestVGene | bestJGene | bestVFamily | bestJFamily |
| -- | -- | -- | -- |
| TRAV7-2 | TRAJ30 | TRAV7 | TRAJ30 | 
| TRAV9-2 | TRAJ23 | TRAV9 | TRAJ23 | 

`bestVGene` contains the full gene name, while `bestVFamily` doesn't (correctly). `bestJGene`, however, is exactly equal to `bestJFamily`. This seems wrong.

**Comment by fabioticconi** [comment]
Note how I used "might" - it could be that the J gene doesn't have "variants", and so there's only one "Family" for each gene. It was better to be safe (and submit this issue) than be sorry :)

**Comment by mikessh** [comment]
My only explanation is that best V family is chosen as a family with highest **average** alignment score across corresponding genes. If this is true, we can have J1-1(200)/J1-2(100) and J2-1(160)/J2-2(160) resulting in J1-1 gene and J2 family. @dbolotin @PoslavskySV correct me if I'm wrong

**Comment by fabio-t** [comment]
@dbolotin, to be honest, I think I'm wrong and the MIXCR output for TRAJ is correct. There doesn't seem to be any subgroup for the TRAJ gene so it stands to reason that "family" and "gene" must be the same. Here is the [IMGT reference](http://imgt.org/IMGTrepertoire/Proteins/taballeles/mouse/TRA/TRAJ/Mu_TRAJall.html). My mistake for not checking it before.

However, there might still be a problem with the export - but for TRAV :)

For a gene like `TRAV7D-2`, the export would have clearly `TRAV7D-2` in the `bestVGene` field, and `TRAV7D` in the `bestVFamily` field. However, according to this [IMGT reference](http://imgt.org/IMGTrepertoire/Proteins/taballeles/mouse/TRA/TRAV/Mu_TRAVall.html), the family name should just be `TRAV7`.

Our collaborators have complained about this, so I need to manually postprocess the export output to strip D and N from the family field.

What is your opinion on this?

**Comment by dbolotin** [comment]
Ok, now I see. Yes we will fix this in the next release. I will leave this issue opened until then.

**Comment by mikessh** [comment]
@fabio-t @dbolotin just wanted to note that I've interpreted the original post incorrectly - I thought that the name of the family is not a substring of gene name :)

Now it looks like it all arrives to naming convention in https://github.com/repseqio

**Comment by dbolotin** [comment]
Will be fixed with https://github.com/repseqio/repseqio/pull/36

**Comment by dbolotin** [comment]
Fixed as repseqio/repseqio#36 is merged.
