### ISSUE TITLE
Overlap Sequences

### ISSUE THREAD

**Issue by sumetha** [milaboratory/mixcr#274]
Hi, 

Is it possible to get the overlap sequences from the paired-end RNA seq reads? 

I'm using this code to obtain the overlapped sequences/alignments.  However, it is unsuccessful.  I would like to see all the overlapping sequences.

mixcr assemblePartial -f -OminimalAssembleOverlap=10 \
x.vdjca \
x_ovelapped.vdjca

alignment Report after the initial align:
```
============= Report ==============
Analysis time: 5.86m
Total sequencing reads: 3086677
Successfully aligned reads: 3026211 (98.04%)
Alignment failed, no hits (not TCR/IG?): 3 (0%)
Alignment failed because of absence of V hits: 13 (0%)
Alignment failed because of absence of J hits: 55844 (1.81%)
Alignment failed because of low total score: 4606 (0.15%)
Overlapped: 1782871 (57.76%)
Overlapped and aligned: 1739652 (56.36%)
Overlapped and not aligned: 43219 (1.4%)
TRA chains: 2485302 (100%)
TRB chains: 4 (0%)
```

However after runniing the assemblepartial on the .VDJCA file i get this report. 
```
============= Report ==============
Analysis time: 3.96m
Total alignments analysed: 2485306
Number of output alignments: 2485306 (100%)
Alignments already with CDR3 (no overlapping is performed): 2455219 (98.79%)
Successfully overlapped alignments: 0 (0%)
Left parts with too small N-region (failed to extract k-mer): 3 (0%)
Extracted k-mer diversity: 447059
Dropped due to wildcard in k-mer: 0 (0%)
Dropped due to too short NRegion parts in overlap: 0 (0%)
Dropped overlaps with empty N region due to no complete NDN coverage: 0 (0%)
Number of left-side alignments: 19054 (0.77%)
Number of right-side alignments: 28516 (1.15%)
Complex overlaps: 0 (0%)
Over-overlaps: 0 (0%)
Partial alignments written to output: 30087 (1.21%)
```

**Comment by dbolotin** [comment]
Hi,

could you please provide some more details on the way the data was generated? Judging by the percent of aligned reads, some enrichment procedure (*in-silico* or *in-vitro* ?)  was applied to the sample.

MiXCR *RNA-Seq* pipeline was developed for processing of randomly shred, non-enriched or weekly enriched datasets, while your sample seems to be framed around CDR3 and to have remarkable enrichment level. So the common MiXCR pipeline (without `assemblePartial`) seems to be more suitable for the data.
