### ISSUE TITLE
"-v" for "--verbose" instead of "--write-all"

### ISSUE THREAD

**Issue by dbolotin** [milaboratory/mixcr#279]

**Comment by wangyingzhen** [comment]
If  "-v" is meaning for "--verbose", so how can i trace these non-aligned reads  and export well formatted alignments of them(such as "absence of J hits") for manual inspection?

**Comment by PoslavskySV** [comment]
@wangyingzhen with `--write-all`

**Comment by PoslavskySV** [comment]
Finally, I propose to remove `-v` at all (to avoid confusing with `--version` etc.) and leave only `--verbose` for verbose output.
