### ISSUE TITLE
Conda package for mixcr

### ISSUE THREAD

**Issue by sebastian-luna-valero** [milaboratory/mixcr#289]
Hello,

@hkoohy and I are interested in building a [conda](http://bioconda.github.io/) package for mixcr.

Is there any effort being made in that direction? 

If not, would you be willing to help us in the process of building the conda package for mixcr?

Best regards,
Sebastian

**Comment by dbolotin** [comment]
Dear Sebastian,

No efforts in this direction were made. Actually conda seemed to me very Python-centric, but now I see that there are many native, Java etc. projects in conda repos.

Main question here is compatibility of our license with such type of distribution. I will discuss this with our legal guys. IANAl, but I think, if it is possible to place package in our own repo, we can easily assemble conda package, and maintain updated versions in it.

If you have any examples of free-for-academic-use software distributed through conda, it would be great if you post some links here!

Best,
Dmitry.

**Comment by sebastian-luna-valero** [comment]
Dear Dmitry,

That's great, many thanks.

Indeed, GenomeAnalisysTK version 3 (aka GATK), is an example:
http://bioconda.github.io/recipes/gatk/README.html

Best regards,
Sebastian

**Comment by dbolotin** [comment]
Thanks for the link!

**Comment by hkoohy** [comment]
thanks

**Comment by sergiigladchuk** [comment]
Hi all,
I cannot find it on bioconda now, it is not listed in the index.
Link 
[https://bioconda.github.io/recipes/mixcr/README.html]()
is broken

**Comment by PoslavskySV** [comment]
Hi,

currently MiXCR is not available from Bioconda (see [this](https://github.com/bioconda/bioconda-recipes/pull/19668)). We will put it back at some moment in the near future when the licensing infrastructure on our backend will be ready.

Meanwhile you can use Homebrew:
```
brew tap milaboratory/all
brew install mixcr
```

or just download package from the [Releases page](https://github.com/milaboratory/mixcr/releases).

If you use Docker we have official image https://hub.docker.com/r/milaboratory/mixcr

**Comment by sergiigladchuk** [comment]
Thanks, I see now,
Would be great to get it back on Bioconda - our HPC does not support docker. 
So meanwhile I will test the tool locally in Docker.
