### ISSUE TITLE
No percentage of all chains in clonReport.log anymore?

### ISSUE THREAD

**Issue by suntaosimon** [milaboratory/mixcr#319]
Report file seems changed after upgrade the software.
How can we get back the No percentage of all chains?
like this,

TRA chains: 1 (0%)
TRB chains: 41947 (100%)
TRG chains: 1 (0%)

**Comment by dbolotin** [comment]
Sorry there is no flags to change report format to the previous one. Actually text report file was not originally intended for automated parsing, so we were not very careful about it's format backward compatibility, and never guaranteed it.

However we indeed see the need for automated ingestion of the information contained in report files, so we introduced JSON reporting option staring from MiXCR v2.1.6 (see [release notes](https://github.com/milaboratory/mixcr/releases/tag/v2.1.6)). You can expect consistent field names across versions for reports (some changes may happen before 2.3 release, when we plan to freeze the format, but this changes are still much more unlikely then changes in text reports). Docs for json-report format coming soon, though I hope field names are pretty self-explanatory. So, if you have some automation scripts on top of mixcr, I strongly recommend you to migrate it to using json-reporting.
