### ISSUE TITLE
`NullPointerException` error during assemble step

### ISSUE THREAD

**Issue by lpryszcz** [milaboratory/mixcr#320]
`~/src/mixcr/mixcr assemble -p default_affine -r mixcr/$s.assemble.log -OassemblingFeatures=VDJRegion -OseparateByC=true -OqualityAggregationType=Average -OclusteringFilter.specificMutationProbability=1E-5 -OmaxBadPointsPercent=0 mixcr/$s.vdjca mixcr/$s.clns`
Exception in thread "main" java.lang.NullPointerException
	at com.milaboratory.mixcr.cli.ActionAssemble.go(ActionAssemble.java:81)
	at com.milaboratory.cli.JCommanderBasedMain.main(JCommanderBasedMain.java:155)
	at com.milaboratory.mixcr.cli.Main.main(Main.java:115)

I've tried v2.1.8 on java 1.8 (Ubuntu 16.04), both openjdk and oracle. 
`java -version`
openjdk version "1.8.0_121"
OpenJDK Runtime Environment (Zulu 8.20.0.5-linux64) (build 1.8.0_121-b15)
OpenJDK 64-Bit Server VM (Zulu 8.20.0.5-linux64) (build 25.121-b15, mixed mode)

`java -version`
java version "1.8.0_151"
Java(TM) SE Runtime Environment (build 1.8.0_151-b12)
Java HotSpot(TM) 64-Bit Server VM (build 25.151-b12, mixed mode)

**Comment by lpryszcz** [comment]
The `mixcr assemble` works ok if I don't specify `-p default_affine`

**Comment by dbolotin** [comment]
Thanks for reporting!

What MiXCR version was used to produce input `.vdjca` file? If you don't remember you can check it by running the following command:
```
mixcr versionInfo alignments.vdjca
```

**Comment by dbolotin** [comment]
Sorry! I figured it out. We changed the behaviour of this part, so that it is no longer required to specify different `assemble` parameters for alignments produced produced with different alignment parameters. Parameters that has to be changed now are inferred automatically. So, just run `assemble` without `-p` option.

I will fix this in docs right away.
