### ISSUE TITLE
external library issue

### ISSUE THREAD

**Issue by yingzhang121** [milaboratory/mixcr#324]
Hi, developer,

I tried to use an external library called primate.json, which is a merge of imgt data of rhesus monkey and macaca Fascicularis. Then when I ran mixcr using command:
mixcr align -p rna-seq -OallowPartialAlignments=true -f --library primate work/test_R1_001.fastq work/test_R2_001.fastq aln.vdjca

I got the following error:

Exception in thread "main" java.lang.RuntimeException: Can't find library for following library name and species: primate + hs
	at io.repseq.core.VDJCLibraryRegistry.getLibrary(VDJCLibraryRegistry.java:376)
	at io.repseq.core.VDJCLibraryRegistry.getLibrary(VDJCLibraryRegistry.java:278)
	at com.milaboratory.mixcr.cli.ActionAlign.go(ActionAlign.java:132)
	at com.milaboratory.cli.JCommanderBasedMain.main(JCommanderBasedMain.java:155)
	at com.milaboratory.mixcr.cli.Main.main(Main.java:115)

So I had to run mixcr like: mixcr align -p rna-seq -OallowPartialAlignments=true -f --library imgt -s 9544 work/test_R1_001.fastq work/test_R2_001.fastq aln.vdjca

Could you provide a solution for the --library primate case?

Best,
Ying

**Comment by PoslavskySV** [comment]
Could you please provide exact commands that you used to make up primate.json ?

**Comment by yingzhang121** [comment]
Sure. Under my mixcr installation directory, I made the libraries directory:

~/src/mixcr/libraries/library-imgt-2$ ls
build.sh  cache  exec.sh  jq-linux64  output  README.md  rules

Then I installed pup and jq, with go/1.9.0 and java/jdk1.8.0_144.

After that I ran: ./build.sh full
So I got the following output directory (there are a few hundred files, using macacaFascicularis as an example):
ls output/macacaFascicularis_*
output/macacaFascicularis_D_IGH.fasta          output/macacaFascicularis_J_IGH.json
output/macacaFascicularis_D_IGH.fasta.mifdx    output/macacaFascicularis_J_IGH.json.compiled
output/macacaFascicularis_D_IGH.json           output/macacaFascicularis_V_IGH.fasta
output/macacaFascicularis_D_IGH.json.compiled  output/macacaFascicularis_V_IGH.fasta.mifdx
output/macacaFascicularis_J_IGH.fasta          output/macacaFascicularis_V_IGH.json
output/macacaFascicularis_J_IGH.fasta.mifdx    output/macacaFascicularis_V_IGH.json.compiled

Then I cat the json files to primate.json.

**Comment by yingzhang121** [comment]
Actually, my point is I want to use multiple species as the reference.  My project uses a species of Macaca Monkeys, which is not in IMGT. So I would like to use the closest relatives: rhesus monkey, macaca Fascicularis and human.  That is why I tried to make a primate-only library, and hope the program will compare to all the 3 species included in the library files.

By enforcing a single species option is really limiting here.

**Comment by dbolotin** [comment]
Ok. Each library is just a json file, and you can easily copy records from one library to another one, under the same species name, and then use it in MiXCR. Please see [JSON format description draft](https://github.com/repseqio/repseqio/wiki/repseqio-JSON-library-format), hope this will provide some help.

I suggest the following pipeline: 

1. Start from repseqio human reference ([link](https://github.com/repseqio/library/tree/master/human))

2. Merge all libraries into a single file for simplicity:
    ```
    repseqio merge *.json human.json
    ```

3. Preprocess files imported from IMGT to prevent duplicate gene names:
  - merge all files for a single specific species using `repseqio` (`*.json`, do not use `.json.compiled`) 
  - keep corresponding fasta files in the same folder
  - rename all genes inside the library with `jq`. Like this:
    ```
    jq '.[].genes[].name |= sub("\\*"; "-macacaFascicularis*")' macacaFascicularis.json > macacaFascicularis_updated.json
    ```
    (see [jq](https://stedolan.github.io/jq/manual/) docs for details) this will e.g. rename `TRBV1*00` into `TRBV1-macacaFascicularis*00`
    (you can do the same transformation with original file, to make library more homogeneous)
4. Directly add records from one file to another:
  - extract only genes section from the file (you can combine it with previous command):
    ```
    jq '.[0].genes' macacaFascicularis_updated.json > macacaFascicularis_genes.json
    ```
  - add this records "as is" to the original file:
    ```
    jq --slurpfile genes macacaFascicularis_genes.json '.[].genes += $genes' human.json > human_and_macacaFascicularis.json
    ```

Please let me know your thoughts on this.

P.S. While in principal it is possible to add several species to analysis, this will at least produce ambiguity on the export step, as genes from different species may have the same names, and there are no means to distinguish between them. And, though, even this can be overcome, by adding species field to the export, overall added complexity for now seems to be too high for such rare case.

**Comment by yingzhang121** [comment]
@dbolotin , you have a good point on the sequence name. Practically, I don't care whether they are the same name or not. I only need to identify all the clone type in my project. So I could simply rename the sequences to follow some numeric order.  Once I have all CDR determined, then I could go back to map the names for each VDJ region.
