### ISSUE TITLE
Performance of assemblePartial. Can it be multi-threaded too?

### ISSUE THREAD

**Issue by yingzhang121** [milaboratory/mixcr#326]
I might miss the point, but after digging into the options, I found no "-thread" option for the assemblePartial function. For other functions, such as align, assemble, the default threading is 24, so these functions could be done within a reasonable time. But the performance of the assemblePartial is really worse when the input alignment is big. I made the following plot to show the nearly-exponential increase of running time given the increase of input alignment numbers.

So could you optimize the code to let it capable of multi-threading too?

![image](https://user-images.githubusercontent.com/11682666/35230140-d52db23e-ff5a-11e7-8147-1e3c0d78359e.png)

**Comment by PoslavskySV** [comment]
The algorithms used in `assemblePartial` are not parallelizable by their nature (at least, that would be extremely hard to implement). In fact, these algorithms have polynomial complexity (not exponential), so with the increase of reads count, the time needed to assemble long contigs increases as a power of read count.

However, the use-case of `assemblePartial` is analysis of RNA-Seq data which typically contains very few potentially interesting sequences (having either V or J hits), so the `assemblePartial` works extremely fast on such input. `assemblePartial` is not intended for use with enriched data.

**Comment by yingzhang121** [comment]
So do you recommend to skip this step for enriched (RNA-Seq) data?

**Comment by dbolotin** [comment]
Could you please describe sample preparation protocol in some more details. What technique was used for enrichment?

**Comment by yingzhang121** [comment]
@PoslavskySV forgot to mention the read length is 300 bp (MiSeq run).

**Comment by PoslavskySV** [comment]
You definitely don't need to run `assemblePartial` on such long reads. Additionally, as it is seen from the report, the number of  "Alignment failed because of absence of CDR3 parts: 10465 (0.69%)" is quite small, so even with the use of `assemblePartial` you will recover a tiny fraction of CDR3 sequences.

Summarizing: `assemblePartial` should be used only for non-enriched or randomly shred cDNA / gDNA RNA-Seq data with quite short reads. This function is useful when the data contains a really tiny fraction of TCR/IG sequences (few dozens or hundreds) in order to recover as much information as possible from such poor data.

**Comment by yingzhang121** [comment]
@PoslavskySV Thank you so much for this piece of advice.

**Comment by dbolotin** [comment]
I confirm, that `assemblePartial` is not needed for the data. If specific primer was used to amplify the library, all molecules should start from the same position and most probably all cover CDR3.

I, just in case, added specific note to the RNA-Seq section to distinguish this types of data, it may help somebody in the future.

**Comment by yingzhang121** [comment]
@dbolotin Yeah, this will be extremely useful to beginners like me.  While trying to make sense out of the data, I also need to make sense out of the program/tool.
