### ISSUE TITLE
Is there Homsap IGHV5-10-1 in MiXCR?

### ISSUE THREAD

**Issue by MathildeFogPerez** [milaboratory/mixcr#327]
Dears,

I used the latest version of MiXCR (2.1.8) and one of my antibody sequence was assigned to IGHV5-51*00(1161). But it should be assigned  IGHV5-10-1 (confirmed by IMGT).
The sequence is: 
GAAGTGCAGCTGGTGCAGTCCGGAGCAGAGGTGAAAAAGCCCGGGGAGTCTCTGAGGATCTCCTGTGAGGCTTCTGGATACAGCTTTATCAGTTTCTGGATCAACTGGGTGCGCCAGATGCCCGGGAAAGGCTTGGAGTGGATGGGGAGGATTGATCCTAGTGACTCTTATACCGACTACAGCCCGTCCTTCCAAGGCCACGTCACCATCTCAGCTGACAAGTCCATCAGCACTGCCTACCTGCAGTGGAGCAGCCTGAAGGCCTCGGACACCGCCATGTATTACTGTGCGAGATCCCCTCACGGGGGGTACTACTACTACTACATGGACGTCTGGGGCAAAGGGACCACGGTCACCGTCTCCTCAG

Then I checked a repertoire that I run previously with MiXCR version 2.1.5, and none of the 100.000 sequences was assigned to  IGHV5-10-1.
So I am wondering if you removed this vGene in MiXCR?
That would be a problem for my analysis, since I use the info related to the Valignment, it gives me too many mutations with IGHV5-51.

Thanks a lot in advance.
Best,
Mathilde

**Comment by dbolotin** [comment]
Dear Mathilde,

Thanks for reporting this!

You can directly use IMGT library in MiXCR, please see corresponding section:
http://mixcr.readthedocs.io/en/latest/importSegments.html#imgt-library
Here is the link to the most recent library:
https://github.com/repseqio/library-imgt/releases/download/v2/imgt.201802-5.sv2.json.gz

Our default reference is based on genomic assemblies, namely IGH is currently based on NG_001019.5, and there is no IGHV5-10-1 in that contig. NCBI updated the sequence with NG_001019.6, where, as I understand, IGHV5-10-1 is present, however, unfortunately, we missed this event to update our internal library.

We will update the repseqio library to reflect updated information, ASAP. However it will take several weeks to check everything.

I will leave this issue opened until then.

Best,
Dmitry.

**Comment by dbolotin** [comment]
Fixed in 5712b1dfe828371fdc7518673a1758a7b0c30b7e with the [new library](https://github.com/repseqio/library/releases/tag/v1.5).
