### ISSUE TITLE
More clones found when running subset of larger FASTQ than original FASTQ?

### ISSUE THREAD

**Issue by bbimber** [milaboratory/mixcr#329]
I'm not sure if this behavior is expected or not, but I thought it was interesting.  We generate whole-transcriptome SMART-Seq2 RNA-Seq libraries that include TCR reads.  TCR are a very low fraction of total reads.  Typically, we have run MIXCR against the entire input dataset since MIXCR is pretty fast.  This generally seems to work, but we had a recent dataset with zero clones found by MIXCR.  To debug this, I ended up exporting all read pairs that overlapped the TCR constant regions (several 1000).  I then gave this subset FASTQ as input to MIXCR.  While MIXCR did not find any clones using the full dataset, it did find one TRA with the subset of reads.  Is this behavior expected?

I was using MIXCR 2.1.6 with either the built-in human library of a custom rhesus macaque library.  I am happy to provide sample data or do some testing locally if you have suggestions.

**Comment by dbolotin** [comment]
Such things may occur, most probably this is a result of randomness of empirics built-in into aligner, which may manifest itself in boundary cases. Namely some alignments having substantial number of indels and substitutions, but having score higher then a threshold, may still not be aligned. This effect may be observed for alignments 10-15 nt long. After we introduced second alignment step (in 2.1), this effect become negligible, though still is there for clones represented by single read, having CDR3 close to one of the read boundaries, having some mutations in the germline region and having bad luck in random k-mer position selection that took place in aligner. I think this is the case in your data.

If you share both of the samples (raw and enriched) I can check it for possible other problems.

**Comment by bbimber** [comment]
Sure -this is not pressing but I would appreciate that.  What's the best mechanism to share data?  It's probably too large for here.  Should I email with a link to a download location?

**Comment by bbimber** [comment]
Actually the issue is simply than this - I missed filtering thresholds.  This was essentially operator error - MiXCR gives consistent results.
