### ISSUE TITLE
some sequences of output file not matching input sequences

### ISSUE THREAD

**Issue by anakro** [milaboratory/mixcr#334]
Hi. I am encountering a problem while annotating 100.000 and 1 million sequences with MiXCR 2.1.8 version. There is one sequences in 100.000 number of sequences and around 100 sequences in 1 million sequences of the column readSeq of the output file, which does not match with any of the sequences of the input file. Please let me know where the problem might be.

**Comment by anakro** [comment]
Forgot to add that this happens in the alignment step (AlignmentExport).

**Comment by PoslavskySV** [comment]
Could you paste exact commands you used?

**Comment by anakro** [comment]
For alignment with 100.000 sequences. I tried with version 2.1.5 and 2.1.8 and there is always the same result - one sequences is not found in an input file and in one million sequences many more sequences. 

/Users/anak/Downloads/mixcr-2.1.8/mixcr align -r alignmenReportIgSimulator_100000_sequences.log -c IGH -s HomoSapiens --save-description -f /Users/anak/Documents/masterThesis/simulators/ig_simulator/ig_simulator_test_100000_sequences/final_repertoire.fasta /Users/anak/Documents/gitMasterThesis/MiXCR_results/IgSimulator_aligned_sequences/100000_sequences/output_file_100000_sequences_IgSimulator_MiXCR.vdjca

For export with 100.000 sequences:
/Users/anak/Downloads/mixcr-2.1.8/mixcr exportAlignments /Users/anak/Documents/gitMasterThesis/MiXCR_results/IgSimulator_aligned_sequences/100000_sequences/output_file_100000_sequences_IgSimulator_MiXCR.vdjca /Users/anak/Documents/gitMasterThesis/MiXCR_results/IgSimulator_aligned_sequences/100000_sequences/output_file_100000_sequences_IgSimulator_MiXCR.txt

**Comment by PoslavskySV** [comment]
Can you check whether reverse complement of those missed sequences are also not present in the initial file?

**Comment by anakro** [comment]
I just checked. Unfortunately they are not.

**Comment by anakro** [comment]
Just to make it a bit clear. The number of output sequences matches the number of input sequences for 100.000 and for one million there are 4 sequences less in the output file due to failed assignment of a gene. The number is alright, but the nucleotide sequences written in the column readSeq somehow does not matches for some sequences with the input file (they are not found in the input file)

**Comment by dbolotin** [comment]
Please try to remove all sequences with 'N' nucleotides from the dataset and rerun the analysis. 'N' nucleotides are converted to random letter with zero quality inside the align pipeline. This might be the reason of the issue.

I mark it as bug, as this behaviour is not expected, but I can't give estimates on the time this will be fixed.

**Comment by anakro** [comment]
I removed all the N, but some sequences still did not match with the input file sequences. Those sequences were reverse complement of the input sequences. Apparently the problem is N and reverse complement. It might be convenient for a user to see in an output file a column of the names of the sequences (the same as they are labeled in a fasta file), then all the tracking of the sequences would be much simpler. Just a modest advice. Thank you a lot for such a quick help.

**Comment by dbolotin** [comment]
Thanks for suggestion! In the latest stable version (2.1.9) tracking of reads with their headers is possible using `-g` option on `align` stage, which attaches header content to each read, and then with `-descrR1` (see [here](http://mixcr.readthedocs.io/en/latest/export.html#available-fields)) field on `exportAlignments` stage which will output corresponding field along with other alignment information.

Tracking of `alignment` to `clone` mapping is also possible with index files (see [this](http://mixcr.readthedocs.io/en/latest/export.html#exporting-reads-aggregated-by-clones) section).

In 2.2 commands and pipeline in general for tracking of alignments to clones mapping will change. Many enhancements to this infrastructure are made. For example, it will work correctly with `assemblePartial` (current index and alignment formats can't track events where several alignments are merge into a single alignment). So don't rely on current API in this respect in your scripts. MiXCR v2.2 will be released somewhere in the end of March. If you are interested in this functionality I can share alpha binaries here, or you can build them yourself from `develop` branch of this repo.

**Comment by anakro** [comment]
Thank you so much. I wrote a script for matching the sequences, therefore now they are matching perfectly. The only question and problem I am still having is, how to determine whether the sequence in the output file of the alignment is productive? Is there any information about in-frame, out-of frame sequence?

**Comment by dbolotin** [comment]
This is not yet implemented. Please see #206 for details. Scheduled for 2.3 (this summer). If you have any suggestions in this respect, they are most welcome, please comment on the issue #206.
