### ISSUE TITLE
TRBV not recognized while clone assembling, but the sequence is TRBV after BLAST

### ISSUE THREAD

**Issue by suntaosimon** [milaboratory/mixcr#340]
Noticed that Reads dropped due to the lack of a clone sequence: 3467898 (43.82%), then I exported vdjca file with exportAlignmentsPretty and noticed those clones are missing V and D. 
e.g,
![image](https://user-images.githubusercontent.com/3598340/35932073-4fc484f2-0bfc-11e8-8e92-7b9845a2d124.png)

I then BLAST the unmapped sequence, the results showed that those sequences are Homo sapiens T cell receptor beta locus (TRB) on chromosome 7

![image](https://user-images.githubusercontent.com/3598340/35931968-f89e0f86-0bfb-11e8-9c23-d21e7361d553.png)

example sequence:

GATGGCTCAAACACAGCGACCTCGGGTGGGAACACGTTTTTCAGGTCCTCCAGCACTGAGAGCCGGGTCCCGGCGCCGAAGTACTGAATGTTTTTGGCTCACAGCCCCGAGACGCGGCACAGAAACTGGCCCTGCGACGCCCCCGGCGTCGACGCCGGGGGCGTCGCAGGGCCAGTTTCTGTGCCGCGTCTCGGGGCTGTG

Wondering why mixcr did not map this sequence as TRBV?

Thanks.

```
>>> Read id: 4466

Quality   66677886888877788887785688888858877888888874856668887858888888888788788888888888   
Target0 0 GATGGCTCAAACACAGCGACCTCGGGTGGGAACACGTTTTTCAGGTCCTCCAGCACTGAGAGCCGGGTCCCGGCGCCGAA 79  Score

Quality    8888788887888888787478788887888888878877887878747788768886268888888888    
Target0 80 GTACTGAATGTTTTTGGCTCACAGCCCCGAGACGCGGCACAGAAACTGGCCCTGCGACGCCCCCGGCGTC 149  Score

                                                                 <J               CDR3><FR4      
   Quality    88888888886268886788774787878877887888888878888787478788888878888788888888888888   
   Target1  0 GACGCCGGGGGCGTCGCAGGGCCAGTTTCTGTGCCGCGTCTCGGGGCTGTGAGCCAAAAACATTCAGTACTTCGGCGCCG 79  Score
TRBJ2-4*00 20                                                    agccaaaaacattcagtacttcggcgccg 48  250

                               FR4><C                                                   
   Quality    8788788888888885878886665847888888877885888888658778888777888868877666    
   Target1 80 GGACCCGGCTCTCAGTGCTGGAGGACCTGAAAAACGTGTTCCCACCCGAGGTCGCTGTGTTTGAGCCATC 149  Score
TRBJ2-4*00 49 ggacccggctctcagtgctgg                                                  69   250
  TRBC2*00  0                      aggacctgaaaaacgtgttcccacccgaggtcgctgtgtttgagccatc 48   245
```

**Comment by dbolotin** [comment]
Could you please specify expected behaviour (alignment) for the provided sequence.
