### ISSUE TITLE
Remove incomplete (corrupted) output file in case of processing error

### ISSUE THREAD

**Issue by dbolotin** [milaboratory/mixcr#344]
All actions affected.

**Comment by dbolotin** [comment]
+1 for this issue

**Comment by dbolotin** [comment]
@PoslavskySV really fixed? Or I accidentally closed it?

**Comment by PoslavskySV** [comment]
accidentally

**Comment by dbolotin** [comment]
No more need in this feature after #444 / #397 will be closed.
