### ISSUE TITLE
Shortcuts for frequently used sets of settings

### ISSUE THREAD

**Issue by dbolotin** [milaboratory/mixcr#35]
Like

```
rna = -OvParameters.geneFeatureToAlign=VTranscript
full-length = ...
short-full-length = full_length - FR4
dont-cluster = ....
```

Possible usage:

```
mixcr align -:rna -:dont-cluster ...
```

here `dont-cluster` will be skipped, as it affects only assembling stage, but by permitting such things we will allow to set the same set of parameters for all stages, in the end it will simplify implementation of #14 to be in the following form:

```
mixcr analyse -r report.txt -:compress-intermediate -:rna -:dont-cluster my_name_R1.fastq.gz my_name_R2.fastq.gz
```

which will produce the following set of files:

```
my_name.vdjca.gz
my_name.clns.gz
my_name.txt
report.txt
```

**Comment by PoslavskySV** [comment]
https://mixcr.readthedocs.io/en/master/analyze.html
