### ISSUE TITLE
Invalid maximum heap size in Windows 10

### ISSUE THREAD

**Issue by chrisdex** [milaboratory/mixcr#356]
I have installed Mixcr 2.1.9 and am struggeling to run it. 
As per the manual, I have used the prompt : 
**java -Xmx4g -Xms3g -jar C:\users\XXXX\documents\mixcr\mixcr-2.1.9\mixcr.jar**
However, i always get the following error message : 
_Invalid maximum heap size: -Xmx4g
The specified size exceeds the maximum representable size.
Error: Could not create the Java Virtual Machine.
Error: A fatal exception has occurred. Program will exit._

Please help !

Also, i included the folder in my paths under Environmental variables but i still need to cd into the folder where the software is.

**Comment by chrisdex** [comment]
The only way i found around the issue is to drop the commands to Xmx1g and Xms1g
But i doubt that will be enough for the software to run.
My system has 16 GB RAM and runs Windows10 64bit

**Comment by PoslavskySV** [comment]
It looks like you have installed **32-bit** Java --- check this with `java -version`. The solution is to install **64-bit** Java. Also look here https://stackoverflow.com/questions/42948972/invalid-maximum-heap-size


Let me know if it works for you.
