### ISSUE TITLE
Reads dropped due to the lack of a clone sequence: 99.84%

### ISSUE THREAD

**Issue by PBarennes** [milaboratory/mixcr#357]
Hi,
We use MiXCR to align TCR reads produced by Adaptive Technology. There are short reads, so we  had set up the mixcr align -OjParameters.parameters.minAlignmentLength=5 -OvjAlignmentOrder=JThenV -OallowPartialAlignments=true ... , and we tried other configuration like RNA-seq processing data configuration. I send you the reports

Reference library: repseqio.v1.5:10090:3f60d52fd55c4444dd9345b7b0843721
Alignment: 10.7%
Alignment: 21.5%  ETA: 00:00:07
Alignment: 64.4%  ETA: 00:00:00
Alignment: 96.6%  ETA: 00:00:00
============= Report ==============
Analysis time: 3.79s
Total sequencing reads: 26204
Successfully aligned reads: 26138 (99.75%)
Alignment failed because of absence of CDR3 parts: 36 (0.14%)
Alignment failed because of low total score: 30 (0.11%)
Overlapped: 0 (0%)
Overlapped and aligned: 0 (0%)
Alignment-aided overlaps: 0 (�%)
Overlapped and not aligned: 0 (0%)
WARNING: unnecessary override -OminimalClonalSequenceLength=12 with the same value.
Initialization: progress unknown
Writing clones: 0%
============= Report ==============
Analysis time: 1.19s
Final clonotype count: 1
Average number of reads per clonotype: 1
Reads used in clonotypes, percent of total: 1 (0%)
Reads used in clonotypes before clustering, percent of total: 1 (0%)
Number of reads used as a core, percent of used: 1 (100%)
Mapped low quality reads, percent of used: 0 (0%)
Reads clustered in PCR error correction, percent of used: 0 (0%)
Reads pre-clustered due to the similar VJC-lists, percent of used: 0 (0%)
Reads dropped due to the lack of a clone sequence: 26137 (99.74%)
Reads dropped due to low quality: 0 (0%)
Reads dropped due to failed mapping: 0 (0%)
Reads dropped with low quality clones: 0 (0%)
Clonotypes eliminated by PCR error correction: 0
Clonotypes dropped as low quality: 0
Clonotypes pre-clustered due to the similar VJC-lists: 0
Exporting clones: 0%

We concluded that ours reads does not contain CDR3 sequence.
But on the " exportAlignmentsPretty" file (attached) we identified CDR3 sequences
[TDP_38_1070_4_R_1_modified.txt](https://github.com/milaboratory/mixcr/files/1762391/TDP_38_1070_4_R_1_modified.txt)

Could you tell me more about that? Which configuration do you recommend?

Thank you.

**Comment by PoslavskySV** [comment]
From the file `TDP_38_1070_4_R_1_modified.txt` it looks like your reads does not fully cover [`JCDR3Part`](http://mixcr.readthedocs.io/en/latest/geneFeatures.html#v-d-j-junction-structure). It seems that just a few letters are not covered. You can try to reconstruct those letters from germline sequence with the `extendAlignments` action:

    mixcr extendAlignments alignments.vdjca alignments_extended.vdjca

For details and motivation behind this action, see [documentation on RNA-Seq processing](http://mixcr.readthedocs.io/en/latest/rnaseq.html) (and also our recent [NBT paper](https://www.nature.com/articles/nbt.3979)).
