### ISSUE TITLE
exportAlignments with readSequence with -p min

### ISSUE THREAD

**Issue by suntaosimon** [milaboratory/mixcr#364]
I would like to use `exportAlignments -p min` to save space and export time. But how do I add "readSequence" information that `-p full` provides with any [options]?
thanks!

**Comment by dbolotin** [comment]
> `-sequence`    Aligned sequence (initial read), or 2 sequences in case of paired-end reads

http://mixcr.readthedocs.io/en/latest/export.html#export

`exportAlignments -p min -sequence ...`
