### ISSUE TITLE
Filter or not clones with low counts

### ISSUE THREAD

**Issue by jvpon** [milaboratory/mixcr#367]
Hello,

The sequencing of RNA extracted from CD4 cells from mouse spleen (mostly naive T cells) was done on MiSeq using the 5’RACE-based amplification protocol. I am using MixCR for alignment and assembly (with default parameters as described at http://mixcr.readthedocs.io/en/latest/quickstart.html#analysis-of-data-obtained-using-5-race-based-amplification-protocols).
In the result I am getting tons (above 99%) of clones with just one count. 
Would you recommend to filter them out as erroneous or not? 
I thought to filter out all the clones that do not present in half (3 mice) of each group with a sum of counts <=6. At the same time I know I am looking at the naive repertoires. Maybe I should change the assemble's parameter such as badQualityThreshold and other?
It seems people use different approaches for filtering depending on the question asked. We are specifically looking for comparison of the TRA and TRB diversity in different groups of mice. 

Thank you for developing and supporting MixCR,
Julia

**Comment by chudakovdm** [comment]
Julia,
Please provide more details on you study and several clonestes.
You do not have UMI, right?
Normally in naive repertoires you have lots of low frequency clonotypes. So you should not filter them.
Ideally do it with UMI, we can send the protocol.
But I should be able to judge based on typical examples, what you have in your hands.
Best,
Dmitriy


--
Отправлено из Mail.Ru для Android среда, 28 марта 2018г., 20:07 +02:00 от Julia Ponomarenko  notifications@github.com :

**Comment by dbolotin** [comment]
MiXCR performs several types of sequence error corrections and filtering, and with default settings, even without UMI, majority of clonotypes even with count 1 should be true clonotypes. In a worst case scenario, that you have very deep sequencing of "very" naive repertoire, so all clonotypes are represented by single read, assuming average error rate in 5'RACE protocols, there will be around 5-10% of erroneous clonotypes (with single mismatch somewhere in CDR3), for real data this value should be much lower. You can increase `-ObadQualityThreshold` (see [here](http://mixcr.readthedocs.io/en/latest/assemble.html#assembler-parameters)) to e.g. 25-30, this should significantly decrease error rate (our analysis shows that sequencing generally produce more errors then PCR), but you will obviously get less clonotypes. Anyway, this tradeoff depends on the following analysis goals, if you are looking for intersections between repertoires, small artificial diversity should not make much differens, this is also true for many other post-analysis techniques, so I recommend using default parameters unless you see that artificial clonotypes spoils your results.

**Comment by jvpon** [comment]
No UMI, correct.
Thank you very much for your reply.
I will try to increase ObadQualityThreshold to 25 as you did in one of your recent papers.
I am also getting 10% more clones (and singletons) because I use -OseparateByV=true -OseparateByJ=true in the assembly. One of the questions we ask is the usage of V and J genes, so I thought it makes sense to break down clonotypes by V and J, correct?

**Comment by jvpon** [comment]
I will take a note about UMI. I had no saying this time. I got data after they were sequenced.

**Comment by dbolotin** [comment]
> One of the questions we ask is the usage of V and J genes, so I thought it makes sense to break down clonotypes by V and J, correct?

Correct. But it should not make much difference as clones with the same CDR3 but different V/J genes are very rare.

**Comment by chudakovdm** [comment]
better send me a couple of datasets, a brief look could help.
 
 to break down clonotypes by V and J - makes sense
 you have paired-end sequencing for 5'RACE data - right? 
 Then 5'UTR should be used by MiXCR and V segment identification should be quite accurate.

**Comment by jvpon** [comment]
Hi Dmitriy,
I have send you email with info on data. Cannot make them public.
Thank you,

Julia
