### ISSUE TITLE
Question: exportAlignmentsPretty for paired reads

### ISSUE THREAD

**Issue by xww52526** [milaboratory/mixcr#369]
Thanks a lot for helping clarify many details so far.

I have a few questions regarding the "exportAlignmentsPretty" feature:
1) can we specify and extract reads to look for using their sequence identifier ( Line 1 in FASTQ begins with a '@' character )?
2) for paired reads, can we have both reads line up underneath germline sequence? The second example in [docs](http://mixcr.readthedocs.io/en/latest/export.html#exporting-well-formatted-alignments-for-manual-inspection) , the IGHV3-33 example, showing Alignment of IGHV3-33 with read 1 from paired-end read and Alignment of IGHV3-33 with read 2 from paired-end read separately in two section; is it possible to have both reads line up underneath germline sequence in a single section? if not, is there a simple way to export the overlapping region of merged sequence?
3) Seems the quality score for "target" is not from FASTQ, could you please clarify how those scores were obtained?
`                                                      5'UTR><L1
   Quality    88888888888888888888888887888888888888888888888888888888888888888888888887888878
   Target0  0 AAGGCCTTTCCACTTGGTGATCAGCACTGAGCACAGAGGACTCACCATGGAGTTGGGGCTGAGCTGGGTTTTCCTTGTTG 79
IGHV3-7*00 54 aaggcctttccacttggtgatcagcactgagcacagaggactcaccatggaAttggggctgagctgggttttccttgttg 133
`

Thanks agin for your help!

**Comment by xww52526** [comment]
Hi @dbolotin , could you please help me understand more about the exportAlignmentsPretty feature. Thank you very much!

**Comment by PoslavskySV** [comment]
@xww52526 sorry for delayed reply.


1. Yes, you can. MiXCR may add additional text to original descriptions (via string concatenation), so to extract exactly the original descriptions as in `fastq`, you should align with `--save-reads` option and then use `-decrR1` and `-descrR2` fields in `exportAlignments`

2. Unfortunately, currently there is no way to do that

3. Actually, in most cases the quality should be the same. Quality is changed when two reads were merged either in `align` (overlapping reads) or in `assemblePartial` (assembling contigs); the quality of merged region is then computed according to `--OmergerParameters.qualityMergingAlgorithm`
