### ISSUE TITLE
Low mapping rates for beta chain clonotypes

### ISSUE THREAD

**Issue by ddemaeyer** [milaboratory/mixcr#376]
I'm currently aligning seperate TCRa en TCRb data using MixCR from the Clontech SMARTer TCR ab human kit. From the results we obtain an alignment rate of 75% for the TCRa chains and only 25% for the TCRb chains. 

This makes that 75% of the reads of the TCRb experiment do not align and are not used in clonotyping. From the log I see that most reads for TCRb do not have any hits to the J region (68% of the reads) while this is lower for the TCRa reads (23% do not hit on a J region). We repeated the experiment twice and the results are very similar across samples. 

Is this a known observation and do you have any ideas why we get this low mapping rate for the TCRb J chains?

**Comment by PoslavskySV** [comment]
This is not about MiXCR, but about the library preparation, which hardly depends on your protocol. You can check how your library actually looks like by manually inspecting some portion of reads. For that align with `-OallowPartialAlignments=true` and then use `exportAlignmentsPretty` to see where and how V and J genes are located in your reads. Hope, this will help to understand what is going on with the experiment.
