### ISSUE TITLE
Defining columns ?

### ISSUE THREAD

**Issue by venkataddala** [milaboratory/mixcr#378]
Hi, 
I'm very naive in T-cell seq analysis, learning currently about the data generated through mixcr and analysis by R package. I'm not bale to figure out while i'm doing Gene usage or entropy plots, I see this error.  Please help

imm.vs.all <- geneUsage(Sam_A, HUMAN_TRBV)
Error in `[.data.frame`(x, rep.int(NA_integer_, nyy), nm.x, drop = FALSE) : 
  undefined columns selected

**Comment by PoslavskySV** [comment]
Sorry, this is not MiXCR-related question, you should ask the developers of R about this.
