### ISSUE TITLE
Alignment failed because of absence of J hits

### ISSUE THREAD

**Issue by ShaeLei** [milaboratory/mixcr#379]
around 78% sequences are not aligned, because of the absence of J hits.
what kind of parameter should I change to improve this?
I currently changed 
minAlignmentLength=0 
absoluteMinScore=0 
floatingRightBound=false 
absoluteMinScore=0 
relativeMinScore=0
not really too much improve.

Thank you!!

**Comment by dbolotin** [comment]
Please post PE fastq files with one or two sequences you confirmed (with BLAST, IgBlast, IMGT VQuest, or similar tools) contain proper V and J genes, that MiXCR fails to align, and please post full align command you are applying to the data.

**Comment by ShaeLei** [comment]
@M05645:22:000000000-BLJGF:1:2119:22819:25041 1:N:0:ATTCAGAN+AGGCGAAG
CCAGAACTGCTCCTAGAAAGAATATTTGTGGGTAGAGAGGGCACTGTGACCGTTGGTTCCAGGAGCTGAAGATTGCCACCTGACCTTCAAAGAGCCCATGGGATCTTCCCCCCTCCCTTGAAGACTCCTCGTTCTTATATTGCCATCCCAGAATAAAGTTTTTCAAAGCTTAATCAGTCTAATTGTCTTGCTTTCATTCTTTGTGTTTCTTGTCCCTCCCATGCTCTCTCCCCAGCTCTATGTCTCCTCAGGTGAGTCCAGATCGGAAGAGCACACGTCTGAACTCCAGTCACATTCAGAN
+
ACCCCFGGGGGGGGGGGGGFGGGFGGFEGGGGGGEGGGGGGGGGGGGGGFGGGGCFEEGGGGGGGGGGGGGGGGGGGGFFGFGGEFGGGCEFGGFGGGEFGG@=EGGGCFFCFGGGCGGGGGGFFFGGGGGDEGGFGGGGFGG<FGGGF<EFGGDFFG@FGGGGGGGGGGGGDGGGFFGDGGDFDGGG9:EFDGGGGGGGGA,EGGGGGGGFGGDCFG+;@ADFFCFGFGGFGGEF6A;@:CFGGGGGFGGCA6<?CEGFFFAGBF58228;A3AFF@A@GFFFGFFFF7;>AEE:CC7C#
@M05645:22:000000000-BLJGF:1:2119:21698:23994 1:N:0:ATTCAGAA+AGGCGAAG
CCCGGTCTGCTCCTCCAGACTGTGACACTATTGTGAATCGTAGAGAGCATTCAGGAGCTTGGCTGGCACAAAGCAGTCAATAGGGAGGGCCTTTGAAGTCTTCTCTGTCTCTATGTGTCTTTTCCTTTTTCTCTGTGTCTGTGTGTCTGTCTGTCTCCATGTGTGTGTCTCTGTTTCTCTGTGTCGGTGGGTGGGTGTGTCTTTCGCTGTGTGTCTGTCTCTCTCGGTGTGTCTCTTTCTTTTTCTGTGTCTGTGTGTCTGTCTGTCTCTAGGTGTGTGTCTCTGTTTCTCGTTCTCTGCG
+
-A@@CFGGGGGGGGGGC<-9EFCEEECFEE<FEGFEFCFGG<@FCFEE@@FE<FCF@<F<6BFFE:@FFC89F,6FG<F<EF9FGCC@+,86EFGF<EF9EF<,6CCE<C,9F9?6CB9B,B?,A555F5,C,9,E@EAEF5CFCEE5::5C,59@?AAF,9CFA=E=E,F,5CB?5@@F44,C44@+6FCGC+@CC33>:CFGF8++@3,5@3@7;F7,5,,4,**3@*:?GF7B2=2+,=+9*=+51BC+B=CF):,==:B8*14+9/++*1/;)6)6+)+)39?CACF(068AEE))(


mixcr align --species mmu input1 alignments.vdjca > align


Thank you!

**Comment by dbolotin** [comment]
For me this does not look like IG/TCR sequences.

Please show V and J genes and corresponding alignments you expect to obtain for the sequences you provided.

**Comment by ShaeLei** [comment]
Thank you for the response!
![screen shot 2018-04-28 at 12 01 37 am](https://user-images.githubusercontent.com/10147006/39392198-65fe1e5e-4a77-11e8-851c-c49122dd1f7b.png)
please see the IGblast results.
It doesn't return a J hit, but in the current stage, the V and D hits are important for us.
Is there some way that we can get such information?

Thank you!

**Comment by PoslavskySV** [comment]
Sorry for the delay, unfortunately for now you can get only info about V genes (not D). For that you align with `-OallowPartialAlignments=true` and then you check the V genes via the `exportAlignments`.

**Comment by mingbao96** [comment]
Hi, 
In the newest version, I can not find the parameter `OallowPartialAlignments`, is there any replacement?
