### ISSUE TITLE
VDJCAlignmentsDifferenceReader#compare fixme issue

### ISSUE THREAD

**Issue by PoslavskySV** [milaboratory/mixcr#380]
`Line 65: // fixme correct in 2.2`  what's this?
https://github.com/milaboratory/mixcr/blob/d1d6fb2a3fac1b8542ed58c6163595576f89a4d2/src/main/java/com/milaboratory/mixcr/util/VDJCAlignmentsDifferenceReader.java#L65

**Comment by dbolotin** [comment]
No idea.
