### ISSUE TITLE
Losing large % of reads due to lack of clone sequence

### ISSUE THREAD

**Issue by Tsmith-87** [milaboratory/mixcr#383]
Hello,

I am using MiXCR to analyse mouse TCRB illumina data, obtained from cDNA amplicons, and whilst 60-70% of the sequences initially align, whilst assembling I lose a further approximately 30% of the reads per sample. I can improve alignment to 90% by allowing for partial alignment, but still lose the majority of reads at the assembly step. The report says this is due to a lack of clone sequence - I presume a lack of CDR3 present? This is unexpected as our reads are from J-V so would expect high coverage of the CDR3 region. Is there any other reason that would account for this? 
I have included a snapshot of both the alignment and assembly reports from a typical sample. Thanks in advance for any advice.

<img width="771" alt="screen shot 2018-05-15 at 12 26 30 pm" src="https://user-images.githubusercontent.com/39301225/40054131-b21f21b2-583b-11e8-97d0-5dbcc3190e1e.png">

<img width="879" alt="screen shot 2018-05-15 at 12 22 28 pm" src="https://user-images.githubusercontent.com/39301225/40054115-a3b78452-583b-11e8-8d7c-9fa28159859f.png">

**Comment by dbolotin** [comment]
Yes, by default CDR3 is clonal sequence, so lack of clonal sequence means no CDR3 sequence were found for 46.61% of the reads. Please provide several (2-3 would be enough) reads in fastq format, for which you can map CDR3 but MiXCR fails to. For instance can you please show CDR3 for the read 1606 that you provided.

P.S. Please post all sequences in the text form instead of a picture, so it would be possible to copy-paste them (e.g. to BLAST).

**Comment by Tsmith-87** [comment]
Thank you for your help, I have put 4 fastq reads in to text format - the first is productive and maps a CDR3, the others align initially but are then lost at assembly.

[test_fastq.docx](https://github.com/milaboratory/mixcr/files/2005155/test_fastq.docx)

**Comment by PoslavskySV** [comment]
I just checked your reads with IgBlast -- they don't contain CDR3 (except first).

**Comment by PoslavskySV** [comment]
You can manually look how they align with `exportAlignmentsPretty` action and you'll see that the CDR3 region is not covered.

**Comment by dbolotin** [comment]
Same here.

**Comment by Tsmith-87** [comment]
Thank you for checking - I assume then the problem is with the data, and we will look in to trying to further optimise CDR3 coverage.

**Comment by dbolotin** [comment]
Closing the issue, the problem seems to be in the data.

P.S. Please read [this](https://github.com/milaboratory/mixcr/issues/332#issuecomment-366035395), it is a very common source for nonproductive byproducts of sample preparation.
