### ISSUE TITLE
help import IMGT

### ISSUE THREAD

**Issue by zhpan99** [milaboratory/mixcr#384]
I would like to run mixcr on RNA-Seq data to extract TCR sequence with IMGT reference. But When I ran mixcr importFromIMGT, I got:

./mixcr: line 114: /Apps/mixcr/importFromIMGT.sh: No such file or directory.

I installed the latest version of mixcr from github from git clone and did not see importFromIMGT.sh under mixcr folder. Any clues?

Here is the version info:
MiXCR v2.2-SNAPSHOT (built Thu May 24 14:20:45 PDT 2018; rev=38bf21e; branch=develop)
RepSeq.IO v1.2.12-SNAPSHOT (rev=cf4fcbe)
MiLib v1.8.4-SNAPSHOT (rev=12be8ed)
Built-in V/D/J/C library: repseqio.v1.5

Thanks.
span

**Comment by PoslavskySV** [comment]
There is no `importFromIMGT.sh` action yet. Just follow the instructions from http://mixcr.readthedocs.io/en/master/importSegments.html
