### ISSUE TITLE
TRA and TRB prediction

### ISSUE THREAD

**Issue by zhpan99** [milaboratory/mixcr#385]
I am using mixcr to extract TCR sequences. The default human TCR reference libraries have each gene in the following format: 

TRAV12-1*00 instead of TRAV12-1*01 or TRAV12-1*02 as in IMGT.

Is there a way to map out the subtypes?

Thanks.
span

**Comment by PoslavskySV** [comment]
Yes, but the mapping is surjective-only: 

```
TRAV12-1*01 (IMGT)  ->  TRAV12-1*00 (MiXCR)
TRAV12-1*02 (IMGT)  ->  TRAV12-1*00 (MiXCR)
```

etc.
