### ISSUE TITLE
MiXCR 2.1.2 output consistency_RNASeq

### ISSUE THREAD

**Issue by anabbi** [milaboratory/mixcr#387]
Hello

I am facing a bit of an issue regarding the MiXCR output being consistent. After reading the previous post on the same matter (#131 ), I understood it might be due to low quality reads. I use the unselected RNAseq data as input for MiXCR and sure, I get a lot of clonotypes with only one read, which might not be reliable. Could you please comment on how I could determine the read quality? I think I should remove all clonotypes with one read but some of them do overlap between MiXCR runs so they are not really "random". I appreciate your comment.

Here is what I run:

`module load java/8`

`module load mixcr/2.1.2`

`java -jar $mixcr_dir/mixcr.jar align -p rna-seq -s hsa -OallowPartialAlignments=true -r ~/projects/RNASeq/LOG_ALIGN_XXXXXX.txt ~/projects/RNASeq/XXXXXX_1.fastq.gz ~/projects/RNASeq/XXXXXX_2.fastq.gz  ~/projects/RNASeq/alignments_XXXXXX.vdjca`

`java -jar $mixcr_dir/mixcr.jar assemblePartial ~/projects/RNASeq/alignments_XXXXXX.vdjca ~/projects/RNASeq/rescue1_XXXXXX.vdjca`

`java -jar $mixcr_dir/mixcr.jar assemblePartial ~/projects/RNASeq/rescue1_XXXXXX.vdjca ~/projects/RNASeq/rescue2_XXXXXX.vdjca`

`java -jar $mixcr_dir/mixcr.jar extendAlignments ~/projects/RNASeq/rescue2_XXXXXX.vdjca ~/projects/RNASeq/extended_XXXXXX.vdjca`

`java -jar $mixcr_dir/mixcr.jar assemble -r ~/projects/RNASeq/LOG_ASSEMBLE_XXXXXX.txt ~/projects/RNASeq/extended_XXXXXX.vdjca ~/projects/RNASeq/XXXXXX.clns`

`java -jar $mixcr_dir/mixcr.jar exportClones --chains TRA ~/projects/RNASeq/XXXXXX.clns ~/projects/RNASeq/CLONES_TRAXXXXXX.txt`

Two different runs yields two different sets of clonotypes (37 TRA clonotypes vs 71), albeit some overlap (judging by aaCDR3seq). Please see attached.

[CLONES_TRAXXXXXX_1.txt](https://github.com/milaboratory/mixcr/files/2094732/CLONES_TRAXXXXXX_1.txt)
[CLONES_TRAXXXXXX_2.txt](https://github.com/milaboratory/mixcr/files/2094733/CLONES_TRAXXXXXX_2.txt)

I understand some level of randomness has been generated in the process but in order for me to proceed forward using RNAseq data, I need to know which clonotypes to trust.

Thanks for your comment

**Comment by PoslavskySV** [comment]
Hi,
could you try the recent MiXCR 2.1.10?

**Comment by PoslavskySV** [comment]
In general, MiXCR has very strong thresholds when processing RNA-Seq data, so the clonotypes with only single read should be reliable and you don't need to remove them. Additionally, the quality string (-qFeature CDR3) produced by MiXCR in `exportClones` for each clone can also give information about reliability (however, this is rare the case of RNA-Seq, since thresholds are already strong enough on the step of alignment). 

Of course, it is always worse (and I actually *strongly* recommend) to manually look few raw alignments (with `exportAlignmentsPretty`) and few clonotypes (with `exportClonesPretty`) just to understand how things look like on the low level (this could be especially helpful to understand the artifacts of the library).

Regarding the issue with unreproducible output. MiXCR should give exactly the same result when running on the same input fastq data. To confirm that there is indeed a bug could you please 1) try the most recent MiXCR version 2) paste the report files for all steps (align/assemblePartial/extendAlignments/assemble) for run 1 and run 2

**Comment by anabbi** [comment]
Hi
thanks for your response and sorry for my delay. I tried the latest version. 2.1.10 is reproducible. This is the alignment reports of run 1 and run 2 with 2.1.2. Input files are RNAseq data.

## Run 1 
Analysis Date: Mon Jun 11 19:13:46 EDT 2018
Input file(s): XXXXX_1.fastq.gz,XXXXX_2.fastq.gz
Output file: alignments1_XXXXX.vdjca
Version: 2.1.2; built=Thu Apr 20 05:22:25 EDT 2017; rev=6abb137; lib=repseqio.v1.2
Analysis time: 204.26m
Command line arguments: align -p rna-seq -s hsa -OallowPartialAlignments=true -r LOG_ALIGN1_XXXXX.txt XXXXX_1.fastq.gz XXXXX_2.fastq.gz alignments1_XXXXX.vdjca
Total sequencing reads: 98690214
Successfully aligned reads: 58716 (0.06%)
Alignment failed, no hits (not TCR/IG?): 97915703 (99.22%)
Alignment failed because of absence of CDR3 parts: 69599 (0.07%)
Alignment failed because of low total score: 646196 (0.65%)
Overlapped: 67573948 (68.47%)
Overlapped and aligned: 31071 (0.03%)
Overlapped and not aligned: 67542877 (68.44%)
TRA chains: 3839 (6.93%)
TRB chains: 855 (1.54%)
TRD chains: 82 (0.15%)
TRG chains: 101 (0.18%)
IGH chains: 17556 (31.68%)
TRA,TRD chains: 3 (0.01%)
IGK chains: 16623 (30%)
IGL chains: 16349 (29.51%)

## Run 2 
Analysis Date: Mon Jun 11 21:02:21 EDT 2018
Input file(s): XXXXX_2.fastq.gz,XXXXX_2.fastq.gz
Output file: alignments2_XXXXX.vdjca
Version: 2.1.2; built=Thu Apr 20 05:22:25 EDT 2017; rev=6abb137; lib=repseqio.v1.2
Analysis time: 312.85m
Command line arguments: align -p rna-seq -s hsa -OallowPartialAlignments=true -r LOG_ALIGN2_XXXXX.txt XXXXX_2.fastq.gz XXXXX_2.fastq.gz alignments2_XXXXXvdjca
Total sequencing reads: 98686517
Successfully aligned reads: 42720 (0.04%)
Alignment failed, no hits (not TCR/IG?): 98028440 (99.33%)
Alignment failed because of absence of CDR3 parts: 65798 (0.07%)
Alignment failed because of low total score: 549559 (0.56%)
Overlapped: 56465 (0.06%)
Overlapped and aligned: 6 (0%)
Overlapped and not aligned: 56459 (0.06%)
TRA chains: 8757 (20.54%)
TRB chains: 548 (1.29%)
TRD chains: 38 (0.09%)
TRG chains: 63 (0.15%)
IGH chains: 11376 (26.68%)
TRA,TRD chains: 3 (0.01%)
IGK chains: 10961 (25.71%)
IGL chains: 10892 (25.55%)

Even the total sequencing reads were not reported reproducibly. (Total reads: 98686435 from FastQC report).

Am I doing anything wrong that caused this issue?
