### ISSUE TITLE
how do I exportClones based on AA sequence?

### ISSUE THREAD

**Issue by suntaosimon** [milaboratory/mixcr#388]
I noticed that the default command of exportClones is based on nt sequence. 
`mixcr exportClones [options] clones.clns clones.txt`

how do I exportClones based on AA sequence? I would like to have all the clones that have the same CDR3 AA merged together and re-calculate the frequency. 

Thanks!

**Comment by PoslavskySV** [comment]
Hi,

this is not possible directly with MiXCR. However, if you really need this, it would be easy to implement  with some script basing on the output of MiXCR.
