### ISSUE TITLE
rna-seq line 175:  1565 Killed

### ISSUE THREAD

**Issue by BastienNguyen** [milaboratory/mixcr#396]
Hello,
I have manually install mixcr on a cluster and I would like to test the software on bulk RNAseq data.

Could you please help me with the following error message when running the software:

`[basnguye@nic49 mixcr-2.1.11]$ ./mixcr align -p rna-seq -s hsa -OallowPartialAlignments=true /projects/iribhm/ngs/Bastien/DBEYOND/rz-hs_DBY-001-N-Biopsy_S1_R1_001.fastq.gz /projects/iribhm/ngs/Bastien/DBEYOND/rz-hs_DBY-001-N-Biopsy_S1_R2_001.fastq.gz alignments.vdjca
Reference library: repseqio.v1.5:9606:29a95112c52f62585b28d241db7fd523
Alignment: 0%
./mixcr: line 175:  1565 Killed                  $java -Dmixcr.path=$dir -Dmixcr.command=mixcr -XX:+AggressiveOpts "${javaArgs[@]}" -jar $jar "${mixcrArgs[@]}"`

Thanks,

B

**Comment by PoslavskySV** [comment]
The process is killed by some cluster daemon, this is unrelated to MiXCR. You should consult your system administrator with this.
