### ISSUE TITLE
Algorithm for deeply sequenced libraries

### ISSUE THREAD

**Issue by anabbi** [milaboratory/mixcr#405]
Hi,
I am a frequent user of MiXCR mostly using MiSeq or RNAseq data. I have a set of targeted libraries that are deeply sequenced on HiSeq (about 1 million reads). When I run MiXCR I get an understandably massive number of clonotypes but also I get the clonotypes with one or two reads. Downsampling process indicates I have not reached saturation point, which is hard to believe considering such a high coverage.
I am wondering whether there is an algorithm for processing deeply sequenced libraries. Any suggestions would be appreciated.

Thanks

**Comment by anabbi** [comment]
I believe this is pretty deep considering the fact that my libs are from targeted libs enriched for TCR regions. What is the typical depth you think would suffice to reach saturation and hence get the actual number of clonotypes?

**Comment by dbolotin** [comment]
This is hugely variable from experiment to experiment. And 1M read for the targeted library (if sample preparation was done right, without creating bottlenecks) in many cases is not enough.

Very very rough estimation would look like this: lets say `N` it the number of T cells you have extracted starting RNA/DNA from, and you prepared your library without bottlenecks. There are at least two things that affect variability in coverage of each specific TCR:
  - variable expression levels of TCR RNA (obviously, applies only to RNA). Very rough estimation I would give here is that cell with the maximal expression level has 10 times more RNA molecules than the cell with the least expression level.
  - variable amplification rate for different molecules. And this is hugely depends on the experimental setup: (i) how many amplification cycles were performed in total for the library (ii) whether PCR was saturated (skew in amplification rate is strongest on the very last cycles of PCR where reaction resources are almost exhausted, actually I have no ref to prove this, but it is my gut feeling, after many discussions on this matter). But, anyway, at least this step should add another order of magnitude for the overall amplification rate.

So you have around two orders of magnitude difference for the total aplification rate for RNA from a certain T-cells to another. This process has less effect on clonotypes represented by many cells, as both processes are partially random, and individual effects are averaged out. But CDR3s from different clonotypes represented by single cell, may end up having 100-fold difference in their concentration, and hence, having 100-fold difference in the number of reads.

Overall, this means that to exhaustively sequence the library you need at least `100*N` reads . Actual numbers may vary greatly, so this factor may be anywhere between 1 to 1000.
