### ISSUE TITLE
Question about searchParameters option

### ISSUE THREAD

**Issue by tiagobrc** [milaboratory/mixcr#415]
Hi, Congratulations on this fantastic software.

I wanna to ask why the -OcloneClusteringParameters.searchParameters option only permits me to choose up to 4 mismatches for the clustering?  Another thing is, could I also consider the length of the clonal region as a parameter for admitting it to be the same clone?

Thanks!

**Comment by dbolotin** [comment]
Hi,

Sorry for the late response. We implemented the feature in 3.0.4 release, it will be officially released soon.

You can try it with this pre-release build:
https://s3.amazonaws.com/files.milaboratory.com/mixcr/mixcr-304f.zip

```
mixcr assemble -f -OcloneClusteringParameters.searchParameters='{"maxSubstitutions":4,"maxDeletions":4,"maxInsertions":4}' alignments.vdjca clones.clns
```

You can add:
`totalMutations` - field to limit total number of mutations (e.g. `{"maxSubstitutions":4,"maxDeletions":4,"maxInsertions":4,"totalMutations":4}` - will allow 3 substitutions + 1 deletion, but not 3 substitutions + 2 deletions)

Best!
