### ISSUE TITLE
information about alignreport text file

### ISSUE THREAD

**Issue by vanessajmh** [milaboratory/mixcr#417]
Hello,
In the alignreport.txt, what does "Alignment failed because of low total score" specifically exclude? Is the total score related to the alignment or the sequencing itself?
Thank you.

**Comment by PoslavskySV** [comment]
Hi,
the total score is related to the alignment only.

**Comment by PoslavskySV** [comment]
Yes, exactly.

**Comment by vanessajmh** [comment]
Thanks.
On another note, is it possible to extract the list of unaligned reads?
