### ISSUE TITLE
TRA/TRD hybrids

### ISSUE THREAD

**Issue by vanessajmh** [milaboratory/mixcr#422]
Hello
I'm using allowChimeras by default and I'm getting TRA/TRD hybrids. How can I eliminate these sequences?
Thanks

**Comment by dbolotin** [comment]
Please elaborate more on the issue. What exact commands are you using, etc...

If this helps: see [the TRA/TRD locus structure](http://www.imgt.org/IMGTrepertoire/index.php?section=LocusGenes&repertoire=locus&species=human&group=TRA), not all TRA/TRD V/J genes that actually can participate in single rearrangement are named like TRAV.../DV.... Most probably those genes are true "physiological" TCRs. The most robust method to distinguish TRA from TRD is by looking at C gene. If you have it in your data I suggest you using it.
