### ISSUE TITLE
Exporting nucleotide sequences for clone specific V/D/J gene

### ISSUE THREAD

**Issue by achiaruna** [milaboratory/mixcr#435]
Hi,
Can you please help me with exporting full nucleotide sequence for V, D, J gene for each clone, so that I can use those sequences in my vector to clone that particular chain?

**Comment by PoslavskySV** [comment]
This is possible with MiXCR 3.0. Check the most recent documentation:  https://mixcr.readthedocs.io/en/master/assembleContigs.html

**Comment by achiaruna** [comment]
Thanks a lot for getting back to me. I will definitely check it out!

Thanks.
Achia.
