### ISSUE TITLE
Questions about the req

### ISSUE THREAD

**Issue by kdh4win4** [milaboratory/mixcr#436]
Hi, 

I have a question about the final .txt document.
In the screenshot image, you can see line 5 has more than one TRBV.
It's fraction is about 1.219%. 
Do you divide the clone fraction by the number of TRBV's?
Or do you use the first one as a representative?
Thank you for any help!

<img width="806" alt="screen shot 2018-10-17 at 7 44 08 am" src="https://user-images.githubusercontent.com/12645005/47084080-89d33580-d1e0-11e8-997d-055ccde0a5b8.png">

## Checklist before submitting the issue:

 - [ ] The issue is strongly related to the MiXCR software
 - [ ] The issue can be reproduced with [the most recent version](https://github.com/milaboratory/mixcr/releases) of MiXCR
 - [ ] There is no answer to the question in the [official documentation](http://mixcr.readthedocs.io/) and there is no duplicate issue in the [bug tracker](https://github.com/milaboratory/mixcr/issues)  
 - [ ] Inspection of raw alignments with [exportAlignmentsPretty](http://mixcr.readthedocs.io/en/master/export.html#exporting-well-formatted-alignments-for-manual-inspection) shows that data has the expected architecture, and sample preparation artefacts are not the reason of the problem (if this is the matter of the issue)

## Expected Result

*A description of what you wanted to happen*

## Actual Result

*A description of what actually happened*

## Exact MiXCR commands 

*Paste here __exact__ MiXCR commands you used (enclose it with single `` ` ``  for better formatting)*

## MiXCR report files 

*Paste here content of the report files produced by MiXCR (enclose it with triple ```` ``` ````  for better formatting)*

**Comment by PoslavskySV** [comment]
Hi! MiXCR doesn't divide clone fraction by the number of TRBVs. The first one (that is the one with the highest alignment score) is used.

**Comment by kdh4win4** [comment]
Do you mean only first one should be cared ? Is it right ?

**Comment by PoslavskySV** [comment]
In general, yes. The other ones may be important for debug purposes or in some special cases.
