### ISSUE TITLE
Error in Mixcr 3.0.2

### ISSUE THREAD

**Issue by kdh4win4** [milaboratory/mixcr#447]
I think the error is not fixed yet. 
There is an error in exportAlignments / exportClones step.

**Comment by PoslavskySV** [comment]
what error?

**Comment by PoslavskySV** [comment]
@kdh4win4 Could you, please, elaborate about the issue in more details? It is best if you paste the exact MiXCR commands that caused error in your case. We are planning to release 3.0.3 today/tomorrow, so if you provide the details about error, we'll include the fix.

**Comment by kdh4win4** [comment]
![screen shot 2018-11-01 at 9 23 56 am](https://user-images.githubusercontent.com/12645005/47854837-34d71800-ddb9-11e8-9416-b91021938cbf.png)

**Comment by kdh4win4** [comment]
This script was worked well at version 2.1.12

**Comment by dbolotin** [comment]
Can you please post the script itself, or the commands it executes.
It also seems that you hit some kind of IO (hardware) problem.

**Comment by PoslavskySV** [comment]
The `extendAlignments` is now outdated. Use universal `extend` command instead. Let me know, if it doesn't help.
