### ISSUE TITLE
Can MIXCR extract TRD?

### ISSUE THREAD

**Issue by qtwwthx** [milaboratory/mixcr#449]
I want to extract TRD from RNA-seq.
This is my command：
java -jar /home/mixcr-2.1.12/mixcr.jar exportClones -c TRD SRR42960${i}_paired_rescued_2_extended.clns  S${i}_TRD.txt
But the result I get will be the same as the result of extracting TRA. Why？ Thank you !

**Comment by PoslavskySV** [comment]
because all v/j genes that belong to tra also belong to trd. see https://github.com/repseqio/library/blob/9111ae88d7efa756aad402e420ab817bf53cb1ba/human/TRA_TRD.json

**Comment by qtwwthx** [comment]
> because all v/j genes that belong to tra also belong to trd. see https://github.com/repseqio/library/blob/9111ae88d7efa756aad402e420ab817bf53cb1ba/human/TRA_TRD.json

Thank you very much!

**Comment by PoslavskySV** [comment]
@qtwwthx also see this #422
