### ISSUE TITLE
--overwrite-if-required in docs but not supported?

### ISSUE THREAD

**Issue by bbimber** [milaboratory/mixcr#451]
Hello,

The docs for analyze list --overwrite-if-required:

https://mixcr.readthedocs.io/en/master/analyze.html?highlight=overwrite

However, when running this command on the latest version (3.0.2), I get an error about this not being supported.  The old "-f" argument is supported still.

**Comment by PoslavskySV** [comment]
Hi! Thanks for reporting. We forget to fix the documentation. From 3.0.2 `--overwrite-if-required` is set to true for all steps of analyze command (align/assemble/etc.) and there is no way to change this (but still you can use `-f` to force overwrite all files). I made a separate issue #452
