### ISSUE TITLE
mixcr analyze shotgun and exports?

### ISSUE THREAD

**Issue by bbimber** [milaboratory/mixcr#454]
hello - we are running analyze shotgun w/ MiXCR 3.  this pipeline appears to always run export; however, the results are not quite what I expect.  it outputs separate text files for each of: ALL, IGH, IGK, IGL, TRA, TRB, TRD, and TRG.  for example: prefix.clonotypes.ALL.txt.  all of these files appear identical though.  is this expected?

also, is it possible to suppress the export command?

**Comment by PoslavskySV** [comment]
Thanks for reporting!

> all of these files appear identical though. is this expected?

this is a bug. Will be fixed at the end of the week. 

> also, is it possible to suppress the export command?

Unfortunately, not. I'll add this feature in the upcoming release (at the end of the week).

**Comment by PoslavskySV** [comment]
fixed via #29bd9eaff36d35c86e5d739c7cb779fe8c89b760

**Comment by AnaBolivar** [comment]
hello
I am having the same issue when running the _analyze amplicon_ pipeline with mixcr 3.0.1 of 5'RACE cDNA libraries. It outputs 4 txt files (TRA, TRB, TRD and TRG) that appear to be identical. Is it possible that it is the same bug?

**Comment by dbolotin** [comment]
This was fixed in 3.0.3, please use [latest MiXCR version](https://github.com/milaboratory/mixcr/releases/latest).

**Comment by AnaBolivar** [comment]
Hi Dmitry
Thank you for your quick response, I have done so and now it is giving me
different files for TRA and TRB, but TRD is the same as the TRA file and
the TRG file is empty. What is the difference between the single clones.txt
file, generated using the default command *exportClones* outside of
the *analyze
amplicon* pipeline, and the four .txt files generated with *analyze
amplicon*? Does the single file generated with the default exportClones
command  include all the sequences of TRA, TRB, TRD and TRG together in one
file?

I appreciate your help,

Ana
