### ISSUE TITLE
Additional Arguments to analyze amplicon

### ISSUE THREAD

**Issue by weshorton** [milaboratory/mixcr#456]
# Background 

Using version 3.0.2, I am unable to add certain additional arguments when running the `mixcr analyze amplicon` module. From the docs, the format is:

```
mixcr analyze amplicon
    -s <species> \
    --starting-material <startingMaterial> \
    --5-end <5End> --3-end <3End> \
    --adapters <adapters> \
    [OPTIONS] input_file1 [input_file2] analysis_name
```

# Minimal Successful Example

Following the above format, I am able to add `--report` and `--receptor-type` as arguments successfully:

```
/usr/bin/java -Xmx15g -jar mixcr analyze amplicon \
        -s mmu \
        --starting-material dna \
        --5-end v-primers \
        --3-end j-primers \
        --adapters no-adapters \
        --report S10 \
        --receptor-type trb \
        LIB180515LC_S10.fastq \
        LIB180515LC_S10
```

The above produces the following (expected) files:

```
LIB180515LC_S10.clna
LIB180515LC_S10.clonotypes.TRB.txt
LIB180515LC_S10.vdjca
S10_report.txt
```

# Failed Examples

If I add any other parameters, I begin to receive errors, which change depending on which parameters I add:

## Add optional analyze arguments where [OPTIONS] is located in documentation

The exact same format as above, with the addition of the next argument from docs `--contig-assembly false` produces an error.

```
/usr/bin/java -Xmx15g -jar mixcr analyze amplicon \
        -s mmu \
        --starting-material dna \
        --5-end v-primers \
        --3-end j-primers \
        --adapters no-adapters \
        --report S10 \
        --receptor-type trb \
        --contig-assembly false \
        LIB180515LC_S10.fastq \
        LIB180515LC_S10
```
Produces this error:

```
ERROR: input file "false" does not exist.
```
If I use `--contig-assembly true`, I get the same error, with `"true" does not exist` instead. If I use any of the other optional parameters **that have a logical value**, such as `impute-germline-on-export false` or `--only-productive true`, I again receive the same error with "true" or "false", depending on the parameter.  

### Notable Exceptions

Interestingly, if I misspell an argument (for example: `imput-germline-on-export false`), I get an error that indicates mixcr is recognizing the parameter:

```
Unknown option: --imput-germline-on-export
Possible solutions: --impute-germline-on-export
```
Also, if I use a **non-logical parameter**, such as `region-of-interest CDR3`, then the run is successful and the same output files I listed above are produced.  

Finally, if I put the extra arguments at the end of the command, intstead of where the docs say `[OPTIONS]` should be located, I get a slightly different error for the **logical parameters** (e.g. `--contig-assembly false`), but a successful run for **non-logical parameters** (e.g. `--region-of-interest CDR3`):

```
/usr/bin/java -Xmx15g -jar mixcr analyze amplicon \
        -s mmu \
        --starting-material dna \
        --5-end v-primers \
        --3-end j-primers \
        --adapters no-adapters \
        --report S10 \
        --receptor-type trb \
        LIB180515LC_S10.fastq \
        LIB180515LC_S10 \
        --contig-assembly false
```
Gives the error:
```
ERROR: input file "LIB180515LC_S10" does not exist.
```

**Comment by PoslavskySV** [comment]
Dear Wes, 

thanks for reporting. Regarding ` --contig-assembly` you should not pass `true` or `false` as the option value. ` --contig-assembly` is just a flag: when it present MiXCR performs contig assembly, when not -- MiXCR skips this step. So, if you want to skip contig assembly, just remove this option from your command. The same for other flags like ` --imput-germline-on-export` etc. This behaviour is quite similar to many POSIX commands.
