### ISSUE TITLE
Include reads in analyze amplicon export

### ISSUE THREAD

**Issue by weshorton** [milaboratory/mixcr#457]
## Problem 

In version 2.1.11, I am able to use the following commands to include a column named `reads` where each cell is a comma-separated vector of the `readId` for all reads assembled into that clone. Is it possible for me to get this same column exported while only using the `analyze amplicon` module, or do I need to continue using the 3-step `align,assemble,export` process?

#### Align
```
usr/bin/java -Xmx15g -jar mixcr align \
    -f \
    -c TRB \
    --species mmu \
    --save-description \
    --save-reads \
    -v \
    --report myAlignReport.txt \
    myFile.fastq
    myFile.vdjca
```

#### Assemble
```
/usr/bin/java -Xmx15g -jar mixcr assemble \
    -f \
    --index myIndex \
    --report myAssembleReport.txt \
    --threads 4 \
    myFile.vdjca
    myFile.clns
```

#### Export clones
```
/usr/bin/java -Xmx15g -jar mixcr exportClones \
    -f \
    --preset-file $PRESET \
    -o \
    -t \
    -readIds myIndex \
    -cloneId myIndex \
    myFile.clns \
    myFile.txt
```

where $PRESET contains:
```
-cloneId
-count
-fraction
-sequence
-vHits
-dHits
-jHits
-vAlignments
-dAlignments
-jAlignments
-nFeature CDR3
-minFeatureQuality CDR3
-aaFeature CDR3
-vHit
-dHit
-jHit
-vAlignment
-dAlignment
-jAlignment
```
This outputs the following columns (the 19 preset fields plus `reads` and `cloneId`):
```
cloneId
cloneCount
cloneFraction
clonalSequence
allVHits
allDHits
allJHits
allVAlignments
allDAlignments
allJAlignments
nSeqCDR3
minQualCDR3
aaSeqCDR3
bestVHit
bestDHit
bestJHit
bestVAlignment
bestDAlignment
bestJAlignment
reads
cloneId
```

### New 3.0.2 method

In the new documentation for `exportClones`, `readIds` and `descrsR1` are listed as specific for alignments. If I try to include them in a `mixcr analyze amplicon` call, I get an error:

```
/usr/bin/java -Xmx15g -jar $MYBIN analyze amplicon \
        -s mmu \
        --starting-material dna \
        --5-end v-primers \
        --3-end j-primers \
        --adapters no-adapters \
        --report S10 \
        --receptor-type trb \
        --align "-OsaveOriginalReads=true" \
        --export "--preset-file $PRESET" \
        LIB180515LC_S10.fastq \
        LIB180515LC_S10
```
Where $PRESET is:
```
-cloneId
-count
-fraction
-vHit
-dHit
-jHit
-vGene
-dGene
-jGene
-vHitScore
-dHitScore
-jHitScore
-vAlignment
-dAlignment
-jAlignment
-vBestIdentityPercent
-dBestIdentityPercent
-jBestIdentityPercent
-nFeature CDR3
-aaFeature CDR3
-qFeature CDR3
-minFeatureQuality CDR3
-avrgFeatureQuality CDR3
-readIds
```
Give these output files (missing `LIB180515LC_S10.clonotypes.TRB.txt`):
```
LIB180515LC_S10.clna
LIB180515LC_S10.vdjca
S10_report.txt
```
And this error message:
```
WARNING: 7 functional genes were excluded, re-run with --verbose option to see the list of excluded genes and exclusion reason.
illegal field: -readIds
Usage: exportClones [-fotv] [--verbose] [-cAlignment] [-cAlignments] [-cBestIdentityPercent]
                    [-cFamilies] [-cFamily] [-cGene] [-cGenes] [-chains] [-cHit] [-cHits]
                    [-cHitScore] [-cHitsWithScore] [-cIdentityPercents] [-cloneId] [-count]
                    [-dAlignment] [-dAlignments] [-dBestIdentityPercent] [-defaultAnchorPoints]
                    [-dFamilies] [-dFamily] [-dGene] [-dGenes] [-dHit] [-dHits] [-dHitScore]
... continue with rest of usage and available arguments
```

**Comment by PoslavskySV** [comment]
MiXCR3  has a special storage type `.clna` which holds all info about alignments<>clones (this file is produced by default by the `analyze` command). At the same time MiXCR drops support of `-readIds` in `exportClones`. Instead, you can e.g. do:

```bash
mixcr exportAlignments -readIds -cloneId LIB180515LC_S10.clna alignments_to_clones_mapping.tsv
```
which produces readId->cloneId mapping (you also can use `-cloneIdWithMappingType` for a more detailed info). The `exportAlignments` is not added by default to the `analyze` pipeline, so you need to call it manually. 

Please, let me know if this new behaviour doesn't feet well in your pipeline or you need  further help / have suggestions regarding this.

**Comment by weshorton** [comment]
Thanks, that actually works better than my original method because now my exported clone files will not be bogged down by tens of thousands of readIds!

Is there information in the docs regarding the output? I didn't see anything specifically mentioning this functionality.  

When I use the `-cloneIdWithMappingType`, I get one of `core`, `mapped`, or `dropped`. I assume these correspond to the definitions provided in steps 1-3 on the assemble page of the docs. Are there other possible values?

**Comment by dbolotin** [comment]
Good to hear!

Yes:
  - `core` are alignments with zero "bad points" (low quality nucleotides, see `-ObadQualityThreshold`) in the clonal sequence region (e.g. CDR3) that initial clonotypes are created from
  - `mapped` are alignments containing "bad points", mapped to core clonotypes through the fuzzy match algorithm allowing some mismatches in these positions. Alignments containing "bad points" but  mapped through the perfect match are marked as `core`.
  - `dropped` alignments are alignments (i) without clonal sequence, e.g. bad alignments, (ii) dropped due to too many low quality positions (see `-OmaxBadPointsPercent`), (iii) alignment for which fuzzy mapping from the previous paragraph failed

P.S. note that rows in `exportAlignments` from `clna` file are not ordered by `readId` (in case you read the file as stream).

**Comment by weshorton** [comment]
Awesome, thanks!
