### ISSUE TITLE
Best way to inspect raw reads for clone(s)?

### ISSUE THREAD

**Issue by bbimber** [milaboratory/mixcr#458]
We are interested in generating full-length V/J sequences from high frequency clones.  Our data are SMART-seq2 / nextera fragmented PE150 RNA-seq data.  I have been using MiXCR 3.0.2 analyze shotgun, with a command approximately like this:

java -jar mixcr.jar analyze shotgun \
	-f \
	--starting-material rna \
	--contig-assembly \
	-s rhesus \
	--align "--library rhesus_v2.1.1" \
	--align "-OallowChimeras=true" \
	--align "-OallowPartialAlignments=true" \
	--align "-OsaveOriginalReads=true" \
	--assemble "-OaddReadsCountOnClustering=true" \
	--assemble "-ObadQualityThreshold=10" \
	fq1.fastq.gz fq2.fastq.gz outputPrefix

I then exportClones, including "-nFeatureImputed VDJRegion".  In many cases, I see the complete V/J regions are assembled from reads, without any lowercase imputed regions.  However, in some cases there are sizable portions imputed.  When I inspect alignments (exportAlignmentsPretty) for such samples, and limit to those CDR3s (--crd3-equals=XXXXXXX), I generally see reads that do span the V region.  Therefore the reads exist; however, they dont appear to have been able to assemble using assembleContigs.  I have a couple questions:

1) Is exportReadsForClones (selecting the IDs of the clone(s) in question), the best way to export the raw reads that span the VRegion for those CDR3 clones?  

2) Are there parameters for assembleContigs I should investigate to see if I can increase my assembly?  I should note that we work in rhesus macaque (less developed V/J library), and there are frequently cases where the V sequence from a given subject diverges from the reference sequence by many SNVs.  i dont know how this would impact assembleContigs.

Thanks for any help or advice.

**Comment by dbolotin** [comment]
(1) Yes, `exportReadsForClones` it the best option. It has no problems with left/right parts as the previous approaches does, etc.. It exports all the reads that were used to assemble target clonotype.

(2) The reference library may affect the performance of the `assembleContigs`, as it uses alignments as a pivot for the multiple alignment of the reads. Actually there are no parameters that "gradually" changes the behaviour of `assembleContigs` ([docs](https://mixcr.readthedocs.io/en/master/assembleContigs.html#full-sequence-assembler-parameters) just in case). You can try to extract some insights from the debug report with the special hidden option `assembleContigs --debug-report report.txt ...`.

Please let me know if you have some reads that should've been assembled, but are not. We can do step by step tracking of the algorithm on the data.
