### ISSUE TITLE
Question: --species hs, HomoSapiens, hsa

### ISSUE THREAD

**Issue by xww52526** [milaboratory/mixcr#459]
I have a naive question, the default value for human genome alignment used to be hsa. I just found out MiXCR now allow hs and HomoSapiens now.
Are hs, HomoSapiens, and hsa the same genome, any minor differences?

Thanks very much!

**Comment by dbolotin** [comment]
These all are synonyms.

MiXCR library supports species name aliasing: https://github.com/repseqio/library/blob/master/human/TRB.json#L3
