### ISSUE TITLE
No Overlap between DNA and RNA clonotypes

### ISSUE THREAD

**Issue by sa256** [milaboratory/mixcr#460]
Hello,
I have data for Exome and RNAseq for same sample. Upon running Mixcr and inferring clonotypes from each data, we wanted to look at overlap between two results. Apparently there is hardly any overlap between the clonotypes from DNA and RNA. In some cases we could find at max 2 clonotypes which were called in both datasets, that too with very low frequency and less counts. What could be the reason for almost no overlap between two molecular levels.   

Regards

**Comment by PoslavskySV** [comment]
Hi!

It is hard to guess the reason:) Could you please provide 

1) the exact MiXCR commands you used to analyze both datasets
2) MiXCR report files
3) the exact commands you used to compare the clonotypes (did you apply outer join of tables?)


This will help us to understand what is going in your case.

**Comment by PoslavskySV** [comment]
@sa256  see also this comment: https://github.com/milaboratory/mixcr/issues/463#issuecomment-439442078
