### ISSUE TITLE
Question: algorithm differences between default aligner and kaligner2

### ISSUE THREAD

**Issue by xww52526** [milaboratory/mixcr#461]
Hello, I tried to find the detailed information regarding kaligner2; which is recommended for data which contain big gaps. Seems there is very limited information regarding the alignment algorithm.
What's the major algorithm difference between kaligner2 and default aligner?
Thank you very much!

**Comment by PoslavskySV** [comment]
Hi! The difference is actually quite complicated. The explanation deserves a special scientific article :-) In a few words (may be not quite helpful), kAligner2 uses k-mers with gaps, allows mismatches in k-mers and uses sophisticated algorithms to clusterize groups of fuzzy matched k-mers. In general, it is  much better suited for work with affine scoring.
