### ISSUE TITLE
No overlap between DNA and RNA clonotypes II

### ISSUE THREAD

**Issue by GuidoLeoni** [milaboratory/mixcr#463]
I encountered the same problem already reported in #460 .

For a tumor sample I have bulk DNA from exomeseq and bulk RNA from rnaseq.

I ran mixcr on the 2  samples with the command reported below:

DNA
java -jar /data/PIPELINE/SW/mixcr-2.1.11/mixcr.jar align -OvParameters.geneFeatureToAlign=VGeneWithP -s hsa -OallowPartialAlignments=true $RTUMOR1 $RTUMOR2 alignments.vdjca
java -jar /data/PIPELINE/SW/mixcr-2.1.11/mixcr.jar assemblePartial  alignments.vdjca alignmentsRescued1.vdjca
java -jar /data/PIPELINE/SW/mixcr-2.1.11/mixcr.jar assemblePartial  alignmentsRescued1.vdjca alignmentsRescued2.vdjca
java -jar /data/PIPELINE/SW/mixcr-2.1.11/mixcr.jar extendAlignments alignmentsRescued2.vdjca alignmentsRescued_2_extended.vdjca
java -jar /data/PIPELINE/SW/mixcr-2.1.11/mixcr.jar assemble alignmentsRescued_2_extended.vdjca clones.clns
java -jar /data/PIPELINE/SW/mixcr-2.1.11/mixcr.jar exportClones -c TRA -o -t clones.clns clonesTRA.txt
java -jar /data/PIPELINE/SW/mixcr-2.1.11/mixcr.jar exportClones -c TRB -o -t clones.clns clonesTRB.txt

RNA

java -jar /data/PIPELINE/SW/mixcr-2.1.11/mixcr.jar align -p rna-seq -s hsa -OallowPartialAlignments=true $RTUMOR1 $RTUMOR2 alignments.vdjca
java -jar /data/PIPELINE/SW/mixcr-2.1.11/mixcr.jar assemblePartial  alignments.vdjca alignmentsRescued1.vdjca
java -jar /data/PIPELINE/SW/mixcr-2.1.11/mixcr.jar assemblePartial  alignmentsRescued1.vdjca alignmentsRescued2.vdjca
java -jar /data/PIPELINE/SW/mixcr-2.1.11/mixcr.jar extendAlignments alignmentsRescued2.vdjca alignmentsRescued_2_extended.vdjca
java -jar /data/PIPELINE/SW/mixcr-2.1.11/mixcr.jar assemble alignmentsRescued_2_extended.vdjca clones.clns
java -jar /data/PIPELINE/SW/mixcr-2.1.11/mixcr.jar exportClones -c TRA -o -t clones.clns clonesTRA.txt
java -jar /data/PIPELINE/SW/mixcr-2.1.11/mixcr.jar exportClones -c TRB -o -t clones.clns clonesTRB.txt
[clonesTRBDNA.txt](https://github.com/milaboratory/mixcr/files/2589912/clonesTRBDNA.txt)
[clonesTRBRNA.txt](https://github.com/milaboratory/mixcr/files/2589913/clonesTRBRNA.txt)

Any tips is very welcome
Guido

**Comment by PoslavskySV** [comment]
Hi! 

The problem is that you don't use `-p rna-seq` for DNA-Seq. With the option `-p rna-seq`  MiXCR uses aligner parameters specifically optimized for any shotgun analysis ( RNA-Seq, DNA-Seq etc.). So, add `-p rna-seq` to the first command. Probably we'll rename the `-p rna-seq` to `-p shotgun` in order to avoid confusing. 

By the way, I recommend to use MiXCR 3: it has a special single command [analyze](https://mixcr.readthedocs.io/en/master/analyze.html) which does the whole job (align/assemble/...). In your case you can use:

DNA:
```
mixcr analyze shotgun --species hs --starting-material dna data_R1.fastq data_R2.fastq dna_analysis_name
```

RNA:
```
mixcr analyze shotgun --species hs --starting-material rna data_R1.fastq data_R2.fastq rna_analysis_name
```


Please, let me know if this helps.

**Comment by dbolotin** [comment]
Dear Guido,

Can you please also post raw vdjca files for the DNA sample. CDR3s there seems to be too long, alignment data will help us figure whether it is a problem with analysis pipeline or a data artefact.

Thanks,
Dmitry.

**Comment by GuidoLeoni** [comment]
guido.leoni@gmail.com sent you some files

2 files, 637 MB in total
・ Will be deleted on 24 November, 2018


Download link:
https://wetransfer.com/downloads/f62f41ad96cd42ce85a53cde8b2ad18720181117112922/de569662440dd7d142c07d556469187b20181117112922/4dd3d0


Message:
RNASEQ EXOMESEQ TCR



2 files

MIXCRs004DNA.tar.gz
MIXCRs004RNA.tar.gz


[Get more out of WeTransfer, get Plus](https://wetransfer.com/plus?trk=WT201704_email&utm_campaign=WT_email_tracking&utm_content=general&utm_medium=plus_footer_ad_link&utm_source=notify_recipient_email)



About WeTransfer: https://wetransfer.com/about
Help: https://wetransfer.zendesk.com/hc/en-us
Legal: https://wetransfer.com/legal/terms


To make sure our emails arrive, please add noreply@wetransfer.com to [your contacts](https://wetransfer.zendesk.com/hc/en-us/articles/204909429).

**Comment by GuidoLeoni** [comment]
Thank you 
Files  are too big 
I sent them through wetransfer if this doesn't work i'll try another way

**Comment by PoslavskySV** [comment]
Dear Guido,

could you please try this (development) version of MiXCR: [MiXCR 3.0.3-dev](https://s3.amazonaws.com/files.milaboratory.com/mixcr/mixcr-303b.zip) ? It contains the fix. If the results remain the same, please, send us a raw fastq files in order we can work with the raw data to fix the problem.

**Comment by GuidoLeoni** [comment]
Dear StanisIav
I tried the new version. The results are more plausible but the overlap now is null.
I attach the TCRB files.
I can also upload the fastq files. Please do you have a ftp connection were I can upload them ?
Otherwise If you provide to me a email address i can give the credentials to connect to my ftp server
thank you
Guido
[alignments.vdjca.clonotypes.TRBDNA.txt](https://github.com/milaboratory/mixcr/files/2592351/alignments.vdjca.clonotypes.TRBDNA.txt)
[alignments.vdjca.clonotypes.TRBRNA.txt](https://github.com/milaboratory/mixcr/files/2592352/alignments.vdjca.clonotypes.TRBRNA.txt)

**Comment by PoslavskySV** [comment]
Dear Guido,

this is my private email: stvlpos (at) mail.ru / otherwise you can share the data via our MiLaboratory's official email support@milaboratory.com ; in both cases I assure you that your data will be kept in private.
