### ISSUE TITLE
Exception with 'analyze shotgun' when no clones found?

### ISSUE THREAD

**Issue by bbimber** [milaboratory/mixcr#467]
I apologize for the non-simplified report; however, I think the issue is relatively simple.  i ran mixcr analyze shotgun on input data that didnt produce clones. As a result there was no output file (i think), and this caused the next step to fail with an exception instead of a more graceful failure.  below is the command, report, and stderr:

28 Nov 2018 15:20:58,157 INFO :     /home/exacloud/lustre1/prime-seq/java/current/bin/java -Dmixcr.path=/home/groups/prime-seq/pipeline_tools/bin -Dmixcr.command=mixcr -XX:+AggressiveOpts -jar /home/groups/prime-seq/pipeline_tools/bin/mixcr.jar analyze shotgun -f --starting-material rna --report /home/exacloud/lustre1/prime-seq/workDir/14b85f77-d591-1036-b685-2143bcd21614/SequenceA.work/22034_Gag69-Clone-58/22034_Gag69-Clone-58.17.rhesus.log.txt --contig-assembly -s rhesus --align "--library rhesus_v2.1.1" --align "-OallowChimeras=true" --align "-t 12" --align "-OallowPartialAlignments=true" --align "-OsaveOriginalReads=true" --assemble "-t 12" --assemble "-OaddReadsCountOnClustering=true" --assemble "-ObadQualityThreshold=10" /home/groups/prime-seq/production/Labs/Bimber/22/@files/sequenceImport/SequenceImport_20160725/22304-Gag69-Clone-58_S9_L001_R1_001.trim.fastq.gz /home/groups/prime-seq/production/Labs/Bimber/22/@files/sequenceImport/SequenceImport_20160725/22304-Gag69-Clone-58_S9_L001_R2_001.trim.fastq.gz /home/exacloud/lustre1/prime-seq/workDir/14b85f77-d591-1036-b685-2143bcd21614/SequenceA.work/22034_Gag69-Clone-58/22034_Gag69-Clone-58.17.rhesus
28 Nov 2018 15:20:58,159 DEBUG: using path: /home/exacloud/lustre1/prime-seq/java/current/bin:/home/groups/prime-seq/pipeline_tools/bin/:/home/exacloud/lustre1/prime-seq/java/current/bin/:/home/groups/prime-seq/pipeline_tools/bin:/usr/local/bin:/usr/bin
28 Nov 2018 15:20:59,482 DEBUG:     WARNING: 1 functional genes were excluded, re-run with --verbose option to see the list of excluded genes and exclusion reason.
28 Nov 2018 15:20:59,961 DEBUG:     Alignment: 2.4%
28 Nov 2018 15:21:01,961 DEBUG:     Alignment: 29.9%  ETA: 00:00:05
28 Nov 2018 15:21:02,962 DEBUG:     Alignment: 59.8%  ETA: 00:00:01
28 Nov 2018 15:21:03,560 DEBUG: setting active task status for job: 7079017 to: running. status was: WAITING (PipelineJob) /RUNNING (StatusFile) / activeTaskId (job): org.labkey.sequenceanalysis.pipeline.AlignmentAnalysisRemoteWorkTask, hostname: exanode-7-14, rowid: 89845
28 Nov 2018 15:21:03,583 DEBUG: updated submission record status to: RUNNING
28 Nov 2018 15:21:03,965 DEBUG:     Alignment: 90.8%  ETA: 00:00:00
28 Nov 2018 15:21:04,318 DEBUG:     ============= Report ==============
28 Nov 2018 15:21:04,321 DEBUG:     Analysis time: 4.95s
28 Nov 2018 15:21:04,322 DEBUG:     Total sequencing reads: 202430
28 Nov 2018 15:21:04,324 DEBUG:     Successfully aligned reads: 34 (0.02%)
28 Nov 2018 15:21:04,325 DEBUG:     Chimeras: 7 (0%)
28 Nov 2018 15:21:04,326 DEBUG:     Alignment failed, no hits (not TCR/IG?): 167154 (82.57%)
28 Nov 2018 15:21:04,327 DEBUG:     Alignment failed because of absence of CDR3 parts: 1260 (0.62%)
28 Nov 2018 15:21:04,329 DEBUG:     Alignment failed because of low total score: 33982 (16.79%)
28 Nov 2018 15:21:04,330 DEBUG:     Overlapped: 93850 (46.36%)
28 Nov 2018 15:21:04,331 DEBUG:     Overlapped and aligned: 4 (0%)
28 Nov 2018 15:21:04,333 DEBUG:     Alignment-aided overlaps: 0 (0%)
28 Nov 2018 15:21:04,334 DEBUG:     Overlapped and not aligned: 93846 (46.36%)
28 Nov 2018 15:21:04,335 DEBUG:     TRA chains: 27 (79.41%)
28 Nov 2018 15:21:04,803 DEBUG:     Building index: 0.6%
28 Nov 2018 15:21:04,829 DEBUG:     Searching for overlaps: 0.6%
28 Nov 2018 15:21:04,846 DEBUG:     ============= Report ==============
28 Nov 2018 15:21:04,848 DEBUG:     Analysis time: 141.00ms
28 Nov 2018 15:21:04,849 DEBUG:     Total alignments analysed: 34
28 Nov 2018 15:21:04,851 DEBUG:     Number of output alignments: 34 (100%)
28 Nov 2018 15:21:04,852 DEBUG:     Alignments already with CDR3 (no overlapping is performed): 0 (0%)
28 Nov 2018 15:21:04,854 DEBUG:     Successfully overlapped alignments: 0 (0%)
28 Nov 2018 15:21:04,855 DEBUG:     Left parts with too small N-region (failed to extract k-mer): 0 (0%)
28 Nov 2018 15:21:04,857 DEBUG:     Extracted k-mer diversity: 0
28 Nov 2018 15:21:04,858 DEBUG:     Dropped due to wildcard in k-mer: 0 (0%)
28 Nov 2018 15:21:04,860 DEBUG:     Dropped due to too short NRegion parts in overlap: 0 (0%)
28 Nov 2018 15:21:04,861 DEBUG:     Dropped overlaps with empty N region due to no complete NDN coverage: 0 (0%)
28 Nov 2018 15:21:04,862 DEBUG:     Number of left-side alignments: 0 (0%)
28 Nov 2018 15:21:04,864 DEBUG:     Number of right-side alignments: 33 (97.06%)
28 Nov 2018 15:21:04,865 DEBUG:     Complex overlaps: 0 (0%)
28 Nov 2018 15:21:04,867 DEBUG:     Over-overlaps: 0 (0%)
28 Nov 2018 15:21:04,868 DEBUG:     Partial alignments written to output: 34 (100%)
28 Nov 2018 15:21:04,918 DEBUG:     Building index: 0.6%
28 Nov 2018 15:21:04,934 DEBUG:     Searching for overlaps: 0.6%
28 Nov 2018 15:21:04,944 DEBUG:     ============= Report ==============
28 Nov 2018 15:21:04,945 DEBUG:     Analysis time: 71.00ms
28 Nov 2018 15:21:04,947 DEBUG:     Total alignments analysed: 34
28 Nov 2018 15:21:04,948 DEBUG:     Number of output alignments: 34 (100%)
28 Nov 2018 15:21:04,950 DEBUG:     Alignments already with CDR3 (no overlapping is performed): 0 (0%)
28 Nov 2018 15:21:04,951 DEBUG:     Successfully overlapped alignments: 0 (0%)
28 Nov 2018 15:21:04,953 DEBUG:     Left parts with too small N-region (failed to extract k-mer): 0 (0%)
28 Nov 2018 15:21:04,955 DEBUG:     Extracted k-mer diversity: 0
28 Nov 2018 15:21:04,957 DEBUG:     Dropped due to wildcard in k-mer: 0 (0%)
28 Nov 2018 15:21:04,958 DEBUG:     Dropped due to too short NRegion parts in overlap: 0 (0%)
28 Nov 2018 15:21:04,960 DEBUG:     Dropped overlaps with empty N region due to no complete NDN coverage: 0 (0%)
28 Nov 2018 15:21:04,961 DEBUG:     Number of left-side alignments: 0 (0%)
28 Nov 2018 15:21:04,962 DEBUG:     Number of right-side alignments: 33 (97.06%)
28 Nov 2018 15:21:04,964 DEBUG:     Complex overlaps: 0 (0%)
28 Nov 2018 15:21:04,965 DEBUG:     Over-overlaps: 0 (0%)
28 Nov 2018 15:21:04,966 DEBUG:     Partial alignments written to output: 34 (100%)
28 Nov 2018 15:21:05,013 DEBUG:     Processing: 0%
28 Nov 2018 15:21:05,046 DEBUG:     ============= Report ==============
28 Nov 2018 15:21:05,048 DEBUG:     Analysis time: 5.00ms
28 Nov 2018 15:21:05,050 DEBUG:     Extended alignments count: 0 (0%)
28 Nov 2018 15:21:05,051 DEBUG:     V extensions total: 0 (0%)
28 Nov 2018 15:21:05,052 DEBUG:     V extensions with merged targets: 0 (0%)
28 Nov 2018 15:21:05,054 DEBUG:     J extensions total: 0 (0%)
28 Nov 2018 15:21:05,055 DEBUG:     J extensions with merged targets: 0 (0%)
28 Nov 2018 15:21:05,057 DEBUG:     V+J extensions: 0 (0%)
28 Nov 2018 15:21:05,058 DEBUG:     Mean V extension length: NaN
28 Nov 2018 15:21:05,059 DEBUG:     Mean J extension length: NaN
28 Nov 2018 15:21:05,138 DEBUG:     Initialization: progress unknown
28 Nov 2018 15:21:05,200 DEBUG:     Preparing for sorting: progress unknown
28 Nov 2018 15:21:09,290 DEBUG:     Writing alignments: 100%
28 Nov 2018 15:21:09,292 DEBUG:     ============= Report ==============
28 Nov 2018 15:21:09,294 DEBUG:     Analysis time: 4.16s
28 Nov 2018 15:21:09,295 DEBUG:     Final clonotype count: 0
28 Nov 2018 15:21:09,297 DEBUG:     Average number of reads per clonotype: ?
28 Nov 2018 15:21:09,298 DEBUG:     Reads used in clonotypes, percent of total: 0 (0%)
28 Nov 2018 15:21:09,300 DEBUG:     Reads used in clonotypes before clustering, percent of total: 0 (0%)
28 Nov 2018 15:21:09,301 DEBUG:     Number of reads used as a core, percent of used: 0 (?%)
28 Nov 2018 15:21:09,302 DEBUG:     Mapped low quality reads, percent of used: 0 (?%)
28 Nov 2018 15:21:09,304 DEBUG:     Reads clustered in PCR error correction, percent of used: 0 (?%)
28 Nov 2018 15:21:09,305 DEBUG:     Reads pre-clustered due to the similar VJC-lists, percent of used: 0 (?%)
28 Nov 2018 15:21:09,307 DEBUG:     Reads dropped due to the lack of a clone sequence: 34 (0.02%)
28 Nov 2018 15:21:09,308 DEBUG:     Reads dropped due to low quality: 0 (0%)
28 Nov 2018 15:21:09,310 DEBUG:     Reads dropped due to failed mapping: 0 (0%)
28 Nov 2018 15:21:09,311 DEBUG:     Reads dropped with low quality clones: 0 (?%)
28 Nov 2018 15:21:09,312 DEBUG:     Clonotypes eliminated by PCR error correction: 0
28 Nov 2018 15:21:09,313 DEBUG:     Clonotypes dropped as low quality: 0
28 Nov 2018 15:21:09,315 DEBUG:     Clonotypes pre-clustered due to the similar VJC-lists: 0
28 Nov 2018 15:21:09,367 DEBUG:     Assembling: 0%
28 Nov 2018 16:36:02,846 DEBUG:     Exception in thread "main" picocli.CommandLine$ExecutionException: Error while running command (com.milaboratory.mixcr.cli.CommandAnalyze$CommandShotgun@49293b43): java.lang.RuntimeException: java.io.FileNotFoundException: /home/exacloud/lustre1/prime-seq/workDir/14b85f77-d591-1036-b685-2143bcd21614/SequenceA.work/22034_Gag69-Clone-58/22034_Gag69-Clone-58.17.rhesus.contigs.clns (No such file or directory)
28 Nov 2018 16:36:02,854 DEBUG:         at picocli.CommandLine.execute(CommandLine.java:1004)
28 Nov 2018 16:36:02,855 DEBUG:         at picocli.CommandLine.access$900(CommandLine.java:142)
28 Nov 2018 16:36:02,857 DEBUG:         at picocli.CommandLine$RunLast.handle(CommandLine.java:1199)
28 Nov 2018 16:36:02,858 DEBUG:         at com.milaboratory.mixcr.cli.Main$1.handle(Main.java:48)
28 Nov 2018 16:36:02,860 DEBUG:         at com.milaboratory.mixcr.cli.Main$1.handle(Main.java:31)
28 Nov 2018 16:36:02,861 DEBUG:         at picocli.CommandLine$AbstractParseResultHandler.handleParseResult(CommandLine.java:1075)
28 Nov 2018 16:36:02,862 DEBUG:         at com.milaboratory.mixcr.cli.Main.handleParseResult(Main.java:53)
28 Nov 2018 16:36:02,864 DEBUG:         at com.milaboratory.mixcr.cli.Main.main(Main.java:25)
28 Nov 2018 16:36:02,865 DEBUG:     Caused by: java.lang.RuntimeException: java.io.FileNotFoundException: /home/exacloud/lustre1/prime-seq/workDir/14b85f77-d591-1036-b685-2143bcd21614/SequenceA.work/22034_Gag69-Clone-58/22034_Gag69-Clone-58.17.rhesus.contigs.clns (No such file or directory)
28 Nov 2018 16:36:02,867 DEBUG:         at com.milaboratory.mixcr.cli.ACommand.run(ACommand.java:77)
28 Nov 2018 16:36:02,868 DEBUG:         at com.milaboratory.mixcr.cli.CommandAnalyze.run0(CommandAnalyze.java:589)
28 Nov 2018 16:36:02,870 DEBUG:         at com.milaboratory.mixcr.cli.ACommand.run(ACommand.java:73)
28 Nov 2018 16:36:02,871 DEBUG:         at picocli.CommandLine.execute(CommandLine.java:996)
28 Nov 2018 16:36:02,872 DEBUG:         ... 7 more
28 Nov 2018 16:36:02,874 DEBUG:     Caused by: java.io.FileNotFoundException: /home/exacloud/lustre1/prime-seq/workDir/14b85f77-d591-1036-b685-2143bcd21614/SequenceA.work/22034_Gag69-Clone-58/22034_Gag69-Clone-58.17.rhesus.contigs.clns (No such file or directory)
28 Nov 2018 16:36:02,875 DEBUG:         at java.io.FileOutputStream.open0(Native Method)
28 Nov 2018 16:36:02,876 DEBUG:         at java.io.FileOutputStream.open(FileOutputStream.java:270)
28 Nov 2018 16:36:02,878 DEBUG:         at java.io.FileOutputStream.<init>(FileOutputStream.java:213)
28 Nov 2018 16:36:02,879 DEBUG:         at java.io.FileOutputStream.<init>(FileOutputStream.java:162)
28 Nov 2018 16:36:02,880 DEBUG:         at com.milaboratory.mixcr.basictypes.IOUtil.createOS(IOUtil.java:155)
28 Nov 2018 16:36:02,882 DEBUG:         at com.milaboratory.mixcr.basictypes.ClnsWriter.<init>(ClnsWriter.java:39)
28 Nov 2018 16:36:02,883 DEBUG:         at com.milaboratory.mixcr.basictypes.ClnsWriter.<init>(ClnsWriter.java:35)
28 Nov 2018 16:36:02,885 DEBUG:         at com.milaboratory.mixcr.cli.CommandAssembleContigs.run1(CommandAssembleContigs.java:158)
28 Nov 2018 16:36:02,886 DEBUG:         at com.milaboratory.mixcr.cli.ACommandWithSmartOverwrite.run0(ACommandWithSmartOverwrite.java:99)
28 Nov 2018 16:36:02,887 DEBUG:         at com.milaboratory.mixcr.cli.ACommand.run(ACommand.java:73)
28 Nov 2018 16:36:02,889 DEBUG:         ... 10 more
28 Nov 2018 16:36:03,282 WARN :     process exited with non-zero value: 1
28 Nov 2018 16:36:03,284 INFO : Failed to complete task 'org.labkey.sequenceanalysis.pipeline.AlignmentAnalysisRemoteWorkTask'
28 Nov 2018 16:36:03,288 DEBUG: inspecting remote work dir: /home/exacloud/lustre1/prime-seq/workDir/14b85f77-d591-1036-b685-2143bcd21614
28 Nov 2018 16:36:03,293 ERROR: process exited with non-zero value: 1

**Comment by PoslavskySV** [comment]
Hi!

It seems that the problem is not on the MiXCR side. MiXCR produces `.clna` and `.clns` files even if clone count is zero. I just tried to use your commands on some dummy files (with no clones), and MiXCR successfully worked. From your error message I can only guess that the directory `/home/exacloud/lustre1/prime-seq/workDir/14b85f77-d591-1036-b685-2143bcd21614/SequenceA.work/22034_Gag69-Clone-58/` was deleted by some other process while MiXCR was executing or something similar. Do you able to reproduce the problem?

**Comment by bbimber** [comment]
It is possible this is some kind of cluster I/O problem.  This is the only category of job to experience these issues though.  I'll look further on our side.
