### ISSUE TITLE
A comma in the targetSequence of exportClones

### ISSUE THREAD

**Issue by mvanmoerbeke** [milaboratory/mixcr#483]
## Checklist before submitting the issue:

 - [X] The issue is strongly related to the MiXCR software
 - [X] The issue can be reproduced with [the most recent version](https://github.com/milaboratory/mixcr/releases) of MiXCR
 - [X] There is no answer to the question in the [official documentation](http://mixcr.readthedocs.io/) and there is no duplicate issue in the [bug tracker](https://github.com/milaboratory/mixcr/issues?utf8=✓&q=)  
 - [X] Inspection of raw alignments with [exportAlignmentsPretty](http://mixcr.readthedocs.io/en/master/export.html#exporting-well-formatted-alignments-for-manual-inspection) shows that data has the expected architecture, and sample preparation artefacts are not the reason of the problem (if this is the matter of the issue)

## Expected Result

The expected result of the sample was a standard targetSequence in the exportClones result.

## Actual Result

The exportClones command returned a targetSequence with a "," in between the nucleotides for cloneID 1. This "," is duplicated in the columns all[v|d|j|c]alignments. 

`
1	2494.0	0.3224305106658048	ATGGCTACAATGTCTCCAGATCAA,CACAGAGGATTTCCCGCTCAGGCTGCTGTCGGCTGCTCCCTCCCAGACATCTGTGTACTTCTGTGCCAGCAGTTACTCCGGGGCAGGCACCGGGGAGCTGTTTTTTGGAGAAGGCTCTAGGCTGACCGTACTGG	[[[[47[,4*[[[4@H$??;+$7B,6B?9<<,?>?;>;;<HA:[CB[B[BC<>2;:>@;>?;[?[;@?;9@<?><[>B>>[>;8;@,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,8;9?889<;58>7:::965;;<7787;9	TRBV6-5*01(880.8),TRBV6-6*01(735.6)	TRBD1*01(31)	TRBJ2-2*01(468.7)		184|208|307|0|24||240.0,209|287|307|0|78||780.0;,270|287|307|61|78||170.0	,11|20|36|78|87|SA15G|31.0	,24|71|71|87|134||470.0		aatgctggtgtcactcagaccccaaaattccaggtcctgaagacaggacagagcatgacactgcagtgtgcccaggat		atgaaccatgaatac		atgtcctggtatcgacaagacccaggcatggggctgaggctgattcattac		tcagttggtgctggtatc		actgaccaaggagaagtccccaATGGCTACAATGTCTCCAGATCAAcCACAGAGGATTTCCCGCTCAGGCTGCTGTCGGCTGCTCCCTCCCAGACATCTGTGTACTTC		TGTGCCAGCAGTTACTCCGGGGCAGGCACCGGGGAGCTGTTTTTT	11	GGAGAAGGCTCTAGGCTGACCGTACTGG	20	nagvtqtpkfqvlktgqsmtlqcaqd	mnhey	mswyrqdpgmglrlihy	svgagi	tdqgevpNGYNVSRSTTEDFPLRLLSAAPSQTSVYF	CASSYSGAGTGELFF	GEGSRLTVL_	:::::::::::::::::::::,:::::::::61:0:78:78:1:-4:87:87:-4:106:134::	TRBV6-5*01
`
Inspection of the exportAlignments after the align and assemble step did not reveal this "," in the target sequenes. However, there was doubt between an A or C nucleotide at the location of the ",". Is the "," in the exportClones an expression of this doubt? The columns all[d|j]allignment  start with a ",", is this due to the missing nucleotide also being part of the d|j genes?

Upon inspecting the exportClonespretty we could see that the targetSequence was divided over a Target0 and Target1.  Could you maybe explain why this has happened?

```
 Clone id: 1
Abundance, reads (fraction): 2494.0 (0.3224305106658048)

                                           
                                           
   Quality     999934923199936706652046    
   Target0   0 ATGGCTACAATGTCTCCAGATCAA 23   Score (hit score)
TRBV6-5*01 184 atggctacaatgtctccagatcaa 207  240 (880)

                                                                                           DP><    
                                                                        FR3><CDR3          V><D    
               _ T  E  D  F  P  L  R  L  L  S  A  A  P  S  Q  T  S  V  Y  F  C  A  S  S  Y  S      
   Quality     46645526565555576596696966553555655659695665465655956559554562222222222222222222    
   Target1   0 CACAGAGGATTTCCCGCTCAGGCTGCTGTCGGCTGCTCCCTCCCAGACATCTGTGTACTTCTGTGCCAGCAGTTACTCCG 79   Score (hit score)
TRBV6-5*01 209 cacagaggatttcccgctcaggctgctgtcggctgctccctcccagacatctgtgtacttctgtgccagcagttactc   286  780 (880)
TRBV6-6*01 270                                                              tgtgccagcagttactc   286  170 (735)
  TRBD1*01  11                                                                               cg 12   31 (31)

              D                                                         
              P    D><J            CDR3><FR4                    FR4>    
              G  A  G  T  G  E  L  F  F  G  E  G  S  R  L  T  V  L _    
   Quality    222222222222222222222222224546444554454555444555444454    
   Target1 80 GGGCAGGCACCGGGGAGCTGTTTTTTGGAGAAGGCTCTAGGCTGACCGTACTGG 133  Score (hit score)
  TRBD1*01 13 ggAcagg                                                19   31 (31)
TRBJ2-2*01 24        caccggggagctgttttttggagaaggctctaggctgaccgtactgg 70   470 (468)
```

## Exact MiXCR commands 

`mixcr align --species HomoSapiens --library imgt -OvParameters.geneFeatureToAlign=VTranscriptWithP -OvParameters.parameters.relativeMinScore=0.99 -OjParameters.parameters.relativeMinScore=0.99 -OdParameters.relativeMinScore=0.99 -OcParameters.parameters.relativeMinScore=0.99 05C12.fastq 05C12.fastq.vdjca -f -r 05C12.fastq.report.txt
`
`mixcr assemble -OaddReadsCountOnClustering=true -OcloneClusteringParameters.clusteringFilter.specificMutationProbability=1E-2 --write-alignments 05C12.vdjca 05C12.clna -f -r 05C12.report.txt
`
`mixcr assembleContigs -OalignedRegionsOnly=true  -OtrimmingParameters.windowSize=1 -OtrimmingParameters.averageQualityThreshold=10 05C12.clna 05C12.clns -f -r  05C12.report.txt`

`mixcr extend --v-anchor L1Begin --j-anchor FR4End 05C12.clns 05C12.e.clns -f`

`mixcr exportClones -m 10 -p fullImputed -f 05C12.e.clns 05C12.txt
`
### align 
```
Version: 3.0.3; built=Sun Nov 18 16:48:30 CET 2018; rev=5281a0f; lib=repseqio.v1.5
Analysis time: 5.39s
Total sequencing reads: 8451
Successfully aligned reads: 8164 (96.6%)
Alignment failed, no hits (not TCR/IG?): 7 (0.08%)
Alignment failed because of absence of J hits: 278 (3.29%)
Alignment failed because of low total score: 2 (0.02%)
Overlapped: 0 (0%)
Overlapped and aligned: 0 (0%)
Alignment-aided overlaps: 0 (�%)
Overlapped and not aligned: 0 (0%)
TRA chains: 5489 (67.23%)
TRB chains: 2675 (32.77%)
```
### assemble

```
Version: 3.0.3; built=Sun Nov 18 16:48:30 CET 2018; rev=5281a0f; lib=repseqio.v1.5
Analysis time: 3.41s
Final clonotype count: 423
Average number of reads per clonotype: 18.29
Reads used in clonotypes, percent of total: 7735 (91.53%)
Reads used in clonotypes before clustering, percent of total: 7735 (91.53%)
Number of reads used as a core, percent of used: 7724 (99.86%)
Mapped low quality reads, percent of used: 11 (0.14%)
Reads clustered in PCR error correction, percent of used: 526 (6.8%)
Reads pre-clustered due to the similar VJC-lists, percent of used: 0 (0%)
Reads dropped due to the lack of a clone sequence: 124 (1.47%)
Reads dropped due to low quality: 0 (0%)
Reads dropped due to failed mapping: 147 (1.74%)
Reads dropped with low quality clones: 0 (0%)
Clonotypes eliminated by PCR error correction: 255
Clonotypes dropped as low quality: 0
Clonotypes pre-clustered due to the similar VJC-lists: 0
```

### assembleContigs

```
Version: 3.0.3; built=Sun Nov 18 16:48:30 CET 2018; rev=5281a0f; lib=repseqio.v1.5
Analysis time: 2.96s
Initial clonotype count: 423
Final clonotype count: 423 (100%)
Longest contig length: 171
Clustered variants: 0 (0%)
Reads in clustered variants: 0.0 (0%)
Reads in divided (newly created) clones: 0.0 (0%)
```

**Comment by PoslavskySV** [comment]
Hi,

the comma separates different target sequences. After contig assembly your clonal sequence may have several targets, so they are all printed in `targetSequences` column separated with comma. You can see how your contigs look by running

```
mixcr exportClonesPretty 05C12.e.clns
```

**Comment by xin8you** [comment]
> Hi,
> 
> the comma separates different target sequences. After contig assembly your clonal sequence may have several targets, so they are all printed in `targetSequences` column separated with comma. You can see how your contigs look by running
> 
> ```
> mixcr exportClonesPretty 05C12.e.clns
> ```
when the comma separates different target sequences, I use one step command 'mixcr analyze amplicon' and use step by step the assemble results were different as below:
One step result:
![image](https://user-images.githubusercontent.com/30464733/117939782-00a22200-b33b-11eb-9ddf-361169afba6a.png)
step by step result:
![image](https://user-images.githubusercontent.com/30464733/117939843-0d267a80-b33b-11eb-8c60-0125e6f76391.png)

**Comment by xin8you** [comment]
I have Another question! Two experiments were done on the same sample but the results were inconsistent, but the sequence and analysis methods were the same.
experiment 1: 
![image](https://user-images.githubusercontent.com/30464733/117943136-680da100-b33e-11eb-9c15-838717e2ddf0.png)
experiment 2:
![image](https://user-images.githubusercontent.com/30464733/117943269-86739c80-b33e-11eb-9621-b56e126c792d.png)
experiment 1 has best Vgene of IGHV4-34 and experiment 1 was IGHV4-39,  can you help explain what caused it ?

best!
