### ISSUE TITLE
clonalSequenceQuality and minQualCDR3 fileds

### ISSUE THREAD

**Issue by innagsc** [milaboratory/mixcr#484]
## Checklist before submitting the issue:

 - [x ] The issue is strongly related to the MiXCR software
 - [x ] The issue can be reproduced with [the most recent version](https://github.com/milaboratory/mixcr/releases) of MiXCR
 - [x ] There is no answer to the question in the [official documentation](http://mixcr.readthedocs.io/) and there is no duplicate issue in the [bug tracker](https://github.com/milaboratory/mixcr/issues?utf8=✓&q=)  
 - [x ] Inspection of raw alignments with [exportAlignmentsPretty](http://mixcr.readthedocs.io/en/master/export.html#exporting-well-formatted-alignments-for-manual-inspection) shows that data has the expected architecture, and sample preparation artefacts are not the reason of the problem (if this is the matter of the issue)

Hello, 

I have exported the clonal file and there are two columns/fields that I couldn't find the meaning for.

What does 
 

- clonalSequenceQuality (H,G,D,E,?)

 

- minQualCDR3 

 
mean?

clonalSequenceQuality | minQualCDR3
--------------------------|----------------
HHHHHHHGGHGHHHHHHHHHHHHHHHGHHHHHHHHHHHHHHHHHHHHHHHHHHH| 38
HHHHHHHHGGGGGGHHHHHHHHHHHHHHHHHGHHHGGGHHHHHHHHHHGGGGGHHHHHHHHHHHHH | 38

Thanks

**Comment by PoslavskySV** [comment]
Hi!

clonalSequenceQuality  is the sequence quality of the clonal sequence encoded using Phred+33.  `minQual` option is not encoded at all, it is given  just by the raw byte value, so minQualCDR3 is just the minimal quality in the clonal sequence (CDR3).
