### ISSUE TITLE
refPoints inconsistencies

### ISSUE THREAD

**Issue by vanessajmh** [milaboratory/mixcr#485]
Hello,

I've been using mixcr for a while now to align TCR sequences and I recently got interested in analyzing the insertions/deletions in my sequences which information is given in the column "refPoints". 
Knowing that miscr uses IMGT libraries as alignment references, I found some inconsistencies and tried to align a few CDR3 sequences manually using also IMGT as a reference. 3 exemples are given below:
1- Number of nucleotide deletions (negative value), or length of P-segment (positive value): I believe the number of P-segment is calculated when there is no gene deletion, but how is this segment identified?
2- For the second sequence, the number of V deletions is 2 while I manually identified one deletion only.
3- What determines the detection or not of a D gene? In the third sequence, a D motif of 4 nucleotides is identified in the region between the V and the J however no D is detected by mixcr.
[mixcr.xlsx](https://github.com/milaboratory/mixcr/files/2787897/mixcr.xlsx)

Thank you !

**Comment by dbolotin** [comment]
Please note that MiXCR uses genome assembly based reference, not IMGT, you can use IMGT's reference as described here:
https://mixcr.readthedocs.io/en/master/importSegments.html#imgt-library
