### ISSUE TITLE
Use clns if clna is not needed in analyze

### ISSUE THREAD

**Issue by dbolotin** [milaboratory/mixcr#487]

**Comment by PoslavskySV** [comment]
If no `--contig-assembly` always use clns?

**Comment by dbolotin** [comment]
Yes, I think analyze should perform the most optimal (both in terms of CPU
and HDD) set of commands.

Another idea is to maybe add an option to delete all intermediate files
after successful clonotype export. What do you think?

**Comment by dbolotin** [comment]
This one is important.
