### ISSUE TITLE
Extremely High Memory Usage

### ISSUE THREAD

**Issue by JulianSpagnuolo** [milaboratory/mixcr#488]
I am running the automated mixcr analyze shotgun pipeline (MiXCR v 3.0.3) on my institute's HTC environment and have noticed that the report sent back by the slurm environment upon job completion is indicating that the amount of memory used by MiXCR is often upto 4 Tb.

In contrast, the equivalent manual procedure using MiXCR v 2.1.9 without the assemblePartial and extend steps never utilised over 12 Gb of memory in total.

Considering that the PE and SE fastq files I am processing are small (< 300 Mb) I would not expect such heavy memory usage.

```
pathin=$1
mode=$2

cd $pathin
rm -r mixcr
mkdir mixcr

module load MiXCR/3.0.3-Java-1.8.0_92

if [ "$mode" = "PE" ]; then
  for r1 in *_1.fastq; do
     mixcr analyze shotgun -s hsa --starting-material rna --receptor-type tcr --only-productive --align "-t 12 -OallowPartialAlignments=true" --assemble "-t 12" --export "-cloneId -count -fraction -vHit -dHit -jHit -cHit -vGene -dGene -jGene -cGene -vFamily -dFamily -jFamily -cFamily -vHitScore -dHitScore -jHitScore -cHitScore -nFeature CDR3 -nFeature VCDR3Part -nFeature DCDR3Part -nFeature JCDR3Part -nFeature VJJunction -nFeature VDJunction -nFeature DJJunction -aaFeature CDR3 -qFeature CDR3 -chains" ${r1} ${r1[@]/_1.fastq/_2.fastq} ${r1[@]/_1.fastq/_mixcr}
  done
elif [ "$mode" = "SE" ]; then
  for r1 in *.fastq; do
    mixcr analyze shotgun -s hsa --starting-material rna --receptor-type tcr --only-productive --align "-t 12 -OallowPartialAlignments=true" --assemble "-t 12" --export "-cloneId -count -fraction -vHit -dHit -jHit -cHit -vGene -dGene -jGene -cGene -vFamily -dFamily -jFamily -cFamily -vHitScore -dHitScore -jHitScore -cHitScore -nFeature CDR3 -nFeature VCDR3Part -nFeature DCDR3Part -nFeature JCDR3Part -nFeature VJJunction -nFeature VDJunction -nFeature DJJunction -aaFeature CDR3 -qFeature CDR3 -chains" ${r1} ${r1[@]/_1.fastq/_mixcr}
  done
else
  echo variable two must be either SE or PE depending on whether sequences are single end reads SE, or paired end PE.
fi
```

**Comment by PoslavskySV** [comment]
Hi! 

Thanks for reporting. It looks really strange, and, unfortunately, it is note possible to detect the reason without debugging. Can you share fastq file(s) with us so we can debug the problem (you can write to poslavskysv@milaboratory.com)? We'll keep it securely and remove right after we'll figure out the problem.
