### ISSUE TITLE
Error when trying to run analyze shotgun

### ISSUE THREAD

**Issue by rosasott** [milaboratory/mixcr#493]
Hi,
I'm very new to mixcr and even to running pipelines for analysis.
anyway I'm trying my best to learn and I just got some fastq RNA-seq files and I want to extract TCR clonality informations.
I installed mixcr but when I run the analyze shotgun it gives me the following error:

mixcr analyze shotgun \
>         --species hs \
>         --starting-material rna \
>         --only-productive \
>         HD265TNKG2Csp_R1.fastq HD265TNKG2Csp_R2.fastq analysis
Java HotSpot(TM) 64-Bit Server VM warning: Option AggressiveOpts was deprecated in version 11.0 and will likely be removed in a future release.
Error: Expected a command, got analyze

I don't know what it is and I also don't understand where to physically place the fastq files in order for the program to find them.

I also tried the "align" command alone and this is what I got:

mixcr align -p rna-seq -s hsa -OallowPartialAlignments=true HD265TNKG2Csp_R1.fastq.gz HD265TNKG2Csp_R2.fastq.gz alignments.vdjca
Java HotSpot(TM) 64-Bit Server VM warning: Option AggressiveOpts was deprecated in version 11.0 and will likely be removed in a future release.
Reference library: repseqio.v1.5:9606:29a95112c52f62585b28d241db7fd523
Exception in thread "main" java.io.FileNotFoundException: HD265TNKG2Csp_R1.fastq.gz (No such file or directory)
	at java.base/java.io.FileInputStream.open0(Native Method)
	at java.base/java.io.FileInputStream.open(FileInputStream.java:219)
	at java.base/java.io.FileInputStream.<init>(FileInputStream.java:157)
	at java.base/java.io.FileInputStream.<init>(FileInputStream.java:112)
	at com.milaboratory.core.io.sequence.fastq.SingleFastqReader.<init>(SingleFastqReader.java:65)
	at com.milaboratory.core.io.sequence.fastq.PairedFastqReader.<init>(PairedFastqReader.java:60)
	at com.milaboratory.mixcr.cli.ActionAlign$AlignParameters.createReader(ActionAlign.java:455)
	at com.milaboratory.mixcr.cli.ActionAlign.go(ActionAlign.java:202)
	at com.milaboratory.cli.JCommanderBasedMain.main(JCommanderBasedMain.java:157)
	at com.milaboratory.mixcr.cli.Main.main(Main.java:124)

Any help would be very much appreciated!
Thanks

**Comment by rosasott** [comment]
Also this happened when exploring other commands...

Last login: Tue Feb 12 18:15:40 on ttys000
lski2537:~ sottiler$ /Users/sottiler/Downloads/mixcr-3.0-2.3/milib
-bash: /Users/sottiler/Downloads/mixcr-3.0-2.3/milib: is a directory
lski2537:~ sottiler$ mixcr align -s hs -p rna-seq \
>     -OvParameters.geneFeatureToAlign=VRegionwithP \
>     -OvParameters.parameters.floatingLeftBound=false \
>     -OvParameters.parameters.floatingRightBound=false \
>     -OvParameters.parameters.floatingRightBound=false \
>     [align options] HD265TNKG2Csp_R1.fastq [HD265TNKG2Csp_R2.fastq] my_analysis.vdjca
Java HotSpot(TM) 64-Bit Server VM warning: Option AggressiveOpts was deprecated in version 11.0 and will likely be removed in a future release.
Error: Too many input files.
lski2537:~ sottiler$

**Comment by PoslavskySV** [comment]
Hi!

This command:
```
mixcr analyze shotgun \
     --species hs \
     --starting-material rna \
     --only-productive \
     HD265TNKG2Csp_R1.fastq HD265TNKG2Csp_R2.fastq analysis
```

should work fine with MiXCR 3.0. The files should be placed in the same folder from which you run `mixcr` command.


Command in the last message is wrong, here is the correct one:
```
mixcr align -s hs -p rna-seq \
 -OvParameters.geneFeatureToAlign=VRegionwithP \
 -OvParameters.parameters.floatingLeftBound=false \
 -OvParameters.parameters.floatingRightBound=false \
 -OvParameters.parameters.floatingRightBound=false \
HD265TNKG2Csp_R1.fastq HD265TNKG2Csp_R2.fastq my_analysis.vdjca
```

Please confirm that it works.

**Comment by rosasott** [comment]
Hi,
Thanks a lot for your reply. Unfortunately I still get this:

Last login: Wed Feb 13 10:45:11 on ttys000
lski2537:~ sottiler$ mixcr analyze shotgun \
>      --species hs \
>      --starting-material rna \
>      --only-productive \
>      HD265TNKG2Csp_R1.fastq HD265TNKG2Csp_R2.fastq analysis
Java HotSpot(TM) 64-Bit Server VM warning: Option AggressiveOpts was deprecated in version 11.0 and will likely be removed in a future release.
Error: Expected a command, got analyze
lski2537:~ sottiler$ 

It always says "expected a command, got analyze"

Something is wrong? I used Homebrew to install MIXCR...maybe I should do the manual installation?

Regarding align command again it cannot find the files:

Last login: Wed Feb 13 10:49:31 on ttys000
lski2537:~ sottiler$ mixcr align -s hs -p rna-seq \
>  -OvParameters.geneFeatureToAlign=VRegionwithP \
>  -OvParameters.parameters.floatingLeftBound=false \
>  -OvParameters.parameters.floatingRightBound=false \
>  -OvParameters.parameters.floatingRightBound=false \
> HD265TNKG2Csp_R1.fastq HD265TNKG2Csp_R2.fastq my_analysis.vdjca
Java HotSpot(TM) 64-Bit Server VM warning: Option AggressiveOpts was deprecated in version 11.0 and will likely be removed in a future release.
WARNING: unnecessary override -OfloatingLeftBound=false with the same value.
Reference library: repseqio.v1.5:9606:29a95112c52f62585b28d241db7fd523
Exception in thread "main" java.io.FileNotFoundException: HD265TNKG2Csp_R2.fastq (No such file or directory)
	at java.base/java.io.FileInputStream.open0(Native Method)
	at java.base/java.io.FileInputStream.open(FileInputStream.java:219)
	at java.base/java.io.FileInputStream.<init>(FileInputStream.java:157)
	at java.base/java.io.FileInputStream.<init>(FileInputStream.java:112)
	at com.milaboratory.core.io.sequence.fastq.SingleFastqReader.<init>(SingleFastqReader.java:65)
	at com.milaboratory.core.io.sequence.fastq.PairedFastqReader.<init>(PairedFastqReader.java:60)
	at com.milaboratory.mixcr.cli.ActionAlign$AlignParameters.createReader(ActionAlign.java:455)
	at com.milaboratory.mixcr.cli.ActionAlign.go(ActionAlign.java:202)
	at com.milaboratory.cli.JCommanderBasedMain.main(JCommanderBasedMain.java:157)
	at com.milaboratory.mixcr.cli.Main.main(Main.java:124)
lski2537:~ sottiler$ 

This is the path of my folder:
/usr/local/Cellar/mixcr/2.1.12-1

Homebrew istalled it here and I put the files in this exact folder. I also tried to specify the path at the beginning of the session but still doesn't work. I'm going crazy! 
Thanks!

**Comment by PoslavskySV** [comment]
Just checked, both commands work on my computer with MiXCR 3. So your problem is related to the Linux usage, but not to MiXCR. I suggest you to ask your system administrator to help.

**Comment by rosasott** [comment]
Well thanks for checking but I don't use Linux, and I still think somebody should explain what the error message is..."expected a command, got analyze"

**Comment by PoslavskySV** [comment]
"expected a command, got analyze" --- that means the command is incorrect. Just found that your MiXCR version is 2.1.12-1, while `analyze` was introduced in MiXCR 3. If you use brew you can install it with 

```
brew install mixcr3
```

Regarding the second error: it suggests that `HD265TNKG2Csp_R2.fastq` does not exist (you can check what files are in your current dir by executing `ls - l`).

**Comment by rosasott** [comment]
Ok,
thanks a lot.
Just so you know in the website https://mixcr.readthedocs.io/en/master/install.html
using homebrew it installs MiXCR version is 2.1.12-1. Now I've installed version 3 with your command and it says:
Last login: Wed Feb 13 11:47:39 on ttys000
lski2537:~ sottiler$ mixcr analyze shotgun \
>         --species hs \
>         --starting-material rna \
>         --only-productive \
>         HD265TNKG2Csp_R1.fastq HD265TNKG2Csp_R2.fastq analysis
-bash: mixcr: command not found
lski2537:~ sottiler$ 
Thanks

**Comment by PoslavskySV** [comment]
Thanks for pointing to the doc, just fixed it. 

If you already have MiXCR installed via brew, try
```
brew unlink mixcr
brew link mixcr3
```

**Comment by PoslavskySV** [comment]
UPD: for reference, `brew install mixcr` will now install MiXCR 3.x, while for MiXCR 2.x one can still use `brew install mixcr2`

**Comment by decenwang** [comment]
> Hi!
> 
> This command:
> 
> ```
> mixcr analyze shotgun \
>      --species hs \
>      --starting-material rna \
>      --only-productive \
>      HD265TNKG2Csp_R1.fastq HD265TNKG2Csp_R2.fastq analysis
> ```
> 
> should work fine with MiXCR 3.0. The files should be placed in the same folder from which you run `mixcr` command.
> 
> Command in the last message is wrong, here is the correct one:
> 
> ```
> mixcr align -s hs -p rna-seq \
>  -OvParameters.geneFeatureToAlign=VRegionwithP \
>  -OvParameters.parameters.floatingLeftBound=false \
>  -OvParameters.parameters.floatingRightBound=false \
>  -OvParameters.parameters.floatingRightBound=false \
> HD265TNKG2Csp_R1.fastq HD265TNKG2Csp_R2.fastq my_analysis.vdjca
> ```
> 
> Please confirm that it works.

Hi Dr. Poslavsky，

I also found the same problem when using the mixcr, anyway, I use the defaul conda command line "conda install -c bioconda mixcr" to install, so the mixcr version is v2.1.11 not the latest. 

So I uninstall mixcr and re-install mixcr by "conda install -c bioconda mixcr=3.0.11". thus the version is the latest. and the error is also cracked.  Unfortunately, the java in conda was degraded to "java-jdk                                        8.0.112-1 --> 7.0.91-1", if I was right.

the command I used previously is: very similar to  rosasott's commands(without report).
mixcr analyze amplicon --species hs \
        --starting-material rna \
        --5-end v-primers \
        --3-end j-primers \
        --adapters adapters-present \
        --receptor-type TRB \
        seq_R1.fastq seq_R2.fastq analysis
No offense, so I guess, this problom is caused by the version, not the linux version or something else.

Best,

Decen

**Comment by PoslavskySV** [comment]
He Decen!

For MiXCR 3.x  you need Java version 8 or higher, so I guess that is the problem.

Best,
Stanislav

**Comment by decenwang** [comment]
Hi Dr. Stanislav,

Thanks for reply. the jave on my linux is JDK 1.8. I think it is ok for mixcr. Anyway, now it can run. I still have another question. I found, for some sequence, the rearrangement outcome refers to two V genes (TRBV12-3*00(906),TRBV12-4*00(906)), I know it is normal, but how could I choose one of them to do the statistics, because I have to arbitrarily choose one rearrangement. In another software IGor, it allows to set up the parameter to generate only one rearrangement with the biggest likelihood. Thanks a million!

Best,

Decen

**Comment by PoslavskySV** [comment]
The thing is that if two alignments - with TRBV12-300 and with TRBV12-400 in your case - have the similar score (**906** in your case), that most probably means that these two genes are _identical_ in the alignment region. So you have no any reason to chose one over another at the `align` step.

**Comment by Emparus** [comment]
Installed mixcr with 'brew install mixcr' on ubuntu but getting command 'mixcr' not found? 
Installing mixcr from milaboratory/all
==> Downloading https://github.com/milaboratory/mixcr/releases/download/v3.0.12/
Already downloaded: /home/hc/.cache/Homebrew/downloads/510008a2b6d5f2295c62201c19916d297e61deff4d75d419e21e42c860d328ea--mixcr-3.0.12.zip
==> Caveats
License notice:

  MiXCR is free for academic and non-commercial use.
  See: https://github.com/milaboratory/mixcr/blob/develop/LICENSE

  For commertial use please contact licensing@milaboratory.com

==> Summary
🍺  /home/linuxbrew/.linuxbrew/Cellar/mixcr/3.0.12-1: 7 files, 8.8MB, built in 2 seconds

**Comment by dbolotin** [comment]
Please check that you have brew's bin folder in your PATH variable?

**Comment by Emparus** [comment]
Indeed that was the problem . Thanks a lot
Cheers Christian
