### ISSUE TITLE
Exporting files from MIXCR

### ISSUE THREAD

**Issue by tiagobrc** [milaboratory/mixcr#495]
## Checklist before submitting the issue:

 - [Kind of] The issue is strongly related to the MiXCR software
 - [X] The issue can be reproduced with [the most recent version](https://github.com/milaboratory/mixcr/releases) of MiXCR
 - [X] There is no answer to the question in the [official documentation](http://mixcr.readthedocs.io/) and there is no duplicate issue in the [bug tracker](https://github.com/milaboratory/mixcr/issues?utf8=✓&q=)  
 - [ ] Inspection of raw alignments with [exportAlignmentsPretty](http://mixcr.readthedocs.io/en/master/export.html#exporting-well-formatted-alignments-for-manual-inspection) shows that data has the expected architecture, and sample preparation artefacts are not the reason of the problem (if this is the matter of the issue)

## Expected Result

I would like to import the MixcR results into VDJ Tools.

## Actual Result

A parsing error breaks up the softwayre

## Exact MiXCR commands 

```
R1=($(find . -name "*_1.fastq.gz" | sort ))
R2=($(find . -name "*_2.fastq.gz" | sort ))

parallel --max-procs 1 --xapply mixcr -Xmx256g analyze amplicon \
-s mmu \
--starting-material rna \
--5-end v-primers  \
--3-end c-primers \
--adapters adapters-present \
--receptor-type igh \
--contig-assembly \
--report {1}.report.txt {1} {2} {1/.} ::: ${R1[@]} ::: ${R2[@]}
```

## MiXCR report files 

*Paste here content of the report files produced by MiXCR (enclose it with triple ```` ``` ````  for better formatting)*

I have been trying to export from MIXCR to vdjtools, the issue [here](https://github.com/mikessh/vdjtools/issues/117). But I did not get any help from their side. It looks like, there are some new characteristics in the new MixCR that are not compatible with vdjtools. I notice that one problem seems to be related to the commas separating different anchor points. After removing all commas, the issue gets solved (in part) but I am afraid that vdjtools is getting the wrong anchor points. 

I looked into the documentation and did not find it clear what exactly the commas are separating. If there is only 1 contig. Why sometimes I get two/three sets of anchor points and sometimes I get only one? Thanks for your attention.

Tiago

**Comment by PoslavskySV** [comment]
@mikessh can you look please?

**Comment by dbolotin** [comment]
The problem might be with `--contig-assembly`, which can assemble disjoint sequences covering only some parts of the receptor sequence. VDJTools in turn don't support such an exotic output. I suggest you try output of MiXCR executed without `--contig-assembly`.

**Comment by tiagobrc** [comment]
Indeed. Without `--contig-assembly` it works normally. Thanks for the help.

**Comment by Tim0thy1** [comment]
@dbolotin @tiagobrc @PoslavskySV 
Hi,all . I used mixCR  extract TCR from RNAseq data, And I met same tissue as  \@tiagobrc. 
**Command show following:**
`$mixCR_tools align -s hsa  -f -p rna-seq -OallowPartialAlignments=true $fq1 $fq2  alignments.vdjca
$mixCR_tools  assemblePartial  alignments.vdjca alignments_rescued_1.vdjca --report assemblePartialReport1
$mixCR_tools  assemblePartial  alignments_rescued_1.vdjca alignments_rescued_2.vdjca --report assemblePartialReport2
$mixCR_tools  extend alignments_rescued_2.vdjca alignments_rescued_2_extended.vdjca --report extendReport
$mixCR_tools assemble -ObadQualityThreshold=0 alignments_rescued_2_extended.vdjca clones.clns --report assembleReport
$mixCR_tools  exportClones clones.clns clones.txt 

$vdjtools Convert -S mixcr  clones.txt  output
`
**Error log:**
[Thu Jul 18 09:30:31 CST 2019 BEGIN]
[Script]
Convert
[CommandLine]
executing vdjtools-1.1.10.jar Convert -S mixcr  clones.txt  output
[Message]
java.lang.RuntimeException: Unable to parse clonotype string 456        6       0.13043478260869565     TGTGCCAGCACCCCCGCCCCCTATGGCTACACCTTC    JJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJ    TRBV7-9*00(310) TRBD1*00(30)    TRBJ1-2*00(220) TRBC1*00(888)   430|440|467|0|10||50.0  23|29|36|14|20||30.0    24|40|68|20|36||80.0    TGTGCCAGCACCCCCGCCCCCTATGGCTACACCTTC    41      CASTPAPYGYTF    :::::::::0:-7:10:14:-11:5:20:20:-4:36::: for MiXcr input type: 23
[StackTrace-Short]
com.antigenomics.vdjtools.io.parser.ClonotypeStreamParser.parse(ClonotypeStreamParser.groovy:189)
com.antigenomics.vdjtools.io.parser.ClonotypeStreamParser$_iterator_closure8.doCall(ClonotypeStreamParser.groovy:249)
com.antigenomics.vdjtools.io.parser.ClonotypeStreamParser$_iterator_closure8.doCall(ClonotypeStreamParser.groovy)
com.antigenomics.vdjtools.sample.Sample.fromInputStream(Sample.java:174)
com.antigenomics.vdjtools.sample.Sample$fromInputStream.call(Unknown Source)
com.antigenomics.vdjtools.io.SampleStreamConnection._load(SampleStreamConnection.groovy:128)
com.antigenomics.vdjtools.io.SampleStreamConnection.getSample(SampleStreamConnection.groovy:139)
com.antigenomics.vdjtools.sample.SampleCollection$_iterator_closure6.doCall(SampleCollection.groovy:320)
com.antigenomics.vdjtools.sample.SampleCollection$_iterator_closure6.doCall(SampleCollection.groovy)
com.antigenomics.vdjtools.misc.Convert.run(Convert.groovy:94)
com.antigenomics.vdjtools.misc.Convert$run.call(Unknown Source)
com.antigenomics.vdjtools.misc.ExecUtil.run(ExecUtil.groovy:94)
com.antigenomics.vdjtools.misc.ExecUtil$run.call(Unknown Source)
com.antigenomics.vdjtools.VdjTools.run(VdjTools.groovy:226)
com.antigenomics.vdjtools.VdjTools.main(VdjTools.groovy)

How can I fix it?

**Comment by ShwetaCh** [comment]
Hello @mikessh, 

Thanks for this tool, it has been working great for me in the past however after recent updates to Mixcr 3.0.3 i.e. Exporting from MiXCR v3.0.3 also produces same error while using Convert routine. This is without using `--contig-assembly` option. Could you please help resolve this error?

Best,
Shweta

I used below options for mixcr:

```
  mixcr analyze amplicon \
     --verbose \
     --species hsa \
     --starting-material dna \
     --5-end v-primers --3-end j-primers \
     --adapters adapters-present \
     --report analysis_${SAMPLE} \
     --receptor-type trb \
     --region-of-interest CDR3 \
     --only-productive \
     ${FASTQ1} ${FASTQ2} ../outputs/${SAMPLE}/${SAMPLE}analysis 
```

Error log:
```
vdjtools Convert -S mixcr /home/schavan/projects/bulk_tcr_seq/inputs/DSCO28-MTC-1analysis.clonotypes.TRB.txt vdjformat
Executing com.antigenomics.vdjtools.misc.Convert -S mixcr /home/schavan/projects/bulk_tcr_seq/inputs/DSCO28-MTC-1analysis.clonotypes.TRB.txt vdjformat
[Mon Sep 06 04:38:10 UTC 2021 Convert] Reading sample(s)
[Mon Sep 06 04:38:10 UTC 2021 Convert] 1 sample(s) loaded
[Mon Sep 06 04:38:10 UTC 2021 SampleStreamConnection] Loading sample DSCO28-MTC-1analysis.clonotypes.TRB
[ERROR] java.lang.RuntimeException: Unable to parse clonotype string 0	1140755.0	0.5021585127985481	TGTGCCATCAGTAGAGAGGAGCCTAATTCACCCCTCCACTTT	FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF	TRBV10-3*00(191)		TRBJ1-6*00(145.7)	TRBC1*00(0),TRBC2*00(0)	533|545|570|0|12||60.0		26|45|73|23|42||95.0	;			TGTGCCATCAGTAGAGAGGAGCCTAATTCACCCCTCCACTTT	37								CAISREEPNSPLHF		:::::::::0:-5:12:::::23:-6:42::: for MiXcr input type: For input string: "1140755.0", see _vdjtools_error.log for details
```

**Comment by mikessh** [comment]
You can convert the count column of mixcr output to integer ```1140755.0 -> 1140755``` and all should work

**Comment by ShwetaCh** [comment]
Thanks @mikessh it works with this fix.
By any chance, is this something that might be taken care of in the new version of VDJtools (or mixcr such that it does not output the said column as float)?
