### ISSUE TITLE
Add export column: identity of the V/D/J/C genes

### ISSUE THREAD

**Issue by dbolotin** [milaboratory/mixcr#50]
Calculate percent of aligned letters and output it in the export tab-delimited files.

**Comment by LeilyR** [comment]
Hi, 

running the mixcr analyze on exome mode. Where do I find the V gene identity? From this issue, it seems as it exists in some of the output files. right?
Thanks!

**Comment by mizraelson** [comment]
Hi, you can add the following column to the export tsv file:
`--append-export-clones-field -vIdentityPercents`
