### ISSUE TITLE
Result interpretation

### ISSUE THREAD

**Issue by audyavar** [milaboratory/mixcr#506]
Hello - 

I am applying MixCR to RNAseq data from solid tumor samples using the code as described in the readthedocs document. I am new to the TCR sequence terminologies, and not very clear on the description of the individual columns. I can't find much of description of what each column means in the output file. Is there any link that you can point me to? 

# step 1 - Align sequencing reads against reference V, D, J and C genes.
./mixcr align -f --verbose -p rna-seq -s hs -OallowPartialAlignments=true -t 32 tumor_rna_reads1-trimmed.fq.gz tumor_rna_reads2-trimmed.fq.gz alignments.vdjca 
# Perform two rounds of contig assembly (please see here for available parameters).
./mixcr assemblePartial alignments.vdjca alignments_rescued_1.vdjca
./mixcr assemblePartial alignments_rescued_1.vdjca alignments_rescued_2.vdjca
#(optional) Perform extension of incomplete TCR CDR3s with uniquely determined V and J genes using germline sequences. As described in the last paragraph of introduction
./mixcr extend alignments_rescued_2_extended.vdjca
#Assemble (see here for details) clonotypes
./mixcr assemble alignments_rescued_2_extended.vdjca clones.clns
#Export all clonotypes:
./mixcr exportClones clones.clns clones.txt
#or clonotypes for a specific immunological chain:
./mixcr exportClones -c TRB /mnt/arcus-data/clones.clns /mnt/arcus-data/clones.TRB.txt
./mixcr exportClones -c TRA /mnt/arcus-data/clones.clns /mnt/arcus-data/clones.TRA.txt
./mixcr exportClones -c IGH /mnt/arcus-data/clones.clns /mnt/arcus-data/clones.IGH.txt

**Comment by dbolotin** [comment]
Please see some description here:
https://mixcr.readthedocs.io/en/master/export.html#available-fields

**Comment by pbpayal** [comment]
Hello,

I am trying to interpret the results of the RNA seq pipeline. I have been through the link mentioned above to explain the results. But I am still having problems. It will be really helpful if you can update your documentation with more information explicitly providing examples of the exact column names after the clones are exported to the result files.

Eg: 
AllDalignments column gives metric but how to decipher what this means?
9\|15\|36\|11\|17\|\|30.0;13\|19\|48\|11\|17\|\|30.0

cloneFraction - What does this mean actually? 
minQualCDR3 - what does this mean?
aaSeqCDR3 - what does this mean?

Thanks,
Payal



--
