### ISSUE TITLE
override "aligner parameters" error?

### ISSUE THREAD

**Issue by decenwang** [milaboratory/mixcr#508]
Hi @dbolotin,

when I tried to follow your tutorials to change the default parameters, mixcr did not work. for examples. you mentioned, `mixcr align -OvParameters.geneFeatureToAlign=VTranscript input_file1 [input_file2] output_file.vdjca`, so the default of "vParameters.geneFeatureToAlign" will be changed. but if I wanna override the J genes, I use `mixcr align -OjParameters.geneFeatureToAlign=JTranscript input_file1 [input_file2] output_file.vdjca`, the mixcr struck. it shows "Unknown feature: JTranscript ". Anyway, I think if the V gene can be overridden like above, I can do make the same command to J gene. If not like this, what should I do? Actually, I wanna block the alignning to C region, there is no use doing this for me. If I block it, I suppose it may save time. command as below:
 `mixcr align \
-f \
--report report \
--species hsa \
 -OsaveOriginalReads=true \
 -OjParameters.geneFeatureToAlign=JTranscript \
tcrb.fq tcrb.vdjca`

Thanks a lot！

**Comment by dbolotin** [comment]
Hi,

The error here is totally legit. There is no such feature as `JTranscript`. Please see [this section of the docs](https://mixcr.readthedocs.io/en/master/geneFeatures.html#germline-features) for the details about gene features.

To turn off C alignments please use the following syntax:
```
mixcr -OcParameters=null ...
```
Let me know if it doesn't work.

Best,
Dmitry
