### ISSUE TITLE
there are so many reads failed map because of absence of J hits

### ISSUE THREAD

**Issue by Lemon128** [milaboratory/mixcr#513]
## Checklist before submitting the issue:

 - [ ] The issue is strongly related to the MiXCR software
 - [x] The issue can be reproduced with [the most recent version](https://github.com/milaboratory/mixcr/releases) of MiXCR
 - [ ] There is no answer to the question in the [official documentation](http://mixcr.readthedocs.io/) and there is no duplicate issue in the [bug tracker](https://github.com/milaboratory/mixcr/issues?utf8=✓&q=)  
 - [ ] Inspection of raw alignments with [exportAlignmentsPretty](http://mixcr.readthedocs.io/en/master/export.html#exporting-well-formatted-alignments-for-manual-inspection) shows that data has the expected architecture, and sample preparation artefacts are not the reason of the problem (if this is the matter of the issue)

## Expected Result

*A description of what you wanted to happen*

## Actual Result

*A description of what actually happened*

## Exact MiXCR commands 

*Paste here __exact__ MiXCR commands you used (enclose it with single `` ` ``  for better formatting)*

## MiXCR report files 

*Paste here content of the report files produced by MiXCR (enclose it with triple ```` ``` ````  for better formatting)*

**Comment by Lemon128** [comment]
Dear Sir or Madam,
Recently I used mixcr to analysis TCR NGS sequencing data. when I made alignment step, I found that most of my data alignment failed because of absence of J hits.  
Also I have seen this issue [https://github.com/milaboratory/mixcr/issues/379]  but it also cannot solve my problem.
My first align command is: java  -jar mixcr.jar align --species hs --report report -p rna-seq -OvParameters.geneFeatureToAlign=VGeneWithP -OvParameters.parameters.floatingLeftBound=true -OjParameters.parameters.floatingRightBound=true-OcParameters.parameters.floatingRightBound=false  input.fastq output.vdjca 
My first report is :
Total sequencing reads: 38709835
Successfully aligned reads: 11675178 (30.16%)
Alignment failed, no hits (not TCR/IG?): 6474435 (16.73%)
Alignment failed because of absence of J hits: 20402230 (52.71%)
Alignment failed because of low total score: 157992 (0.41%)

Then I change the parameter, the second align command is: java  -jar mixcr.jar align --species hs --report report -p rna-seq -OvParameters.geneFeatureToAlign=VGeneWithP -OvParameters.parameters.floatingLeftBound=true -OjParameters.parameters.floatingRightBound=flase -OcParameters.parameters.floatingRightBound=false -OallowPartialAlignments=true input.fastq output.vdjca
The second report is 
Total sequencing reads: 38709835
Successfully aligned reads: 1878739 (4.85%)
Alignment failed, no hits (not TCR/IG?): 1020341 (2.64%)
Alignment failed because of absence of CDR3 parts: 10467587 (27.04%)
Alignment failed because of low total score: 25343168 (65.47%)

**I'm confused that how can I improve the mapping rate. what kind of parameter should I change to improve this?**

And I'm confused why there are so many reads alignment failed because of absence of J hits at the first alignment. and the second time there are so many reads failed because of low total score. Is there something wrong with the parameters I set?
Looking forward to your response.

**Comment by mingbao96** [comment]
Hi, 
Why was the issue closed, had the problem been solved?  I also meet it now.
I have searched online and found that the author emailed a user saying that one of the reads from two-paired sequencing must hit both the V and J genes.
Is there any parameter to change it?
Looking forward to any reply.

Best wish

**Comment by mizraelson** [comment]
Hi. The issue was closed by the user. Can you describe the protocol and share the command you are using?

**Comment by mingbao96** [comment]
Hi, thanks to your reply.

I tried to use MIXCR to analyze the IGH mutated.
Data is from Illumina two-paired sequencing with 300 cycles, I think the read starting from 5' should cover the V gene and part of the J gene.

The command I used and its result:
`
mixcr analyze generic-amplicon -f --rigid-left-alignment-boundary --rigid-right-alignment-boundary C --rna --species hs  R1.fastq.gz R2.fastq.gz 
`
<img width="862" alt="image" src="https://github.com/milaboratory/mixcr/assets/35926661/a10e3b06-6555-48d8-aaea-d01fd1122c14">

Then I tried the `--keep-non-CDR3-alignments` parameter, the result changed :
<img width="847" alt="image" src="https://github.com/milaboratory/mixcr/assets/35926661/63d191fa-0cf3-4fc4-a9af-4a0017b78c3d">

But in assemble, I found that there are too many reads dropped:
 `Reads dropped due to the lack of a clone sequence, percent of total: 578087 (85.36%)`

I'm not sure what can I do next step, should I change the parameter `--assemble-contigs-by` ? 

Actually, I think the length of pairing reads does cover the whole IGH, so I'm really confused.

**Comment by Lemon128** [comment]
Hi, 
&nbsp;&nbsp;&nbsp; you can merge R1.fq and R2.fq to SE.fq first, then use SE.fq as input to anlysis mixcr.

**Comment by mizraelson** [comment]
Is it a multiplex or a 5'Race based protocol? Would it be possible to share a couple of reads from R1 and R2?

**Comment by mingbao96** [comment]
Thanks for your timely reply @Lemon128 @mizraelson 

> Is it a multiplex or a 5'Race based protocol? Would it be possible to share a couple of reads from R1 and R2?

The data is from NCBI PRJNA850089

R1: 
@SRR19720449.1 1 length=301
TCCCAAGTTCAACTTGTTCAATCTGGTGCTGAAGTTAAGAAACCAGGTGCTTCTGTTAAAGTTTCTTGTAAAGCTTCTGGTTATACTTTTACTGATTACGTTATGCATTGGGTTAGACAAGCTCCAGGTCAGGGTTTGGAATGGATGGGTAGAGTTAATCCAAATGCAGGGGGCACTACTTATAATCAAAAGTTTGAAGGTCGTGTAACTATGACTACTGATACTTCTACGTCTACTGCTTATATGGTATTGCGTTCTCTTATATCTGATTATACTTCTGTATATTACTTTGCTAGATCTT
+SRR19720449.1 1 length=301
-AAC<9<EFF<<FGGCGGGCCFGGDCFCFGF<9AFG9-CAA<FFDECFGGGGGGGGGGGGGGGGGGGGGGGGGFGGGGGGGGCFDFGGGGAFFGFGGGGGFGCF<E9FFC8AFEE8@E9,CAEEF<<,EFFCCFFGGCCCAFFDFGECGFDB,?FE<,EFG@8<F<B<<A7+7++8@8BFGEE9,>D9,,?,CFF=,,C8F=+F=@8,@D,F+,9=,@@+2E9=FFFE7D:@A@@BC<?EGAG@FGC,5@D+=1CFAFFGF=+*B9C*8B*8?+8=+9C*B,11@E/5B*=.8>))775A+

@SRR19720449.2 2 length=301
TCCCAAGTTCAACTTGTTCAATCTGGTGCTGAAGTTAAGAAACCAGGTGCTTCTGTTAAAGTTTCTTGTAAAGCTTCTGGTTATACTTTTACTGATTACGCTATTCATTGGGTTAGACAAGCTCCAGGTCAGGGTTTGGAATGGATGGGTAAGGTTAATCCAAATGCAAAATATACTACTTATAATCAAAAGTTTGAAGGTCGTGTAACTATGACTACTGATACTTCTACGTCTACTGCTTATATGGAATTGCTTTCTCTTTGATCTGATGATACTTCTGTTTATTACTTTGCTATAGATT
+SRR19720449.2 2 length=301
-A@C99-CFFAAFGGEGGG9<CFF@<F<EF<<9CEF,-6,,,CE,C7FFGGGGGGGGGGGGGGGGGGGGGGGFFGGGGGAFG9F9CFFGG9EFEFGGGG,,,,8,C<FF,<,BE7,,C,,6:AFC,,,CE,,,6CFF,,,,CB,?F<@FF9,,5CF<AFAE9,,C,AB9?,:,@,5@,CFFEG9,DE,,,,4CEF;,,,,A=+@+@,,:=,A+,A=,8B+@C,9CE9;+,+@6=+=@4<DE7D=CA,,+8@*+,@FADAFF+5*D0?**7**2+*6+*5*=,1*@E6*?*>*96**9**=+

@SRR19720449.3 3 length=301
GCCCAAGTTCAACTTGTTCAATCTGGTGCTGAAGTTAAGAAACCAGGTGCTTCTGTTAAAGTTTCTTGTAAAGCTTCTGGTTATACTTTTACTGATTACGTCATGCATTGGGTTAGACAAGCTCCAGGTCAGGGTTTGGAATGGATGGGTGCGGTTAATCCAAATGGGAGAGCCACTACTTATAATCAAAAGTTTGAAGGTCGTGTAACTATGACTACTGATACTTCTACGTCTACTGCTTATATGGAATTGCTTTCTCTTAGATCTGATGATACTTCTGTTTATTACTGTTCTATAGCCA
+SRR19720449.3 3 length=301
-ABC<99EFGCDFGGAFGG9<EFGCEFFFGF9@CFG9<<9<8EE8ECFFGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGDG9FFGGGCFGFGGGGGGE,,E,C9EF<8CFGF@C<<8EAEEF8<,EF@<@FGGGE>8EEAAEGFEFFCF>CFG79EEE<89F<,?8++:<E8BEAFFFBFDFFF99,,DFFGF9?>8FA7F6D8,C@;F9,>D9DD2;@;AFGCE7;4DACCCFECGG6F5E:E7*@F7@,@FBF9FG62*=6C46B**;16?+9B*=,1*@C*>E5E*9??40/5)*

R2:
@SRR19720449.1 1 length=301
TTTAGTAGAAGCAGAAGAAACAGTAACGGTAGTGCCTTGACCCCAAAAGTCCAACGCATTAGATCTAGCACAGTAATATACAGCAGTATCATCAGATCTAAGAGAACGCAATTCCATATAAGCAGTAGACGTAGAAGTATCAGTAGTCATAGTTACACGACCTTCAAACTTTTGATTATAAGTAGTGCCCCCTGCATTTGGATTAACTCTACCCATCCATTCCAAACCCTTACCTGTTTCTTGTCTAACCCAATGCATAACGTTATCCGTATTATTATACCCAGAAGCTTTACACTAAACT
+SRR19720449.1 1 length=301
ACC9<F<<,CAE8<9-<-<9C,EFCDFF7B8,C,CFFG8CFFFF77,,<EEF99E@:7CF96,CEFCFG9FGGGGGGFFCFCAEGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGFGGGGGGGGGGGGGGGGGGGGGGGGGGGGGF;FFCF9?=+>FGGFF9<FGGGGGEEGCF<DFF,3E;,60616+=,CDD,,36>,,52:;=@,@*8@:*CCAC,,,+@B9)5;AE,,+*33>1E8;+*3@>*-::16>6**--**0/*(:)))+*1/8*+10*((/(44:7).)))(/4.)

@SRR19720449.2 2 length=301
TTTAGTAGAAGCAGAAGAAACAGTAACGGTAGTGCCTTGACCCCAATCGTCCAACGCATTATCTCTAGCACAGTAATATACAGCAGTATCATCAGATCTAAGAGAACGCAATTCCATATAAGCAGTAGACGTAGAAGTATCAGTAGTCATAGTTACACGACCTTCAAACTTTTGATTATAAGTAGTATTTTTTTCATTTTTATTAACCTTACCCATCCATTCCTCACCCTGACCTTTATCTTGTCTAACCCAATGCATTTCTTTATTCGTATCTTTATATCCCTCAGCTTTACATGTAACT
+SRR19720449.2 2 length=301
ACC9,E9@,,<C@9------;66C,@FE7C8,C,CCFGGAFDEF7,,6,CEC7<E,++BC,ECFEFCACAFGFGGGF9F<E99CFFGGGGGGGGGGGGGGGGGGGGGGGGGGFGGFFGGGFGGGGGGGGGDFG?FGGGGGGGGGGGGGFGGFGGC9,B=+4@FGGC,,EFGGGFGGGGF@,?E,3C;F83?FD+,,CEE,,,7@,,+259+:,3*:76*CE:C,,,413<)0;0=,,+*30@*79:+*,42*/<)4*822+*0++1**-2)))+*1*1*++*0),/().::)..)1)//1)

@SRR19720449.3 3 length=301
TTTAGTAGAAGCAGAAGAAACAGTAACGGTAGTGCCTTGACCCCAATCGTCCAACAAATTGTCTCTAGCACAGTAATATACAGCAGTATCATCAGATCTAAGAGAACGCAATTCCATATAAGCAGTAGACGTAGAAGTATCAGTAGTCATAGTTACACGACCTTCAAACTTTTGATTATAAGTAGTGTCTCTCCCATTTTGATTATCCTCACCCATCCATTCCCAACCCTTACCTTTAGCTTTTCTATCCCCATGCCTTTCTTTTTCCTTTTACTTTTATCCTTAAGCTTTCCCCTTAACT
+SRR19720449.3 3 length=301
8AC-,CD<9,9C,-----6-;,CF,CFF+B,,C,CEFFE9EFAB,,;6,CFE@EE:,,;E<,<FFG9<@<FGGGFGGDFDE9,EFGGFGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGCFFEGF99,E++>FEGGF,BFGFFGGGGGAE<D+@,6C?,@C8=2+,1CDD,7+7A,,+,*5+6>=)3,3*5C=2,,,313:)309A,,+**3@*<AE+*33,*):5,)1**4*1++1)**=+*+**1*0*+4/*/***8888***(((/74)



> Hi, &nbsp;&nbsp;&nbsp; you can merge R1.fq and R2.fq to SE.fq first, then use SE.fq as input to anlysis mixcr.

I tried  `mixcr analyze generic-amplicon -f --rigid-left-alignment-boundary --rigid-right-alignment-boundary C --rna --species hs --keep-non-CDR3-alignments SRR19720449.fastq SRR19720449`

But according to 'assemble.report', there still are too many reads dropped : 
```
Final clonotype count: 53
Reads used in clonotypes, percent of total: 661 (0.15%)  
Average number of reads per clonotype: 12.47  
Reads dropped due to the lack of a clone sequence, percent of total: 416444 (93.72%)
```
The number of dropped reads is equal to the 'Alignments that do not cover CDR3'

**Comment by mizraelson** [comment]
So, bellow is an alignment for one of the read pairs from the dataset:

```
>>> Read ids: 122


              L2><FR1                                                                   FR1><C
               A  Q  V  Q  L  V  Q  S  G  A  E  V  K  K  P  G  A  S  V  K  V  S  C  K  A  S  G
   Quality    66666777777777777777777777777777777777777777777777777777777777777777777777776777
   Target0  0 GCCCAAGTTCAACTTGTTCAATCTGGTGCTGAAGTTAAGAAACCAGGTGCTTCTGTTAAAGTTTCTTGTAAAGCTTCTGG 79   Score
IGHV1-3*00 74 TcccaGgtCcaGcttgtGcaGtctggGgctgaGgtGaagaaGccTggGgcCtcAgtGaaGgtttcCtgCaaGgcttctgg 153  318

                                CDR1><FR2
                 Y  T  F  T  D  Y  D  M  H  W  V  R  Q  A  P  G  Q  G  L  E  W  M  G  R  V  N
   Quality     77777777777577777777777777777777777777777777777777777777777777777777777777777777
   Target0  80 TTATACTTTTACTGATTACGATATGCATTGGGTTAGACAAGCTCCAGGTCAGGGTTTGGAATGGATGGGTAGGGTTAATC 159  Score
IGHV1-3*00 154 AtaCacCttCactAGCtaTgCtatgcattgggt                                                186  318


            P  N  E  E  G  T  T  Y  N  Q  K  F  E  G  R  V  T  M  T  T  D  T  S  T  S  T  A
Quality     77777777777777777777777777777777777777777777777777777777777777777777777777777777
Target0 160 CAAATGAAGAGGGCACTACTTATAATCAAAAGTTTGAAGGTCGTGTAACTATGACTACTGATACTTCTACGTCTACTGCT 239  Score


             Y  M  E  L  R  S  L  R  S  D  D  T  A  V  Y  Y  C  A  R  A  N  G  L  D  A  W  G
Quality     77777777777777777777777777777777777777777777777777777777777777777777777777777777
Target0 240 TATATGGAATTGCGTTCTCTTAGATCTGATGATACTGCTGTATATTACTGTGCTAGAGCTAATGGGTTGGACGCCTGGGG 319  Score


              Q  G  T  T  V  T  V  S  S  A  S  T  K
Quality     7777777777777777777777777777777777766666
Target0 320 TCAAGGCACTACCGTTACTGTTTCTTCTGCTTCTACTAAA 359  Score
```

As you can see it only partially aligns to  the V gene (with lots of mismatches) and lacks the alignment for D and J genes.  When `--keep-non-CDR3-alignments` is used you preserve these alignments but they are being dropped during the assemble due to the lack of clonal sequence (`CDR3` by default). I have briefly reviewed the publication and it seems they deal with highly mutated artificial sequences. Thus by default MiXCR discard such alignments as they don't usually exist in biological systems.

However, if you want to force the alignment it is possible to do by lowering the scores, e.g.:

```
mixcr analyze generic-amplicon \
--floating-left-alignment-boundary \
--floating-right-alignment-boundary C \
--rna \
--species hs \
-Malign.parameters.vParameters.parameters.scoring.subsMatrix='simple(match=10,mismatch=-7)' \
-Malign.parameters.vParameters.parameters.mapperNValue=7 \
-Malign.parameters.jParameters.parameters.scoring.subsMatrix='simple(match=10,mismatch=-7)' \
-Malign.parameters.jParameters.parameters.mapperNValue=5 \
SRR19720449_R1.fastq.gz \
SRR19720449_R2.fastq.gz \
SRR19720449
```
This will align and use the majority of the reads. 

Let me know if it helps.

Sincerely,
Mark

**Comment by mingbao96** [comment]
Thanks for your patience, it does help!

The assemble report is as below:
```
Final clonotype count: 1353
Reads used in clonotypes, percent of total: 534067 (78.86%)
Average number of reads per clonotype: 394.73
Reads dropped due to the lack of a clone sequence, percent of total: 932 (0.14%)
```

So I wanna know the meaning of `simple(match=10,mismatch=-7)` , does that mean scores? 
If matches it gets 10, if not it minus 7 ?

Another question is that if I'm not sure of the primers used in sequencing when using the public data how can I set the parameters about `alignment-boundary` ?

Best wishes

**Comment by mizraelson** [comment]
Yes, you are correct about the scoring. 
I have set both boundaries to `floating` because we don't trim the primers. This directs MiXCR to use semi-local alignment on the edges.
