### ISSUE TITLE
recommended approach for single-cell RNA

### ISSUE THREAD

**Issue by RichardCorbett** [milaboratory/mixcr#514]
Hi folks,

We are working on developing a single-cell protocol targetting full length RNA coverage for each cell.     The libraries are sequenced using paried-end 125bp reads, but the insert sizes in the current iteration frequently are smaller than the read length resulting in adapter at the ends of the reads.

We are hoping to demonstrate that our protocol allows us to identify meaningful results through analysis tools like mixcr.

Given that are data are dependably single cell (ie. there are no multiplets) would you still recommend using " mixcr analyze shotgun", or would another approach be more appropriate?

thanks
Richard

**Comment by dbolotin** [comment]
Hi Richard,

Default `mixcr analyze shotgun ...` pipeline should perfectly solve the problem.

Still, you are right that for now MiXCR behaves too safe for such data. It assembles only sequences that at least partially cover CDR3 by one of its' paired-end mates. However, knowing that all the sequences came from the same cell (ignoring the fact that there are two chromosomes), one can use all the sequences mapped onto corresponding V / J / C gene and including those not touching CDR3.

We are actively working on such functionality, so MiXCR 3.1 will assemble the output sequence from all available sequences in case of single-cell data. I can't give you exact time estimates, but it is our top priority for 3.1.

If your protocol is based on UMIs, cell barcodes, etc.,  you may also be interested in our new software called [MiNNN](https://github.com/milaboratory/minnn) for barcoded data processing. It solves all common tasks for such data, uses advanced algorithms for barcode error correction, consensus assembly and barcode parsing and plays well with MiXCR, so MiNNN's output can be directly fed to MiXCR and MiXCR will process the data without the need to split it to separate cell-specific files.

Best,
Richard.

**Comment by alexpan82** [comment]
Hello,

Like Richard, we would like to eventually use mixcr 3.1 to analyze our single-cell data. Do you have any updates regarding the approximate release of this functionality? We are happy and anxious to test a beta of the new version anytime.

Thank you,
Alex

**Comment by diazdc** [comment]
Hello, I'm checking in to see if there are any updates or best practices for handling UMI/barcoded scRNA-seq data . I couldn't find anything in the documentation.  Right now I'm trying to analyze a 10X targeted data set in preparation for a custom scRNA-seq protocol and `mixcr analyze shotgun` hasn't identified known clonotypes. I appreciate any help I can get. Cheers.

For reference I'm running MiXCR version 3.0.13.
