### ISSUE TITLE
java.lang.OutOfMemoryError: GC overhead limit exceeded

### ISSUE THREAD

**Issue by mvanmoerbeke** [milaboratory/mixcr#515]
## Checklist before submitting the issue:

 - [X] The issue is strongly related to the MiXCR software
 - [X] The issue can be reproduced with [the most recent version](https://github.com/milaboratory/mixcr/releases) of MiXCR
 - [X] There is no answer to the question in the [official documentation](http://mixcr.readthedocs.io/) and there is no duplicate issue in the [bug tracker](https://github.com/milaboratory/mixcr/issues?utf8=✓&q=)  
 - [X] Inspection of raw alignments with [exportAlignmentsPretty](http://mixcr.readthedocs.io/en/master/export.html#exporting-well-formatted-alignments-for-manual-inspection) shows that data has the expected architecture, and sample preparation artefacts are not the reason of the problem (if this is the matter of the issue)

## Expected Result

The error appeared in the assemble command applied to a large sample. It was expected that the assemble step would run normally.

## Actual Result

The assemble step resulted in the return of an error message showing an out of memory. However, the machine indicated that only 6% of memory was actually used. Could there be a memory leak in the code?

```
Initialization: progress unknown
Assembling initial clonotypes: 0.6%
Assembling initial clonotypes: 11%  ETA: 00:02:42
Assembling initial clonotypes: 21.5%  ETA: 00:02:16
Assembling initial clonotypes: 31.5%  ETA: 00:01:56
Assembling initial clonotypes: 41.5%  ETA: 00:01:41
Assembling initial clonotypes: 51.8%  ETA: 00:01:19
Assembling initial clonotypes: 61.9%  ETA: 00:01:03
Assembling initial clonotypes: 72.1%  ETA: 00:00:46
Assembling initial clonotypes: 82.6%  ETA: 00:00:29
Assembling initial clonotypes: 93%  ETA: 00:00:14
Assembling initial clonotypes: 100%  ETA: 00:00:00

Exception in thread "main" java.lang.OutOfMemoryError: GC overhead limit exceeded
at com.milaboratory.core.tree.SequenceTreeMap$Node.<init>(SequenceTreeMap.java:203)
at com.milaboratory.core.tree.SequenceTreeMap$Node.getOrCreate(SequenceTreeMap.java:209)
at com.milaboratory.core.tree.SequenceTreeMap.createIfAbsent(SequenceTreeMap.java:56)
at com.milaboratory.mixcr.assembler.CloneAssembler.beginMapping(CloneAssembler.java:209)
Exception: java.lang.OutOfMemoryError thrown from the UncaughtExceptionHandler in thread "main"`

```
## Exact MiXCR commands 

```
mixcr align --species HomoSapiens -OvParameters.geneFeatureToAlign=VRegionWithP -OvParameters.parameters.relativeMinScore=0.99 -OjParameters.parameters.relativeMinScore=0.99 -OdParameters.relativeMinScore=0.99 -OcParameters.parameters.relativeMinScore=0.99 19C12.fastq 19C12.vdjca -f -r 19C12.alignReport.txt

mixcr assemble -OaddReadsCountOnClustering=true -OcloneClusteringParameters.clusteringFilter.specificMutationProbability=1E-2  --write-alignments 19C12.vdjca 19C12.clna -f -r 19C12.assembleReport.txt

mixcr assembleContigs -OalignedRegionsOnly=true -OtrimmingParameters.windowSize=1 -OtrimmingParameters.averageQualityThreshold=10 19C12.clna 19C12.clns -f -r 9C12.assembleContigsReport.txt

mixcr exportClones -s -c TRA,TRB -m 10 -q 0.05 19C12.clns 19C12.txt

```

## MiXCR report files 

The align step was run succesfully: 
```
Analysis date: Thu Apr 25 14:03:41 CEST 2019
Input file(s): 19C12.fastq
Output file(s): 19C12.vdjca
Version: 3.0.6; built=Wed Apr 10 16:54:31 CEST 2019; rev=4035a6a; lib=repseqio.v1.5
Command line arguments: align --species HomoSapiens -OvParameters.geneFeatureToAlign=VRegionWithP -OvParameters.parameters.relativeMinScore=0.99 -OjParameters.parameters.relativeMinScore=0.99 -OdParameters.relativeMinScore=0.99 -OcParameters.parameters.relativeMinScore=0.99 19C12.fastq 19C12.vdjca -f -r 19C12.report.txt
Analysis time: 47.45m
Total sequencing reads: 17790703
Successfully aligned reads: 16856651 (94.75%)
Chimeras: 1152 (0.01%)
Alignment failed, no hits (not TCR/IG?): 41552 (0.23%)
Alignment failed because of absence of J hits: 886441 (4.98%)
Alignment failed because of low total score: 6059 (0.03%)
Overlapped: 0 (0%)
Overlapped and aligned: 0 (0%)
Alignment-aided overlaps: 0 (NaN%)
Overlapped and not aligned: 0 (0%)
 chains: 22 (0%)
TRA chains: 12123321 (71.92%)
TRB chains: 4729964 (28.06%)
TRD chains: 2160 (0.01%)
IGH chains: 18 (0%)
IGK chains: 5 (0%)
IGL chains: 9 (0%)

```

**Comment by PoslavskySV** [comment]
Hi! 

Typically, if you have enough memory in the system, but still face OutOfMemory, this indicates some problem in your environment (e.g. running MiXCR in a PBS job or something). Which OS and environment do you have? 

As a solution you you can always specify the memory limit explicitly:

```
mixcr assemble -Xmx64g ...
```
where you can replace `64g` (64 Gb) with the amount of your choice. Let me know whether it helps.

**Comment by mvanmoerbeke** [comment]
Hi! 

Thank you for your reply!
Explicitly specifying the memory limit helped us proceed the analysis and the samples ran through the mixcr software without any further issues.

Thank you for the suggestion!

**Comment by dbolotin** [comment]
Great!
