### ISSUE TITLE
No jar problems

### ISSUE THREAD

**Issue by Cuppaaaa** [milaboratory/mixcr#516]
Hello
     When I want to use mixcr in my Linux system, it only return "no jar"   How can I solve this problem? 
    
![微信图片_20190429162734](https://user-images.githubusercontent.com/50099338/56884245-b9ba9a00-6a9b-11e9-94e5-f056601e4a16.png)

**Comment by dbolotin** [comment]
Please provide some additional information about the environment you are using, how MiXCR was installed, mixcr version, etc...

**Comment by Cuppaaaa** [comment]
I use mixcr-3.0.6.tar.gz , download from github.  And my Linux version : 2.6.32-504.el6.x86_64   
   Thank you!

**Comment by dbolotin** [comment]
Please use [zip with the binary](https://github.com/milaboratory/mixcr/releases/download/v3.0.6/mixcr-3.0.6.zip) instead of a source package.

**Comment by Cuppaaaa** [comment]
Emm.... Does zip files can be open in Linux ???  I thought the Linux system can only use tar.gz files to install programs....

**Comment by PoslavskySV** [comment]
Of course you can unzip files in Linux. Just use `unzip` utility.

**Comment by Cuppaaaa** [comment]
Thank you so much!!
