### ISSUE TITLE
Data preprocessing and quality trimming for RNA-Seq protocol

### ISSUE THREAD

**Issue by mxdeluca** [milaboratory/mixcr#517]
Hi,
I looked in the documentation and past issues, but could not find a definitive answer this question. Do you have any recommendation with respect to preprocessing of  PE shotgun RNASeq data in mixcr?-is trimming required?
Thank you

**Comment by dbolotin** [comment]
If the data is of high quality trimming is not required. If the data has substantial amount of low quality ends, some trimming may increase analysis yield. Unfortunately I cant suggest you the universal pipeline for the case, trimming options can only be picked experimentally.

@Alex-Davydov can you suggest what would be the best starting point?

**Comment by Alex-Davydov** [comment]
For RNA-seq we usually recommend to check the fastq data quality first with FastQC etc., and then perform adaptor and quality trimming using conventional tools (eg Trimmomatic), this can increase your yield in case of low quality or high adaptor proportions in the data.

**Comment by mxdeluca** [comment]
Thanks for the advice !
