### ISSUE TITLE
Non-overlapping reads dropped analyzing TCR RACE PCR data

### ISSUE THREAD

**Issue by TimFugmann** [milaboratory/mixcr#518]
Hi there,

I am trying to extract as complete TCR sequences as possible from TCR RACE PCR data analyzed by Mixcr. The resulting sequences are (especially for FR1) often not extracted from alignments but imputed. This even though we do paired end sequencing and the reads in FR1 are of high quality (as can also be seen from PrettyAlignment report). R1 and R2 reads often do not overlap. This should however not be a problem, as these alignments are stored in the PrettyAlignment. For ExportClones it seems these sequences are dropped. Can this be prevented?

Many thanks and best wishes,
Tim

**Comment by dbolotin** [comment]
Please provide exact commands you used for analysis. Can you please post prettyAlignments and results you get in the export? Please also post report files. Or, if you don't want to post it publically you can send it to support@milaboratory.com .

**Comment by TimFugmann** [comment]
Dear Dmitry,

Many thanks for the quick Reply. Please find attached an outline document of some of the Tests I did to extract the full sequence. Is there a link to the Mixcr Quality metric? I couldn’t find any. Some/most of the Quality scores after Mixcr look very bad. Is this true? Can this be improved?
Sorry, I had to remove CDR3 sequences due to confidentiality.

Let me know if you have suggestions or Questions.

With best wishes,
Tim

Gesendet von Mail<https://go.microsoft.com/fwlink/?LinkId=550986> für Windows 10

________________________________
Von: Dmitry Bolotin <notifications@github.com>
Gesendet: Tuesday, May 14, 2019 6:31:28 PM
An: milaboratory/mixcr
Cc: TimFugmann; Author
Betreff: Re: [milaboratory/mixcr] Non-overlapping reads dropped analyzing TCR RACE PCR data (#518)


Please provide exact commands you used for analysis. Can you please post prettyAlignments and results you get in the export? Please also post report files. Or, if you don't want to post it publically you can send it to support@milaboratory.com<mailto:support@milaboratory.com> .

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub<https://nam04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fmilaboratory%2Fmixcr%2Fissues%2F518%3Femail_source%3Dnotifications%26email_token%3DAMCJKTW5KGAG6G5GUN7NCUDPVLSOBA5CNFSM4HM3QX6KYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGODVMBMRY%23issuecomment-492312135&data=02%7C01%7C%7C0e886a55a907472f422708d6d8899de9%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C636934482899012865&sdata=b46wB0XvHJA5S71f08gDYIxvbAYAXINFFyM6fYIvyvI%3D&reserved=0>, or mute the thread<https://nam04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAMCJKTXUE2PFQURT2P7DG6LPVLSOBANCNFSM4HM3QX6A&data=02%7C01%7C%7C0e886a55a907472f422708d6d8899de9%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C636934482899022864&sdata=XOudIpufjmDaH0k9oS0zb%2BP9B4txExD6M6797%2BRdosk%3D&reserved=0>.

cloneId	cloneCount	cloneFraction	targetSequences	targetQualities	allVHitsWithScore	allDHitsWithScore	allJHitsWithScore	allCHitsWithScore	allVAlignments	allDAlignments	allJAlignments	allCAlignments	nSeqImputedFR1	minQualFR1	nSeqImputedCDR1	minQualCDR1	nSeqImputedFR2	minQualFR2	nSeqImputedCDR2	minQualCDR2	nSeqImputedFR3	minQualFR3	nSeqCDR3	minQualCDR3	nSeqImputedFR4	minQualFR4	aaSeqImputedFR1	aaSeqImputedCDR1	aaSeqImputedFR2	aaSeqImputedCDR2	aaSeqImputedFR3	aaSeqCDR3	aaSeqImputedFR4	refPoints
0	71019	0.130177048	TGTCCTCTTGATAGCCTTATATAAGGCTGGTGAATTGACCTCAAATGGAAGACTGACTGCTCAGTTTGGTATAACCAGAAAGGACAGCTTCCTGAATATCTCAGCATCCATACCTAGTGATGTAGGCATCTACTTCTGTGCTGGGCTTGATAGCAACTATCAGTTAATCTGGGGCGCTGGGACCAAGCTAATTATAAAGCCAGATATCCAGAACCCTGACCCTGCCGTGTACCAGC,ACGGGAGGAGGAAA,CCTTTGGGACAGGCAC,CAGCTAAAAGTGGAACTCAATATCCAGAACCCTGACCCTGCCGTGTACCAGCTGAGAGA	:;9::::;<=::<:889:=>:;98<=;;9??:>>9;8;=:;::;;>;>=9<:?>::???<=;;7:;;0=>:=:7><>@><<;8::89==?<;;>=<<9:A:<=>>>;?;>=<<>=?@A<<><@=8<=>0><<@>=A////////////////////////////////////=B:<?><==:=<@=:?B>>8??A>=<====;?AA??=?>@<<><;:<?>=<:<98<999;6645,&&%(%$'%%('*[%,&$''%'&$&%%'$&$$,%'$&$)&6%$&'&(&%)$''$$%&'%'5$&(%%%'((&&'0''''''0'''''''''''	TRAV35*02(1108.1),TRAV35*01(1086.1)		TRAJ33*01(274.4)		128|270|270|0|142||710.0,,,;264|274|276|136|146||50.0,,,		22|77|77|148|203||275.0,,,		ggtcaacagctgaatcagagtcctcaatctatgtttatccaggaaggagaagatgtctccatgaactgcacttcttca		agcatatttaacacc		tggctatggtacaagcaggaccctggggaaggtccTGTCCTCTTGATAGCC		TTATATAAGGCTGGTGAATTG	23	ACCTCAAATGGAAGACTGACTGCTCAGTTTGGTATAACCAGAAAGGACAGCTTCCTGAATATCTCAGCATCCATACCTAGTGATGTAGGCATCTACTTC	15		14	GGCGCTGGGACCAAGCTAATTATAAAGCCAG	23	gqqlnqspqsmfiqegedvsmnctss	sifnt	wlwykqdpgegPVLLIA	LYKAGEL	TSNGRLTAQFGITRKDSFLNISASIPSDVGIYF		GAGTKLIIKP_	:::::::16:37:136:0:142:::::148:-2:172:203::,:::::::::::::::::::::,:::::::::::::::::::::,:::::::::::::::::::::
1	51476	0.094354944	AAGCAGTGGTATCAACGCA,AAGCAGTGG,ACAAAG,TGGGTTC,GGAAC,CAGAGTACGTGATTCATGGTCTTACAAGCAATGTGAACAACAGAATGGCCTCTCTGGCAATCGCTGAAGACAGAAAGTCCAGTACCTTGATCCTGCACCGTGCTACCTTGAGAGATGCTGCTGTGTACTACTGCATCCTGAGAGACGGGGGAGCCCAGAAGCTGGTATTTGGCCAAGGAACCAGGCTGACTATCAACCCAAATATCCAGAACCCTGACCCTGCCGTGTAC,AAGAGCGTCGTGT	%%%%%$$1$$$/$$$$$/%,&$'$'&'&(,$$'$$%,%%%$$%%,&&%&%,==<>>?>:=/<=?=;>=<=><=?>>=>>5@C?<?=@@>?@=>===?=?==;><=><==A@?=>=><@<???=>?@>@><<<?<>><??><?>>>>>==<===??@@>>?>?@=@??=?>>?>=B>?A??=>.......................................>>;=<@>?>>>=>=;>B=<>>?@=;=>>;>P8887>788?7=<8878@=776=667666;,('')'+'&'%$%%	TRAV26-2*01(1114.6)		TRAJ54*01(264.5)		,,,,,130|276|276|0|146||730.0,		,,,,,27|80|80|148|201||265.0,		gatgctaagaccacacagccaaattcaatggagagtaacgaagaagagcctgttcacttgccttgtaaccactcc		acaatcagtggaactgattac		atacattggtatcgacagcttccctcccagggtcCAGAGTACGTGATTCAT		GGTCTTACAAGCAAT	20	GTGAACAACAGAATGGCCTCTCTGGCAATCGCTGAAGACAGAAAGTCCAGTACCTTGATCCTGCACCGTGCTACCTTGAGAGATGCTGCTGTGTACTAC	26		13	GGCCAAGGAACCAGGCTGACTATCAACCCAA	26	dakttqpnsmesneeepvhlpcnhs	tisgtdy	ihwyrqlpsqgPEYVIH	GLTSN	VNNRMASLAIAEDRKSSTLILHRATLRDAAVYY		GQGTRLTINP_	:::::::::::::::::::::,:::::::::::::::::::::,:::::::::::::::::::::,:::::::::::::::::::::,:::::::::::::::::::::,:::::::17:32:131:0:146:::::148:-7:170:201::,:::::::::::::::::::::
2	23282	0.042675651	GCAGAG,AAGCAGTGGTATCAACG,TTGTCCACCTAATTTTAATACGTTCAAATGAAAGAGAGAAACACAGTGGAAGATTAAGAGTCACGCTTGACACTTCCAAGAAAAGCAGTTCCTTGTTGATCACGGCTTCCCGGGCAGCAGACACTGCTTCTTACTTCTGTGCTACGGACGCGAATACAGGAGCCAATAGTAAGCTGACATTTGGAAAAGGAATAACTCTGAGTGTTAGACCAGATATCCAGAAGCCTGACCCTGCCGTGTACCAGCTGA	())''',)(''')'+')')'(&&$,55525569@ABB<==@@B@@=<<>:=??8<@=?=?=?=<A=A<>;@<<??=>=A<?@@<@=?=>==A>=;A??=====@=:@@;>@@@B=>=;A;<=<>>>=<=;@?:==<;<=>=>?>A???B?>AB?A8@AA@??/////////////////////////////////////////////>@:@?;7>?A?F?@=A<<=?@>B@>B@?===@@B?>8:?>;9>==>=@?>?:<9:=;:9;6655445	TRAV17*01(992.3)		TRAJ56*01(285.3)		,,127|277|277|0|150||750.0		,,22|82|82|153|213|ST26A|286.0		agtcaacagggagaagaggatcctcaggccttgagcatccaggagggtgaaaatgccaccatgaactgcagttacaaa		actagtataaacaat		ttacagtggtatagacaaaattcaggtagaggccTTGTCCACCTAATTTTA		ATACGTTCAAATGAAAGAGAG	23	AAACACAGTGGAAGATTAAGAGTCACGCTTGACACTTCCAAGAAAAGCAGTTCCTTGTTGATCACGGCTTCCCGGGCAGCAGACACTGCTTCTTACTTC	23		14	GGAAAAGGAATAACTCTGAGTGTTAGACCAG	22	sqqgeedpqalsiqegenatmncsyk	tsinn	lqwyrqnsgrgLVHLIL	IRSNERE	KHSGRLRVTLDTSKKSSSLLITASRAADTASYF		GKGITLSVRP_	:::::::::::::::::::::,:::::::::::::::::::::,:::::::17:38:137:0:150:::::153:-2:182:213::
3	23143	0.042420865	AGCAGTGGTATCAACG,AAGCAG,CTTGCTAAGACCACCCAGCCCATCTCCATGGACTCATATGAAGGACAAGAAGTGAACATAACCTGTAGCCACAACAACATTGCTACAAA,ATTCAAGGATACAAGACAAAAGTTACAAACGAAGTGGCCTCCCTGTTTATCCCTGCCGACAGAAAGTCCAGCACTCTGAGCCTGCCCCGGGTTTCCCTGAGCGACACTGCTGTGTACTACTGCCTCGTGGGTGACCGGTATCAGTTAATCTGGGGCGCTGGGACCAAGCTAATTATAAAGCCAGATATCCAGAACCCTGACCCTGCCGTGTACCAGCTGA,AAGAGCGTCGTGTAGGGAAA	[[[[[[[[[[[[[[[[,%)$$%$,56555564545561665666654827744552827344264354375845652457757666754443656835734633435167665,=><:;;9===?<=><<>:=>8?=;>=;;:=>=;=>;>>;:<;<;<<<>?<=:>=<:;<>=??=:=><?<?;5<@>A>=<><<=86=>===>?A?>>@?>=B=?A>=B?==@=B/@<@>>>.................................=@:=>>=<?>??@A=?E@>?>?A>><>>>>;@CF>=>???><>=<<<>@<=9<98<999;6645445,))))%)&&**%)(['(''''	TRAV4*01(1106.5)		TRAJ33*01(229.5)		,,0|89|277|0|89||445.0,141|276|277|0|135||675.0,		,,,31|77|77|138|184||230.0,		CTTGCTAAGACCACCCAGCCCATCTCCATGGACTCATATGAAGGACAAGAAGTGAACATAACCTGTAGCCACAAC	16	AACATTGCTACAAAtgattat		atcacgtggtaccaacagtttcccagccaaggaccacgatttattATTCAA		GGATACAAGACAAAA	23	GTTACAAACGAAGTGGCCTCCCTGTTTATCCCTGCCGACAGAAAGTCCAGCACTCTGAGCCTGCCCCGGGTTTCCCTGAGCGACACTGCTGTGTACTAC	14		13	GGCGCTGGGACCAAGCTAATTATAAAGCCAG	25	LAKTTQPISMDSYEGQEVNITCSHN	NIATndy	itwyqqfpsqgprfiIQ	GYKTK	VTNEVASLFIPADRKSSTLSLPRVSLSDTAVYY		GAGTKLIIKP_	:::::::::::::::::::::,:::::::::::::::::::::,::::0:75::::::::::::::::,:::::::6:21:120:-1:135:::::138:-11:153:184::,:::::::::::::::::::::
4	19040	0.034900111	AAGCAG,ACTGTGGGAACTGCTC,GCTCAACTAGAAAAATCAAGGCTGCTCAGTGATCGGTTCTCTGCAGAGAGGCCTAAGGGATCTTTCTCCACCTTGGAGATCCAGCGCACAGAGCAGGGGGACTCGGCCATGTATCTCTGTGCCAGCAGCTTACCCGTAGCGGGATACACCGGGGAGCTGTTTTTTGGAGAAGGCTCTAGGCTGACCGTACTGGAGGACCTGAAAAACGTGTTCCCACCCGAGGTCGCTGTGTTTGAGCCA,AGATCGGAAGAG,GTAGGC	)*($$$,$%$$$&$%$%$$%&$$,69-37264=;:8B>>>><==7@>><;<>><=<><=??>>=?;>=@@==<>?=:<=;=;>@?>>==>>7<<<?<>=><A>>>==?;<>=>=><=<:4?<=92=>><=9<B?<?=><?=------------------------------------------------:@<?<:?;?;><?=@>@=<><??>=?>>;>><?>>;A>==66776<8<=76<=756:766665666<?7666855,(-+,,/.2,-+&,[$[%[%	TRBV7-9*03(998.3),TRBV7-9*01(971.3),TRBV7-9*05(932.7),TRBV7-9*02(914)	TRBD2*02(40),TRBD2*01(35)	TRBJ2-2*01(239.4)		,,156|288|290|0|132||660.0,,;,,273|288|290|117|132||75.0,,;,,273|283|288|117|127||50.0,,;,,273|288|290|117|132||75.0,,	,,21|29|48|136|144||40.0,,;,,21|28|48|136|143||35.0,,	,,23|71|71|145|193||240.0,,		gatactggagtctcccaggaccccagacacaagatcacaaagaggggacagaatgtaactttcaggtgtgatccaatt		tctgaacacaaccgc		ctttattggtaccgacagaccctggggcagggcccagagtttctgacttac		ttccagaatgaaGCTCAA		CTAGAAAAATCAAGGCTGCTCAGTGATCGGTTCTCTGCAGAGAGGCCTAAGGGATCTTTCTCCACCTTGGAGATCCAGCGCACAGAGCAGGGGGACTCGGCCATGTATCTC	17		12	GGAGAAGGCTCTAGGCTGACCGTACTGG	25	dtgvsqdprhkitkrgqnvtfrcdpi	sehnr	lywyrqtlgqgpeflty	fqneAQ	LEKSRLLSDRFSAERPKGSFSTLEIQRTEQGDSAMYL		GEGSRLTVL_	:::::::::::::::::::::,:::::::::::::::::::::,::::::::6:117:-2:132:136:-5:-3:144:145:-3:165:193::,:::::::::::::::::::::,:::::::::::::::::::::
5	18123	0.03321926	AAGCAGTGGTATCAACGCAGAG,AAGCAGTGGTATCAACGCAGAGTACGG,AGGAGCTCCAGATGAAAGACTCTGCCTCTTACTTCTGCGCTGTGAGAAGAGATGACAAGATCATCTTTGGAAAAGGGACACGACTTCATATTCTCCCCAATATCCAGAACCCTGACCCTGCCGTGTAC	('[[(((([([()((((&&')$,1&&&&&&'$%$$$''$''''$'$$$$$,;;?<?A<<><>C@?=>@=;>@=>=<><??@C>=@=/////////////////////////////////<>8>?<==>>?<;<?==<;>><=<=8>=>5A5555<555;5:=5555=;554;4454449	TRAV1-1*01(1092.2),TRAV1-1*02(1062.6)		TRAJ30*01(259.2)		,,226|273|275|0|47||235.0;,,261|269|269|35|43||40.0		,,25|77|77|47|99||260.0		ggacaaagccttgagcagccctctgaagtgacagctgtggaaggagccattgtccagataaactgcacgtaccag		acatctgggttttatggg		ctgtcctggtaccagcaacatgatggcggagcacccacatttctttcttac		aatgctctggatggtttg		gaggagacaggtcgtttttcttcattccttagtcgctctgatagttatggttacctccttctacAGGAGCTCCAGATGAAAGACTCTGCCTCTTACTTC			14	GGAAAAGGGACACGACTTCATATTCTCCCCA	20	gqsleqpsevtavegaivqinctyq	tsgfyg	lswyqqhdggaptflsy	naldgl	eetgrfssflsrsdsygylllQELQMKDSASYF		GKGTRLHILP_	:::::::::::::::::::::,:::::::::::::::::::::,:::::::::35:-2:47:::::47:-5:68:99::
6	13869	0.025421725	AAAAATGAAGTGGAGCAGAGTCCTCAGAACCTGACTGCCC,AAGCAGTGGTATCAAC,GGGAAGCACAGCTCCCTGCACATCACAGCCTCCCATCCCAGAGACTCTGCCGTCTACATCTGTGCTGACCACCCGCTATAATAACACCGACAAGCTCATCTTTGGGACTGGGACCAGATTACAAGTCTTTCCAAATATCCAGAAGCCTGACCCTGCCGTGTAC,AGATCGGAAGAGCGTCGTGTAGGGAAAGAGTGTAGGCTA	5755658:77867777874527553@99775747977675,1&&&&$$$$$&%%%%%,@$$;<@=?>9=?<<><<<=@CA?@@>>>AA;>>?@=><@>B>ACC@?@@=@?D?DD=CA>///////////////////////////////////////////=?>B??;>?=C=?>@@??=?>@AA??@<<=[99:9=999@96@8899>A897<778666;,000//50600/0/0-/1+0-.77036..-/+.,-5/.(/	TRAV41*01(580.9)		TRAJ34*01(269.8)		0|40|270|0|40||200.0,50|66|270|0|16|ST51AST52GST53CST55GSC56TSA57GSC58GSA59T|-32.0,198|265|270|0|67|SA199GSA200G|307.0,		,,24|78|78|80|134||270.0,		AAAAATGAAGTGGAGCAGAGTCCTCAGAACCTGACTGCCCaggaaggagaAAGCAGTGGTATCAACtgcagttactcg		gtaggaataagtgcc		ttacactggctgcaacagcatccaggaggaggcattgtttccttgtttatg		ctgagctcagggaag		aagaagcatggaagattaattgccacaataaacatacagGGGAAGCACAGCTCCCTGCACATCACAGCCTCCCATCCCAGAGACTCTGCCGTCTACATC			14	GGGACTGGGACCAGATTACAAGTCTTTCCAA	26	KNEVEQSPQNLTAqegESSGINcsys	vgisa	lhwlqqhpgggivslfm	lssgk	kkhgrliatiniqGKHSSLHITASHPRDSAVYI		GTGTRLQVFP_	::::0:::::::::::::::::,:::::::::::::::::::::,:::::::::60:-5:67:::::80:-4:103:134::,:::::::::::::::::::::
7	13571	0.024875494	AAGCAGTGGTATCAACGCAGAGTACGGGGAGGCTTTGTCGGGTGGAGCTGATTGGTTGCAGGAGCAGCAACAGTTCCAGA,GCTCATCAACCTGTTTTACATTCCCTCAGGGACAAAACAGAATGGAAGATTAAGCGCCACGACTGTCGCTACGGAACGCTACAGCTTATTGTACATTTCCTCTTCCCAGACCACAGACTCAGGCGTTTATTTCTGTGCTGTAACCCCCCTTCGACTTTCCCTTTTTTCTGGTGGCTACAATAAGCTGATTTTTGGAGCAGGGACCAGGCTGGCTGTACACCCATATATCCAGAAGCCTGACCCTGCCGTGTACCA	%2$$$$$$3$$$$$3$$$$$$$$$$$36-,3321:711229522502102018242321114/1100003111/32'''$,57562574476;<4?;:79>::<=;;<<<;;<;:?<;??=>@=<==<:>>>>;B=;?;=>=;==?==>@=@=<<==<??@>C<<>==><B;=??==@>>>=>:8=><<::?>;=;>;C>>;>>>=>@@EBC><,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,<@<<==:=:>>;=;<>C;<;==@><?<><7=AE?=>>@@>6:>;:;<>;9;:;88<787955	TRAV22*01(970.3)		TRAJ4*01(304.2)		,125|266|271|0|141||705.0		,22|83|83|163|224||305.0		ggaatacaagtggagcagagtcctccagacctgattctccaggagggagccaattccacgctgcggtgcaatttttct		gactctgtgaacaat		ttgcagtggtttcatcaaaacccttggggacaGCTCATCAACCTGTTTTAC		ATTCCCTCAGGGACA	25	AAACAGAATGGAAGATTAAGCGCCACGACTGTCGCTACGGAACGCTACAGCTTATTGTACATTTCCTCTTCCCAGACCACAGACTCAGGCGTTTATTTC	23		11	GGAGCAGGGACCAGGCTGGCTGTACACCCAT	22	giqveqsppdlilqeganstlrcnfs	dsvnn	lqwfhqnpwgQLINLFY	IPSGT	KQNGRLSATTVATERYSLLYISSSQTTDSGVYF		GAGTRLAVHP_	:::::::::::::::::::::,:::::::19:34:133:-5:141:::::163:-2:193:224::
8	11895	0.021803405	ACAAGCAGTGGTATC,AAGCAGTGGTATCAACGCAGAGTACGGGAGGAGCAGTGACATCACAGGAAAAACCACCAA,CTCATGTTTGTCTACAACTTTAAAGAACAGACTGAAAACAACAGTGTGCCAAGTCGCTTCTCACCTGAATGCCCCAACAGCTCTCACTTATTCCTTCACCTACACACCCTGCAGCCAGAAGACTCGGCCCTGTATCTCTGTGCCAGCAGCCAAGTGTTCGCCGCGGGCTTCTCCTACGAGCAGTACTTCGGGCCGGGCACCAGGCTCACGGTCACAGAGGACCTGAAAAACGTGTTCCCACCCGAGGTCGCTGTGTTTGAGCCATCAGA,CAGAGAGA	%%&[%%&(%$&&$$$,/%%%%%%(%%(%%((%%%%%%(%%%/)),-/-((((((('/'--''.0'1'&)&(%%$%&,6-8766278<7A2;<99[[[[[[[[[[[[[[[[23[8??<4>4<>=>><><>?>=<?=8=;>:>?=<<;<;9===?>>;;C:><>;A=@;@@=><;@:B><9@8?7?<=<==<@>?B><;A:=<;<=<==<==?@?;?---------------------------------------------------:A>>;97=6<=<<7@><7:78:88:9:;99<>>>=9A@==76888=7;?87<=877:876676777<A87768664443;,$$[(%(%%	TRBV4-2*51_EH (1279.5)	TRBD2*01(25),TRBD2*02(25)	TRBJ2-7*01(233.8),TRBJ2-7*02(214)		,,189|343|344|0|154|ST313C|756.0,	,,23|28|48|162|167||25.0,;,,23|28|48|162|167||25.0,	,,20|67|67|170|217||235.0,;,,20|40|67|170|189|SG36TDG39|69.0,		atgggctgcaggctgctctgctgtgcggttctctgtctcctgggagcggtccccatggaaacgggagttacgcagacaccaagacacctggtcatgggaatgacaaataagaagtctttgaaatgtgaacaacat		ctggggcataaagct		atgaattgggacaagcaaagtgctaagaagccactggagCTCATGTTTGTC		TACAACTTTAAAGAACAG	17	ACTGAAAACAACAGTGTGCCAAGTCGCTTCTCACCTGAATGCCCCAACAGCTCTCACTTATTCCTTCACCTACACACCCTGCAGCCAGAAGACTCGGCCCTGTATCTC	17		12	GGGCCGGGCACCAGGCTCACGGTCACAG	21	mgcrllccavlcllgavpmetgvtqtprhlvmgmtnkkslkceqh	lghka	mnwdkqsakkpleLMFV	YNFKEQ	TENNSVPSRFSPECPNSSHLFLHLHTLQPEDSALYL		GPGTRLTVT_	:::::::::::::::::::::,:::::::::::::::::::::,:::::::12:30:138:-1:154:162:-7:-4:167:170:0:189:217::,:::::::::::::::::::::
9	10787	0.019772453	AAGCAGTGGTATCAACGCAGAGTACGGGGAGGACAGATTCTTTTTATGATTCCTAAAGTGGAAGAAATAAAGTATCTCTGCTATGTTCATTTCTTTTTGGATTGAAAATTTTAATCCTCAGTGAACCAGGGCAGAAAAGAATGATGATATCCTTGAGAGTTTTACTGGTGATCCTGTGGCTTCAGTTAAGCTGGGTTTGGAGCCAACGGAAGGAGGTGGAGCAGGATCCTGGACCCTTCAATGT,ACTGTCGCTTTCAACTGTACTTACAGCAACAGTGCTTCTCAGTCTTTCTTCTGGTACAGACAGGATTGCAGGAAAGAACCTAAGTTGCTGATGTCCGTATACTCCAGTGGTAATGAAGATGGAAGGTTTACAGCACAGCTCAATAGAGCCAGCCAGTATATTTCCCTGCTCATCAGAGACTCCAAGCTCAGTGATTCAGCCACCTACCTCTGTGTGGCCCGCTCTGGGGGTTACCAGAAAGTTACCTTTGGAACTGGAACAAAGCTCCAAGTCATCCCAAATATCCAGAACCCTGACCCTGCCGTGTAC	%+$$$$$$1$%$$$*$$$$$%$$$$%*3*0*2*'))()'&&&&&&((1%(%%(%((%%%(%%%%$&%&)&&(&((((((1(((((((((((((2((((350132574234546653423442335333443234234342544344334422233432502354453363333554434412446263454454346742253244455127516525424''''''&%%3%2%%%%2%%$$$$,5959576845665586:758586978867989499787498;596:7:9<99678:98?7::8888:9<=;:9@<:8<<=@<>=<==<:<>><;;;:=>>:>9::=@@<>@>A>=?<;><=>;<===<?===:<>@@<@=;><@>A;;==@?<>?>@@?<>>=<=@=><<>?>=?@;=<@<>?8@<?=<?D=>@??=;===;@?><@@<@.......................................<?<=[?<<>@C=@<>>;>><>?>>><>=;=[9987@888>8==8888>B886<667666<	TRAV12-1*01(858.8),TRAV12-1*02(834.7)		TRAJ13*02(289.4),TRAJ13*01(271.9)		0|38|274|206|244||190.0,51|268|274|0|217||1085.0;,261|268|274|210|217||35.0		,25|83|83|222|280||290.0;,25|52|83|222|249||135.0		CGGAAGGAGGTGGAGCAGGATCCTGGACCCTTCAATGTtccagagggagccACTGTCGCTTTCAACTGTACTTACAGC		AACAGTGCTTCTCAGTCT	19	TTCTTCTGGTACAGACAGGATTGCAGGAAAGAACCTAAGTTGCTGATGTCC	21						13	GGAACTGGAACAAAGCTCCAAGTCATCCCAA	26	RKEVEQDPGPFNvpegaTVAFNCTYS	NSASQS	FFWYRQDCRKEPKLLMS				GTGTKLQVIP_	::::206:::::::::::::::::,:::::27:45:96::210:-6:217:::::222:-5:249:280::
10	10436	0.019129074	AAGCAGTGGTATCAACGCAGAGTACGGGGATTTCTACTGGGTTTT,AAAGC,GCAGGACAAAGCCTTGAGCAGCCCTCTGAAGTGAC,AAGCAGTGGTATCAACGCAGAGT,GGGTGGATGGTTTGGAGGAGACAGGTCGTTTTTCTTCATTCCTTAGTCGCTCTGATAGTTATGGTT,AGGAGCTCCAGATGAAAGACTCTGCCTCTTACTTCTGCGCTGTGAGAGATTGGCCCCCAAGGGATGCCAGACTCATGTTTGGAGATGGAACTCAGCTGGTGGTGAAGCCCAATATCCAGAAGCCTGACCCTGCCGTGTACCAGCTGA	12./////3/0//12.///./././/0...,.---/,--1,$$$$,$%$$$,85566367426657644555665757361375556,&%&%*0*%&%&&&&3&&0&&&&),$$$$$$$$$77$$$$$?$$$7$$=$$$$$7$$$$$$$67$$$$$$$$=$$0;$$$$$$:$$$$$:$,::?<>?><===CD=>=A?>?>?=@<DAD?<AC?GA/////////////////////////////////////////////>C@A=D=@=>@>?>><A>D?;A>==??>>;[<<=<?;<<A;9B:;;;C=:;9<98:888;6646445	TRAV1-1*01(691.8),TRAV1-1*02(653.1)		TRAJ31*01(240)		,,0|32|275|3|35||160.0,112|135|275|0|23|ST113ASA115CST116ASG118TSC119GSG121TSG123TI125ASC127GSC130GDT132ST133G|-54.0,148|214|275|0|66|SC148GST149GSC150G|288.0,226|275|275|0|49||245.0;,,,,,261|269|269|35|43||40.0		,,,,,28|76|76|63|111||240.0		GGACAAAGCCTTGAGCAGCCCTCTGAAGTGACagctgtggaaggagccattgtccagataaactgcacgtaccag		acatctgggttttatggg		ctgtcctggtaccagcaacAAGCAGTGGTATCAACGCAGAGTctttcttac		aatgGGGTGGATGGTTTG		GAGGAGACAGGTCGTTTTTCTTCATTCCTTAGTCGCTCTGATAGTTATGGTTacctccttctacAGGAGCTCCAGATGAAAGACTCTGCCTCTTACTTC			14	GGAGATGGAACTCAGCTGGTGGTGAAGCCCA	26	GQSLEQPSEVtavegaivqinctyq	tsgfyg	lswyqqQAVVSTQSlsy	nGVDGL	EETGRFSSFLSRSDSYGylllQELQMKDSASYF		GDGTQLVVKP_	:::::::::::::::::::::,:::::::::::::::::::::,::::3:::::::::::::::::,:::::::::::::::::::::,::::::::14:::::::::::::,:::::::::35:0:49:::::63:-8:80:111::

**Comment by dbolotin** [comment]
Several important fixes for the `assembleContigs` procedure will come out with 3.0.8 (will release it very soon), please also add `--trimming-window-size 3 --trimming-quality-threshold 17` on the `align` step, this should make analysis pipeline more robust to the artefacts happening with low quality input data.
