### ISSUE TITLE
Mismatch between exported reads and clone target sequence

### ISSUE THREAD

**Issue by SeanGriffith** [milaboratory/mixcr#524]
## Expected Result

Extracting the reads for different clones from the mixcr output of RNA-seq data using mixcr 3.0.5

## Actual Result

After successfully running the "analyze" pipeline on RNA-seq data (with the "assembleContigs" step enabled) the last step of clone export is not automatically executed and no clones table file is generated (We are talking about the output file "my_analysis.txt" in [https://mixcr.readthedocs.io/en/master/analyze.html#id1](https://mixcr.readthedocs.io/en/master/analyze.html#id1), which is not automatically generated).

Running the "exportClones" command by hand and checking the output against the raw reads exported for each clone we found a discrepancy between the exported reads and the target sequences for several clones. ( Reads were exported by "exportReadsForClones". The option "-OsaveOriginalReads=true" flag has been set for the alignment step beforehand.) 
 
Example: Exporting the reads for clone 430 in our data we realized that the sequences in the exported reads do not fit to the target sequences that are given by "exportClones"/"exportClonesPretty" or "exportAlignments" (we also checked reverse complement)  - It turned out that the correct reads are assigned to the clone 409, these do not fit to the target sequence of clone 409, but they do fit to the target sequence of clone 430.

The reads stated in the "exportAlignments" output in column "descrsR1"/ "descrsR2" show the same behaviour: reads for several clones are wrong.

Interestingly the reported reads for clones with small numbers like 0 and 1 are matching to the reported target sequences.

## Exact MiXCR commands 

```
mixcr analyze shotgun -s hsa --starting-material rna --contig-assembly --align "-OsaveOriginalReads=true" --report sample/report_mixcr_analyze_sample.txt trimmed_R1.fastq trimmed_R2.fastq sample/mixcr_analysis_sample
mixcr exportAlignments -p full -descrsR1 -descrsR2 -cloneId -cloneIdWithMappingType -readIds -readHistory -chains -topChains -lengthOf CDR3 mixcr_analysis_sample.clna mixcr_analysis_sample.alignments.txt
mixcr exportClones -p fullImputed mixcr_analysis_sample.contigs.clns mixcr_analysis_sample.clones.txt 
mixcr exportReadsForClones --id 430 mixcr_analysis_sample.clna reads_sample_clone430
```

Version info:

> MiXCR v3.0.5 (built Mon Feb 25 00:04:20 CET 2019; rev=af538f7; branch=release/v3.0.5; host=Dmitrys-MacBook-Pro.local)
> RepSeq.IO v1.3.1 (rev=89048b0)
> MiLib v1.10 (rev=cd564d4)
> Built-in V/D/J/C library: repseqio.v1.5

**Comment by PoslavskySV** [comment]
Hi! Sorry for late reply. Could you please share the problematic sample so that we can debug the problem? You can send the dataset to support@milaboratory.com

**Comment by dbolotin** [comment]
The possible fix for the problem will be released with 3.0.8.

**Comment by SeanGriffith** [comment]
Okay, thank you for the fix.
Once it is available I will give it a try and let you know whether the problem persists.
Is it necessary to run the whole `mixcr analyze shotgun ...`  pipeline again or is running `exportClones` with 3.0.8 sufficient?

**Comment by dbolotin** [comment]
Hi, just to let you know, [MiXCR 3.0.8](https://github.com/milaboratory/mixcr/releases/tag/v3.0.8) was just released. Yes, please re-run the whole pipeline, some of the issue originate from the first `align` step.
