### ISSUE TITLE
How to create external library correctly?

### ISSUE THREAD

**Issue by rajasanjeevkumar** [milaboratory/mixcr#529]
Hi,

 I am trying to build an external library by adding new entries to the default imgt library. 
The goal is to build hybrid library by adding human entries to mouse species. I have added the 
following entries to the json file. The following entries are added for the mouse species. I am sure 
I am missing some of the steps in building correct library. Can someone please outline the 
steps for building hybrid library?

  }, {
    "baseSequence": "CIS43_UCA_LIGHT",
    "name": "CIS43_UCA_LIGHT",
    "geneType": "V",
    "isFunctional": true,
    "chains": [ "IGK" ],
    "meta": {
      "comments": "Testing manual"
    },
    "anchorPoints": {
      "FR1Begin": 0,
      "CDR1Begin": 78,
      "FR2Begin": 114,
      "CDR2Begin": 165,
      "FR3Begin": 174,
      "CDR3Begin": 282,
      "VEnd": 338
    }
  }, {
  
....

  }, {
    "uri": "CIS43_UCA_LIGHT",
    "range": {
      "from": 0,
      "to": 338
    },
    "sequence": "GACATCGTGATGACCCAGTCTCCAGACTCCCTGGCTGTGTCTCTGGGCGAGAGGGCCACCATCAACTGCAAGTCCAGCCAGAGTGTTTTATACAGCTCCAACAATAAGAACTACTTAGCTTGGTACCAGCAGAAACCAGGACAGCCTCCTAAGCTGCTCATTTACTGGGCATCTACCCGGGAATCCGGGGTCCCTGACCGATTCAGTGGCAGCGGGTCTGGGACAGATTTCACTCTCACCATCAGCAGCCTGCAGGCTGAAGATGTGGCAGTTTATTACTGTCAGCAATATTATAGTACTCCTCTCACTTTCGGCGGAGGGACCAAGGTGGAGATCAAA"
  }, {

**Comment by PoslavskySV** [comment]
Hi, sorry for late reply. You should use our [repseqio](https://github.com/repseqio/repseqio) tool for creating custom libriries.

**Comment by dbolotin** [comment]
Please see this [link](https://github.com/repseqio/repseqio/wiki/Creating-repseqio-formatted-JSON-library).
