### ISSUE TITLE
question about kAligner2

### ISSUE THREAD

**Issue by mimisikai** [milaboratory/mixcr#530]
## Checklist before submitting the issue:
Can you explain more about kAligner2 parameter? If the samples were Ig PCR amplicon from B cells, should I use kAligner2 or normal setting for the analysis? I see quite different outcomes from two settings.

**Comment by PoslavskySV** [comment]
kAligner2 is specifically optimized for analysis of B-cell data, in particular it better supports long gaps and insertions. One should use kAligner2 for Ig PCR amplicon from B cells.
