### ISSUE TITLE
V2.1.8 manual not available

### ISSUE THREAD

**Issue by xww52526** [milaboratory/mixcr#537]
Hello,

I tried to compare results generated from latest version MiXCR with that generated by v2.1.8. And just found the manual for v2.1.8 is no longer available. Is it possible to fix the manual download link: https://mixcr.readthedocs.io/en/v2.1.8/. So that users could download a copy for reference.

Thank you!

Best,
Wen

**Comment by dbolotin** [comment]
Here you go:
https://mixcr.readthedocs.io/en/v2.1.8/
