### ISSUE TITLE
clone type is  duplicate

### ISSUE THREAD

**Issue by BlingArida** [milaboratory/mixcr#539]
Dear，

Thank you for your work to help me analysis RNA-seq data. While I try to do clone typeing,I find something strange. The same cdr3 sequences can appear multiple times although they are in different clone ID.

cloneId | Chains | cloneCount | cloneFraction | bestVHit | aaSeqCDR3 | aaSeqImputedVDJRegion
-- | -- | -- | -- | -- | -- | --
0 | IGH | 6849 | 0.011385 | IGHV3S39*01 | CAKPNGRINYGMDNW | qvqlvesggglvqpggslrlscaasgftfssyamswvrqapgkglewvsdinsgggstyyadsvkgrftisrdnakntlylqmnslkpegtavyyCAKPNGRINYGMDNWgkgtlvtvss_
1 | IGH | 5733 | 0.00953 | IGHV3S17*01 | CARGVLPIATIDYGMDYW | qlqlvesggglvqpggslrlscaasgftfddygmswvrhspgkglewvsaiswnggstyyaesmkgrftisrdnakntvylqmnslkpegtavyyCARGVLPIATIDYGMDYWgkgtlvtvss_
2 | IGH | 4801 | 0.007981 | IGHV3S39*01 | CAKPNGRINYGMDNW | qvqlvesggglvqpggslrlscaasgftfssyamswvrqapgkglewvsdinsgggstyyadsvkgrftisrdnakntlylqmnslkpegtavyyCAKPNGRINYGMDNWgkgtlvtvss_
3 | IGH | 3774 | 0.006273 | IGHV3S41*01 | CANFGDSYYYGMDYW | qlqlvesggglvqpggslrlscaasgftfssyamswvrqapgkglewvsainsgggstsyadsvkgrftisrdnakntlylqmnslkpegtavyyCANFGDSYYYGMDYWgkgtlvtvss_

As you can see, the cloneId0  and cloneID3 ,their `aaSeqCDR3` and `aaSeqImputedVDJRegion` are totally no difference. So,could you please tell me is there any bug in you software or I did anything wrong.
The following code is my execution step：
```
mixcr align -p rna-seq --library imgt -s alpaca -OallowPartialAlignments=true P2_R1.fastq.gz B2-P2_R2.fastq.gz P2_alignments.vdjca
mixcr assemblePartial P2_alignments.vdjca /P2_alignments_rescued_1.vdjca
mixcr assemblePartial P2_alignments_rescued_1.vdjca P2_alignments_rescued_2.vdjca

mixcr assemble --write-alignments --report P2_report.txt P2_alignments_rescued_2.vdjca P2_clones.clna 
mixcr assembleContigs --report report.txt P2_clones.clna P2_full_clones.clns
mixcr exportClones -c IG -p fullImputed /P2_full_clones.clns P2_full_clones.xls
mixcr exportAlignments -cloneId -aaFeature CDR3 -nFeature CDR3 -nFeatureImputed VDJRegion -aaFeatureImputed VDJRegion P2_clones.clna -f P2_full_clones.tsv 

mixcr assemble P2_alignments_rescued_2.vdjca P2_clones.clns  

mixcr exportClones -cloneId -chains -count -fraction -vFamily -vGene -vHit -aaFeature CDR3 -lengthOf CDR3 -aaFeatureImputed VDJRegion P2_clones.clns P2_clone.xls 
less /P2_clone.xls |cut -f 1-4,7,8,10 > P2_result.xls
```

Many thanks,
Arida

**Comment by dbolotin** [comment]
MiXCR uses nucleotide sequences as a clonotype "key". Please see nSeqCDR3 for the difference between clonotypes.
