### ISSUE TITLE
Problem with splitting chains in output

### ISSUE THREAD

**Issue by mikessh** [milaboratory/mixcr#541]
Default pipeline ("analyze shotgun" in my case) creates .TRA.txt, .TRB.txt ... .ALL.txt clonotype tables as output. It seems that .TRD file is still filled with .TRA sequences in the absence of any TRD chains.

**Comment by dbolotin** [comment]
It seems impossible to distinguish actual TRA from TRD genes without having TRA/D C gene. We observed many cases with V genes annotated as TRA to be a part of assemblies with TRD C genes.

Actual chain assignment in MiXCR is performed by intersecting chain lists for V / J / C genes. After some time we assigned both chains for all the genes from TRA/D locus in the library.

Any suggestions on this matter are welcome. Here is the link to [the library file](https://github.com/repseqio/library/blob/master/human/TRA_TRD.json). If there are any robust biological factors that can be used to assign V or J gene to one of the chains please point to them. @Alex-Davydov can help with the library adjustment, so we can include changes into the 3.1 release.

**Comment by tdfy** [comment]
Does the same case apply for TRDV1/TRDV2? I have a large fraction of these chains in my gamma report files (MiXCR v3.0.3.) Thank you.
