### ISSUE TITLE
10x cellranger vdj data

### ISSUE THREAD

**Issue by cstrlln** [milaboratory/mixcr#542]
Hello,
do you have a suggested pipeline to use with single cell vdj data like the output from cellranger vdj? eg. filtered contigs and filtered annotations.

Or how to use mixcr with the raw single cell fastq files?

thank you

**Comment by PoslavskySV** [comment]
Hi, sorry for the late reply. In general, single cell vdj is under our `active work in progress`. I believe in Feb we'll come with the release. See also #514
