### ISSUE TITLE
Retaining VDJ aligned reads that do not cover CDR3

### ISSUE THREAD

**Issue by alexpan82** [milaboratory/mixcr#544]
Hello,

Is it possible to retain the alignments of reads that do not cover the CDR3 region, but align to other VDJ gene features? For example, I would like to know which reads mixcr aligned to region FR1 but do not cover the CDR3. I do not plan on using these reads for clonotype assembly.

Thank you!

**Comment by dbolotin** [comment]
Yes, this is possible but not documented, just add:
`... -OallowPartialAlignments=true -OallowNoCDR3PartAlignments=true ...`
to the `align` command line.

Let me know whether it is what you need.

**Comment by alexpan82** [comment]
This is exactly what I was looking for. Thank you!
