### ISSUE TITLE
Include Java heap size parameter in analyze

### ISSUE THREAD

**Issue by dahjan** [milaboratory/mixcr#551]
When working with a big dataset, I often run into a `java.lang.OutOfMemoryError: Java heap space` error. One of the ways to fix this has been discussed in #515 already.

However, I do not currently see an option to add the parameter `-Xmx16g` when running `mixcr analyze`.

Could this be included?

**Comment by dbolotin** [comment]
Hi, `mixcr` will pass `-Xmx...` option to `java` process. So you can just run:

```
mixcr -Xmx16g analyze ...
```
