### ISSUE TITLE
sequence name affects alignment results

### ISSUE THREAD

**Issue by ms201420201029** [milaboratory/mixcr#552]
Hi, when I use 
>plasmidL2_0_FULL
CGGCCGTGTATTACTGTGCGAGAGATATGGCAAGTACTACGTACCGGCGAAACCTACTAC
TACGGTATGGACGTCTGGGGCCAAGGGACCAC
to align and exportAlignments, can get CDR3 seq.

But I use
>plasmidL2_Cluster0_FULL
CGGCCGTGTATTACTGTGCGAGAGATATGGCAAGTACTACGTACCGGCGAAACCTACTAC
TACGGTATGGACGTCTGGGGCCAAGGGACCAC
to align and exportAlignments, there is no result of CDR3 seq.
Is there some requirement for the sequence name？

**Comment by PoslavskySV** [comment]
Hi!

Yes, that's true. The k-mer based alignments algorithm used in MiXCR selects k-mers randomly from the sequence and the seed used for pseudo random generator is computed as a hash of the sequencing read description. So the results are fully reproducible when running mixcr on the same samples. However, if you change description lines, the results might be different.
