### ISSUE TITLE
Number of clonotype

### ISSUE THREAD

**Issue by Tinalxt** [milaboratory/mixcr#554]
Hi, I have a naive question about how many  TCR clonotypes are normal in tumor samples?
I found my PBMC TCR RNA data of some samples were about 10000+ clonotypes, but a few samples were about 100+ clonotypes. Is there a problem with my data or is this normal?

**Comment by PoslavskySV** [comment]
Hi! The results may vary significantly depending on the library structure and its quality; in general it is not possible to answer without looking the data. I advice you to manually inspect raw alignments using [`exportAlignmentsPretty`](https://mixcr.readthedocs.io/en/master/export.html) - this should help to understand whether there are problems with the data or not.

**Comment by Tinalxt** [comment]
Sorry, my reply is slow. I tried your suggestion and executed the exportAlignmentsPretty command. I don't understand the results. Does this mean that the quality of my reads is not good?
my code is as follow:
`mixcr exportAlignmentsPretty --skip 1000 --limit 10 sample.vdjca  test.txt`
[test.txt](https://github.com/milaboratory/mixcr/files/4322176/test.txt)
