### ISSUE TITLE
Dedicated receptor type for analysis

### ISSUE THREAD

**Issue by AnaBolivar** [milaboratory/mixcr#556]
When I use the _analyze amplicon_ command, and I specify TCR as the --receptor-type, for some of the samples the .txt output for TRBs is the exact same as the TRAs, with both files including both TRA and TRB clonotypes. Why is it not splitting them as separate .txt files in all samples?

**Comment by PoslavskySV** [comment]
HI! Can you reproduce the problem with the latest MiXCR?
