### ISSUE TITLE
Can I use the Mixcr to analyze the third generation sequencing data? such as pacbio

### ISSUE THREAD

**Issue by CromitDolores0808** [milaboratory/mixcr#557]
## Checklist before submitting the issue:

 - [x] The issue is strongly related to the MiXCR software
 - [ ] The issue can be reproduced with [the most recent version](https://github.com/milaboratory/mixcr/releases) of MiXCR
 - [x] There is no answer to the question in the [official documentation](http://mixcr.readthedocs.io/) and there is no duplicate issue in the [bug tracker](https://github.com/milaboratory/mixcr/issues?utf8=✓&q=)  
 - [ ] Inspection of raw alignments with [exportAlignmentsPretty](http://mixcr.readthedocs.io/en/master/export.html#exporting-well-formatted-alignments-for-manual-inspection) shows that data has the expected architecture, and sample preparation artefacts are not the reason of the problem (if this is the matter of the issue)

## Expected Result

*A description of what you wanted to happen*

## Actual Result

*A description of what actually happened*

## Exact MiXCR commands 
`Hi guys,
Now I have to analyze the third generation RNA-seq data of human cancer sample. I wonder if I can use the Mixcr to analyze it and get the BCR and TCR information. If yes, what commands should I use? Can I use the  --mixcr analyze shotgun?
Thanks,
Dolores  `
*Paste here __exact__ MiXCR commands you used (enclose it with single `` ` ``  for better formatting)*

## MiXCR report files 

*Paste here content of the report files produced by MiXCR (enclose it with triple ```` ``` ````  for better formatting)*

**Comment by PoslavskySV** [comment]
Hi! 

Unfortunately, we can't answer without more details - we never tested third generation. Could you share some piece of third-generation data with us? Then we'll be able to give a feedback.
