### ISSUE TITLE
Quality control suggestion needed: what is the influence of PE library with low merge percent (<60%) ?

### ISSUE THREAD

**Issue by Ming-Lian** [milaboratory/mixcr#559]
## Checklist before submitting the issue:

 - [ ] The issue is strongly related to the MiXCR software
 - [ ] The issue can be reproduced with [the most recent version](https://github.com/milaboratory/mixcr/releases) of MiXCR
 - [ ✓] There is no answer to the question in the [official documentation](http://mixcr.readthedocs.io/) and there is no duplicate issue in the [bug tracker](https://github.com/milaboratory/mixcr/issues?utf8=✓&q=)  
 - [x] Inspection of raw alignments with [exportAlignmentsPretty](http://mixcr.readthedocs.io/en/master/export.html#exporting-well-formatted-alignments-for-manual-inspection) shows that data has the expected architecture, and sample preparation artefacts are not the reason of the problem (if this is the matter of the issue)

## MiXCR report files 

I want to know the influence of my PE library with low merge percent (<60%). Is it acceptable to process downstream analysis with confidence?

Can you give me some adivce for quality control based on MiXCR report?

**Comment by PoslavskySV** [comment]
Hi! 

> low merge percent (<60%)

it could be. Basically, you can superficially check the quality of your library by looking the numbers in the alignment report (`--report align.report` at [`align`](https://mixcr.readthedocs.io/en/master/align.html) step). There you can find how many reads were not aligned and for what reason. If in total you observe a significant number of reads dropped (not aligned), then it signals that there are problems with the library. Then you can rigorously check your library structure using [`exportAlignmentsPretty`](http://mixcr.readthedocs.io/en/master/export.html#exporting-well-formatted-alignments-for-manual-inspection).
