### ISSUE TITLE
Output Error: Output file name prefix, matches the existing file name. Most probably you specified paired-end file names but forgot to specify output file name prefix.

### ISSUE THREAD

**Issue by Pio82** [milaboratory/mixcr#564]
## Checklist before submitting the issue:

 - [x] The issue is strongly related to the MiXCR software
 - [x] The issue can be reproduced with [the most recent version](https://github.com/milaboratory/mixcr/releases) of MiXCR
 - [x] There is no answer to the question in the [official documentation](http://mixcr.readthedocs.io/) and there is no duplicate issue in the [bug tracker](https://github.com/milaboratory/mixcr/issues?utf8=✓&q=)  
 - [x] Inspection of raw alignments with [exportAlignmentsPretty](http://mixcr.readthedocs.io/en/master/export.html#exporting-well-formatted-alignments-for-manual-inspection) shows that data has the expected architecture, and sample preparation artefacts are not the reason of the problem (if this is the matter of the issue)

## Expected Result

*A description of what you wanted to happen*

## Actual Result

*A description of what actually happened*

## Exact MiXCR commands 

*Paste here __exact__ MiXCR commands you used (enclose it with single `` ` ``  for better formatting)*

## MiXCR report files 

*Paste here content of the report files produced by MiXCR (enclose it with triple ```` ``` ````  for better formatting)*

**Comment by Pio82** [comment]
I just upgraded Mixcr from version 3.0.8 to 3.0.12 using brew.  I tried to run a batch using a script I've always used before, but now I receive the following message for each file:

"Output file name prefix, matches the existing file name. Most probably you specified paired-end file names but forgot to specify output file name prefix."

I originally installed Mixcr manually.

Here's the script I use:  

#!/bin/bash

for index in /mnt/data/TCR_PROCESSING-ISEQ100/Data/ISeq_Fastq/*_L001_R1_001.fastq.gz
do
mixcr analyze amplicon -s hs \--starting-material dna \--5-end v-primers \--3-end j-primers \--adapters no-adapters \--receptor-type trb \--only-productive \--report /mnt/data/TCR_PROCESSING-ISEQ100/Data/ISeq_Fastq/Mixcr_analysis.report ${index} ${index/R1/R2}
done

Has something changed in the command requirements?  Should I have updated Mixcr manually?  Please advise.

**Comment by PoslavskySV** [comment]
Hi! The scripts looks not OK, since you didn't specify the analysis name. The syntax for analyze is:
```
mixcr analyze [options] R1.fastq.gz R2.fastq.gz analysis_name
```
(3 last required arguments: file R1, file R2 and analysis name)

MiXCR 3.0.12 helps to identify the mistake (while MiXCR 3.0.8 not). So, previously 
the results were not correct (you lost R2). 

The correct command is something like:
```bash
#!/bin/bash

for index in /mnt/data/TCR_PROCESSING-ISEQ100/Data/ISeq_Fastq/*_L001_R1_001.fastq.gz
do
    mixcr analyze amplicon -s hs \
        --starting-material dna \
        --5-end v-primers \
        --3-end j-primers \
        --adapters no-adapters \
        --receptor-type trb \
        --only-productive \
        --report /mnt/data/TCR_PROCESSING-ISEQ100/Data/ISeq_Fastq/Mixcr_analysis.report \
        ${index} ${index/R1/R2} ${index/R1/}_result
done
```

**Comment by Pio82** [comment]
Thank you very much.  Do you know if naming the output file has always been a requirement?  I don't remember it being a requirement in version 3.0.8

**Comment by PoslavskySV** [comment]
Yes, it always was a requirement, we just added error message, since it was a frequent mistake. What was happening with  paired-end analysis and without specifying analysis name, eg like this
```bash
mixcr analyze ... R1.fastq.gz R2.fastq.gz
```
MiXCR considered the input as single-end, and used "R2.fastq.gz" for analysis name.

**Comment by Pio82** [comment]
I fear to ask, but does this mean that MiXCR was ignoring the R1 input reads and just using the R2 reads whenever no output name was specified?

**Comment by PoslavskySV** [comment]
it was ignoring r2...
