### ISSUE TITLE
encounter exception

### ISSUE THREAD

**Issue by ChandlerHo** [milaboratory/mixcr#565]
## Checklist before submitting the issue:

 - [ x] The issue is strongly related to the MiXCR software
 - [ x] The issue can be reproduced with [the most recent version](https://github.com/milaboratory/mixcr/releases) of MiXCR
 - [x ] There is no answer to the question in the [official documentation](http://mixcr.readthedocs.io/) and there is no duplicate issue in the [bug tracker](https://github.com/milaboratory/mixcr/issues?utf8=✓&q=)  
 - [ ] Inspection of raw alignments with [exportAlignmentsPretty](http://mixcr.readthedocs.io/en/master/export.html#exporting-well-formatted-alignments-for-manual-inspection) shows that data has the expected architecture, and sample preparation artefacts are not the reason of the problem (if this is the matter of the issue)

## Expected Result

*A description of what you wanted to happen*

## Actual Result

I encountered exception during the exporting step. The alignment and assembly went fine. Thank you so much for your help.

## Exact MiXCR commands 

*Paste here __exact__ MiXCR commands you used (enclose it with single `` ` ``  for better formatting)*
'
for READ1 in Desktop/TCRMRD/tcr/trb/*_R1_*; do     READ2=${READ1/_R1_/_R2_};     OUTPUT=${READ1/TR/Output};     mixcr analyze amplicon --species hsa         --starting-material dna         --5-end v-primers         --3-end j-primers         --adapters no-adapters     --contig-assembly         --receptor-type tcr         --align '--library TCR'         --export '-cloneId -targetSequences -count -fraction -vGene -dGene -jGene -nFeature CDR3 -aaFeature CDR3'        "$READ1" "$READ2" "$OUTPUT"; done
'

## MiXCR report files 

*Paste here content of the report files produced by MiXCR (enclose it with triple ```` ``` ````  for better formatting)*
'''
NOTE: report file is not specified, using Desktop/TCRMRD/tcr/trb/Output06_S1_L001_R1_001.fastq.gz.report to write report.
Alignment: 0.1%
Alignment: 10.3%  ETA: 00:08:22
Alignment: 20.4%  ETA: 00:06:26
Alignment: 30.5%  ETA: 00:06:04
Alignment: 40.6%  ETA: 00:05:19
Alignment: 50.6%  ETA: 00:04:11
Alignment: 60.7%  ETA: 00:03:12
Alignment: 70.7%  ETA: 00:02:15
Alignment: 80.9%  ETA: 00:01:29
Alignment: 91%  ETA: 00:00:42
============= Report ==============
Analysis time: 8.34m
Total sequencing reads: 2811368
Successfully aligned reads: 2639881 (93.9%)
Paired-end alignment conflicts eliminated: 85876 (3.05%)
Alignment failed, no hits (not TCR/IG?): 5411 (0.19%)
Alignment failed because of absence of V hits: 313 (0.01%)
Alignment failed because of absence of J hits: 34330 (1.22%)
No target with both V and J alignments: 11501 (0.41%)
Alignment failed because of low total score: 119932 (4.27%)
Overlapped: 2691616 (95.74%)
Overlapped and aligned: 2540518 (90.37%)
Alignment-aided overlaps: 16545 (0.65%)
Overlapped and not aligned: 151098 (5.37%)
V gene chimeras: 1296 (0.05%)
J gene chimeras: 1534 (0.05%)
TRB chains: 1438812 (54.5%)
TRG chains: 1201069 (45.5%)
Realigned with forced non-floating bound: 272594 (9.7%)
Realigned with forced non-floating right bound in left read: 1620 (0.06%)
Realigned with forced non-floating left bound in right read: 1620 (0.06%)
Initialization: progress unknown
Assembling initial clonotypes: 4.1%
Assembling initial clonotypes: 19.1%  ETA: 00:00:10
Assembling initial clonotypes: 38.4%  ETA: 00:00:06
Assembling initial clonotypes: 57.7%  ETA: 00:00:04
Assembling initial clonotypes: 77%  ETA: 00:00:02
Assembling initial clonotypes: 95.3%  ETA: 00:00:00
Mapping low quality reads: 2%
Mapping low quality reads: 16.4%  ETA: 00:00:11
Mapping low quality reads: 34.4%  ETA: 00:00:07
Mapping low quality reads: 50.4%  ETA: 00:00:06
Mapping low quality reads: 70.2%  ETA: 00:00:03
Mapping low quality reads: 88%  ETA: 00:00:01
Clustering: 0%
Clustering: 13.3%  ETA: 00:00:19
Clustering: 30%  ETA: 00:00:08
Clustering: 50.2%  ETA: 00:00:04
Clustering: 79.7%  ETA: 00:00:00
Building clones: 79.9%  ETA: 00:01:32
Preparing for sorting: progress unknown
Writing alignments: 0%
============= Report ==============
Writing alignments: 100%  ETA: 00:00:00
Analysis time: 4.19m
Final clonotype count: 22013
Average number of reads per clonotype: 106.85
Reads used in clonotypes, percent of total: 2352083 (83.66%)
Reads used in clonotypes before clustering, percent of total: 2418333 (86.02%)
Number of reads used as a core, percent of used: 2399873 (99.24%)
Mapped low quality reads, percent of used: 18460 (0.76%)
Reads clustered in PCR error correction, percent of used: 66250 (2.74%)
Reads pre-clustered due to the similar VJC-lists, percent of used: 648 (0.03%)
Reads dropped due to the lack of a clone sequence, percent of total: 160710 (5.72%)
Reads dropped due to low quality, percent of total: 7815 (0.28%)
Reads dropped due to failed mapping, percent of total: 53023 (1.89%)
Reads dropped with low quality clones, percent of total: 0 (0%)
Clonotypes eliminated by PCR error correction: 11644
Clonotypes dropped as low quality: 0
Clonotypes pre-clustered due to the similar VJC-lists: 222
TRB chains: 11901 (54.06%)
TRG chains: 10112 (45.94%)
Assembling: 0%
Assembling: 54.8%  ETA: 00:00:00
Exception in thread "main" picocli.CommandLine$ExecutionException: Error while running command (com.milaboratory.mixcr.cli.CommandAnalyze$CommandAmplicon@66ce6f87): java.lang.RuntimeException: While processing clone #0
	at picocli.CommandLine.execute(CommandLine.java:1004)
	at picocli.CommandLine.access$900(CommandLine.java:142)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:1199)
	at com.milaboratory.mixcr.cli.Main$1.handle(Main.java:72)
	at com.milaboratory.mixcr.cli.Main$1.handle(Main.java:61)
	at picocli.CommandLine$AbstractParseResultHandler.handleParseResult(CommandLine.java:1075)
	at com.milaboratory.mixcr.cli.Main.handleParseResult(Main.java:85)
	at com.milaboratory.mixcr.cli.Main.main(Main.java:55)
Caused by: java.lang.RuntimeException: While processing clone #0
	at com.milaboratory.mixcr.cli.CommandAssembleContigs.lambda$run1$13(CommandAssembleContigs.java:230)
	at cc.redberry.pipe.blocks.ParallelProcessor$Worker.run(ParallelProcessor.java:313)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.lang.OutOfMemoryError: Java heap space
	at com.milaboratory.mixcr.assembler.fullseq.FullSeqAssembler.calculateRawData(FullSeqAssembler.java:1318)
	at com.milaboratory.mixcr.cli.CommandAssembleContigs.lambda$run1$13(CommandAssembleContigs.java:204)
	at com.milaboratory.mixcr.cli.CommandAssembleContigs$$Lambda$106/0x000000080032d440.process(Unknown Source)
	... 2 more
'''

**Comment by PoslavskySV** [comment]
You encounter `Java heap space` error, which means that there are not enough RAM for the job. Try to increase RAM for mixcr by specifying e.g. 
```bash
mixcr -Xmx32g analyze ....
```
where you can replace `32g` (32 Gigabytes) with some other value.

**Comment by ChandlerHo** [comment]
thank you so much!
