### ISSUE TITLE
Separating FR1/2/3 reads

### ISSUE THREAD

**Issue by ChandlerHo** [milaboratory/mixcr#567]
Question:
My library includes primer sets that target different frameworks of IGH (FR1/2/3). I am trying to separate the reads based on features (filterAlignments --contains-feature). Is there an inverse function that could do 'does not contain feature'? for example, a FR2 read would not contain FR1.  Thank you.

**Comment by PoslavskySV** [comment]
Hi, 

there is no such option. Could do you please describe your use case in more details?
