### ISSUE TITLE
How export reads of clones after assembleContigs 

### ISSUE THREAD

**Issue by JorgeLTD** [milaboratory/mixcr#569]
Hello, i've been reading the documentation and notice that you can only export mapped reads of clones from a .clna file but not with .clns files. I'm interested in the reads of clones obtained with the assembleContigs function which seem to differ with the clones generated with only Assemble. Does exist a work around for this issue.

**Comment by dbolotin** [comment]
Hi, unfortunately it is fundamentally impossible. The `assembleContigs` procedure (if `subCloningRegion` is used), may split clonotypes into several instances (e.g. by hypermutations), and reads that don't cover the region of the sequence where clonotypes differ are in some sense  distributed between those clonotypes, this is why you can see non-integer values for clonotypes. So, exact reads-to-clones relation is "blurred" after the procedure, and this is why the procedure can output only `clns` file (which stores information only for clonotypes, but not reads).
