### ISSUE TITLE
IMGT library

### ISSUE THREAD

**Issue by BioinfoMonzino** [milaboratory/mixcr#572]
Please I would like to use IMGT library for the “analyze amplicon” workflow but appling “--align --library imgt” to the analyze amplicon command doesn’t work. The imgt .json is correctly placed in the working directory.
Thank you very much.

**Comment by PoslavskySV** [comment]
Did you try (ensure double quotes at right place):

```bash
mixcr analyze amplicon --align "--library imgt" ...
```

**Comment by BioinfoMonzino** [comment]
Yes it solved the issue.
Now, the worflow correctly works!
Thank you very much for your prompt reply.
