### ISSUE TITLE
analyze amplicon

### ISSUE THREAD

**Issue by BioinfoMonzino** [milaboratory/mixcr#574]
Hi,
I'm trying to run an 'analyze amplicon' worflow as follows:

```bash
mixcr analyze amplicon -s hsa --starting-material rna --5-end v-primers --3-end c-primers --adapters adapters-present --contig-assembly --receptor-type trb --assemble "-OassemblingFeatures="[VDJRegion]"" --export "-p fullImputed" --verbose file-name.fq analysis_name
```

I obtained the .vdjca, .clna, .contigs.clns files but the final clono table (.txt file) is empty (only the header is present) with no results displayed.
The problem seems related to the option --assemble "-OassemblingFeatures="[VDJRegion]"" because when I left it out from the script, I obtained the expected clono table .txt file.
How can I use the OassemblingFeatures option for gene features different from CDR3?
Thank you in advance.

**Comment by PoslavskySV** [comment]
Hi, please check this doc https://mixcr.readthedocs.io/en/master/assemble.html for the explanation of `assemblingFeatures` option. Basically, your reads should fully cover `VDJRegion` if you use "-OassemblingFeatures="[VDJRegion]". With [`contigAssembly`](https://mixcr.readthedocs.io/en/master/assembleContigs.html) you can leave `CDR3` as the assembling feature, and allow MiXCR to assemble as long contigs as possible from the data.

**Comment by BioinfoMonzino** [comment]
Ok, thank you for your prompt reply.
