### ISSUE TITLE
analyze amplicon report

### ISSUE THREAD

**Issue by BioinfoMonzino** [milaboratory/mixcr#575]
Hi,
i would like to better understand the meaning of the results written in the report file of the 'analyze amplicon' worflow. Specifically, I obtained '_Successfully aligned reads: 1964768 (86.88%)_' but '_Reads used in clonotypes, percent of total: 1017690 (45%)_' and '_Reads dropped due to failed mapping, percent of total: 881216 (38.97%)_'. I don't understand the possible reason for the high percentage of dropped reads and the relative low percentage of reads used in clonotype. 
The option I used were as follows:
`mixcr analyze amplicon -s hsa \
--starting-material rna \
--5-end no-v-primers \
--3-end c-primers \
--adapters no-adapters \
--assemble "-OseparateByV=true" \
--assemble "-OseparateByJ=true" \
--assemble "-OseparateByC=true" \
--contig-assembly \
--receptor-type trb \
--export "-p fullImputed" \
--verbose \
sample.fq \
analysis_name`

What could be the possible explanation about that?
Thank you.
Regards.

**Comment by BioinfoMonzino** [comment]
I understand that decreasing the ‘_badQualityThreshold_’ results in an improvement in both ‘_Reads used in clonotypes, percent of total_’ and ‘_Reads used in clonotypes before clustering_’. 
For example, the reduction from 20 (default) to 10 of the ‘_badQualityThreshold_’ increases the ‘_Reads used in clonotypes, percent of total_’ from 45% to 57.48%, with the concomitant (greater) increase of the total number of ‘_Final clonotype count_’ from 2815 to 11215.  
To find a good balance between the quality thereshold and the number of final clonotypes, please, may you tell me whether the ‘_badQualityThreshold_’ is the ‘Phred score’ or any other indicator of nucleotide quality?
Thanks again.

**Comment by PoslavskySV** [comment]
Hi, `badQualityThreshold` is the phred score.

**Comment by BioinfoMonzino** [comment]
Ok thank you!

**Comment by zznx** [comment]
Hi,
the reduction from 20 (default) to 10 of the ‘badQualityThreshold’ decreases the ‘Reads used in clonotypes, percent of total’ from (1776)1.36% to (1088)0.84%.
may you tell me why?
Thanks again.
