### ISSUE TITLE
Mixcr exportClones blank rows for nFeature

### ISSUE THREAD

**Issue by AbhinayaSr** [milaboratory/mixcr#576]
I used the Mixcr code to export the required fields from my .clns file and I get the nFeature sequences only for some of the clones, despite having the aaCDR3 region

<img width="1380" alt="image" src="https://user-images.githubusercontent.com/10031172/73091193-e58e7300-3ea7-11ea-8cfb-ab83242695cc.png">

Code I used: mixcr exportClones -count -vHit -dHit -jHit -vAlignment -dAlignment -jAlignment -aaFeature CDR3 -nFeature FR1+CDR1+FR2+CDR2+FR3+CDR3+FR4 File.clns Output.txt

**Comment by PoslavskySV** [comment]
Hi, 

when you specify
```
 -nFeature FR1+CDR1+FR2+CDR2+FR3+CDR3+FR4
```
you ask MiXCR to export full VDJRegion. Empty row means that clone does not contain VDJRegion.  If you want to export separately FR1, CDR1, FR2, CDR2, FR3, CDR3, FR4 you can use
```
 -nFeature FR1 -nFeature CDR1 -nFeature FR2 ...
```

**Comment by AbhinayaSr** [comment]
Thank you so much for tour reply
I’m a little confused about how there’s a V D and J gene hit and alignment but no nucleotide region? 
I specifically need the entire region concatenated so I used that particular format

**Comment by PoslavskySV** [comment]
Depending on your library type, you either should use VDJRegion as `assemblingFeature` (see [assemble](https://mixcr.readthedocs.io/en/master/assemble.html)) or try to assemble contigs (see [assembleContigs](https://mixcr.readthedocs.io/en/master/assembleContigs.html)).

**Comment by AbhinayaSr** [comment]
So my dataset is Bulk Ig seq and I followed each of these steps:
# align raw sequences
mixcr align --species ha --report report.txt input_R1.fq input_R2.fq alignments.vdjca

# assemble default CDR3 clonotypes
mixcr assemble --write-alignments --report report.txt alignments.vdjca clones.clna

# assemble full BCR receptors
mixcr assembleContigs --report report.txt clones.clna full_clones.clns

# export full BCR receptors
mixcr exportClones -count -vHit -dHit -jHit -vAlignment -dAlignment -jAlignment -aaFeature CDR3 -nFeature FR1+CDR1+FR2+CDR2+FR3+CDR3+FR4 File.clns Output.txt

**Comment by PoslavskySV** [comment]
So, the empty `nFeature` means that contig does not cover _full_ VDJRegion. You can figure out why this happens by inspecting raw alignments with `exportAlignmentsPretty` - this command will help you to understand how the data is covered. Also, you can use `-nFeatureImputed` instead of `-nFeature` - uncovered fragments will be imputed from germline, lowercase letters will be used to identify those pieces.
