### ISSUE TITLE
analyze with --threads option specified individually for align/assemble etc

### ISSUE THREAD

**Issue by PoslavskySV** [milaboratory/mixcr#579]
```bash
mixcr analyze shotgun --species mmu --starting-material rna --receptor-type tcr --export "-c TRA,TRB,TRG,TRD" --align "--threads 4" --assemble "--threads 4" r1.fq r2.fq an
```

fails with error
```
Expected parameter for option '--align' but found '-t 4'
```

**Comment by PoslavskySV** [comment]
Can't fix with picocli3.

**Comment by PoslavskySV** [comment]
Depends on #596

**Comment by vd-dragan21** [comment]
Hi! I'm getting the same output when adding --align "--threads 8" to the mixcr shotgun script:
Expected parameter for option '--align' but found '--threads 8'

Notice: the mixcr analyze shotgun works fine for me without threading (but it takes over 30h to run) & align command alone works also fine with threading when running separately. The error occurs only when trying to add threading as an additional parameter of align inside of a shotgun script.

**Comment by ilobon** [comment]
Hi, I get this same error.

Iam running analyze with --align "--threads 4" and I am using version 3.0.13
