### ISSUE TITLE
Question about export nMutations results returned

### ISSUE THREAD

**Issue by zilbert97** [milaboratory/mixcr#582]
Please forgive me in advance - i'm new to both GitHub and MiXCR, so if this isn't the right place for this kind of question (and if the questions are silly) please let me know!

Was wondering if you could help with the output in export for `-nMutations <gene_feature>`. In the resultant .txt from exportClones, I get a range of different things - sometimes nothing (just two tab-delimiters side by side), a dash ('-'), or something like SG7C. I'm assuming the SG7C means substitution of G for C, but the number (7) is throwing me somewhat. And is there a difference between nothing and the dash?

Also, how are mutations determined - I know it's relative to germline, does this mean it takes into account different alleles (so for example if in exportClones passing argument -nMutations VRegion, for an IGHV4-34 allele, determining mutations takes into account all allelic differences and doesn't return these as mutations)?

One last thing - in the docs under analyze ([https://mixcr.readthedocs.io/en/master/analyze.html#ref-analyze]), under "Analysis of targeted TCR/IG libraries" and "Analysis of non-enriched or random fragments" both are followed by "The command analyze amplicon [...]" which for the latter I think is a typo? Isn't it meant to be analyze shotgun?

**Comment by PoslavskySV** [comment]
Hi, 

Empty space means no mutations, '-' means that gene feature is not covered by the sequence, and about format of mutations see https://mixcr.readthedocs.io/en/master/appendix.html#alignment-and-mutations-encoding.

Regarding docs - you are right, thats a typo) Thanks!

**Comment by sdwien** [comment]
I have a related question:
I exported with exportClones `-nMutations VRegion` and `-vAlignment`, and then compared the mutation information in the output fields nMutationsVRegion and bestVAlignment[6] . I expected these two fields to be the same, but I see for the same clone e.g.:
`bestVAlignment 157|450|471|0|293|SG171CSG181ASA224CSA256GSG323A|1385.0`
and
`nMutationsVRegion -`

For another clone, I see:
`bestVAlignment 157|453|471|0|296|ST255AST312CST334CSA344GSC387TSA395TSA397CSC403TST438C|1336.0`
and
`nMutationsVRegion ST98A,ST155C,ST177C,SA187G,SC230T,SA238T,SA240C,SC246T,ST281C`

So these two fields are showing something completely different.
Is it maybe the case that VRegion does not refer to the same region for which the alignment stats are given? 
Which `<gene_feature>` would have to be used in the `-nMutations` option for these two fields to be the same?
For me it would be very helpful to know this, for a better understanding of the output.
Many thanks, best, Sophia

**Comment by PoslavskySV** [comment]
@sdwien sorry for the late reply. Could you please open a separate issue with your question? Also please add the commands you used to run MiXCR. Thanks!
