### ISSUE TITLE
J hits

### ISSUE THREAD

**Issue by LandiMi2** [milaboratory/mixcr#585]
@dbolotin and @PoslavskySV 
How do you adjust the Jhit score? The default is 5 but I want to adjust it to 2 to fit my dataset because 33% of my reads fail to align because of an absence of Jhits

**Comment by PoslavskySV** [comment]
Hi,

you can find how to do this here: https://mixcr.readthedocs.io/en/master/align.html

**Comment by LandiMi2** [comment]
I already read that part @PoslavskySV and tried to use -OmaxHit=3 to override it but still getting the same results. That's why I was asking.
