### ISSUE TITLE
Alignment report 

### ISSUE THREAD

**Issue by LandiMi2** [milaboratory/mixcr#587]
From the documentation example of an alignment report;
Successfully aligned, percent: 65.08%
Alignment failed because of absence of V hits: 4.26%
Alignment failed because of absence of J hits: 30.19%
Alignment failed because of low total score: 0.48%

@PoslavskySV What flag can you use to adjust J hits to get 95%-100% alignment? Is this possible? I have read the alignment part of your documentation and did multiple trials but I wasn't able to.

**Comment by LandiMi2** [comment]
especially when you are dealing with a species that only utilizes two J genes

**Comment by dbolotin** [comment]
I suggest manually aligning 20 reads from the fastq file (with [IGBlast](https://www.ncbi.nlm.nih.gov/igblast/) for example), to verify you actually have desired fraction of reads containing complete CDR3 sequences. Better skip first 10k reads from the beginning of the file because they are often low quality.

**Comment by LandiMi2** [comment]
@dbolotin I am using a simulated dataset (reads simulated by ART) that has undergone quality check. my question specifically is if you can adjust J hits parameter

**Comment by PoslavskySV** [comment]
Nevertheless,  could you try igblast to confirm that you should retrieve more that 30% ?

**Comment by LandiMi2** [comment]
@dbolotin & @PoslavskySV 
What I am doing is comparing IMGT, IgBlast and MiXCR ...For IgBlast and IMGT I get the same number of aligned reads. It's a challenge for me when I am doing my calculation of percentage hits and mishits for MiXCR because I get smaller denominator. To be fair with my comparison I would rather fix MiXCR to get 95-100% aligned reads and get a relatively close denominator. At the moment its only 64%

**Comment by LandiMi2** [comment]
"Alignment failed because of absence of J hits: 30.19%" have you guys tried to modify parameters to see if this percentage error can be reduced to increase on aligned reads? 

To my thinking, it is really smart of MiXCR to leave out some reads to increase accuracy.

**Comment by dbolotin** [comment]
Can you please post fastqs with 10000 reads from the dataset you are analyzing.

**Comment by LandiMi2** [comment]
https://drive.google.com/open?id=1fZJSArQGmo3ehryJdCkx5eM5VM_Wz1L7 
https://drive.google.com/open?id=1K9cufJkJ7xQofOhgDB7X5Q8Cl-sXgWZL

**Comment by LandiMi2** [comment]
@dbolotin  above comment is linked to read 1 and read 2.

**Comment by PoslavskySV** [comment]
@LandiMi2 which species? Could you also paste exact commands you used to align please

**Comment by PoslavskySV** [comment]
also can't download second file - access required

**Comment by LandiMi2** [comment]
@PoslavskySV  you can download it now. ( shared to bolotin.dmitriy@gmail.com). Specie -  "bovine"

**Comment by dbolotin** [comment]
Our test shows that MiXCR correctly discarded 30+% reads as not having CDR3 sequence. Please see a characteristic read (sixth read in file):

```
>>> Read ids: 5



                                                      FR1><CDR1              CDR1><FR2
                       P  S  Q  T  L  S  L  T  C  T  V  S  G  F  S  L  S  S  N  G  V  V  W  V  R  Q  A
           Quality    46666666776676777777767778776577787767877886777777877747777776776877777777777887
           Target0  0 CCCTCACAGACCCTCTCCCTCACCTGCACGGTCTCTGGATTCTCATTGAGCAGCAATGGTGTAGTCTGGGTCCGCCAGGC 79   Score
Bostau_IGHV1-30*01 39 ccctcacagaccctctccctcacctgcacggtctctggattctcattgagcagcaatggtgtagtctgggtccgccaggc 118  1183
Bostau_IGHV1-20*01 39 ccctcacagaccctctccctcacctgcacggtctctggattctcaCtgagcagcTatgCtgtagGctgggtccgccaggc 118  1071
Bostau_IGHV1-17*01 39 ccctcacagaccctctccctcacctgcacggtctctggattctcattgagcagcTatgCtgtaAGctgggtccgccaggc 118  1057


                                                  FR2><CDR2           CDR2><FR3
                         P  G  K  A  L  E  W  L  G  G  I  C  S  G  G  S  T  S  F  N  P  A  L  K  S  R
           Quality     88757777788887657777777777777677777777777777777777777778777777776777777777275767
           Target0  80 TCCAGGGAAGGCACTGGAGTGGCTCGGTGGTATATGCAGTGGTGGAAGCACAAGCTTTAACCCAGCCCTGAAATCCCGGC 159  Score
Bostau_IGHV1-30*01 119 tccagggaaggcGctggagtggctcggtggtatatgcagtggtggaagcacaagctttaacccagccctgaaatcccggc 198  1183
Bostau_IGHV1-20*01 119 tccagggaaggcGctggagtggctcggtggtataAgcagtggtggaagcacaTActAtaacccagccctgaaatcccggc 198  1071
Bostau_IGHV1-17*01 119 tccagggaaggcTctggagtggctTggtgAtataAgcagtggtggaagcacaGgctAtaacccagccctgaaatcccggc 198  1057


                                                                                                      F
                       L  S  I  T  K  D  N  S  K  S  Q  V  S  L  S  V  S  S  V  T  P  E  E  T  A  T  Y
           Quality     77777776577777777767777777777776377777777777767777776677767777777770777777757777
           Target0 160 TCAGCATCACCAAGGACAACTCCAAGAGCCAAGTCTCTCTGTCAGTGAGCAGCGTGACACCTGAGGAGACAGCCACATAC 239  Score
Bostau_IGHV1-30*01 199 tcagcatcaccaaggacaactccaagagccaagtctctctgtcagtgagcagcgtgacacctgaggaCacGgccacatac 278  1183
Bostau_IGHV1-20*01 199 tcagcatcaccaaggacaactccaagagccaagtctctctgtcagtgagcagcgtgacacctgaggaCacGgccacatac 278  1071
Bostau_IGHV1-17*01 199 tcagcatcaccaaggacaactccaagagccaagtctctctgtcagtgagcagcgtgacacctgaggaCacGgccacatac 278  1057

                          V>
                       R3><CDR3
                        Y  C  M  H  S  I  V  V  L  M  V  I  I  M  V  M  V  V  V  M  V  M  V  V  V  V  M
           Quality     67767777776517777776677777777777776717777777877777767272777777477757182777278772
           Target0 240 TACTGCATGCATTCGATAGTTGTCCTGATGGTTATAATTATGGTTATGGTTGTGGTTATGGTTATGGTTGTAGTGGTTAT 319  Score
Bostau_IGHV1-30*01 279 tactg                                                                            283  1183
Bostau_IGHV1-20*01 279 tactg                                                                            283  1071
Bostau_IGHV1-17*01 279 tactg                                                                            283  1057



              I  V  V  V  M  V  V  M  V  V  M  V  V  M  V  I  V  V  I  A  I  V  I  R _
Quality     87877771767877777677776577887667778747877777728787777767777777776766662566
Target0 320 GATTGTTGTGGTTATGGTGGTTATGGTGGTTATGGTGGTTATGGTTATAGTAGTTATAGCTATAGTTATACGTA 393  Score
```

Part of the read on the 3' end from detected V gene is a very long D gene:
```
>seq
CATGCATTCGATAGTTGTCCTGATGGTTATAATTATGGTTATGGTTGTGGTTATGGTTATGGTTGTAGTGGTTATGATTGTTGTGGTTATGGTGGTTATGGTGGTTATGGTGGTTATGGTTATAGTAGTTATAGCTATAGTTATACGTA
```
(see [BLAST result](https://blast.ncbi.nlm.nih.gov/Blast.cgi?CMD=Get&RID=793DCCSR01R))

MiXCR aligns D genes only after V/J junction position is determined, and hence there is no J gene,  MiXCR can't produce successful alignment here. The sequence anyway has no complete CDR3 sequence.

The results on the top were obtained with:
```
 mixcr align -f -n 10000 -OallowPartialAlignments=true -OallowNoCDR3PartAlignments=true  --library imgt --species bovine simulated_reads1.fq simulated_reads2.fq test.vdjca
mixcr exportAlignmentsPretty -n 10 test.vdjca
```

If you have any further questions, in the following messages please support them with enough information for us to understand your analysis goals and data origins, and, most importantly, I suggest doing your research on the problem before asking for support from software developers.

**Comment by LandiMi2** [comment]
Actually the answer to my question was these below parameters/flags
that prevent MiXCR from discarding overlapped and not aligned reads.
Now running with this parameters I get 98% aligned something I wanted.

-OallowPartialAlignments=true -OallowNoCDR3PartAlignments=true

Apologies if my questions were too much. I am a masters student and
these kind of analysis is new to me, and so everyday is a learning
experience. Thank you again.

Michael
