### ISSUE TITLE
Wether the .vdjca file are able to be split?

### ISSUE THREAD

**Issue by decenwang** [milaboratory/mixcr#590]
Hi There,

Cause my laptop does not have a large RAM, it is impossible to run my command with a big file (>Gb). I wanna know can I split the .vdjca file into small one to run again, and then merge the the exported files again. If yes,  how could I do it? Anyway, I don't think it is a good idea to split the R1* and R2* file into small ones. Looking forward to your reply! Many thanks!

Decen

**Comment by PoslavskySV** [comment]
Hi,

currently there is no such possibility. Anyway, I don't think this is good idea to split vdjca file and assemble clones separately - obviously, it will give wrong picture.
