### ISSUE TITLE
J alignment

### ISSUE THREAD

**Issue by TimFugmann** [milaboratory/mixcr#592]
I don't understand how MiXCR calculates/displays TCR J alignments: Vor V it is clear, nucleotide 0-3 is atg, which is however not displayed in the IMGT Json file. For J, I don't get it and can't find a rule: in the Json file, the J sequence starts with 0, but in the pretty aligmnet, the J genes start somewhere between 26 and 30 or so, without any obvious reference to the J gene. Can you please comment on how the J gene alignment is calculated?

Example:
Json file code:
```
{
    "uri": "file://human_J_TRA.fasta#TRAJ20*01",
    "range": {
      "from": 0,
      "to": 57
    },
    "sequence": "GTTCTAACGACTACAAGCTCAGCTTTGGAGCCGGAACCACAGTAACTGTAAGAGCAA"
  }
```
And example from the pretty alignment:
```
                                                                       FR3><CDR3      V> <J         
                S  K  Y  I  S  L  F  I  R  D  S  Q  P  S  D  S  A  T  Y  L  C  A  M  S  G  D  Y     
    Quality     77777777777777777577777777777777777777777777777777777777777777777777777777777777    
    Target1  80 GCAAGTATATCTCCTTGTTCATCAGAGACTCACAGCCCAGTGATTCAGCCACCTACCTCTGTGCAATGAGCGGCGACTAC 159  Score
TRAV12-3*01 205 gcaagtatatctccttgttcatcagagactcacagcccagtgattcagccacctacctctgtgcaatgagcg         276  760
TRAV12-3*02 205 gcaagtatatctccttgttcatcagagactcacagcccagtgattcagccacctacctctgtgcaatgagcg         276  760
  TRAJ20*01  27                                                                          cgactac 33   250

                     CDR3><FR4                       FR4>                                         
               K  L  S  F  G  A  G  T  T  V  T  V  R  A _                                         
  Quality     77777777777777777777777777777777777777777777577777777777777777777777777777777777    
  Target1 160 AAGCTCAGCTTTGGAGCCGGAACCACAGTAACTGTAAGAGCAAATATCCAGAACCCTGACCCTGCCGTGTACCAGCTGAG 239  Score
TRAJ20*01  34 aagctcagctttggagccggaaccacagtaactgtaagagcaa                                      76   250
```

**Comment by PoslavskySV** [comment]
Hi,

the first 26 letters were trimmed from J gene during TCR rearrangement, so the alignment of J gene covers letters from 27 to 76 in germline.

**Comment by TimFugmann** [comment]
Hi,
Thanks for the reply. Unfortunately, I cannot find any sequence on IMGT which demonstrates that there are additional 20 nucleotides beyond the sequence I copied from the Json file (which is derived from IMGT reference sequences. If you check http://www.imgt.org/ligmdb/view?id=IMGT000024, the only sequence I see for TRAJ20*01 is "GTTCTAACGACTACAAGCTCAGCTTTGGAGCCGGAACCACAGTAACTGTAAGAGCAA". Can you please indicate where the trimmed nucleotides are?
Thanks
Tim

**Comment by dbolotin** [comment]
J alignment is local on the left side (like in Smith–Waterman algorithm; it is also called floating left bound in MiXCR parameters), to account for the J gene trimming in VDJ recombination. Can you please describe what you expect to see instead of the alignments you posted?

**Comment by TimFugmann** [comment]
Hi, 
I would expect at least one pointer to the sequence start, i.e. TRAJ*20 alignment to start with 8, as the C of CGACT is the 8th nucleotide, not nucleotide nr. 27. In the AllJAlignments, no information is given with which nucleotide the alignment starts except 27. And since the 19 remaining nucleotides are no-where in the databases, I don't see how to identify that the alignment starts with CGACT. Do you always add a fixed number to start of J or how does MiXCR end up with 27?
Thanks
Tim

**Comment by PoslavskySV** [comment]
Oh, sorry, now I understand your question. The thing is that MIXCR takes into account P segments by adding 20 RC nucleotides on V end and J begin. So it aligns target sequence against [`JRegionWithP`](https://mixcr.readthedocs.io/en/master/geneFeatures.html)  which is `= {JBegin(20):JBegin} + {JBegin:FR4End}`, not just `{JBegin:FR4End}`. This is why the numbers stars from 27 (20 + 7).
