### ISSUE TITLE
SHM rate

### ISSUE THREAD

**Issue by gknit** [milaboratory/mixcr#593]
Hi all,

First of all thank you for the excessive software packages you are providing!

I performed RNA-based full length BCR sequencing and I've assembled full contigs using the migec/mixcr software packages.
Now I would like to answer the question whether the plasma cells I'm looking at went through the germinal center and what the mutation rate in the whole VDJ region is. 
I do find the outputs %identity with best V,D,J hits. But what I need is a mutation frequency over the whole VDJ region, x of y bases mutated from the best hit. If that cannot be a direct output, can I output the lengths of the best V, D and J hits?

It would be great if you could help me out.

Best!
Gero

**Comment by PoslavskySV** [comment]
Hi,

currently there is no such possibility. So, in order to get what you want, you have to process the output of mixcr with some other script.

**Comment by PoslavskySV** [comment]
Uh, I forgot that there is one option in MiXCR which may help you. You can use 
```
mixcr exportClones -lengthOf [gene_feature] ...
```
to export length of specific gene feature

**Comment by suntaosimon** [comment]
Dose this kind of information of IGH exportClones data "|SA444G|"  mean SHM or just a regular mutation? 
Thanks.
