### ISSUE TITLE
floatingLeftBound and floatingRightBound

### ISSUE THREAD

**Issue by fjptwenger** [milaboratory/mixcr#595]
Can you give an example of the difference between true and false for these two parameters（floatingLeftBound and floatingRightBound）？

**Comment by dbolotin** [comment]
- `floatingLeftBound=true` means alignment is [local](https://en.wikipedia.org/wiki/Sequence_alignment#Global_and_local_alignments) on the left side of the sequence, and alignment will be terminated if leftover on the left can't be aligned to increase total alignment score,
- `false` means it is global, and alignment will be build until the end of either reference or query sequence, even if it is not beneficial in terms of total alignment score. Anyway alignments always maximize total alignment score aside from this constraint.

Actual algorithms uses k-mer-based pre-alignment with dynamic-programming-based second pass.
