### ISSUE TITLE
about C region format in mixcr database

### ISSUE THREAD

**Issue by fjptwenger** [milaboratory/mixcr#597]
I am curious how the **sequence** or other format of the human C region of the mixcr database exists? I found that mixcr provides c region  parameters, but I tried to view the c region sequence from the data but empty result.

I download the sequence of C from IMGT,for example :
```
>J00241|IGKC*01|Homo sapiens|F|C-REGION|c,334..653|321 nt|1|+1| | | |321+0=321| | |
cgaactgtggctgcaccatctgtcttcatcttcccgccatctgatgagcagttgaaatct
ggaactgcctctgttgtgtgcctgctgaataacttctatcccagagaggccaaagtacag
tggaaggtggataacgccctccaatcgggtaactcccaggagagtgtcacagagcaggac
agcaaggacagcacctacagcctcagcagcaccctgacgctgagcaaagcagactacgag
aaacacaaagtctacgcctgcgaagtcacccatcagggcctgagctcgcccgtcacaaag
agcttcaacaggggagagtgt
....
```
but either use **IGKC** or part sequence **cgaactgtggctgcaccatctgtcttcatcttcccgccatctgatgagcagttgaaatct** , `grep` return empty ;

if i use IGHD.fasta of human ,for example:
```
>X97051|IGHD1-1*01|Homo sapiens|F|D-REGION|33714..33730|17 nt|1| | | | |17+0=17| | |
ggtacaactggaacgac
....
```
use 'IGHD'  I can find the sequence and anchorPoints.

![image](https://user-images.githubusercontent.com/25705121/79085982-1aa2b700-7d6d-11ea-93e7-af0c3b8118d2.png)

![image](https://user-images.githubusercontent.com/25705121/79085900-ce577700-7d6c-11ea-8de3-19aac4b39f77.png)

**Comment by dbolotin** [comment]
The library imported from IMGT does not have C region sequences. Built-in library has the following sequence for `IGKC`:
```
>IGKC*00|F|taxonId=9606
GAACTGTGGCTGCACCATCTGTCTTCATCTTCCCGCCATCTGATGAGCAGTTGAAATCTGGAACTGCCTCTGTTG
TGTGCCTGCTGAATAACTTCTATCCCAGAGAGGCCAAAGTACAGTGGAAGGTGGATAACGCCCTCCAATCGGGTA
ACTCCCAGGAGAGTGTCACAGAGCAGGACAGCAAGGACAGCACCTACAGCCTCAGCAGCACCCTGACGCTGAGCA
AAGCAGACTACGAGAAACACAAAGTCTACGCCTGCGAAGTCACCCATCAGGGCCTGAGCTCGCCCGTCACAAAGA
GCTTCAACAGGGGAGAGTGTTAG
```

Can be exported with [repseqio](https://github.com/repseqio/repseqio) util from the default/built-in library (can be downloaded from [here](https://github.com/repseqio/library/releases/tag/v1.6)):
```
wget https://github.com/repseqio/library/releases/download/v1.6/repseqio.v1.6.json.gz
repseqio fasta -s hs -g CExon1 -n 'IGKC.*' repseqio.v1.6.json.gz
```
