### ISSUE TITLE
how to get the full sequence of the major clone?

### ISSUE THREAD

**Issue by nkwendy** [milaboratory/mixcr#599]
I am very new to MIXCR and coding. I have successfully used MIXCR to align and assemble my paired-end IGH NGS files, but the problem is there were too much sequences generated. For example, there is one case with 17 clones identified after assembling (targeting CDR3), but I want to get the full IGH rearranged sequence of the top clone. I used the target CDR3 sequence of the top clone to looked back of all the sequences from alignment, but found at least 500 different sequences with the same CDR3 sequence.

My samples are B-cell lymphomas, which we expect clonal IGH rearrangement. Due to PCR/sequencing errors, there may be some difference generated. But how can I figure out the most real full IGH sequence of the major clone then?

Thanks so much for the help!

**Comment by PoslavskySV** [comment]
Hi,

you can use `assembleContigs` action to assemble full length sequences. Please, look [this section in docs](https://mixcr.readthedocs.io/en/master/assembleContigs.html).

**Comment by nkwendy** [comment]
> Hi,
> 
> you can use `assembleContigs` action to assemble full length sequences. Please, look [this section in docs](https://mixcr.readthedocs.io/en/master/assembleContigs.html).

Thanks a lot! this is very convenient and helpful!
