### ISSUE TITLE
Obtaining TCR clones from total tissue RNASeq?

### ISSUE THREAD

**Issue by ampmartinez** [milaboratory/mixcr#601]
Hello,
I am running RNA-Seq samples from total tissue (lung), not enriched in T fraction, with default options (mixcr analyze shotgun \  --species mmu \ --starting-material rna \ --only-productive \ Sample.fastq TCRAnalysis), and I have obtained really low number of TCR clones.

I am aware that the inputs are not as good as possible because samples were not T cell enriched, but I was wondering if you have previously tried to obtain TCR information from total tissue and if you recommended any workflow to obtain better results, as using other non-default parameters or special previous trimming ...

Thank you so much in advance.

**Comment by dbolotin** [comment]
Hi,

It is pretty common to have very low TCR yield from the tissue RNA-Seq data, basically, there are too few target reads.

Paired-end datasets on average gives significantly higher output (judging by the command your data is single-end). Also, the longer the read length the higher the output.

`mixcr analyze shotgun` - is the recommended way for analysis of RNASeq data.

Please see our [original paper](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC6169298/).

Very rough estimation (see [supplementary materials](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC6169298/bin/NIHMS976350-supplement-Supplementary.pdf)) is the following:
*about 90–100 TRB CDR3 reads per million unique reads for the pure T-cell population*
multiply this number by TCR content for the tissue you are analyzing.
