### ISSUE TITLE
exportClones failed in distingush between TRD and TRA

### ISSUE THREAD

**Issue by StayHungryStayFool** [milaboratory/mixcr#602]
I export clonnes code : 
 mixcr exportClones -c TRD -count -vGene -jGene  -aaFeature CDR3 TRD477KOTHYLIB.clns TRD477KOTHYLIB.TRD.clones.txt
but i find many TRAV gene in result, such as TRAV10D .
By the way, how does Mixcr export do with parameter (-c TRD) when J gene belong to TRD but V gene belong to TRA .

**Comment by PoslavskySV** [comment]
please, look this https://github.com/milaboratory/mixcr/issues/541
