### ISSUE TITLE
Invalid maximum heap size: -Xmx4g. The specified size exceeds the maximum representable size.

### ISSUE THREAD

**Issue by Narges2020** [milaboratory/mixcr#603]
Hi guys! I is the size of RAM matter for installation? Mine is 8Gb, can I still install it? I just download and unzip the file as explained here: https://mixcr.readthedocs.io/en/latest/install.html but when I write the installation in my command prompt, it says (screen shot of the error is also attached
![screen shot](https://user-images.githubusercontent.com/65049610/81794054-7b5b1600-950a-11ea-9869-4a8465cad0d0.png)
):

 C:\Users\narge>java -Xmx4g -Xms3g -jar C:\Users\narge\Desktop\mixcr-3.0.13\mixcr-3.0.13\mixcr.jar
Invalid maximum heap size: -Xmx4g
The specified size exceeds the maximum representable size.
Error: Could not create the Java Virtual Machine.
Error: A fatal exception has occurred. Program will exit.

have you guys also facing the same problem? 
Any advice would be highly appreciated!

**Comment by PoslavskySV** [comment]
Hi! It seems that you have 32-bit Java Virtual Machine. You can check it with 
```bash
java -version 
```
