### ISSUE TITLE
Extraction and interpretation of Ig class information

### ISSUE THREAD

**Issue by yyoshiaki** [milaboratory/mixcr#604]
Hi, 

I'm trying to extract information about the Ig class for each clone using the output of mixcr analyze command for a bulk RNAseq. I think the `allCHitsWithScore` column in `*.clonotypes.IGH.txt` represents that, but I could not find the description on the columns. Could you explain to me what is the Score? In addition, there are clones with several Ig classes like clone 109 below, and can I know the proportion of Ig class in it? 

|  cloneId  |  cloneCount  | ... | allCHitsWithScore|
| ---- | ---- | ---- | ---- |
|  2 |  32.0  | ... | IGHG1*00(108.5)  |
|  16  |  5.0  | ... | IGHM*00(122) |
| 109 | 2.0 | ... | IGHG2*00(232.5),IGHG4*00(224.5) |

Our goal is to compare the proportion of Ig class among groups and to do that I need the information. 
Best regards,
Yoshiaki.

**Comment by PoslavskySV** [comment]
Hi, 

score is the alignment score. `allCHitsWithScore` contains all C genes that were successfully aligned against target sequence with corresponding alignment scores (in parentheses). In most cases you need only the top one. See here for possible export options: https://mixcr.readthedocs.io/en/master/export.html

Let me know if it helps.

With best wishes,
Stanislav

**Comment by yyoshiaki** [comment]
Thank you for your quick response! I understood!

**Comment by anabbi** [comment]
Hello,

My questions are somehow related to this issue. I would like to get all IGH CDR3s separated by their isotype. I understand I could use `separateByC` parameter in assembly step, but all I have are conventional mixcr clones.txt file (from unselected RNAseq data). Do you think it is fair to manually separate them? In the example above, is the third CDR3 supported by both IGHG2 and IGHG4 and okay to separate them accordingly? Does `separateByC` parameter take anything else into account?

My only concern with this approach is scores, could you comment on what would be considered as "good enough" alignment score when processing RNAseq data? Again in the example provided above, is the IGHG1 call for the first clone reliable with score = 108.5?

Thank you
