### ISSUE TITLE
What's the --species for Rabbit IGH?

### ISSUE THREAD

**Issue by suntaosimon** [milaboratory/mixcr#605]
-s, --species <species>   Species (organism), as specified in library file or taxon id.
                            Possible values: hs, HomoSapiens, musmusculus, mmu, hsa, 9606, 10090 etc.

what's the name for rabbit?

Thanks!

**Comment by PoslavskySV** [comment]
There is no built-in reference for rabbit. You can use IMGT library for that, see https://mixcr.readthedocs.io/en/master/importSegments.html
