### ISSUE TITLE
parameter -c for exportAlignments does not work (MiXCR v3.0.13)

### ISSUE THREAD

**Issue by Blowfish82** [milaboratory/mixcr#606]
Hi, 
I aligned paired fastq files:
`~/bin/mixcr align --library imgt --species hsa -r IGH-File_R1_001.fastq.gz IGH-File_R2_001.fastq.gz IGH-File.vdjca`
and then exported the alignments:
`~/bin/mixcr exportAlignments --force-overwrite --chains IGH -vHit -dHit -jHit -vGene -dGene -jGene -vFamily -dFamily -jFamily -vHitScore -dHitScore -jHitScore -nFeature CDR3 -aaFeature CDR3 -lengthOf CDR3 -readIds IGH-File.vdjca IGH-File.mixcr_annotation.txt`

I noticed some TRB assignments in the resulting file. I was wondering, because
1. the command -c IGH should restrict to only IGH genes
2. in the further processed clone.txt file, these TRB files are properly converted to IGH genes with the -c IGH parameter.

So the -c (--chains) seems not to work for exportAlignments.

I´m very thankful for any help or suggestions.
Best!

![image](https://user-images.githubusercontent.com/48549897/83638822-0bd8c380-a5aa-11ea-86f6-e942d5817ffe.png)

**Comment by PoslavskySV** [comment]
Hi,

please try [MiXCRv4](https://github.com/milaboratory/mixcr/releases/tag/v4.0.0), it should be fixed.

Best, 
Stan
