### ISSUE TITLE
long-time lasting at one step : writing alignments:0%

### ISSUE THREAD

**Issue by decenwang** [milaboratory/mixcr#607]
Hi All,

When I run the command lines, the program doesn't go forward at the step: writing alignments: 0%, which can remain more than hours. I found it generates a file with suffix **.clna.presorted**. and this file is massive, more than **10 Gb**. For each one, sequence file is around 1 Gb with PE150. I would like to know if it is normal? My workstation owns 6 cores and 256 RAM. Thanks a lot!

Best,

Decen

**Comment by dbolotin** [comment]
Hi Decen,

This one will be fixed soon, and will hopefully work much faster.

Anyway thanks for reporting!

**Comment by decenwang** [comment]
> Hi Decen, This one will be fixed soon, and will hopefully work much faster. Anyway thanks for reporting! The file is needed as a temporary storage to form a clna file where all alignments are collated by the clone they were assigned to. All the best, Dmitry.

Thanks  a lot, Dr. Bolotin,

Excuse me, I forgot one thing, I am using the mixcr 3.0.12, not the latest one. Cause you know, it will take more than one week, so I may not use the latest one for following analysis. Everything for me is in a hurry. Many thanks!

Cheers,

Decen
