### ISSUE TITLE
How to calculate score

### ISSUE THREAD

**Issue by amufaamo** [milaboratory/mixcr#612]
I got the result "TRAV11*00(2332.5)", and I understand 2332.5 is score. But I wanna know how does mixcr calculate the score. I thought mixcr calculate score like this
match = 5, mismatch = -9, gapPenalty = -12. 

But our target sequence is 337 bp, so even if it is 100% match, the score will be 5 x 337 = 1685. 

Could you tell me how does it calculate the score?

**Comment by PoslavskySV** [comment]
Do you use kAligner2?

**Comment by amufaamo** [comment]
Sorry, I'm not familiar with MIXCR. I just used `mixcr analyze` and got output.

**Comment by dbolotin** [comment]
Please post full command you use for analysis.

All actual parameters are listed here:
https://github.com/milaboratory/mixcr/blob/develop/src/main/resources/parameters/vdjcaligner_parameters.json
Depending on the analysis mode `default` or `kAligner2` parameter sets are used.

**Comment by amufaamo** [comment]
Thanks so much! It solved. I was running with kAligner2, and score exactly matched with kAligner2 calculation.
