### ISSUE TITLE
Running MiXCR using custom database

### ISSUE THREAD

**Issue by Bharat-Dekoskylab** [milaboratory/mixcr#613]
## Checklist before submitting the issue:

 - [X] The issue is strongly related to the MiXCR software
 - [X] The issue can be reproduced with [the most recent version](https://github.com/milaboratory/mixcr/releases) of MiXCR
 - [X] There is no answer to the question in the [official documentation](http://mixcr.readthedocs.io/) and there is no duplicate issue in the [bug tracker](https://github.com/milaboratory/mixcr/issues?utf8=✓&q=)  
 - [ ] Inspection of raw alignments with [exportAlignmentsPretty](http://mixcr.readthedocs.io/en/master/export.html#exporting-well-formatted-alignments-for-manual-inspection) shows that data has the expected architecture, and sample preparation artefacts are not the reason of the problem (if this is the matter of the issue)

## Expected Result

I am trying to run MiXCR using a custom database consisting of rhesus and human IG genes. To make the custom database, I downloaded the genes from IMGT and changed their names (For eg: IGH-V1*01 to IGH_human-V1*01, IGH_rhesus-V1*01). I used the repseqio fromPaddedFasta command to make the libraries. I obtained the anchor points from the rules folder (came with imgt libraries folder from MiXCR) for the respective organism. I merged IGH v,d,j libraries using merge command and then compiled the merged database. Everything went well up till then and when I ran the align command, I am not getting any alignments because of the absence of J genes hits.

Could you please help me solve this issue?

## Actual Result
Here's the alignment result. 
Reference library: custom_lib_imgt_IGH_compiled:1001:e8667541ea124f57b0e2e3720b499f8c
WARNING: 11 functional genes were excluded, re-run with --verbose option to see the list of excluded genes and exclusion reason.
Alignment: 100%
============= Report ==============
Analysis time: 496.00ms
Total sequencing reads: 25
Successfully aligned reads: 0 (0%)
Alignment failed because of absence of J hits: 25 (100%)
Overlapped: 0 (0%)
Overlapped and aligned: 0 (0%)
Alignment-aided overlaps: 0 (?%)
Overlapped and not aligned: 0 (0%)

Here's how the custom database library looks:
[ {
  "taxonId": 1001,
  "speciesNames": [ "rhe_hu" ],
  "genes": [ {
    "baseSequence": "file://imgt_lib_custom_d.json.fasta#IGH_Human_D1-1*01",
    "name": "IGH_Human_D1-1*01",
    "geneType": "D",
    "isFunctional": true,
    "chains": [ "IGHD" ],
    "meta": {

## Exact MiXCR commands 

repseqio fromPaddedFasta --species-name rhe_hu -t 1001 -c IGHV -j 3 -n 1 -g V -PFR1Begin=0 -PCDR1Begin=78 -PFR2Begin=114 -PCDR2Begin=165 -PFR3Begin=195 -PCDR3Begin=309 -PVEnd=-1 custom_IGHV_padded.fasta imgt_lib_custom_v.json.fasta imgt_lib_custom_v.json

 repseqio fromPaddedFasta -t 1001 -c IGHJ -j 3 -n 1 -g J -PJBegin=0 -PFR4Begin=-31 -LFR4Begin='\[WF\]\(G\.G\)'  -PFR4End=-1 custom_IGHJ_padded.fasta imgt_lib_custom_j.json.fasta imgt_lib_custom_j.json

 repseqio fromPaddedFasta -t 1001 -c IGHD -j 3 -n 1 -g D -PDBegin=0 -PDEnd=-1 custom_IGHD_padded.fasta imgt_lib_custom_d.json.fasta imgt_lib_custom_d.json

repseqio merge imgt_lib_custom_v.json imgt_lib_custom_d.json imgt_lib_custom_j.json custom_lib_imgt_IGH.json

repseqio compile custom_lib_imgt_IGH.json custom_lib_imgt_IGH_compiled.json.gz

mixcr align --library custom_lib_imgt_IGH_compiled  -f -g -s rhe_hu -r VH_alignmentReport.txt -OvParameters.geneFeatureToAlign=VRegion R1_001.fastq  VH_alignment.vdjca

## MiXCR report files 

*Paste here content of the report files produced by MiXCR (enclose it with triple ```` ``` ````  for better formatting)*

**Comment by PoslavskySV** [comment]
Hi,

if you still need assistance, please contact us at support@milaboratories.com

Best,
Stan
