### ISSUE TITLE
Ig isotypes

### ISSUE THREAD

**Issue by anabbi** [milaboratory/mixcr#616]
Hello,

I initially wrote this on a closed issue. You may not have seen it so I thought I open a new issue. Please see my message below. Thank you.

My questions are somehow related to this issue. I would like to get all IGH CDR3s separated by their isotype. I understand I could use `separateByC` parameter in assembly step, but all I have are conventional mixcr clones.txt file (from unselected RNAseq data). Do you think it is fair to manually separate them? In the example above, is the third CDR3 supported by both IGHG2 and IGHG4 and okay to separate them accordingly? Does `separateByC` parameter take anything else into account?

My only concern with this approach is scores, could you comment on what would be considered as "good enough" alignment score when processing RNAseq data? Again in the example provided above, is the IGHG1 call for the first clone reliable with score = 108.5?

Thank you

_Originally posted by @anabbi in https://github.com/milaboratory/mixcr/issues/604#issuecomment-653979889_

**Comment by anabbi** [comment]
Any comment would be helpful. Thank you

**Comment by anabbi** [comment]
Hello, thank you for your reply. 

I don't want to use `separatebyC` as this will require me to rerun all my samples. Instead, I want to take CDR3s with multiple C gene calls and separate them based on their C gene into new rows. Here is an example where I have one CDR3 with multiple C genes.

cloneId | cloneCount | cloneFraction | clonalSequence | clonalSequenceQuality | allVHitsWithScore | allDHitsWithScore | allJHitsWithScore | allCHitsWithScore
-- | -- | -- | -- | -- | -- | -- | -- | --
475 | 20 | 0.01515152 | TGTGCGAGACACATGGACGTCTGG | GGGGGGGGGGGGGGGGGGGGGGGG | IGHV3-11*00(165),IGHV3-53*00(165) |   | IGHJ6*00(85) | IGHG3*00(235),IGHG4*00(235),IGHG2*00(219)

I would take the highest alignment score for C gene. Since two C genes have the same score, I would separate this CDR3 into two entries (same CDR3 but different C gene):

cloneId | cloneCount | cloneFraction | clonalSequence | clonalSequenceQuality | allVHitsWithScore | allDHitsWithScore | allJHitsWithScore | allCHitsWithScore
-- | -- | -- | -- | -- | -- | -- | -- | --
475 | 20 | 0.01515152 | TGTGCGAGACACATGGACGTCTGG | GGGGGGGGGGGGGGGGGGGGGGGG | IGHV3-11*00(165),IGHV3-53*00(165) |   | IGHJ6*00(85) | IGHG3*00(235)
-- | -- | -- | -- | -- | -- | -- | -- | --
475 | 20 | 0.01515152 | TGTGCGAGACACATGGACGTCTGG | GGGGGGGGGGGGGGGGGGGGGGGG | IGHV3-11*00(165),IGHV3-53*00(165) |   | IGHJ6*00(85) | IGHG4*00(235)

Do you think this would make sense to do? The purpose behind this analysis is to find immunoglobulin class switch, where a B-cell with one VDJ recombination can express different isotypes (eg, IGG3, IGG1) during its activation.

thanks for your help

**Comment by PoslavskySV** [comment]
Hi,

if you still have this issue, please contact us at support@milaboratories.com

Best,
Stan
