### ISSUE TITLE
How to extract full clonal sequences for IMGT?

### ISSUE THREAD

**Issue by ElArkk** [milaboratory/mixcr#620]
Hi,

I'm using mixcr's `analyze` command for my IgSeq data (2x 300 bp MiSeq). As I also need information on nucleotide additions in each clone, I was thinking about using the error-corrected and clustered clonal output sequences from mixcr as input for IMGT's HighV-QUEST. Is there a way of getting for each clone the full nucleotide sequence spanning the VDJ region? I tried using the `--contig-assembly` flag, however I think this does not provide me with a single column containing the full sequence. Can I simply merge the sequence chunks in specific columns to get the full sequence? 

This is the full command I am using right now:

```bash
mixcr analyze amplicon -s mmu --starting-material RNA --5-end v-primers \ 
--3-end c-primers --adapters adapters-present --receptor-type Igh --only-productive \
 --contig-assembly --export "-p fullImputed" R1.fastq.gz R2.fastq.gz output_file
```

Thanks!

**Comment by PoslavskySV** [comment]
Hi,

sorry for delay. Your command is correct; you can then use the following command to export VDJ region with imputation:

```
mixcr export -nFeatureImputed VDJRegion ... clones.clns vdj_regions.txt
```
