### ISSUE TITLE
Running Mixcr with unique molecular barcoded data

### ISSUE THREAD

**Issue by arnavaz** [milaboratory/mixcr#625]
Hi MIXCR team,
We have a series of fastqs containing Unique Molecular Identifiers (UMIs). These fastqs are from hybrid-capturing of CDR3 regions of TCR (genomic DNA).
Since troubleshooting of the pipelines related to UMI-incorporated reads is not fully done yet, we have, for now, decided to remove the UMIs from the fastqs and then feed fastqs to the MIXCR for TCR analysis.
UMIs are therefore removed from the fastq reads and are tagged to the header of each line.
However, after feeding the fastqs with removed UMIs to MIXCR, the number of TRA and TRB clonotypes that we get are significantly decreased compared to the samples we’ve been doing MIXCR on before (samples that didn’t have UMIs and therefore fastqs were fed to MIXCR with no changes).
After doing a quick QC, we noticed that for fastqs with removed UMIs, the percentage of “Reads dropped due to the lack of a clone sequence” has significantly increased (in some cases pretty close to 100%).
We are therefore trying to find a reason for this. There was a similar question on your github and you’ve mentioned that it’s either library prep or data.
If we assume that library prep have been done properly, one of the problem with the data could be the removal of UMIs from the fastqs.
In the attachment 

you can see the similar lines of fastqs, before and after UMI removal. As you can see, UMIs are added to the headers and change them. Is there any chance that this is affecting the mixcr output? Does MIXCR read the headers?
[mixcr_example_UMI.txt](https://github.com/milaboratory/mixcr/files/5386261/mixcr_example_UMI.txt)

**Comment by PoslavskySV** [comment]
Hi,

could you please paste version of MiXCR (mixcr -v), exact commands you used for running MiXCR, and some typical problematic alignment report (for non truncated and for UMI-truncated data) produced by MiXCR.

**Comment by arnavaz** [comment]
Below are the mixcr commands we used in the first attachment.
The following files are the stats for pre and post UMI extraction for the Oracle data.
The Inspire data did not incorporate UMIs.
Please note that the fraction of "clones dropped due to lack of sequence" is higher in data with UMIs compared to Inspire data that did not have UMIs. We are wondering if this is a technical issue in our pipeline or something that happened in the lab.

[mixcr_version_commands.txt](https://github.com/milaboratory/mixcr/files/5386532/mixcr_version_commands.txt)

[oracle_cfdna_post_UMI_extraction_align_stats.txt](https://github.com/milaboratory/mixcr/files/5393019/oracle_cfdna_post_UMI_extraction_align_stats.txt)
[oracle_cfdna_post_UMI_extraction_assemble_stats.txt](https://github.com/milaboratory/mixcr/files/5393020/oracle_cfdna_post_UMI_extraction_assemble_stats.txt)
[oracle_cfdna_pre_UMI_extraction_align_stats.txt](https://github.com/milaboratory/mixcr/files/5393021/oracle_cfdna_pre_UMI_extraction_align_stats.txt)
[oracle_cfdna_pre_UMI_extraction_assemble_stats.txt](https://github.com/milaboratory/mixcr/files/5393022/oracle_cfdna_pre_UMI_extraction_assemble_stats.txt)
[inspire_cfdna_align_stats.txt](https://github.com/milaboratory/mixcr/files/5393026/inspire_cfdna_align_stats.txt)
[inspire_cfdna_assemble_stats.txt](https://github.com/milaboratory/mixcr/files/5393027/inspire_cfdna_assemble_stats.txt)

**Comment by PoslavskySV** [comment]
Hi,

native support of UMI is introduced in [MiXCR v4](https://github.com/milaboratory/mixcr/releases/tag/v4.0.0).

Best,
Stan
