### ISSUE TITLE
Best parameters for getting TCR or BCR from RNA-seq data

### ISSUE THREAD

**Issue by dankim97817** [milaboratory/mixcr#626]
Thank you for developing this useful tool. I am planning to get TCRs and BCRs from RNA-seq data with MiXCR. BCR has somatic hypermutations, so it should be more difficult to get. Can I ask for the best/most appropriate parameters and commands to get TCRs and BCRs from RNA-seq data with MiXCR? If there are different sets of parameters for TCRs and BCRs other than the default parameters, I plan to run MiXCR twice with different parameters and only use TCR or BCR results from that run. Thank you.

**Comment by PoslavskySV** [comment]
Hi, you can use the predefault parameters for RNA-seq data via `analyze` command. See these docs: https://mixcr.readthedocs.io/en/master/analyze.html#analysis-of-non-enriched-or-random-fragments

**Comment by dankim97817** [comment]
Thank you!
