### ISSUE TITLE
L1 region missing from fullImputed

### ISSUE THREAD

**Issue by JaredJGartner** [milaboratory/mixcr#627]
Hello, 

I am interested in getting the full sequence of the TCRs from our data.  When I run the command below I am only able to get the imputed sequence from the FR1 to the FR4.  When I run exportalignemntspretty I can see in the alignment the L1 but I can't seem to get it output when I export the clone.  Is there something I'm missing to get this as part of the output.  I can extract it from the alignments but if it's something simple I'm missing I'd appreciate any help.

mixcr exportClones -f  -nFeatureImputed VGene -aaFeatureImputed VGene  -vHit -jHit -cHit  -c TRA,TRB -p fullImputed cln_files/AACTGGTTCAGTGTTG_TCR.clns test.txt

Thanks, 

Jared

**Comment by PoslavskySV** [comment]
Hi,

if you use RNA library, you should use  `VTranscript`:
```
mixcr exportClones -f -nFeatureImputed VTranscript ....
```

See https://mixcr.readthedocs.io/en/master/geneFeatures.html

![img](https://mixcr.readthedocs.io/en/master/_images/VStructure.svg)

**Comment by JaredJGartner** [comment]
Thank you for the quick response.  I am trying to use mixcr on 10X VDJ sequencing data.  I have ran the command with the VTranscript as you suggest:
mixcr exportClones -f -nFeatureImputed VTranscript -aaFeatureImputed VTranscript -vHit -jHit -cHit -c TRA,TRB -p fullImputed cln_files/AACTGGTTCAGTGTTG_TCR.clns test.txt

Still the L1 region is not in the output fields.  I am currently using version 3.0.13.  is it possible some of the align and assembly steps performed are conflicting with this?

align:  mixcr align -s hsa -OsaveOriginalReads=true -OvParameters.geneFeatureToAlign=VTranscript  -OdParameters.geneFeatureToAlign=DRegion -OjParameters.geneFeatureToAlign=JRegion...
assemble: mixcr assemble -f --write-alignments  -OassemblingFeatures="[CDR3+FR4]"...

Thanks again for your help with this.

Jared

**Comment by PoslavskySV** [comment]
Since you use 'CDR3+FR4' as assembling feature, your clonotypes do not cover anything except 'CDR3+FR4'. You can find more details on how the clone assembly works [here](https://mixcr.readthedocs.io/en/master/assemble.html). 

What you can do in your case is to use [contig assembly](https://mixcr.readthedocs.io/en/master/assembleContigs.html). Additionally I suggest to use [`analyze`](https://mixcr.readthedocs.io/en/master/analyze.html) instead of `align`-`assemble`. You can then check how your clonotypes cover L1 with `exportClonesPretty` command.

**Comment by suntaosimon** [comment]
> Since you use 'CDR3+FR4' as assembling feature, your clonotypes do not cover anything except 'CDR3+FR4'. You can find more details on how the clone assembly works [here](https://mixcr.readthedocs.io/en/master/assemble.html).
> 
> What you can do in your case is to use [contig assembly](https://mixcr.readthedocs.io/en/master/assembleContigs.html). Additionally I suggest to use [`analyze`](https://mixcr.readthedocs.io/en/master/analyze.html) instead of `align`-`assemble`. You can then check how your clonotypes cover L1 with `exportClonesPretty` command.

Hi, I also tried to export 5UTR+L1+L2 information, but when I used `mixcr exportClones -c IGH -p fullImputed` it only started with FR1. 

```
mixcr  align --species hs -p kaligner2  -OvParameters.geneFeatureToAlign=VTranscript R1.fastq.gz R2.fastq.gz alignment.vdjca
mixcr  assemble -f --write-alignments  --report clonReport.log  alignment.vdjca alignment.clna
mixcr assembleContigs alignment.clna  full.clns
mixcr exportClones -c IGH -p fullImputed -o -t   full.clns output_full/full.tsv
```
if I used `mixcr exportClones -c IGH -p fullImputed -o -t  -nFeatureImputed VTranscript full.clns output_full/full.tsv`the -nFeatureImputedVTranscript colunm is empty.

Thanks!
