### ISSUE TITLE
IMGT library update

### ISSUE THREAD

**Issue by CarlenaNa** [milaboratory/mixcr#629]
## Checklist before submitting the issue:

 - [ ] The issue is strongly related to the MiXCR software
 - [ ] The issue can be reproduced with [the most recent version](https://github.com/milaboratory/mixcr/releases) of MiXCR
 - [ ] There is no answer to the question in the [official documentation](http://mixcr.readthedocs.io/) and there is no duplicate issue in the [bug tracker](https://github.com/milaboratory/mixcr/issues?utf8=✓&q=)  
 - [ ] Inspection of raw alignments with [exportAlignmentsPretty](http://mixcr.readthedocs.io/en/master/export.html#exporting-well-formatted-alignments-for-manual-inspection) shows that data has the expected architecture, and sample preparation artefacts are not the reason of the problem (if this is the matter of the issue)

## Expected Result

*A description of what you wanted to happen*

## Actual Result

*A description of what actually happened*

## Exact MiXCR commands 

*Paste here __exact__ MiXCR commands you used (enclose it with single `` ` ``  for better formatting)*

## MiXCR report files 

*Paste here content of the report files produced by MiXCR (enclose it with triple ```` ``` ````  for better formatting)*

**Comment by CarlenaNa** [comment]
I am making a repertoire of antibodies in horses, I made an external library last year because IMGT did not have that spice, but at the beginning of this year I added the horse library to its system, when I try to make an annotation by placing IMGT library it is not there updated. The species that are are from 2019, the horse is not yet, will it be possible to make this update?

**Comment by fabio-t** [comment]
I usually clone this repository: https://github.com/repseqio/library-imgt and run the build script, then copy the resulting json file into one of the directories that mixcr will read, eg:

```
$ ls -ltr ~/.mixcr/libraries/
total 368
-rw-rw---- 1 fabio fabio 376775 Jun 17 14:51 imgt.202122-1.sv6.json.gz
```

Essentially just like described here: https://mixcr.readthedocs.io/en/master/importSegments.html?highlight=imgt#imgt-library but building your own IMGT release.
