### ISSUE TITLE
98% of Reads dropped due to the lack of a clone sequence

### ISSUE THREAD

**Issue by RoundTab1er** [milaboratory/mixcr#632]
I am analyzing a BCR library containing UMI-barcoded reads. I processed the barcoded reads using PRESTO, and fed the resulting fastq output into mixcr. 98% or more of our reads are getting discarded due to the lack of a clone sequence. Below is the command I ran, and attached is the pretty output of 20 clonotypes. Any help would be appreciated.
[demo_pretty_alignment.txt](https://github.com/milaboratory/mixcr/files/5609812/demo_pretty_alignment.txt)

```
mixcr analyze amplicon \
        --species hsa \
        --starting-material rna \
        --5-end v-primers \
        --3-end c-primers \
        --adapters adapters-present \
        --receptor-type igh \
        --region-of-interest VDJRegion \
        --only-productive \
        --assemble "-ObadQualityThreshold=-1" \
        $f $of
```

**Comment by PoslavskySV** [comment]
Hi,

the thing is that you specify `--region-of-interest VDJRegion` which means that R1+R2 should fully cover `VDJRegion` in order to be assembled into clone. 98% of your reads do not cover full VDJ. 

You can try using [contig assembly](https://mixcr.readthedocs.io/en/master/assembleContigs.html) based on CDR3 clones:

```
mixcr analyze amplicon \
        --species hsa \
        --starting-material rna \
        --5-end v-primers \
        --3-end c-primers \
        --adapters adapters-present \
        --receptor-type igh \
        --region-of-interest CDR3 \
        --contig-assembly \
        --only-productive \
        --assemble "-ObadQualityThreshold=-1" \
        $f $of
```
