### ISSUE TITLE
Question on separateBy parameters

### ISSUE THREAD

**Issue by emm1R** [milaboratory/mixcr#633]
Hi,
In the documents at https://mixcr.readthedocs.io/en/master/assemble.html?highlight=separateByV#separation-of-clones-with-same-cdr3-clonal-sequence-but-different-v-j-c-genes it is said that `separateBy` parameters are all false but in the analysis.report files I have:

```
Command line arguments: --report mixcr/cd4/analysis.report --threads 6 --write-alignments -OseparateByV=true -OseparateByJ=true mixcr/cd4/analysis.extended.vdjca mixcr/cd4/analysis.clna
```

So separateBy for V and J are true by default? If so, why are V and J the ones that are true?

Here is my MiXCR command:
``` 
mixcr analyze shotgun \
      --species hs \
      --starting-material rna \
      --receptor-type TCR \
      --only-productive \
      --export "-cloneId -count -fraction -nFeature CDR3 -qFeature CDR3 -aaFeature CDR3 -vHit -dHit -jHit -cHit -vHitScore -dHitScore -jHitScore -cHitScore -vHitsWithScore -dHitsWithScore -jHitsWithScore -cHitsWithScore" \
      $first $second ${save}/analysis
```

**Comment by PoslavskySV** [comment]
Hi,

these parameters are true for `analyze shotgun`. They are also true by default for `analyze amplicon` if there are no primers and adapters. Regarding `separateByC` - it is false by default since it is not possible to certainly identify C-gene for libraries which does not deeply cover C region.
