### ISSUE TITLE
should primer trimming before MIXCR

### ISSUE THREAD

**Issue by skyfall-lyc** [milaboratory/mixcr#635]
Hi,
I have some raw IR-seq data. Should i cut the primer sequences before mixcr analysising ? Any suggestions are welcome！

**Comment by PoslavskySV** [comment]
It is not necessary (but you can do that, depending on your library type and preparation protocol) for running MiXCR, just follow the parameters provided by [`analyze`](https://mixcr.readthedocs.io/en/master/analyze.html).
