### ISSUE TITLE
Download error thru homebrew

### ISSUE THREAD

**Issue by Dtau-TAU** [milaboratory/mixcr#636]
## Checklist before submitting the issue:

 - [X] The issue is strongly related to the MiXCR software
 - [X] The issue can be reproduced with [the most recent version](https://github.com/milaboratory/mixcr/releases) of MiXCR
 - [X] There is no answer to the question in the [official documentation](http://mixcr.readthedocs.io/) and there is no duplicate issue in the [bug tracker](https://github.com/milaboratory/mixcr/issues?utf8=✓&q=)  
 - [ ] Inspection of raw alignments with [exportAlignmentsPretty](http://mixcr.readthedocs.io/en/master/export.html#exporting-well-formatted-alignments-for-manual-inspection) shows that data has the expected architecture, and sample preparation artefacts are not the reason of the problem (if this is the matter of the issue)

## Expected Result

*Please verify download paths thru homebrew for linux (Ubuntu)*

## Actual Result

*Error codes while downloading thru homebrew on linux*

## Exact MiXCR commands 

*Paste here __exact__ MiXCR commands you used (enclose it with single `` ` ``  for better formatting)*

## MiXCR report files 

*![image](https://user-images.githubusercontent.com/71630471/103098530-b7fbfd80-4613-11eb-8e0f-0dc9789276c0.png)*

**Comment by dbolotin** [comment]
Thanks for reporting! Will fix it today or tomorrow.

**Comment by dbolotin** [comment]
Done, please try again.
