### ISSUE TITLE
symbol meaning in CDR3?

### ISSUE THREAD

**Issue by swuecho** [milaboratory/mixcr#64]
I find '*', '~', '-' in CDR3, what does each of them means? Thanks.

**Comment by dbolotin** [comment]
`*` - stop codon
`~` - incomplete codon (it is a very old syntax, now the `_` symbol is used instead)
Here is an example of translation of the following nucleotide sequence: `ATTAGACA`
    
    ATT AG  ACA
     I   _   T    -   current syntax
     I   ~   T    -   old syntax

`-` - should never appear in CDR3 sequences (could you provide an example?)

What version of MiXCR do you use?

**Comment by swuecho** [comment]
Thanks.

Yeah. I should type '_' instead of '-'.

'~' was found from result of mitcr.  

Thanks.
