### ISSUE TITLE
Duplicate clones in export

### ISSUE THREAD

**Issue by fabio-t** [milaboratory/mixcr#640]
Hi,

Clones with the same CDR3, vHit and jHit are reported multiple times in the output. The only differences are in the exact alignment scores, or with occasional alternative hits:

```
3	23	0.015764222069911	IGHV6-3*01(2951),IGHV6-3*02(2835),IGHV6-3*03(2835)	IGHD4-1*01(50),IGHD4-1*02(50)	IGHJ2*01(400)		TGCACAGAACTGGGACGAGACTACTGG	CTELGRDYW
51	7	0.004797806716929	IGHV6-3*01(2980),IGHV6-3*02(2864),IGHV6-3*03(2864)	IGHD4-1*01(50),IGHD4-1*02(50)	IGHJ2*01(400)		TGCACAGAACTGGGACGAGACTACTGG	CTELGRDYW
164	3	0.002056202878684	IGHV6-3*01(2777),IGHV6-3*02(2661),IGHV6-3*03(2661)	IGHD4-1*01(50),IGHD4-1*02(50)	IGHJ2*01(400),IGHJ2*03(371)		TGCACAGAACTGGGACGAGACTACTGG	CTELGRDYW
```

I think there's should be an option to allow clone calling via only the top hits (any combination of vHit/jHit/cHit) or gene (any combination of vGene/jGene/cGene).

**Comment by PoslavskySV** [comment]
Hi,

I think the reason is that they have different cHits - could you check please?

**Comment by fabio-t** [comment]
Interesting - actually I got no cHits, and was wondering why. I'll give more details soon. Note that in this case I put `separateByC=false` so it shouldn't happen anyway but I'll dig more in this direction.

**Comment by fabio-t** [comment]
Just wanted to up this again. I haven't been able to any c-hits with either migec or mixcr, although the cprimer is correctly identified using IMGT blastn.

This is an example read from our data (mouse, IGH):

R1:
```
CACTCTATCCGACAAGCAGTGGTATCAACGCAGAGTGTTATAGTCTGTGATCTTGGGGAGCATATGACCCCTGTCTTCTCCACAGTCCCTGAACACACTGACTCTAACCATGGAATGGCCTTTGATCTTTCTCTTCCTCCTGTCAGGAACTGCAGGTGTCCAATCCCAGGTTCAGCTGCAGCAGTCTGGGGCTGAGCTGGTGAAGCCTGGGGCCTCAGTGAAGATTTCCTGCAAAGCTTCTGGCTACGCATCCAGTAGCTACTGGATGAACTGGGTGAAGCAGAGGCCTGGAAAGGGTCTT
```

R2:
```
ATTGGGCAGCCCTGATTTCAGTGGGTAGATGGTGGGATTTCTCGCAGACTCTGAGGAGACGGTGACCGTGGTCCCTGTGCCCCAGACATCGAAGTACCAGTAGTAACCCCCCCCTCTTGCACAGAAATAGACCGCAGAGTCCTCAGAGGTCAGGCTGCTGAGCTGCATGTAGGCCGTGCTGGAGGATTTGTCTGCGGTCAGTGTGGCCTTGCCCTTGAACTTTCCGTTGTAGTTAGTATCACCATCTCCAGGATACATCGGTCACATCCACTCAAGCCCCTTTCCAGGCCTCTGCTTCCCC
```

The C-primer is at the beginning of R2: `ATTGGGCAGCCCTGATTTCAGTGGGTAGATGGTG`

When blasted, it aligns correctly:

```
>V00785|Mouse germ line gene for immunoglobulin alpha H constant part (coding
          for the last three exons). 
          Length = 1674

 Score = 34.2 bits (17), Expect = 0.23
 Identities = 17/17 (100%)
 Strand = Plus / Minus

                           
Query: 18 tcagtgggtagatggtg 34
          |||||||||||||||||
Sbjct: 83 tcagtgggtagatggtg 67
```

This is the mixcr command I use, after UMI demultiplexing with MIGEC (in a for loop, hence the `i`):

```
mixcr analyze amplicon --report mixcr_${i}/report.log --verbose -f -b imgt --species MusMusculus --starting-material rna --5-end v-primers --3-end c-primers --adapters adapters-present --receptor-type ${chain} --region-of-interest VDJRegion --only-productive --align "-OreadsLayout=Collinear" --assemble "-OseparateByC=false" --assemble "-OseparateByV=true" --assemble "-OseparateByJ=true" --assemble "-OqualityAggregationType=Max" --assemble "OclusteringFilter.specificMutationProbability=1E-5" --assemble "-OmaxBadPointsPercent=0" assembly_${i}_safe/S0_R1.*.fastq assembly_${i}_safe/S0_R2.*.fastq mixcr_${i}/analysis
```

Which other reasons could cause the c-hit to be empty?

**Comment by fabio-t** [comment]
This is the final clonotype file: https://file.io/aFkEQgUk9W9Z
The duplicate issue is always there, but now I'm more worried about the C-hit missing.

**Comment by fabio-t** [comment]
I *think* the duplicates are due to my using VDJRegion as the assembling feature - even a single base difference might cause the split.

I guess using something like `[VGene, CDR3, JGene]` or along those lines, should merge together the clones.. essentially I do this downstream, but I think the documentation could could cover this better somehow.

**Comment by PoslavskySV** [comment]
Hi,

if you still have this issue, please contact us at support@milaboratories.com

Best,
Stan
