### ISSUE TITLE
parameter -p rna-seq for Exome seq data analysis ?

### ISSUE THREAD

**Issue by HugoMananet** [milaboratory/mixcr#646]
Hi,
I try to use MiXCR to extract clones from tumor exome sequencing data (short reads ~100pb) 

The tool (v3.0.4) was already used in my lab with the same type of data with the commands:
```
mixcr align \
	--threads 8 \
	--species hsa \
	tumor_R1.fastq.gz \
	tumor_R2.fastq.gz \
	tumor_alignments.vdjca

mixcr assemble \
	--threads 8 \
	tumor_alignments.vdjca \
	tumor_clones.clns

exportClones \
	--chains IGH \
	tumor_clones.clns \
	tumor_clones.txt
```
I wanted to update to the new version.
I could reproduce the results (or very close) with the same commands with the newest version (v3.0.13) 

But, reading the documentation, i also tested the recommended parameters (i.e analyze shotgun with default parameters) but got no clones found
```
analyze shotgun \
	--starting-material dna \
	-s hsa \
	--receptor-type igh \
	--contig-assembly \
	--verbose \
	--threads 8 \
	--assemble-partial-rounds 2 \
	tumor_R1.fastq.gz \
	tumor_R2.fastq.gz \
	tumor_MiXCR_analysis_IGH_new_version
```
and found no results.

To determine which parameter generated the difference between the results i tried with and without a lot of parameters but it was when i removed `-p rna-seq` that some clones were found by MiXCR but were different than the ones found with the first method.
The command was as described in the docs:
```
mixcr align \
    -OallowPartialAlignments=true \
    --species hsa \
    --library default \
    --threads 16 \
    --report tumor_pipelinenoprnaseqshotgun.report \
    -OvParameters.geneFeatureToAlign=VGeneWithP \
    -OvParameters.parameters.floatingLeftBound=false \
    -OvParameters.parameters.floatingRightBound=false \
    -OvParameters.parameters.floatingRightBound=false \
    tumor_R1.fastq.gz \
    tumor_R2.fastq.gz \
    tumor_new_version_pipelinenoprnaseqshotgun.vdjca

mixcr assemblePartial \
    --report tumor_pipelinenoprnaseqshotgun.report \
    tumor_pipelinenoprnaseqshotgun.vdjca \
    tumor_pipelinenoprnaseqshotgun.rescued_0.vdjca

mixcr assemblePartial \
    --report tumor_pipelinenoprnaseqshotgun.report \
    tumor_pipelinenoprnaseqshotgun.rescued_0.vdjca \
    tumor_pipelinenoprnaseqshotgun.rescued_1.vdjca

mixcr extend \
    --report tumor_pipelinenoprnaseqshotgun.report \
    --threads 16 \
    tumor_pipelinenoprnaseqshotgun.rescued_1.vdjca \
    tumor_pipelinenoprnaseqshotgun.extended.vdjca

mixcr assemble \
    --report tumor_pipelinenoprnaseqshotgun.report \
    --threads 16 \
    --write-alignments \
    tumor_pipelinenoprnaseqshotgun.extended.vdjca \
    tumor_pipelinenoprnaseqshotgun.clna

mixcr assembleContigs \
    --report tumor_pipelinenoprnaseqshotgun.report \
    --threads 16 \
    tumor_pipelinenoprnaseqshotgun.clna \
    tumor_pipelinenoprnaseqshotgun.contigs.clns

# export to tsv
mixcr exportClones \
    tumor_pipelinenoprnaseqshotgun.contigs.clns \
    tumor_pipelinenoprnaseqshotgun.contigs.txt
```

Which method do you think is the optimal in my situation ? and which results are the most fitting my data ? 

I also join the report files, hoping that can help.
[tumor_pipelinenoprnaseqshotgun_report.txt](https://github.com/milaboratory/mixcr/files/6230223/tumor_pipelinenoprnaseqshotgun_report.txt)
[tumor_MiXCR_analysis_IGH_new_version_report.txt](https://github.com/milaboratory/mixcr/files/6230224/tumor_MiXCR_analysis_IGH_new_version_report.txt)
[tumor_MiXCR_analysis-new_version_standard_report.txt](https://github.com/milaboratory/mixcr/files/6230226/tumor_MiXCR_analysis-new_version_standard_report.txt)

Thanks in advance.

Hugo

**Comment by PoslavskySV** [comment]
Hello Hugo,

There is a chance that those clones obtained without `-p rnaseq` are false-positives. The `-p rnaseq` parameter set was specifically designed to minimize the false-positive alignment rate. You can find much more details in our paper  dedicated to the analysis of short RNA-Seq data https://www.nature.com/articles/nbt.3979. 

So, I can't give any particular advise in your case: if you do not use `-p rnaseq` for shotgun data you need to ensure somehow that the produced clonotypes are not false-positives.
