### ISSUE TITLE
Why TRA and TRD give the same thing?

### ISSUE THREAD

**Issue by beginner984** [milaboratory/mixcr#649]
Hello

I have been trying to export clone for different chains but the results for A and D chanis is the same?

```
mixcr exportClones -c TRA -o -t sample.clns TRA.txt
mixcr exportClones -c TRD -o -t sample.clns TRD.txt
```

These two exactly give the samme output

Please help me to get the reason

Thank you ss omuch in advance

**Comment by PoslavskySV** [comment]
Hi,

please see the answer here: https://github.com/milaboratory/mixcr/issues/541#issuecomment-545963300
