### ISSUE TITLE
Running Mixcr in a PBS environment

### ISSUE THREAD

**Issue by SoniaWolf149** [milaboratory/mixcr#652]
I am running Mixcr, and keep getting told the memory is exceeded, even when I run it on 32 cores.

I notice that in a previous post you said you can have problems running MiXCR in a PBS environment, but I have to do this as that is what my university HPC requires.

I am running version 3.0.3 in a Conda environment

This is the script

`mixcr align -p rna-seq -s hsa -t 32 -OallowPartialAlignments=true $INFILE1 $INFILE2 $(basename $INFILE1 _1P.fq.gz)_alignments.vdjca`

MiXCR reports:
`=>> PBS: job killed: ncpus 38.28 exceeded limit 32 (sum)`

What is going on here?! Is it because it's on a PBS system?

**Comment by PoslavskySV** [comment]
Hi,

MiXCR should perfectly work in PBS, so  the issue is related to your PBS setup. You may try the following to overcome `ncpus` problem:
```
mixcr align --threads 32 ...
```
or even
```
mixcr align --threads 30 ...
```

If this does not help, you'd better to consult with your PBS administrator.
