### ISSUE TITLE
how could I get clonotype result in a paired (TRA, TRB) pattern?

### ISSUE THREAD

**Issue by overshiki** [milaboratory/mixcr#658]
Hi, 
Just new to mixcr. 

I am trying to analyze TCR data using the following command:
mixcr align --species hsa ./R1.fastq ./R2.fastq ./alignments.vdjca
mixcr exportAlignments -vHit -dHit -jHit ./alignments.vdjca ./alignments.txt

I suppose the first command 'align' will merge the TRA and TRB, and the following command 'exportAlignments' will give me the clonotype information of a paired pattern, which should look like:
bestVHit(alpha)  bestJHit(alpha) bestVHit(beta)  bestDHit(beta)  bestJHit(beta)
TRAV2*00       TRAJ39*00     TRBV20-1*00	TRBD1-6*00	TRBJ1-6*00
TRAV20*00	TRAJ39*00     TRBV2-1*00	TRBD1-6*00	TRBJ1-6*00
...

I made such an assumption since the clonotype of alpha chain and beta chain together determine the clonotype of the TCR.

However, the real alignments.txt I got looks like this:

bestVHit	bestDHit	bestJHit
TRBV20-1*00		TRBJ1-6*00
TRAV2*00		TRAJ39*00
TRBV20-1*00	TRBD1*00	TRBJ1-1*00
TRBV20-1*00		TRBJ1-6*00

which do not follow a (TRA, TRB) pair pattern, instead, the TRA clonotype and TRB clonotype are list in seperate lines, thus I do not know which clonetype of TRA pairs with which clonotype of TRB ...

I also tried using NGmerge to merge the fastq file into a paired file before doing alignment, however I still got same result.

It seems such an output pattern is not designed for alpha-beta paired clonetype identification, then how could I do this through mixcr?

thanks a lot in advance

**Comment by suntaosimon** [comment]
need to use single cell TCR sequencing.

**Comment by overshiki** [comment]
Hi, we finally have solved this problem by manual pairing each read of R1 and R2, using the -readIds options provided by mixcr exportAlignments command. 

More specifically, we separately run 
mixcr align --species hsa XX.fastq ./alignments_XX.vdjca
while XX stands for R1 and R2
and then export the txt file using mixcr exportAlignments with one additional -readIds option
and finally pair R1 and R2 reads with readId tag in the txt file
