### ISSUE TITLE
B-cell lineage analysis

### ISSUE THREAD

**Issue by fabio-t** [milaboratory/mixcr#659]
In MIGEC, there's a [post-processing step to create a hypermutation graph](https://migec.readthedocs.io/en/latest/post.html), which can be put in cytoscape to be able to visualise the b-cell clonal trees.

Is there something like this compatible with MIXCR? Vdjtools doesn't seem to support it, for example. Maybe there's some way that the MIGEC command above can be run on MIXCR results?

**Comment by PoslavskySV** [comment]
Hi, [MiXCR v4.1](https://github.com/milaboratory/mixcr/releases/tag/v4.1.0) introduces powerful functionality to reconstruct SHM trees. Please, check the [docs](https://docs.milaboratories.com)
