### ISSUE TITLE
v3.0.3 `--only-productive` option

### ISSUE THREAD

**Issue by ShwetaCh** [milaboratory/mixcr#665]
Hello @PoslavskySV 

Thank you for this software, it is super useful for my research.

I'm facing the following issue- I get exact same results with and without `--only-productive` option, the non-productive ones seem to be always filtered out by default for v3.0.3. However, I want to retain all sequences including non-coding cdr3 for a specific comparison. I've tried it as true/false/explicitly using the option/hashing it out as in the below code -- which is the right way to retain all the non-productive sequences as well?
I'm not sure if the issue is at my end or the new mixcr version, could you also confirm that this option works as expected in the new version 3.0.3?
 
Thank you,
Shweta

```
     mixcr analyze amplicon \
     --verbose \
     --species hsa \
     --starting-material dna \
     --5-end v-primers --3-end j-primers \
     --adapters adapters-present \
     --report analysis_${SAMPLE} \
     --receptor-type trb \
     --region-of-interest CDR3 \
     #--only-productive \
     ${FASTQ1} ${FASTQ2} ../outputs/${SAMPLE}/${SAMPLE}analysis
```

**Comment by PoslavskySV** [comment]
Hi Shweta, 

is there a chance that there are no non-productive CDR3s in your data? You can check this by running the pipeline with [align/assemble](https://mixcr.readthedocs.io/en/master/analyze.html) commands:

```bash
# align raw reads
mixcr align -s hs -p \
    -OvParameters.geneFeatureToAlign=VGeneWithP \
    -OvParameters.parameters.floatingLeftBound=true \
    -OvParameters.parameters.floatingRightBound=true \
    -OvParameters.parameters.floatingRightBound=false \
    input_R1.fastq [input_R2.fastq] my_analysis.vdjca

# assemble clonotypes based on --region-of-interest
mixcr assemble my_analysis.vdjca my_analysis.clns

# export to tsv
mixcr exportClones my_analysis.clns my_analysis.txt
```

Best,
Stanislav

**Comment by ShwetaCh** [comment]
Hi Stanislav, 

Thanks for your prompt response!

I double checked, so I do know that we have non-productive sequences in these samples, because we had the same sample run on mixcr via Illumina Basepace interface and that showed some in the top clonotype list.

Just for my understanding and to make sure I'm running it correctly, what should the parameter be set as so as to not filter them?
--only-productive as "false" or not add the parameter at all in the command?

Best,
Shweta

**Comment by PoslavskySV** [comment]
Just remove ``--only-productive`` from the command, and all sequences will be exported, not only productive. Regarding Illumina - I would not rely on that, the version on Basespace is quite outdated, so it is better to cross check with the pipeline I provided above.
