### ISSUE TITLE
B-Cell Analysis with WGS data

### ISSUE THREAD

**Issue by evcon131** [milaboratory/mixcr#666]
What's the best ```-p``` parameter to use with WGS data when analyzing for Ig genes?
I have used ```-p kAligner2```, should I use a different option since it's whole genome data?

**Comment by PoslavskySV** [comment]
Hi, it is best to use `mixcr analyze shotgun ...` or if you want to run pipeline manually you can follow this doc: https://mixcr.readthedocs.io/en/master/rnaseq.html

**Comment by robinycfang** [comment]
Hi,

Sorry to reopen this isusse...I am running mixcr on WBC WGS data too, but couldn't find the preset for shotgun, wondering if it has been removed from the new relsease?

`mixcr/mixcr analyze shotgun 
--species hsa 
--dna 
R1_001.fastq.gz 
R2_001.fastq.gz 
result`

returns:

> No preset with name "shotgun".
Here are supported presets with similar names:
To list all built-in presets run `mixcr listPresets`.

**Comment by PoslavskySV** [comment]
Hi,

please, use the corresponding preset: https://mixcr.com/mixcr/reference/overview-built-in-presets/#exome-data

```
mixcr analyze exome-cdr3 \
    --species hsa \
      input_R1.fastq.gz \
      input_R2.fastq.gz \
      result
```

**Comment by robinycfang** [comment]
> Hi,
> 
> please, use the corresponding preset: https://mixcr.com/mixcr/reference/overview-built-in-presets/#exome-data
> 
> ```
> mixcr analyze exome-cdr3 \
>     --species hsa \
>       input_R1.fastq.gz \
>       input_R2.fastq.gz \
>       result
> ```

Thanks!
For exome-cdr3 or exome-full-length, I assume it only maps reads to the exons of the TCR genes? For my WGS data, would it be more sensitive to capture TCR rearrangement by mapping reads to the whole TCR genes including introns?

**Comment by mizraelson** [comment]
Hi,
The exome presets use DNA reference, so it includes the intron in the V gene.
