### ISSUE TITLE
colneIds not matching between exportClones and exportAlignments outputs

### ISSUE THREAD

**Issue by mehdiborji** [milaboratory/mixcr#670]
In case of clones with the same count, the ordering of clones will (probably randomly) change with every iteration of `assembleContigs` command, in a way reads and clones cannot be matched. The output of `exportAlignments` seem to maintain the same ordering with multiple iterations of `assemble` command.

Here I am showing bottom of tables for `exportAlignments` (on the left) `exportClones` (on the right) which corresponds to clones with count of one:
![Screen Shot 2021-10-08 at 11 48 46 AM](https://user-images.githubusercontent.com/16826309/136586608-966184cb-9048-48a7-8cf2-74bae5349c51.png)
However the issue can observed in cases where the counts are equal but not count of one, so I suspect this has to do with sorting of clones in assembleContigs step. This may or may not be related to this previous issue: #468

version:
`mixcr-3.0.13`
sample commands:
 ```
mixcr assemble -r $1.txt -t 16 -a $1.vdjca $1.clna -f
mixcr assembleContigs $1.clna $1.clns -f
mixcr exportClones -cloneId -count -topChains $1.clns $1_clones.txt -f
mixcr exportAlignments -descrsR1 -cloneId -topChains $1.clna $1_cloneID.txt -f
```

**Comment by PoslavskySV** [comment]
Hi,

this is fixed in [MiXCR v4.0](https://github.com/milaboratory/mixcr/releases/tag/v4.0.0).

Best,
Stan
