### ISSUE TITLE
allCAlignments column is empty

### ISSUE THREAD

**Issue by plezar** [milaboratory/mixcr#674]
## Checklist before submitting the issue:

 - [x] The issue is strongly related to the MiXCR software
 - [x] The issue can be reproduced with [the most recent version](https://github.com/milaboratory/mixcr/releases) of MiXCR
 - [x] There is no answer to the question in the [official documentation](http://mixcr.readthedocs.io/) and there is no duplicate issue in the [bug tracker](https://github.com/milaboratory/mixcr/issues?utf8=✓&q=)  
 - [x] Inspection of raw alignments with [exportAlignmentsPretty](http://mixcr.readthedocs.io/en/master/export.html#exporting-well-formatted-alignments-for-manual-inspection) shows that data has the expected architecture, and sample preparation artefacts are not the reason of the problem (if this is the matter of the issue)

## Expected Result

`allCAlignments` column in the `mixcr exportClones` output table should contain info about C alignments from a `.vdjca` file.

## Actual Result

Although `allCHitsWithScore` are given, `allCAlignments` column is empty ([example output file](https://github.com/milaboratory/mixcr/files/7792918/example_data.txt)). 

## Exact MiXCR commands 

```
mixcr align --species 10114 \
    -p kAligner2 \
    --library rat_IGH \
    --not-aligned-R1 ${out_dir}/unaligned_reads/${prefix}_R1.unaligned.fastq \
    --not-aligned-R2 ${out_dir}/unaligned_reads/${prefix}_R2.unaligned.fastq \
    -OcParameters.geneFeatureToAlign=CRegion \
    --force-overwrite \
    --report ${out_dir}/${prefix}.align_report.txt \
    ${in_dir}/${prefix}.consensus-R1.fastq ${in_dir}/${prefix}.consensus-R2.fastq ${out_dir}/${prefix}_alignments.vdjca

mixcr assemble --write-alignments \
    --verbose \
    -OseparateByC=true \
    -OassemblingFeatures=CDR3 \
    --report ${out_dir}/${prefix}.assemble_report.txt \
    ${out_dir}/${prefix}_alignments.vdjca ${out_dir}/${prefix}_clones.clna

mixcr assembleContigs -OalignedRegionsOnly=true \
    --report ${out_dir}/${prefix}.assembleContigs_report.txt \
    ${out_dir}/${prefix}_clones.clna ${out_dir}/${prefix}_contigs.clns

mixcr exportClones -c IG \
    -p fullImputed \
    ${out_dir}/${prefix}_contigs.clns ${out_dir}/${prefix}.txt
```
## MiXCR report files

[AlignmentsPretty_example.txt](https://github.com/milaboratory/mixcr/files/7792911/AlignmentsPretty_example.txt)

**Comment by PoslavskySV** [comment]
Hi,

please check this with the [MiXCR v4](https://github.com/milaboratory/mixcr/releases/tag/v4.0.0). Also, keep in mind that the `allCAlignments` may be empty if there were no any mismatches or indels.

Best,
Stan
