### ISSUE TITLE
OvParameters=null

### ISSUE THREAD

**Issue by zznx** [milaboratory/mixcr#675]
Hi,
I tried the following code but it didn't work.Looking forward to your reply
`mixcr align -s human -t 16 -f -OminSumScore=200 -OallowPartialAlignments=true -OvjAlignmentOrder=JThenV -OvParameters=null --library imgt.201946-3.sv6 -OsaveOriginalReads=true` @dbolotin

**Comment by PoslavskySV** [comment]
Hi,

the code is missing input and output files.
