### ISSUE TITLE
Installation on Mac OS

### ISSUE THREAD

**Issue by MilaBrun** [milaboratory/mixcr#678]
Hi there, 

I faced some issues with installing and especially open & run Mixcr on my MacOS which runs with the Big Sur Version 11.5.1
I also tried to download the Zip file but somehow nothing is working and I also followed the recommendations and updated home-brew etc. 

I´m looking forward to your response and thanks already in advance, 
Mila

**Comment by molecules** [comment]
Dear Mila,

I'm not part of the mixcr project, but came across your message while searching for something else.

In order for the mixcr team to help you, they probably need more details. For example, what exactly are the install commands that you tried and and what error message are you getting when you try to install it?

Have a good day!

--Christopher Bottoms
