### ISSUE TITLE
Low alignment rates for randomly shredded TCR-B library with MixCR

### ISSUE THREAD

**Issue by genome2020** [milaboratory/mixcr#679]
Hello,
I recently applied the MiXCR pipeline in 'shotgun' mode to analyze my randomly shredded TCR-B library. However the alignment rates for my full set of samples is lowish (20-37%). As I can see from the report, it seems 'Alignment failed because of absence of CDR3 parts' seems to be the main reason for the low alignment (see part of the report for one of the samples below:

Total sequencing reads: 358155
Successfully aligned reads: 73769 (20.6%)
Paired-end alignment conflicts eliminated: 1142 (0.32%)
Alignment failed, no hits (not TCR/IG?): 20007 (5.59%)
Alignment failed because of absence of CDR3 parts: 257575 (71.92%)
Alignment failed because of low total score: 6804 (1.9%)
Overlapped: 323 (0.09%)
Overlapped and aligned: 174 (0.05%)
Alignment-aided overlaps: 106 (60.92%)
Overlapped and not aligned: 149 (0.04%)
V gene chimeras: 35 (0.01%)
J gene chimeras: 34 (0.01%)
TRA chains: 1 (0%)
TRB chains: 73759 (99.99%)
TRG chains: 9 (0.01%)

Here is the command that I am using:

mixcr analyze shotgun -s hsa --starting-material rna --receptor-type trb --contig-assembly --only-productive --align "-OallowPartialAlignments=true" --assemble "-OaddReadsCountOnClustering=true" --export "-m 2 -vGene -nFeature CDR3 -aaFeature CDR3 -dGene -jGene -lengthOf CDR3 -defaultAnchorPoints -count" $baseDir/S59_trimmed_R1.fastq $baseDir/S59_trimmed_R1.fastq S59_trimmed

Would you have any input on how to improve my alignment rate?

**Comment by PoslavskySV** [comment]
Hi,

the source of the low alignment rate is in the wet lab part (artefacts with the library / wrong library structure). You should inspect raw alignments with [exportAlignmentsPretty](http://mixcr.readthedocs.io/en/master/export.html#exporting-well-formatted-alignments-for-manual-inspection) to validate that data has the expected architecture, and sample preparation artefacts are not the reason of the problem.

**Comment by Angieiscute** [comment]
> Hi,
> 
> the source of the low alignment rate is in the wet lab part (artefacts with the library / wrong library structure). You should inspect raw alignments with [exportAlignmentsPretty](http://mixcr.readthedocs.io/en/master/export.html#exporting-well-formatted-alignments-for-manual-inspection) to validate that data has the expected architecture, and sample preparation artefacts are not the reason of the problem.

Hi, 
A quick question about this issue, 
Is "Alignment failed because of absence of CDR3 parts: 257575 (71.92%)" reads stored in the VDJCA file? I mean if I can use 'exportAlignmentsPretty` to validate this part of reads?

Thanks!

**Comment by mizraelson** [comment]
Hi, by default these reads are dropped. But, you can use the following parameter to preserve such reads `--keep-non-CDR3-alignments`. If done so, you can then investigate manually with `exportAlignmentsPretty`.

**Comment by Angieiscute** [comment]
> Hi, by default these reads are dropped. But, you can use the following parameter to preserve such reads `--keep-non-CDR3-alignments`. If done so, you can then investigate manually with `exportAlignmentsPretty`.

Thanks for your explanation. One more question,
What's the difference between "Reads.dropped.due.to.the.lack.of.a.clone.sequence" in clonReport.log and "Alignment failed because of absence of CDR3 parts" in the alignmentReport.log? If these reads that are absent of CDR3 are dropped in the alignment process, what kind of reads will be dropped again in the assembly process? 

Thanks!
