### ISSUE TITLE
Fail when building from source

### ISSUE THREAD

**Issue by Rmulet** [milaboratory/mixcr#680]
Hi,

I searched and I could not find this issue anywhere, but my apologies if it has been answered before. Although there is a `jar` file available, I tried to build from source as instructed in the Github repository. However, the process failed when building the RepSeq.IO util. This is the message I got:

`Failed to execute goal on project repseqio: Could not resolve dependencies for project io.repseq:repseqio:jar:1.3.5-SNAPSHOT: The following artifacts could not be resolved: com.milaboratory:milib:jar:1.14-SNAPSHOT, com.milaboratory:milib:jar:tests:1.14-SNAPSHOT: Failure to find com.milaboratory:milib:jar:1.14-SNAPSHOT in https://oss.sonatype.org/content/repositories/snapshots was cached in the local repository, resolution will not be reattempted until the update interval of sonatype-nexus-snapshots has elapsed or updates are forced -> [Help 1]
`

If it's of any help, I am using Ubuntu 20.04 with Apache Maven 3.6.3

**Comment by PoslavskySV** [comment]
Hi,

MiXCR is not intended to be build from source: the source code is available for information purposes. Please, use [binary releases](https://github.com/milaboratory/mixcr/releases/tag/v4.0.0).
