### ISSUE TITLE
Advice needed on deprecated parameters in older versions of mixcr exportAlignment

### ISSUE THREAD

**Issue by yyw-informatics** [milaboratory/mixcr#681]
Hi,

Thank you for making and maintaining this great software. :smiley:

I'm trying to run a script wrote with an outdated version (unspecified, but should be <1.7) of mixcr.  In the following command, some parameters for example `-sequence` are no longer used in the most current version. I wonder what parameter(s) should I use to replace for the current release? 

`mixcr exportAlignments -readId -sequence -vGene -dGene -jGene -cGene -nFeature CDR1 -nFeature CDR2 -nFeature CDR3 -aaFeature FR1 -aaFeature CDR1 -aaFeature FR2 -aaFeature CDR2 -aaFeature FR3 -aaFeature CDR3 -aaFeature FR4 -vBestIdentityPercent alignment.vdjca`

Thanks,
Yuanyuan

**Comment by PoslavskySV** [comment]
Hi, 

you can check the list of actual parameters with

```
mixcr help exportAlignments
```
