### ISSUE TITLE
mixcr exportAlignments error: Unmatched argument: alignments.txt

### ISSUE THREAD

**Issue by Drinchai** [milaboratory/mixcr#682]
## Checklist before submitting the issue:

 - [ x] The issue is strongly related to the MiXCR software
 - [x ] The issue can be reproduced with [the most recent version](https://github.com/milaboratory/mixcr/releases) of MiXCR
 - [x ] There is no answer to the question in the [official documentation](http://mixcr.readthedocs.io/) and there is no duplicate issue in the [bug tracker](https://github.com/milaboratory/mixcr/issues?utf8=✓&q=)  
 - [ x] Inspection of raw alignments with [exportAlignmentsPretty](http://mixcr.readthedocs.io/en/master/export.html#exporting-well-formatted-alignments-for-manual-inspection) shows that data has the expected architecture, and sample preparation artefacts are not the reason of the problem (if this is the matter of the issue)

## Expected Result
* Thank you for creating this wonderful package. It is very useful for work. However, I have some issues about exporting step.
*  I would expect to have both alignment and clone information together so
I did run the script below expecting to have all needed information*

## Actual Result

*I got an error message Unmatched argument: alignments.txt*
Usage: mixcr exportAlignments [-fv] [--verbose] [-cAlignment] [-cAlignments]
                              [-cBestIdentityPercent] [-cFamilies] [-cFamily] [-cGene] [-cGenes]
                              [-chains] [-cHit] [-cHits] [-cHitScore] [-cHitsWithScore]
                              [-cIdentityPercents] [-cloneId] [-cloneIdWithMappingType]
                              [-dAlignment] [-dAlignments] [-dBestIdentityPercent]
                              [-defaultAnchorPoints] [-descrR1] [-descrR2] [-descrsR1] [-descrsR2]
                              [-dFamilies] [-dFamily] [-dGene] [-dGenes] [-dHit] [-dHits]
                              [-dHitScore] [-dHitsWithScore] [-dIdentityPercents] [-jAlignment]
                              [-jAlignments] [-jBestIdentityPercent] [-jFamilies] [-jFamily]
                              [-jGene] [-jGenes] [-jHit] [-jHits] [-jHitScore] [-jHitsWithScore]
                              [-jIdentityPercents] [-nw] [-readHistory] [-readId] [-readIds]
                              [-targetQualities] [-targets] [-targetSequences] [-topChains]
                              [-vAlignment] [-vAlignments] [-vBestIdentityPercent] [-vFamilies]
                              [-vFamily] [-vGene] [-vGenes] [-vHit] [-vHits] [-vHitScore]
                              [-vHitsWithScore] [-vIdentityPercents] [-c <chains>] [-n <limit>] [-p
                              <preset>] [-pf <presetFile>] [-aaFeature PARAM]... [-aaFeatureImputed
                              PARAM]... [-aaMutations PARAM]... [-avrgFeatureQuality PARAM]...
                              [-lengthOf PARAM]... [-minFeatureQuality PARAM]...
                              [-mutationsDetailed PARAM]... [-nFeature PARAM]... [-nFeatureImputed
                              PARAM]... [-nMutations PARAM]... [-positionInReferenceOf PARAM]...
                              [-positionOf PARAM]... [-qFeature PARAM]... [-aaMutationsRelative
                              PARAM PARAM]... [-mutationsDetailedRelative PARAM PARAM]...
                              [-nMutationsRelative PARAM PARAM]... <in> [<out>]
Export V/D/J/C alignments into tab delimited file.
.......

## Exact MiXCR commands 
`mixcr assemble -r assemble_log.txt -a alignments.vdjca clones.clna

mixcr exportAlignments -readIds -cloneId -vGenes -jGenes -cGenes -nFeatureImputed FR1 -nFeatureImputed CDR1 -nFeatureImputed FR2 -nFeatureImputed CDR2 -nFeatureImputed FR3 -nFeatureImputed FR4 -aaFeatureImputed FR1 -aaFeatureImputed CDR1 -aaFeatureImputed FR2 -aaFeatureImputed CDR2 -aaFeatureImputed FR3 -aaFeatureImputed FR4-nMutations FR1 -nMutations CDR1 -nMutations FR2 -nMutations CDR2 -nMutations FR3 -nMutations FR4 -aaMutations FR1 -aaMutations CDR1 -aaMutations FR2 -aaMutations CDR2 -aaMutations FR3 -aaMutations FR4 clones.clna alignments.txt`

## MiXCR report files 
`Unmatched argument: alignments.txt`

**Comment by PoslavskySV** [comment]
It seems you missed space between -aaFeatureImputed FR4 and next argument
