### ISSUE TITLE
full IG contigs assembly questions

### ISSUE THREAD

**Issue by slowsmile** [milaboratory/mixcr#685]
Dear All
I am trying to assemble full IG contigs based on the clone I identified using the amplicon pipeline: ### https://mixcr.readthedocs.io/en/develop/assembleContigs.html

The procedure looks good but I have 2 additional questions
1) is there a way to output the percentage of IGs covered by all the reads from the clone? I'd like to know how much the reads from my top clone covers the IG (from FR1 to FR4) systematically (I had to scan a good number of clones) but I could not find corresponding parameters

2) when I specify -p fullImputed in contigs export, Mixcr will perform germline bp imputation, however, I'd like to know how does mixcr choose which VDJ segments to impute if my reads did not cover that region? What algorithm does mixcr use to determine the appropriate germline segments to impute?

Thanks a lot for your help!
Xiao

**Comment by mizraelson** [comment]
Hi,
1. Could you please elaborate on what you are trying to do? perhaps an example would help.

3. MiXCR aligns available reads and based on that alignment assigns a particular segment (the one which has the best score).  If fullImputed, MiXCR will use that best-score segment to impute an uncovered region.

**Comment by suntaosimon** [comment]
> Hi,
> 
> 1. Could you please elaborate on what you are trying to do? perhaps an example would help.
> 2. MiXCR aligns available reads and based on that alignment assigns a particular segment (the one which has the best score).  If fullImputed, MiXCR will use that best-score segment to impute an uncovered region.

Hi,
Is it possible to `exportClones   -p fullImputed` 5UTR+L1+L2 information? or only can start with FR1?

Thanks!

**Comment by PoslavskySV** [comment]
Yes, it is possible, just follow the docs in [export](https://docs.milaboratories.com/mixcr/reference/mixcr-export/)

**Comment by suntaosimon** [comment]
> Yes, it is possible, just follow the docs in [export](https://docs.milaboratories.com/mixcr/reference/mixcr-export/)

oh, I think I got it! Thank you!
