### ISSUE TITLE
JThenV and VThenJ

### ISSUE THREAD

**Issue by zznx** [milaboratory/mixcr#686]
hi,
To better understand mixcr, can you tell me the difference between JThenV and VThenJ?
thanks

**Comment by PoslavskySV** [comment]
Hi,

from the [docs](https://mixcr.readthedocs.io/en/develop/align.html):

Order in which V and J genes aligned in target (possible values JThenV and VThenJ). Parameter affects only single-read alignments and alignments of overlapped paired-end reads. Non-overlaping paired-end reads are always processed in VThenJ mode. JThenV can be used for short reads (~100bp) with full (or nearly full) J gene coverage.
