### ISSUE TITLE
MiXCR v3.0.14 and Immcantation

### ISSUE THREAD

**Issue by aislinnjennings** [milaboratory/mixcr#689]
Hi.

I'm wondering when the next version of MiXCR will be released?
 I believe it's expected to be AIRR compliant?

I would like to be able to use MiXCR output in the Immcantation pipelines, but I don't believe this is possible with the current version unfortunately :( I want to do somatic hypermutation analysis on BCR data which Immcantation looks to address well.

Any ideas of a release date for v14? Or an alternative to Immcantation I can use? 
I'm a big fan of MIGEC and MiXCR and hopefully won't be forced to deviate.

Thanks
Ais.

**Comment by PoslavskySV** [comment]
Hi Ais,

MiXCR 4.0 release will be rolled out on 1st o June, and it supports AIRR format as well. Also, later in June we will roll out beta version of SHM trees and allele identification natively in MiXCR; it will be possible to use MiXCR as an alternative to immcantation then. 

Warm regards,
Stan

**Comment by aislinnjennings** [comment]
Hi Stan.

Hope you are well.
That is great to hear. Thanks a million. Looking forward to using the new MiXCR on Wednesday.

On a sidenote; I was wondering if you could help with another issue please.

 I'm trying to run the following bash script through the terminal on my Mac. The bash script is designed to run all my fastq files in a folder through the MiXCR pipeline, as opposed to individually.

I have 'A' on the last line as I was getting the error:

Output file name prefix, matches the existing file name.


However, then it writes over all the analysed files in the folder with 'A'.
Do you have any ideas for code I can use to run MiXCR as a loop and keep the output for each sample?


Thanks so much for all the help.
Appreciate it.

BW,
Ais.


________________________________

**Comment by dbolotin** [comment]
Hi Stan,

we just release [MiXCR v4.0](https://github.com/milaboratory/mixcr/releases/tag/v4.0.0)

regarding the AIRR format, please see this [example](https://github.com/milaboratory/mixcr/wiki/Export-of-AIRR-formatted-tsv). Please note, that most probably you also should give repseqio exported reference library to the immcantation pipeline to set both software packages in sync regarding the germline segment sequences and their markup.

regarding your question about script, you seem to be writing output to the same files, you should somehow derive last parameter from the input file names.

Best,
Dmitry.
