### ISSUE TITLE
Some mandatory columns are absent in the input file

### ISSUE THREAD

**Issue by sean-bigsheng** [milaboratory/mixcr#690]
mixCR version == 3.0.13; vdjtools version == 1.2.1
I used `Java -Xmx4g -Xms3g -jar F:\mixcr-3.0.13\mixcr.jar analyze amplicon  -s hsa  --starting-material dna  --5-end v-primers --3-end c-primers  --adapters adapters-present  D:\1\FCHH3LYCCX2_L1_HOMknpwR113488-33-1_1.fq.gz  D:\1\FCHH3LYCCX2_L1_HOMknpwR113488-33-1_2.fq.gz D:\result\ERR3445170`
 it worded very well.
BUT, next step made me confused:
`java -jar F:\vdjtools-1.2.1/vdjtools-1.2.1.jar Convert -S mixcr D:\vdjtools_files\ERR3445170.TRB.txt D:\vdjtools_files\`
```
Sat May 28 17:49:29 GMT+08:00 2022 Convert] Reading sample(s)
[Sat May 28 17:49:29 GMT+08:00 2022 Convert] 1 sample(s) loaded
[Sat May 28 17:49:29 GMT+08:00 2022 SampleStreamConnection] Loading sample ERR3445170.clonotypes.TRB
[ERROR] java.lang.RuntimeException: Unable to parse clonotype string 795694     0.08793043221498285     TGCGCCAGCAGCCTAGGACAGAGCACAGATACGCAGTATTTT      CASSLGQSTDTQYF  TRBV5-1 TRBD1   TRBJ2-3 11      15      20      21 for MiXcr input type: Some mandatory columns are absent in the input file., see _vdjtools_error.log for details
```
Could you help me?

**Comment by PoslavskySV** [comment]
Hi, this not related to MiXCR, so I close it here. If you still experience issues with VDJTools, please contact us at support@milaboratories.com.

**Comment by linqy-immune** [comment]
Hello!!! I encountered the problem like yours "for MiXcr input type: Some mandatory columns are absent in the input file" and attempted to solve this for several days but didn't succeed. Could you please tell me how you solved this problem finally. Best wishes and thank you very much!

**Comment by mizraelson** [comment]
Please follow the instructions in #1617
