### ISSUE TITLE
Using cat

### ISSUE THREAD

**Issue by evcon131** [milaboratory/mixcr#691]
Is it possible to use cats? I've tried `--species cat`, `--species feliscatus`, and `--species felis_catus`. I believe it's in IMGT and I'm using imgt.202141-1.sv7.json

**Comment by dbolotin** [comment]
Hi, thanks for pointing out! We will add cat importing rules to our IMGT library converter in a coupe of weeks.

**Comment by PoslavskySV** [comment]
Cat is added:

https://github.com/repseqio/library-imgt/releases/tag/v8

Also, please use latest MiXCR.
