### ISSUE TITLE
Codon usage and  Amber/Opal suppressors

### ISSUE THREAD

**Issue by rsneumann** [milaboratory/mixcr#693]
Hi, we are using Amber and Opal suppressor strains for BCR expression. Does MiXCR support alternative codon usage (TAG->Gln and TGA->Trp)? I could not find this in the docs, sorry if I missed it...
Thanks!

**Comment by PoslavskySV** [comment]
Hi,

Internally MiXCR works with nucleotide sequences and translates them to aa only in `export`. So you can use MiXCR but just don't use aa columns in export. You will have to manually translate nt to aa using your alphabet.
