### ISSUE TITLE
"Infinite" Alignment when using concatenated fastq files 

### ISSUE THREAD

**Issue by vd-dragan21** [milaboratory/mixcr#694]
## Checklist before submitting the issue:

 - [x] The issue is strongly related to the MiXCR software
 - [x] The issue can be reproduced with [the most recent version](https://github.com/milaboratory/mixcr/releases) of MiXCR
 - [x] There is no answer to the question in the [official documentation](http://mixcr.readthedocs.io/) and there is no duplicate issue in the [bug tracker](https://github.com/milaboratory/mixcr/issues?utf8=✓&q=)  
 - [x] Inspection of raw alignments with [exportAlignmentsPretty](http://mixcr.readthedocs.io/en/master/export.html#exporting-well-formatted-alignments-for-manual-inspection) shows that data has the expected architecture, and sample preparation artefacts are not the reason of the problem (if this is the matter of the issue)

## Expected Result

I'm trying to run mixcr analysis shotgun on the merged fastq.gz files. One big sample was split in smaller ones for paired sequencing, so I have several R1 and R2 files for each sample. I want to analyze the whole sample, so I'm merging all R1s and all R2s with each other first.

## Actual Result
When running the code, I'm getting "infinite alignment" as output. It looks like it is still working but I was confused by the infinity. Should I be worried?
Alignment: ∞%
Alignment: ∞%
Alignment: ∞%
Alignment: ∞%
Alignment: ∞%

## Exact MiXCR commands 
I'm concatenating fastq.gz files and giving them to the mixcr command through the named pipe: 

mkfifo R1
mkfifo R2
zcat *R1.fastq.gz > R1 &
zcat *R2.fastq.gz > R2 &
 
mixcr analyze shotgun -s hs --starting-material rna --report $output/report R1 R2 $output/test.analysis

## MiXCR report files 

Report file looks normal but not sure if the results are reliable. When using a single (not merged) fastq/fastq.gz file, everything is working fine and the alignment starts with 0%.

**Comment by PoslavskySV** [comment]
Hi,

this is fine and the the reason is that MiXCR needs to know the input file size to compute ETA. In case of piped input, MiXCR does not know the size of the input files in advance, so it shows you infinity. 

Best,
Stan
