### ISSUE TITLE
License errors MIXCR 4.0

### ISSUE THREAD

**Issue by vd-dragan21** [milaboratory/mixcr#698]
## Checklist before submitting the issue:

 - [x] The issue is strongly related to the MiXCR software
 - [x] The issue can be reproduced with [the most recent version](https://github.com/milaboratory/mixcr/releases) of MiXCR
 - [x] There is no answer to the question in the [official documentation](http://mixcr.readthedocs.io/) and there is no duplicate issue in the [bug tracker](https://github.com/milaboratory/mixcr/issues?utf8=✓&q=)  
 - [x] Inspection of raw alignments with [exportAlignmentsPretty](http://mixcr.readthedocs.io/en/master/export.html#exporting-well-formatted-alignments-for-manual-inspection) shows that data has the expected architecture, and sample preparation artefacts are not the reason of the problem (if this is the matter of the issue)

## Expected Result
Upgraded my mixcr to the new released MIXCR 4.0, got the license per email, activated it successfully and also successfully ran several commands on the small test data. When trying to run on the actual data, I started to get license errors (different errors for different runs), see below.

I could also come back to the previous MIXCR version but I'm having another error as described in the https://github.com/milaboratory/mixcr/issues/648.

## Actual Result

License error: ConnectionError
License error: UnknownError
License error: WrongValidityPeriod: License expired

## Exact MiXCR commands 

Just usuall MIXCR command, that was working fine before: 
mixcr analyze shotgun \
	-s hs \
        --starting-material rna \
	--report $outdir/report.shotgun \
         $outdir/R1  $outdir/R2 ${outdir}/analysis

## MiXCR report files 

No report files, since the errors occurred before the first step was done.

**Comment by PoslavskySV** [comment]
Hi,

it seems that you are running MiXCR on offline sever. MiXCR academic license requires internet connection to validate periodically. Please, write us on licensing@milaboratories.com to inquire for offline license.
