### ISSUE TITLE
Missing FR4 aa sequence

### ISSUE THREAD

**Issue by rsneumann** [milaboratory/mixcr#701]
Hi,
I am struggeling with getting MiXCR to output FR4 aa sequences.
I have two IGH sequences, I produce alignments as "mixcr align -s hsa  in.fastq out.vdjca", I then export alignments as "mixcr exportAlignments -aaFeature FR4  out.vdjca out.txt". From the first sequence I get the FR4 sequence "SQGTLVTVSS", but the second sequence does not give me any sequence (blank string). Using the "exportAlignmentsPretty" option, I have looked at the alignments, and J-gene alignment for the second sequence scores higher than that for the first sequence (211 vs 190). Why does MiXCR not give me the second FR4 sequence?

Thanks for any help!

The two sequences are: 

@seq1
TGCAGTCGAACATGTAGCTGACTCAGGTCACTGAGCGGATAACAATTTCACACAGAATTCATTAAAGAGGAGAAATTAACCATGGCCCAGGTGCAAGCTACAGCAGTGGGGCGCAGGACTGTTGAAGCCTTCGGAGACCCTGTCCCACACCTGCGCTGTCTATGGTGGGTCCTTCAGTGGTTACTACTGGAGCTGGATCCGCCAGCCCCCAGGGAAGGGGCTGGAGTGGATTGGGGAAATCAATCATAGTGGAAGCACCAACTACAACGCGTCCCTCAAGAGTCGAGTCACCATATCAGTAGACACGTCCAAGAATCAGTTCTCCCTGAGGCTGACCTCTGTGACCGCCGCGGACACGGCTGTCTATTACTGTGCGAGAACACAGATTTTCTATGGTGGTAGTGACTATTACTACGGCTACTTTGACTACTGGAGCCAGGGAACCCTGGTCACTGTCTCCTCG
+
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
@seq2
TCACTGAGCGGATAACAATTTCACACAGAATTCATTAAAGAGGAGAAATTAACCATGGCCCAGATCACCTTGAAGGAGTCTGGTCCTACGCTGGTGAAACCCACACAGACCCTCACGCTGACCTGCACCTTCTCTGGGTTCTCACTCAGCACTAGTGGAGTGGGTGTGGGCTGGATCCGTCAGCCCCCAGGAAAGGCCCTGGAGTGGCTTGCACTCATTTATTGGGATGATGATAAGCGCTACAGCCCATCTCTGAAGAGCAGGCTCACCATCACCAATGACACCTCCAAAAACCAGGTGGTCCTTACAATGACCAACATGGACCCTGTGGACACAGCCACATATTACTGTGCACACAGTAAAGATACAGCTATGGGTTACTTTGACTACTGGGGCCAGGGAACCCTGGTCACTGTCTCCTCA
+
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII

**Comment by PoslavskySV** [comment]
Hi,

your second sequence does not fully cover FR4 (it misses one letter) which you can check with `exportAlignmentsPretty`, that is why you have empty FR4. If you need, you can use `-aaFeatureImputed FR4` to impute uncover part from germline.

**Comment by rsneumann** [comment]
Hi,
Thanks for your quick reply! My question is really part of a bigger issue that I am trying to understand.
We have IGH sequences that we try to align and assemble. Aligning produces sequences that do not have FR4 sequences (but yes, I can retrieve the FR4 imputed sequences). I then try to assemble, and want to retrieve the whole length of each clone exactly as sequenced (thus I cannot specify “-OassemblingFeatures=CDR3”, since this gives me the germline seuqences for FR1, CDR1, FR2 etc, not the actually sequenced sequences).
If I try “-OassemblingFeatures=FR1+CDR1+ FR2+CDR2+ FR3+CDR3” I get pretty good results (31190 clones), but I can only retrieve the imputed FR4 (almost always in lowercase letters, so the germline consensus rather than the actually sequenced sequences). If I try “-OassemblingFeatures=FR1+CDR1+ FR2+CDR2+ FR3+CDR3+FR4” I get hardly any clones at all (49 clones only). I think this happens because almost all FR4 sequences in the ali.vdjca are empty, even though FR4 imputed sequences give me good sequences…
Is there any way around this?
Thanks again!

**Comment by PoslavskySV** [comment]
Hi,

you should definitely try [`assembleContigs` functionality](https://mixcr.readthedocs.io/en/develop/assembleContigs.html) - it is specifically designed for your case. You can even assemble clones only by CDR3 and then run `assembleContigs` to get full coverage you have in the data. Let me know if you need further assistance, we can organize a brief zoom with our bioinformaticians to help with the exact commands.

Best,
Stan

**Comment by rsneumann** [comment]
Hi again,
I have now tried out the assembleContigs functionality. Unfortunately, some new problems are showing up…
For the assembled clones, I have to be able to trace back to all the reads supporting them. So far, this has not been a problem – I do as follows:
-build the alignments (“mixcr align”), output the alignments.vdjca file
-assemble clones (“mixcr assemble”),output the clones.clna file
-export cloneIds, readIds and read headers ("mixcr exportAlignments -cloneId -readIds -descrsR1”), output the ali.txt file

Based on the ali.txt file, I can now trace back each clonotype to its supporting reads.

However, when adding the assembleContigs functionality (“mixcr assembleContigs”, input clones.clna, output clones.clns) I lose this connection between the clones defined in the clones.clns file and the associated reads.

I have tried exporting the cloneId-readId-descrsR1 using the clones.clna as the input. This gives me the reads for the clones as defined in the clones.clna file, but I have found that the cloneIds in the clones.clns file differ from those of the clones.clna file. I tested this as follows:

-I am looking for sequences with a specific CDR3 sequence.
-The clones.clna and clones.clns have the same number of cloneIds (say, 0 to 1000).
-I find exactly four clones with my CDR3 sequence in both the clones.clna and the clones.clns file
-But the former (clones.clna) gives me the cloneIds 4, 27, 55 and 955. The other (clones.clns) gives me the cloneIds 4, 29, 57 and 955 (i.e. some are identical, some are slightly different…)

Because of this, the "mixcr exportAlignments -cloneId -readIds -descrsR1 clones.clna” command cannot give me the correct reads for clones 27/29 and 55/57. I have tried running the command as "mixcr exportAlignments -cloneId -readIds -descrsR1 clones.clns”, but this gives me an error….

Thanks for your help!

Ralf

**Comment by PoslavskySV** [comment]
Hi Ralf,

yes, `assembleContigs` "erases" in some sense the information clone<>readId and this is essentially the consequence of  how contig assembly works. In short, `contigAssembly` takes a clone from `clna` and all alignments that support this clone; it gathers the information from all alignments on how they cover different regions trying to build a "consensus" contig. During this procedure the initial clone may be divided into several ones, e.g. due to hypermutations. And at this step you really don't have a way to re-assign a portion of reads to a new clone, because different reads cover different regions. There are some ways to manage this if you really need to backtrack original reads. Can you describe for what purpose you need this backtracking and more general what is your project with the data? (If it's more easy we can zoom to discuss)

Best, 
Stan

**Comment by rsneumann** [comment]
The background is as follows:
We have paired IGH-linker-IGK receptor data, and I need to compute clonotypes for the paired data.
I do this as follows:
-I split each read based on the linker sequence
-I use Mixcr separately to annotate the heavy and the light chain sequence
-I have to put heavy and light chain data back together again (which heavy-chain clones go together with which light-chain clones).
Since the linkage between the heavy and light chain clones is defined by the shared  (IGH-linker-IGK) reads, I have to be able to extract all reads for every clone. If one particular heavy-chain clone is connected to one particular lightchain clone (via shared reads), then fine – we have one valid receptor clone. If for instance one heavy-chain clone is connected to two distinct light-chain clones, then we have two distinct receptors sharing the heavy chain in question.

Yes, zooming would be fine!

Ralf

**Comment by rsneumann** [comment]
Just one more thing:
The setup I described to you in the previous mail actually works very well (we are comparing our sequencing data to wetlab-Sanger-sequenced data, and both sequences and read counts seem reasonable).
The current problem of actually retrieving the sequenced FR4 sequence (rather than the germline sequence) is really the only (minor!) problem we are facing. We had a similar problem with the FR1 region (getting only the germline/imputed sequence, rather than the actually sequenced one), but I solved this by including the “-OvParameters.parameters.floatingLeftBound=false” parameter to the mixcr align command (we know that out sequences may depart from germline in the start of FR1, and it may be vital to get hold of the actual sequence – as we now have!). I have tried a similar approach with the FR4 region
(both “-OjParameters.parameters.floatingRightBound=false” and “-OjParameters.parameters.floatingRightBound=true”) but no luck…

Ralf

**Comment by PoslavskySV** [comment]
Thank you, now I understand your case. For the moment I suggest you to try

```
mixcr assemble -OassemblingFeatures="FR1+CDR1+ FR2+CDR2+ FR3+CDR3+FR4(0,-2)" ..
```

and then export with imputation (only last letters of FR4 will be imputed). Please, let me know how it will work.

Meanwhile we are going to implement an ability to add tags to the sequences from fastq headers (like with UMI or Cell-barcodes which are already supported), and then you'll be able to switch to `assembleContigs` pipeline and export tags for each clone in order to match heavy/light pairs.

**Comment by dongspy** [comment]
Hi,
I have similar problems. My sequence has fully covered  FR4, while the FR4 in the exportClones is null.

Is it the NNN(X) in the tail of sequence problem ?
If so, what should I do about it

<img width="861" alt="image" src="https://user-images.githubusercontent.com/32101973/192246448-7b8a2336-16dd-416e-95a3-d6c0b8ec6990.png">


Below is the sequence

@seq1
CAGGTCAACTTAAGGGAGTCCGGGGGTCGCCTGGTCACGCCTGGGACACCCCTGACACTCACCTGCACAGCCTCTGGATTCTCCCTCAACAACTACGACATGAGCTGGGTCCGCTAGGCTCCAGGGAAGGGGCTGGAGTGGATCGGATACATTTATGGTGGTGGTCTCGCCTACTACGCGAGCTGGGCGAAAGGCCGATTCAACATCTCCAAAACCTCGACCACGGTGGATCTGAAAATCACCAGTCCGACAACCGAGGACACGGCCACCTATTTCTGTGCCAGAGGTGATGTTTTTAACACTGCTTATGTGATGGACCTCTGGGGCCCAGGGACCNNGGTCACCGTCTCCTCANNCCCAGACCACCAGC

**Comment by zznx** [comment]
Hi,
Thanks to the mixcr team!

Do you mean that FR4 in the exportClones is null, possibly due to hypermutations

> Hi Ralf,
> 
> yes, `assembleContigs` "erases" in some sense the information clone<>readId and this is essentially the consequence of how contig assembly works. In short, `contigAssembly` takes a clone from `clna` and all alignments that support this clone; it gathers the information from all alignments on how they cover different regions trying to build a "consensus" contig. During this procedure the initial clone may be divided into several ones, e.g. due to hypermutations. And at this step you really don't have a way to re-assign a portion of reads to a new clone, because different reads cover different regions. There are some ways to manage this if you really need to backtrack original reads. Can you describe for what purpose you need this backtracking and more general what is your project with the data? (If it's more easy we can zoom to discuss)
> 
> Best, Stan
