### ISSUE TITLE
No report file is created from correctAndSortTags

### ISSUE THREAD

**Issue by michaeleekk** [milaboratory/mixcr#705]
## Checklist before submitting the issue:

 - [x] The issue is strongly related to the MiXCR software
 - [x] The issue can be reproduced with [the most recent version](https://github.com/milaboratory/mixcr/releases) of MiXCR
 - [x] There is no answer to the question in the [official documentation](http://mixcr.readthedocs.io/) and there is no duplicate issue in the [bug tracker](https://github.com/milaboratory/mixcr/issues?utf8=✓&q=)  
 - [ ] Inspection of raw alignments with [exportAlignmentsPretty](http://mixcr.readthedocs.io/en/master/export.html#exporting-well-formatted-alignments-for-manual-inspection) shows that data has the expected architecture, and sample preparation artefacts are not the reason of the problem (if this is the matter of the issue)

## Expected Result

I followed [this guide](https://github.com/milaboratory/mixcr/wiki/Analysis-of-10X-Single-Cell-data) and used `correctAndSortTags` function and expected to have a report file with `--report` or `-r`

## Actual Result

No report file is created at the `correctAndSortTags` step.

## Exact MiXCR commands 

`mixcr correctAndSortTags -report barcode.correction.report alignments.vdjca alignments.corrected.vdjca`

## MiXCR report files 

No report file.

**Comment by dbolotin** [comment]
Thanks for reporting! Fix is already in develop, will be released with 4.1.
