### ISSUE TITLE
Different results between mixcr analyze amplicon and four separate steps

### ISSUE THREAD

**Issue by wuying1984** [milaboratory/mixcr#712]
Hi,

I am analyzing TCR profiling sequencing data from SMARTer Mouse TCR ab Profiling Kit using MIXCR. The sequencing reads are from Miseq, and both reads have 300bp. 
I used two types of command, but got different results. I wonder if the parameter between analysze amplicon is different from the four steps. Which one I should use for the profiling?

**command #1:**  
mixcr analyze amplicon -s mmu --starting-material  rna --5-end no-v-primers --3-end c-primers --adapters no-adapters --receptor-type TCR --only-productive --contig-assembly --export "-p full" --verbose  read1.fastq read2.fastq project_name 1>TCR_command1.log 2>TCR_command1.err

In the result, I got 
Total sequencing reads: 7104110
Successfully aligned reads: 6346412 (89.33%)
Final clonotype count: 70156
Average number of reads per clonotype: 79.74
TRA chains: 70147 (99.99%)
And in the clonotypes.TRA.txt and clonotypes.TRD.txt file, I get both 59444 clonotypes (I think they are productive ones).

**command#2:**
mixcr align --species mmu --report report_align.txt read1.fastq read2.fastq  alignments.vdjca 1>0align.log 2>0align.err
mixcr assemble --write-alignments --report report_assemble.txt alignments.vdjca clones.clna  1>1assemble.log 2>1assemble.err
mixcr assembleContigs --report repor_assembleContigs.txt clones.clna full_clones.clns 1>2assembleContig.log 2>2assembleContig.err
mixcr exportClones -c TRA -p full full_clones.clns full_clones_TRA.txt 1>exportTRA.log 2>exportTRA.err
mixcr exportClones -c TRB -p full full_clones.clns full_clones_TRB.txt 1>exportTRB.log 2>exportTRB.err
mixcr exportClones -c TRD -p full full_clones.clns full_clones_TRD.txt 1>exportTRD.log 2>export_TRD.err

In this analysis, I got the results:
Total sequencing reads: 7104110
Successfully aligned reads: 6563493 (92.39%)
Final clonotype count: 36739
Average number of reads per clonotype: 165.6
TRA chains: 36726 (99.96%)
TRB chains: 2 (0.01%)
TRD chains: 7 (0.02%)

And in the clonotypes.TRA.txt and clonotypes.TRD.txt file, I get both 36737 clonotypes. And there are 2 clonotypes in clonotypes.TRB.txt.

My questions are
1) why the results from the above two commands are different? I used both default parameters for the two commands, whether the parameters are different?
2)Since the two results are different, which command do you suggest to use.
3)For the command#2, there are no column in the final clonotypes.TRA.txt file labeled as "productivity" Are all the clonotypes are productive? Where I can get that information?

Thank you very much and look forward to you answers!

Best,
Ying

**Comment by PoslavskySV** [comment]
Hi Ying,

you can check here what is the pipeline under the hood of analyze: https://mixcr.readthedocs.io/en/develop/analyze.html#analysis-of-targeted-tcr-ig-libraries 

In short, you have to tune align options based on the primers/adapters options, and in your case I guess it will be the following:

```
    -OvParameters.parameters.floatingLeftBound=false \
    -OjParameters.parameters.floatingRightBound=false \
    -OcParameters.parameters.floatingRightBound=true \
```

Please let me know the results. 

Best,
Stan

**Comment by wuying1984** [comment]
Hi Stan,

I added the parameters you suggested, but still get 36309 clonetypes for the separate pipelines .
my command:
mixcr align --species mmu **-OvParameters.parameters.floatingLeftBound=false -OjParameters.parameters.floatingRightBound=false -OcParameters.parameters.floatingRightBound=true**    --report report_align.txt read1.fastq read2.fastq   alignments.vdjca 1>0align.log 2>0align.err
mixcr assembleContigs --report repor_assembleContigs.txt clones.clna full_clones.clns 1>2assembleContig.log 2>2assembleContig.err
mixcr exportClones -c TRA -p full full_clones.clns full_clones_TRA.txt 1>exportTRA.log 2>exportTRA.err
mixcr exportClones -c TRB -p full full_clones.clns full_clones_TRB.txt 1>exportTRB.log 2>exportTRB.err
mixcr exportClones -c TRD -p full full_clones.clns full_clones_TRD.txt 1>exportTRD.log 2>export_TRD.err

In this analysis, I got the results:
Total sequencing reads: 7104110
Successfully aligned reads: 6393604 (90%)
Final clonotype count: 36309
Average number of reads per clonotype: 163.45
TRA chains: 36294 (99.96%)
TRB chains: 1 (0%)
TRD chains: 10 (0.03%)

The clonotypes number is still much less than that from the one step command (Clonotype number: 70156, productive clonotypes 59444).
mixcr analyze amplicon -s mmu --starting-material rna --5-end no-v-primers --3-end c-primers --adapters no-adapters --receptor-type TCR --only-productive --contig-assembly --export "-p full" --verbose read1.fastq read2.fastq project_name 1>TCR_command1.log 2>TCR_command1.err

Best,
Ying

**Comment by PoslavskySV** [comment]
Closing this issue so far as it is not reproduced. Please, update to the most recent version of MiXCR.
