### ISSUE TITLE
IGL can be aligned but can not be assembled?

### ISSUE THREAD

**Issue by suntaosimon** [milaboratory/mixcr#716]
dear mixcr,
I used the IMGT pig library.
With the default command, after alignment I can get,
IGH chains: 74430 (21.77%)
IGK chains: 129449 (37.86%)
IGL chains: 138048 (40.37%)

but after assembling, 
the IGL chain is missing as,
IGH chains: 100092 (85.95%)
IGK chains: 16355 (14.05%)

so, when I export IGL, there is nothing in the export txt file.

I manually use mixcr exportAlignmentsPretty command to check the vdjca file, I can see many IGL reads with CDR3, starting with  "C" in V region and "F" appearing in the J region. 

<img width="782" alt="image" src="https://user-images.githubusercontent.com/3598340/177168821-53c5c348-a165-4653-95f3-a9f91249be2e.png">

that's weird.

Thanks for any recommendations !

**Comment by suntaosimon** [comment]
> 

MiXCR v3.0.13

**Comment by PoslavskySV** [comment]
Could you check it with v4 and with the latest release of IMGT library please? May things were fixed in v4

**Comment by suntaosimon** [comment]
IGH chains: 74180 (21.71%)
IGK chains: 129435 (37.88%)
IGL chains: 138045 (40.4%)

**Comment by PoslavskySV** [comment]
Got it, thanks! Could you please paste the full report? Also, can you check exportClonesPretty to validate that there are no IGKL clones, because it may be a bug in the report.

**Comment by dbolotin** [comment]
Please also post complete command you used for alignment.

**Comment by dbolotin** [comment]
Please also confirm you used IMGT reference from [here](https://github.com/repseqio/library-imgt/releases).

**Comment by suntaosimon** [comment]
> Got it, thanks! Could you please paste the full report? Also, can you check exportClonesPretty to validate that there are no IGKL clones, because it may be a bug in the report.

there are no IGKL clones after check with exportClonesPretty

here is the full report and full commands,



Input file(s): pig_bcr-1_R1.fastq.gz,pig_bcr-1_R2.fastq.gz
Output file(s): pig_bcr-1.alignment.vdjca
Version: 4.0.0a; built=Fri Jun 17 03:52:47 CST 2022; rev=c604f8d43b; lib=repseqio.v2.0
Command line arguments: align --library pig_BCR_20220704.json --species pig -OallowPartialAlignments=true -OvParameters.geneFeatureToAlign=VTranscript --report pig_bcr-1.alignmentReport.log pig_bcr-1_R1.fastq.gz pig_bcr-1_R2.fastq.gz pig_bcr-1.alignment.vdjca
Analysis time: 1.02m
Total sequencing reads: 507164
Successfully aligned reads: 341660 (67.37%)
Paired-end alignment conflicts eliminated: 827 (0.16%)
Alignment failed, no hits (not TCR/IG?): 50934 (10.04%)
Alignment failed because of absence of CDR3 parts: 33619 (6.63%)
Alignment failed because of low total score: 80951 (15.96%)
Overlapped: 125324 (24.71%)
Overlapped and aligned: 27390 (5.4%)
Alignment-aided overlaps: 264 (0.96%)
Overlapped and not aligned: 97934 (19.31%)
No CDR3 parts alignments, percent of successfully aligned: 39 (0.01%)
Partial aligned reads, percent of successfully aligned: 173478 (50.78%)
V gene chimeras: 866 (0.17%)
J gene chimeras: 86 (0.02%)
IGH chains: 74180 (21.71%)
IGK chains: 129435 (37.88%)
IGL chains: 138045 (40.4%)
Realigned with forced non-floating bound: 764208 (150.68%)
Realigned with forced non-floating right bound in left read: 10379 (2.05%)
Realigned with forced non-floating left bound in right read: 10379 (2.05%)
======================================

Input file(s): pig_bcr-1.alignment.vdjca
Output file(s): pig_bcr-1.alignment.clns
Version: 4.0.0a; built=Fri Jun 17 03:52:47 CST 2022; rev=c604f8d43b; lib=repseqio.v2.0
Command line arguments: assemble --report pig_bcr-1.clonReport.log pig_bcr-1.alignment.vdjca pig_bcr-1.alignment.clns
Analysis time: 11.94s
Final clonotype count: 71967
Average number of reads per clonotype: 2.32
Reads used in clonotypes, percent of total: 166816 (32.89%)
Reads used in clonotypes before clustering, percent of total: 166816 (32.89%)
Number of reads used as a core, percent of used: 166657 (99.9%)
Mapped low quality reads, percent of used: 159 (0.1%)
Reads clustered in PCR error correction, percent of used: 0 (0%)
Reads pre-clustered due to the similar VJC-lists, percent of used: 0 (0%)
Reads dropped due to the lack of a clone sequence, percent of total: 1 (0%)
Reads dropped due to low quality, percent of total: 3 (0%)
Reads dropped due to failed mapping, percent of total: 1332 (0.26%)
Reads dropped with low quality clones, percent of total: 0 (0%)
Clonotypes eliminated by PCR error correction: 0
Clonotypes dropped as low quality: 0
Clonotypes pre-clustered due to the similar VJC-lists: 0
Clonotypes dropped in fine filtering: 0
Partially aligned reads attached to clones by tags: 0 (0%)
Partially aligned reads with ambiguous clone attachments by tags: 0 (0%)
Partially aligned reads failed to attach to clones by tags: 0 (0%)
IGH chains: 59539 (82.73%)
IGK chains: 12428 (17.27%)
======================================

**Comment by suntaosimon** [comment]
> Please also confirm you used IMGT reference from [here](https://github.com/repseqio/library-imgt/releases).

I have checked the IMGT reference from the link, and noticed there is no pig BCR database, so I used my own build IMGT pig bcr library. (made with [repseqio](https://github.com/repseqio/repseqio))

**Comment by suntaosimon** [comment]
> Please try the latest build from the link I posted above. The library you use seem to have wrong or absent positions of 'CDR3End' for J genes.

latest build of IMGT reference from [here](https://github.com/repseqio/library-imgt/releases)? But there is no pig BCR in the reference, only pig TRB.

**Comment by dbolotin** [comment]
It contains pig BCRs, it was added back in 2021 in v7 build.

**Comment by suntaosimon** [comment]
> It contains pig BCRs, it was added back in 2021 in v7 build.

That works! thanks!
