### ISSUE TITLE
Cat TRA and TRD files are empty

### ISSUE THREAD

**Issue by evcon131** [milaboratory/mixcr#719]
# Expected Result

Output files with TRA and TRD clones

## Actual Result
TRA and TRD files are empty

## Exact MiXCR commands 
```
mixcr analyze shotgun -f -t 4 \
--library imgt \
--species cat \
--starting-material rna \
--report DU125841.rep.txt \
../trim/DU125841_1_val_1.fq.gz \
../trim/DU125841_2_val_2.fq.gz \
DU125841
```

## MiXCR report files 

DU125841.clonotypes.TRA.txt and DU125841.clonotypes.TRD.txt are empty, IGH is as well, but that is missing from IMGT so I think that's to be expected. Sorry to be the annoying crazy cat person.

**Comment by PoslavskySV** [comment]
Hi,

can you paste reports files produced by MiXCR?

**Comment by evcon131** [comment]
Sure, here's a .rep.txt

Analysis date: Fri Jul 01 16:56:58 MDT 2022
Input file(s): ../trim/DU147694_1_val_1.fq.gz,../trim/DU147694_2_val_2.fq.gz
Output file(s): DU147694.vdjca
Version: 4.0.0a; built=Thu Jun 16 13:52:47 MDT 2022; rev=c604f8d43b; lib=repseqio.v2.0
Command line arguments: -OallowPartialAlignments=true --species cat --library imgt --threads 4 --report DU147694.rep.txt -p rna-seq -OvParameters.geneFeatureToAlign=VTranscriptWithP ../trim/DU147694_1_val_1.fq.gz ../trim/DU147694_2_val_2.fq.gz DU147694.vdjca
Analysis time: 90.3m
Total sequencing reads: 77954580
Successfully aligned reads: 113668 (0.15%)
Paired-end alignment conflicts eliminated: 771 (0%)
Alignment failed, no hits (not TCR/IG?): 77686790 (99.66%)
Alignment failed because of absence of CDR3 parts: 84393 (0.11%)
Alignment failed because of low total score: 69729 (0.09%)
Overlapped: 50015324 (64.16%)
Overlapped and aligned: 73601 (0.09%)
Alignment-aided overlaps: 9217 (12.52%)
Overlapped and not aligned: 49941723 (64.07%)
No CDR3 parts alignments, percent of successfully aligned: 886 (0.78%)
Partial aligned reads, percent of successfully aligned: 48790 (42.92%)
V gene chimeras: 791 (0%)
J gene chimeras: 13 (0%)
TRB chains: 7486 (6.59%)
TRG chains: 19815 (17.43%)
IGK chains: 12711 (11.18%)
IGL chains: 73656 (64.8%)
Realigned with forced non-floating bound: 55896946 (71.7%)
Realigned with forced non-floating right bound in left read: 8136 (0.01%)
Realigned with forced non-floating left bound in right read: 8136 (0.01%)
======================================
Analysis date: Fri Jul 01 18:27:18 MDT 2022
Input file(s): DU147694.vdjca
Output file(s): DU147694.rescued_0.vdjca
Version: 4.0.0a; built=Thu Jun 16 13:52:47 MDT 2022; rev=c604f8d43b; lib=repseqio.v2.0
Command line arguments: --report DU147694.rep.txt DU147694.vdjca DU147694.rescued_0.vdjca
Analysis time: 7.32s
Total alignments analysed: 113668
Number of output alignments: 110893 (97.56%)
Alignments already with CDR3 (no overlapping is performed): 63917 (56.23%)
Successfully overlapped alignments: 2775 (2.44%)
Left parts with too small N-region (failed to extract k-mer): 10957 (9.64%)
Extracted k-mer diversity: 29021
Dropped due to wildcard in k-mer: 0 (0%)
Dropped due to too short NRegion parts in overlap: 2046 (1.8%)
Dropped overlaps with empty N region due to no complete NDN coverage: 264 (0.23%)
Number of left-side alignments: 7143 (6.28%)
Number of right-side alignments: 34430 (30.29%)
Complex overlaps: 0 (0%)
Over-overlaps: 22 (0.02%)
Partial alignments written to output: 44201 (38.89%)
======================================
Analysis date: Fri Jul 01 18:27:25 MDT 2022
Input file(s): DU147694.rescued_0.vdjca
Output file(s): DU147694.rescued_1.vdjca
Version: 4.0.0a; built=Thu Jun 16 13:52:47 MDT 2022; rev=c604f8d43b; lib=repseqio.v2.0
Command line arguments: --report DU147694.rep.txt DU147694.rescued_0.vdjca DU147694.rescued_1.vdjca
Analysis time: 3.17s
Total alignments analysed: 110893
Number of output alignments: 110885 (99.99%)
Alignments already with CDR3 (no overlapping is performed): 66661 (60.11%)
Successfully overlapped alignments: 8 (0.01%)
Left parts with too small N-region (failed to extract k-mer): 10749 (9.69%)
Extracted k-mer diversity: 25103
Dropped due to wildcard in k-mer: 0 (0%)
Dropped due to too short NRegion parts in overlap: 1631 (1.47%)
Dropped overlaps with empty N region due to no complete NDN coverage: 232 (0.21%)
Number of left-side alignments: 4271 (3.85%)
Number of right-side alignments: 31546 (28.45%)
Complex overlaps: 0 (0%)
Over-overlaps: 7 (0.01%)
Partial alignments written to output: 44216 (39.87%)
======================================
Analysis date: Fri Jul 01 18:27:28 MDT 2022
Input file(s): DU147694.rescued_1.vdjca
Output file(s): DU147694.extended.vdjca
Version: 4.0.0a; built=Thu Jun 16 13:52:47 MDT 2022; rev=c604f8d43b; lib=repseqio.v2.0
Command line arguments: --report DU147694.rep.txt --threads 4 DU147694.rescued_1.vdjca DU147694.extended.vdjca
Analysis time: 1.61s
Extended alignments count: 285 (0.26%)
V extensions total: 13 (0.01%)
V extensions with merged targets: 2 (0%)
J extensions total: 272 (0.25%)
J extensions with merged targets: 16 (0.01%)
V+J extensions: 16 (0.01%)
Mean V extension length: 2.3076923076923075
Mean J extension length: 21.345588235294116
======================================
Analysis date: Fri Jul 01 18:27:30 MDT 2022
Input file(s): DU147694.extended.vdjca
Output file(s): DU147694.clns
Version: 4.0.0a; built=Thu Jun 16 13:52:47 MDT 2022; rev=c604f8d43b; lib=repseqio.v2.0
Command line arguments: --report DU147694.rep.txt --threads 4 -OseparateByV=true -OseparateByJ=true DU147694.extended.vdjca DU147694.clns
Analysis time: 3.46s
Final clonotype count: 7217
Average number of reads per clonotype: 9.12
Reads used in clonotypes, percent of total: 65792 (0.08%)
Reads used in clonotypes before clustering, percent of total: 65796 (0.08%)
Number of reads used as a core, percent of used: 64176 (97.54%)
Mapped low quality reads, percent of used: 1620 (2.46%)
Reads clustered in PCR error correction, percent of used: 4 (0.01%)
Reads pre-clustered due to the similar VJC-lists, percent of used: 232 (0.35%)
Reads dropped due to the lack of a clone sequence, percent of total: 0 (0%)
Reads dropped due to low quality, percent of total: 0 (0%)
Reads dropped due to failed mapping, percent of total: 1974 (0%)
Reads dropped with low quality clones, percent of total: 1934 (0%)
Clonotypes eliminated by PCR error correction: 2
Clonotypes dropped as low quality: 266
Clonotypes pre-clustered due to the similar VJC-lists: 81
Clonotypes dropped in fine filtering: 0
Partially aligned reads attached to clones by tags: 0 (0%)
Partially aligned reads with ambiguous clone attachments by tags: 0 (0%)
Partially aligned reads failed to attach to clones by tags: 0 (0%)
TRB chains: 44 (0.61%)
TRG chains: 186 (2.58%)
IGK chains: 842 (11.67%)
IGL chains: 6145 (85.15%)
======================================

**Comment by PoslavskySV** [comment]
Did you use the most recent IMGT library (https://github.com/repseqio/library-imgt/releases)? From the reports it is seen that there are no any TRA/D assignments.

**Comment by evcon131** [comment]
I did use the most recent one, I don't know any java, but I did use python to read the json file and I think TRA and TRD are missing from it.

**Comment by Alex-Davydov** [comment]
Hi,
unfortunately now we can't include cats TRA/TRD locus in the library due to reference format issue. We will try to add them in the future releases.
