### ISSUE TITLE
V/D/J annotations with *00 allelic information

### ISSUE THREAD

**Issue by zktuong** [milaboratory/mixcr#721]
Hi MiXCR team, 

i'm trying to reannotate some short TRB nucleotide sequences (immunoSeq data) with MiXCR version 3/4 and was wondering if i'm doing anything wrong:

I created a small fasta file from the nucleotide sequences:
```
>test1
CGCACACAGCAGGAGGACTCGGCCGTGTATCTCTGTGCCAGCAGCTTAGTGGCAGGGATACTCTCAACCTGGCAGTTCTTCGGGCCA
>test2
CCGACAGCTTTCTATCTCTGTGCCAGTAGTACCACAGGGTGGGGAGTCTTCCGAAGAGGAGAAGAACATGGGCAGTTCTTCGGGCCA
>test3
CTTGGAGATCCAGTCCACGGAGTCAGGGGACACAGCACTGTATTTCTGTGCCAGCAGTCGGGACAGCCTGAGCAGTTCTTCGGGCCA
```

And ran it in `shotgun` mode
```bash
mixcr analyze shotgun -s hsa --starting-material DNA --receptor-type trb test.fa test
```

When I looked at the output file,  all the V/D/J calls were return with `*00`. 
```pandas
import pandas as pd
df = pd.read_csv('test.clonotypes.TRB.txt', sep ='\t')
df[['aaSeqCDR3', 'allVHitsWithScore', 'allDHitsWithScore', 'allJHitsWithScore']]
               aaSeqCDR3                allVHitsWithScore allDHitsWithScore allJHitsWithScore
0  CASSTTGWGVFRRGEEHGQFF                   TRBV19*00(155)      TRBD1*00(30)    TRBJ2-1*00(84)
1       CASSLVAGILSTWQFF  TRBV7-2*00(245),TRBV7-8*00(229)      TRBD1*00(25)    TRBJ2-1*00(80)
2           CASSRD_PEQFF                 TRBV21-1*00(285)      TRBD1*00(40)    TRBJ2-1*00(95)
```
Is this behavior expected? What does it mean when it's `*00`?

**Comment by mizraelson** [comment]
Yes, you can use IMGT reference instead of MiXCR build-in reference, and you will see allelic variants. But we urge to be really cautious about TCR alleles data in IMGT reference.

**Comment by zktuong** [comment]
thank you! that clarifies a lot. I'll close this issue now.
