### ISSUE TITLE
License issue (mixcr hangs)

### ISSUE THREAD

**Issue by vd-dragan21** [milaboratory/mixcr#722]
## Expected Result

I was using the mixcr 4.0 with the offline license, it worked fine for me, I started the analysis for some samples on the 6th of July and everything went fine and I had results on the day after. On 8th of July I wanted to run another mixcr command and it just didn't respond (the terminal was hanging, while other applications are working fine for me). I didn't change anything between these 2 days, would be thankful for your help!

## Actual Result

I  might have exited the running mixcr command with ctrl+Z before but I checked for the background processes and killed the java-related ones but it didn't help. I reinstalled the software, tried to activate the license again and got the following erroŕ:
Checking the license...
License Error:
UnknownError
null 

## Exact MiXCR commands 

mixcr activate-license

**Comment by vd-dragan21** [comment]
Could successfully activate the license with the new build that was sent to me for another issue #720 (https://cdn.milaboratory.com/software/mixcr/mixcr-4.0.0-27-develop-03bac154c210ea66e5afb4d1b66d94d2c0730e8d.zip). The mixcr is working fine for me again.

**Comment by PoslavskySV** [comment]
Proxy settings are fixed in [MiXCR 4.3](https://github.com/milaboratory/mixcr/releases/tag/v4.3.1). For general firewall instructions see [this doc](https://mixcr.com/mixcr/getting-started/milm/#offline-use).
