### ISSUE TITLE
Metadata downstream analysis mixcr 4.0

### ISSUE THREAD

**Issue by vd-dragan21** [milaboratory/mixcr#723]
I'm testing the new functions of downstream analysis in MiXCR 4.0 (https://github.com/milaboratory/mixcr/wiki/Downstream-analysis#downsampling)
In the usage examples all commands are having metadata as an input file. Could you provide the format of metadata the MiXCR is expecting? Thank you!

**Comment by PoslavskySV** [comment]
Hi Valeriia,

sorry for inconvenience, we are building new documentation portal which we will make public in July, it will have all the docs. Meanwhile for metadata: it should be a tsv/csv file, and it must contain "sample" column with the names of samples. Optionally it may have "chain" column if you have separate alpha/beta or heavy/light samples.
