### ISSUE TITLE
Wrong document? floatingRightBound, True or False?

### ISSUE THREAD

**Issue by suntaosimon** [milaboratory/mixcr#729]
![image](https://user-images.githubusercontent.com/3598340/180400060-6fe44785-27e4-4513-af20-a2e12f29e2bf.png)

Please see the document from https://mixcr.readthedocs.io/en/develop/align.html?highlight=floatingRightBound#v-j-and-c-aligners-parameters

I want to double-check the parameter. The default J value of floatingRightBound is False, but "you can change value of this parameter for J gene to false" again? Should here be "True"?

Thanks!

**Comment by PoslavskySV** [comment]
Yep, docs are misleading, you are right

https://github.com/milaboratory/mixcr/blob/ce099272578f0e76c35ef2920bcdfe9a5850c8a9/src/main/resources/parameters/vdjcaligner_parameters.json#L53


Thanks for reporting!

**Comment by suntaosimon** [comment]
I used VJ primers and set this parameter to true, how bad will the results be?

>

**Comment by PoslavskySV** [comment]
I can't say, that largely depends on many factors and on what you are expecting to get from the data. What I can definitely suggest is to inspect your alignments with `exportAlignmentsPretty`  command (also you can use  `-OallowNoCDR3PartAlignments=true` and `-OallowPartialAlignments=true` for `align` to see partial alignments as well).

**Comment by PoslavskySV** [comment]
and on the 99% it depends on the quality of the library itself
