### ISSUE TITLE
V alignment column in exportClones

### ISSUE THREAD

**Issue by fabioticconi** [milaboratory/mixcr#73]
While using exportClones for a mouse TRA experiment, I get proper J alignments but a strange output for **V alignment**:

```
“;;;;”
```

This caused a crash in tcR, as referred to here: https://github.com/imminfo/tcr/issues/42

tcR author is taking care of that, but I was wondering what does that output mean?

**Comment by dbolotin** [comment]
Did you use IMGT reference?

Could you please attach resulting txt file, or just copy-paste the problem line here.

Thanks.

**Comment by fabioticconi** [comment]
I did indeed use IMGT reference. These are column 10 and 12 of the full exportClones output:

```
All V alignments	All J alignments
;;;;	5|26|57|15|36||105.0
;;;;	3|30|61|15|42||135.0
;;;;	0|26|57|13|39||130.0;0|26|57|13|39|SA6G|116.0
;;;;	5|32|63|12|39||135.0
;;;;	3|28|59|17|42||125.0
;;	1|28|59|12|39||135.0
;	3|32|63|16|45||145.0
;;;;	9|35|66|16|42||130.0
;;;	10|27|58|16|33||85.0
```

For the rest, it seems to work fine - I didn't notice this until trying to parse it with tcR.

**Comment by dbolotin** [comment]
What parameters did you use for this analysis? Did you change `-OassemblingFeatures`?

For now it looks like some IMGT V genes ends right in the CDR3 begin, so there is no intersection between V gene and `assemblingFeature=CDR3`:
```
Seq: VVVVVVV......JJJJJJJJJJJJJ
  ---FR3---><--CDR3--><--FR4---
```
So there is basically no alignment between V gene and clonal sequence.

What V genes produced this alignments?

If it is the case I will discuss it with @vadimnazarov to correct the tcR's parser. Recently we introduced additional field with anchor point positions in the output, so maybe tcR's parser can be rewritten to use this information instead of raw alignments data.

**Comment by fabioticconi** [comment]
Very simple really. At the alignment level, I use these:

```
--library local -l TRA -s mm
```

at the assemble level I use this:

```
-ObadQualityThreshold=30
```

and for exportClones I use `-t -o`.

To note that the CDR3 sequence is (apparently) right (ie, C/FW bounds are correct).

**Comment by fabioticconi** [comment]
These are the V hits containing the gene for the same lines as above:

```
All V hits
TRAV12D-1*02(316.6),TRAV12D-1*01(316.6),TRAV12N-3*01(300.6),TRAV12D-1*04(297.3),TRAV12-2*01(297.3)
TRAV12D-1*02(315.1),TRAV12D-1*01(315.1),TRAV12N-3*01(302.2),TRAV12D-1*04(302.2),TRAV12-2*01(302.2)
TRAV12D-1*02(317.6),TRAV12D-1*01(317.6),TRAV12D-1*04(311.1),TRAV12N-3*01(310.3),TRAV12-2*01(310.3)
TRAV12N-3*01(320),TRAV12D-1*02(320),TRAV12D-1*01(320),TRAV12D-1*04(307.2),TRAV12-2*01(307.2)
TRAV12D-1*02(333.8),TRAV12D-1*01(333.8),TRAV12N-3*01(319.8),TRAV12D-1*04(319.8),TRAV12-2*01(319.8)
TRAV12D-2*02(304.4),TRAV12-1*03(301.7),TRAV12N-2*01(291.7)
TRAV12D-1*02(312.3),TRAV12D-1*01(312.3)
TRAV12D-2*01(333.1),TRAV12-3*01(312.7),TRAV12-3*03(312.7),TRAV12D-2*03(303.3),TRAV12D-1*01(299.6)
TRAV12D-2*02(303.6),TRAV12N-2*01(303.6),TRAV12-1*03(303.6),TRAV12D-2*04(246.3)
```

**Comment by dbolotin** [comment]
I reproduced the problem, and confirm it is a bug.

For now you can add `-OvParameters.featureToAlign=VRegion` override on the `assemble` stage  as a workaround.

Thank you, for letting us know!
