### ISSUE TITLE
How do we export the reads that failed in alignment?

### ISSUE THREAD

**Issue by suntaosimon** [milaboratory/mixcr#731]
such as those reads Alignment.failed.because.of.low.total.score.

BTW, what does "Overlapped and not aligned" mean? Can not be aligned with V/J and then dropped?

**Comment by PoslavskySV** [comment]
HI, sorry for late reply. You can export not aligned reads using --not-aligned-R1/2 option:

```
mixcr align -s hsa --not-aligned-R1 na_R1.fastq.gz --not-aligned-R2.fastq.gz ...
```

And  "Overlapped and not aligned" stands for reads that were overlapped (R1 overlapped with R2), but still the overlapped read was not aligned due to the one of the reasons ("failed due"...)
