### ISSUE TITLE
Error while using external library for alignment 

### ISSUE THREAD

**Issue by ligalaizik** [milaboratory/mixcr#741]
Hi, while trying to use an external library for alignment, I encountered this error: 
code:
mixcr align -p kaligner2 --library Mouse_BALB_c_IGH_rev.json -s mmu -r report_align_M2_D1.txt M2-D1-232_S3_L001_R1_001.fastq.gz M2-D1-232_S3_L001_R2_001.fastq.gz output_align_M2_D2.vdjca --verbose -f
error:
picocli.CommandLine$ExecutionException: Error while running command (com.milaboratory.mixcr.cli.CommandAlign@3cc20577): java.lang.RuntimeException: com.fasterxml.jackson.databind.exc.MismatchedInputException: Cannot deserialize value of type `[Lio.repseq.dto.VDJCLibraryData;` from Object value (token `JsonToken.START_OBJECT`)

I've attached here the .jason file. 

Thanks!
[Mouse_BALB_c_IGH_rev.json.tar.gz](https://github.com/milaboratory/mixcr/files/9401196/Mouse_BALB_c_IGH_rev.json.tar.gz)

**Comment by mizraelson** [comment]
Hi,
MiXCR uses it's own library format. For example [here](https://github.com/repseqio/library-imgt/releases) you can see how do libraries from IMGT look like converted into MiXCR format.

**Comment by ligalaizik** [comment]
Thank you, 
Is there a way I can convert my external library to the MiXCR format? 


Ligal Aizik
PhD student
Dr. Yariv Wine's research group
The Shmunis School of Biomedicine and  Cancer Research
George S. Wise Faculty of Life Sciences
Tel-Aviv University , Green Bldg. 223,
Tel-Aviv, 69978, ISRAEL
E-mail: ***@***.***

**Comment by mizraelson** [comment]
Unfortunatly, the only

**Comment by mizraelson** [comment]
Yes, here you can find [the manual](https://docs.milaboratories.com/mixcr/guides/create-custom-library/) that describes how to make a MiXCR custom library.
