### ISSUE TITLE
exportAirr etc. subcommands are  unavailable in 4.0.0

### ISSUE THREAD

**Issue by 0x1orz** [milaboratory/mixcr#758]
exportAirr etc. subcommands are  unavailable in 4.0.0

[exportAirr](https://docs.milaboratories.com/mixcr/reference/mixcr-exportAirr/)
[exportReadsForClones](https://docs.milaboratories.com/mixcr/reference/mixcr-exportReadsForClones/)
[exportReports](https://docs.milaboratories.com/mixcr/reference/mixcr-exportReports/)
[exportQc](https://docs.milaboratories.com/mixcr/reference/mixcr-exportQc/)
[postanalysis](https://docs.milaboratories.com/mixcr/reference/mixcr-postanalysis/)
[exportPlots](https://docs.milaboratories.com/mixcr/reference/mixcr-exportPlots/)
[exportTables](https://docs.milaboratories.com/mixcr/reference/mixcr-exportTables/)
[exportPreprocTables](https://docs.milaboratories.com/mixcr/reference/mixcr-exportPreprocTables/)
[exportClonesOverlap](https://docs.milaboratories.com/mixcr/reference/mixcr-exportClonesOverlap/)
[overlapScatterPlot](https://docs.milaboratories.com/mixcr/reference/mixcr-overlapScatterPlot/)

**Comment by PoslavskySV** [comment]
Hi,

all these commands are available for 4.0.0 except `exportQc` which is available in a snapshot build so far.

<img width="1002" alt="image" src="https://user-images.githubusercontent.com/3834261/187448937-5a52a817-0717-451d-a5fa-2744734589ff.png">

**Comment by PoslavskySV** [comment]
BTW, latest shapshot build can be found here:

https://cdn.milaboratory.com/software/mixcr/mixcr-4.0.0-68-develop-9ba4fd3636d88ce3398c995e6d44b0f94a20da38.zip
