### ISSUE TITLE
assembleContigs question

### ISSUE THREAD

**Issue by zznx** [milaboratory/mixcr#768]
Hi,
Why does the first clone targetSequence have different lengths in the same sample with different sequencing data? I want to understand how `AssembleCotigs `work. Is the original sequencing data not used? Can you briefly talk about alignment-guided Assembly algorithms?

Thanks for any help!

**Comment by mizraelson** [comment]
Hi,
Could you please share the exact mixcr commands you have used and, if its possible, these two different outputs that you get (may be just this one top record you are referring to or a few top records).

As for the algorithm, briefly, initially alignments with the same CDR3 sequence are assigned to a particular clone. `mixcr AssembleCotigs` tries to use alignments that cover the rest of the receptor gene to assemble a full-length sequence. Sometimes, e.g. in case of hypermutations, alignments originally assembled by CD3 sequence form 2 different full-length clones with the same CDR3 and slightly different V gene sequences.

**Comment by zznx** [comment]
Hi,
Thank you for your reply

MiXCR v3.0.13

```
Output1: top record
GATGTAAAACGACGGCCAGTATTCTCTGGCTCCAAGTCTGGCACCTCAGCCTCCCTGGCCATCAGTGGGCTCCAGTCTGAGGATGAGGCTGATTATTACTGTGCAGCATGGGATGACAGCCTGAATGGTCCGGTATTCGGCGGAGGGACCAAGCTCACCGTCCTAGCCCTATAGTGAGTCGTATTAA

output2: top record
GGGATGTAAAACGGGATGTAAAACGACGGCCAGTATTCTCTGGCTCCAAGTCTGGCACCTCAGCCTCCCTGGCCATCAGTGGGCTCCAGTCTGAGGATGAGGCTGATTATTACTGTGCAGCATGGGATGACAGCCTGAATGGTCCGGTATTCGGCGGAGGGACCAAGCTCACCGTCCTAGCCCTATAGTGAGTCGTATTAA
```
commands
```
filename=file1.fastq
java -Xmx4g -Xms3g -jar D:\mixcr-3.0.13\mixcr.jar align -s human -t 16 --library imgt.201946-3.sv6 -OminSumScore=200 -OsaveOriginalReads=true ${filename}.fastq ${filename}_align.vdjca
java -Xmx4g -Xms3g -jar D:\mixcr-3.0.13\mixcr.jar assemble --write-alignments -t 16 -ObadQualityThreshold=10 ${filename}_align.vdjca ${filename}_assemble.clna
java -Xmx4g -Xms3g -jar D:\mixcr-3.0.13\mixcr.jar assembleContigs -t 16 ${filename}_assemble.clna ${filename}_assembleContig.clns

filename=file2.fastq
java -Xmx4g -Xms3g -jar D:\mixcr-3.0.13\mixcr.jar align -s human -t 16 --library imgt.201946-3.sv6 -OminSumScore=200 -OsaveOriginalReads=true ${filename}.fastq ${filename}_align.vdjca
java -Xmx4g -Xms3g -jar D:\mixcr-3.0.13\mixcr.jar assemble --write-alignments -t 16 -ObadQualityThreshold=10 ${filename}_align.vdjca ${filename}_assemble.clna
java -Xmx4g -Xms3g -jar D:\mixcr-3.0.13\mixcr.jar assembleContigs -t 16 ${filename}_assemble.clna ${filename}_assembleContig.clns
```

**Comment by mizraelson** [comment]
Hi, first of all, I would suggest using the latest MiXCR v4.0 which is already available. It contains a lot of adjustments and new features. Lets first check that this issue persists in the latest version if it does.

**Comment by zznx** [comment]
Hi,
Thank you for your reply
```
Output1: top record
GGGATCCCTGAGCGATTCTCTGGCTCCAAGTCTGGCACCTCAGCCTCCCTGGCCATCAGTGGGCTCCAGTCTGAGGATGAGGCTGATTATTACTGTGCAGCATGGGATGACAGCCTGAATGGTCCGGTATTCGGCGGAGGGACCAAGCTCACCGTCCTAGCCNAG
Output2: top record
GGATCGGGATCCCTGAGCNATTCTCTGGCTCCAAGTCTGGCACCTCAGCCTCCCTGGCCATCAGTGGGCTCCAGTCTGAGGATGAGGCTGATTATTACTGTGCAGCATGGGATGACAGCCTGAATGGTCCGGTATTCGGCGGAGGGACCAAGCTCACCGTCCTAGCC
```
commands
```
filename=file1
mixcr align -s human --tag-pattern "^GTAAAACGACGGCCAGT(R1:*)CCCTATAGTGAGTCGTATTA" -t 16 --library imgt.201946-3.sv6 -OminSumScore=200 -OsaveOriginalReads=true ${filename}.fastq ${filename}_align.vdjca
mixcr assemble --write-alignments -t 16 -ObadQualityThreshold=10 ${filename}_align.vdjca ${filename}_assemble.clna
mixcr assembleContigs --ignore-tags -t 16 ${filename}_assemble.clna ${filename}_assembleContig.clns

filename=file2
mixcr align -s human --tag-pattern "^GTAAAACGACGGCCAGT(R1:*)CCCTATAGTGAGTCGTATTA" -t 16 --library imgt.201946-3.sv6 -OminSumScore=200 -OsaveOriginalReads=true ${filename}.fastq ${filename}_align.vdjca
mixcr assemble --write-alignments -t 16 -ObadQualityThreshold=10 ${filename}_align.vdjca ${filename}_assemble.clna
mixcr assembleContigs --ignore-tags -t 16 ${filename}_assemble.clna ${filename}_assembleContig.clns
```
Can you explain how the following two reads come from? I couldn't find them in the raw data
```
GGGATCCCTGAGCG    --->  output1
GGATCGGGATCCCTGAGCN   ---> output2 
```

**Comment by mizraelson** [comment]
Is it possible to share the input files, so I can investigate?

**Comment by mizraelson** [comment]
And can you also give some info on the protocol you have used for cDNA library synthesis (did you use any sequence specific primers?)

**Comment by zznx** [comment]
Hi,
Now I have got part of the original data, I believe it can help you, how should I give it to you?
```
Output1: top record
ATTCTCTGGCTCCAAGTCTGGCACCTCAGCCTCCCTGGCCATCAGTGGGCTCCAGTCTGAGGATGAGGCTGATTATTACTGTGCAGCATGGGATGACAGCCTGAATGGTCCGGTATTCGGCGGAGGGACCAAGCTCACCGTCCTAGC
Output2: top record
GGATCCCTGAGCGATTCTCTGGCTCCAAGTCTGGCACCTCAGCCTCCCTGGCCATCAGTGGGCTCCAGTCTGAGGATGAGGCTGATTATTACTGTGCAGCATGGGATGACAGCCTGAATGGTCCGGTATTCGGCGGAGGGACCAAGCTCACCGTCCTAG
```
Can you share some articles related to alignment - guided assembly algorithms?

Thank you very much for your help

**Comment by zznx** [comment]
`-OalignedRegionsOnly=true`
Hi,
I've fixed the problem, but can you tell me why? Why does it have this parameter

Thank you very much for your help

**Comment by zznx** [comment]
`CAGTGGATCCCTGAGCGATTCTCTGGCTCCAAGTCTGGCACCTCAGCCTCCCTGGCCATCAGTGGGCTCCAGTCTGAGGATGAGGCTGATTATTACTGTGCAGCATGGGATGACAGCCTGAATGGTCCGGTATTCGGCGGAGGGACCAAGCTCACCGTCCTAG`

Can you tell me where this `CAGTGGATCCCTGAGCG` came from, I didn't find it in the original data

**Comment by mizraelson** [comment]
Hi, its hard to say without the original data. If the issue still persist feel free to write an e-mail to our support team  on support@milaboratory.com and share the data. You can share the data in any convenient way for your, if security is an issue we will provide you an access to our s3 bucket so you can upload it with aws-cli. I will close this issue for now.
