### ISSUE TITLE
What is the DNA clone sequence after clustering?

### ISSUE THREAD

**Issue by fabioticconi** [milaboratory/mixcr#77]
My understanding is that clonal sequences which are very similar will be clustered together after alignment, and a "consensus" sequence will be used. So the "clone count" refers to all occurrences of all sequences clustered together.

How is this consensus generated?

**Comment by PoslavskySV** [comment]
Yes, you are right that the "clone count" refers to all occurrences of all sequences clustered together. For the detailed information on how this consensus generated, look https://mixcr.readthedocs.org/en/latest/assemble.html#assemble-clones

**Comment by fabioticconi** [comment]
Ah, I had missed that: the "consensus" is actually the "head" sequence. Thanks for the link.

**Comment by PoslavskySV** [comment]
@fabioticconi you are welcome:)
