### ISSUE TITLE
5' scRNA-seq GEX for clonotype reconstruction

### ISSUE THREAD

**Issue by Mussa1122** [milaboratory/mixcr#770]
Hi

Please I need your personal view of point

Actually in our lab we are trying to reconstruct clonotype information from a `10X Genomics 5' scRNA-seq` run (without dedicated V(D)J amplification). I admit that with 3' libraries there will be very few extracted TCRs or even nothing, because CDR3 is quite distant from the 3' end. But, by 10x 5' mRNA libraries as I have read, using a software like MiXCR that is possible to recontract clonotypes.

Please could you correct me on what I have perceived from my Googling? clonotype reconstruction by 10x 5' mRNA libraries without TCR/BCR libraries

So in cellranger fastq folder for two healthy PBMCs I have

```

[1] "PN0340_0001_BCR_S2_L001_I1_001.fastq.gz" "PN0340_0001_BCR_S2_L001_I2_001.fastq.gz"
 [3] "PN0340_0001_BCR_S2_L001_R1_001.fastq.gz" "PN0340_0001_BCR_S2_L001_R2_001.fastq.gz"
 [5] "PN0340_0001_GEX_S3_L001_I1_001.fastq.gz" "PN0340_0001_GEX_S3_L001_I2_001.fastq.gz"
 [7] "PN0340_0001_GEX_S3_L001_R1_001.fastq.gz" "PN0340_0001_GEX_S3_L001_R2_001.fastq.gz"
 [9] "PN0340_0001_TCR_S1_L001_I1_001.fastq.gz" "PN0340_0001_TCR_S1_L001_I2_001.fastq.gz"
[11] "PN0340_0001_TCR_S1_L001_R1_001.fastq.gz" "PN0340_0001_TCR_S1_L001_R2_001.fastq.gz"
[13] "PN0340_0002_BCR_S5_L001_I1_001.fastq.gz" "PN0340_0002_BCR_S5_L001_I2_001.fastq.gz"
[15] "PN0340_0002_BCR_S5_L001_R1_001.fastq.gz" "PN0340_0002_BCR_S5_L001_R2_001.fastq.gz"
[17] "PN0340_0002_GEX_S6_L001_I1_001.fastq.gz" "PN0340_0002_GEX_S6_L001_I2_001.fastq.gz"
[19] "PN0340_0002_GEX_S6_L001_R1_001.fastq.gz" "PN0340_0002_GEX_S6_L001_R2_001.fastq.gz"
[21] "PN0340_0002_TCR_S4_L001_I1_001.fastq.gz" "PN0340_0002_TCR_S4_L001_I2_001.fastq.gz"
[23] "PN0340_0002_TCR_S4_L001_R1_001.fastq.gz" "PN0340_0002_TCR_S4_L001_R2_001.fastq.gz"
```

This is my command for alignment

```
$ ./mixcr align --tag-pattern '^(CELL:N{16})(UMI:N{10})\^(R2:*)' -p rna-seq -s hs - OvParameters.geneFeatureToAlign=VTranscriptWithP - OvParameters.parameters.floatingLeftBound=false - OjParameters.parameters.floatingRightBound=false - OcParameters.parameters.floatingRightBound=false -OallowPartialAlignments=true - OallowNoCDR3PartAlignments=true --report align.report N0340_0001_GEX_S3_L001_R1_001.fastq.gz PN0340_0001_GEX_S3_L001_R2_001.fastq.gz alignments.vdjca
Too many input files.
[picocli WARN] Could not format 'Use higher compression for output file, 10~25% slower, minus 30~50% of file size.' (Underlying error: Conversion = s, Flags =  ). Using raw String: '%n' format strings have not been replaced with newlines. Please ensure to escape '%' characters with another '%'.
[picocli WARN] Could not format 'Use higher compression for output file, 10~25% slower, minus 30~50% of file size.' (Underlying error: Conversion = s, Flags =  ). Using raw String: '%n' format strings have not been replaced with newlines. Please ensure to escape '%' characters with another '%'.
[picocli WARN] Could not format 'Use higher compression for output file, 10~25% slower, minus 30~50% of file size.' (Underlying error: Conversion = s, Flags =  ). Using raw String: '%n' format strings have not been replaced with newlines. Please ensure to escape '%' characters with another '%'.

```

Please can you help me with this error?

Thanks a lot for any thought

**Comment by PoslavskySV** [comment]
Hi,

in fact we have a dedicated MiXCR pipeline for reconstructing repertoire information specifically from 10x 5' GEX data. This will be released in 4.1 by the end of September. Meanwhile, if you need this functionality earlier, we can send you a pre-release build - in this case please write us to support@milaboratories.com

**Comment by Mussa1122** [comment]
> Hi,
> 
> in fact we have a dedicated MiXCR pipeline for reconstructing repertoire information specifically from 10x 5' GEX data. This will be released in 4.1 by the end of September. Meanwhile, if you need this functionality earlier, we can send you a pre-release build - in this case please write us to [support@milaboratories.com](mailto:support@milaboratories.com)

Thanks for answering me

So, this thread is not applicable for my case?

https://github.com/milaboratory/mixcr/issues/672

**Comment by gianfilippo** [comment]
Hi,

have the same problem. I have 10 Genomics scRNAseq data. 
In my case, I have 4 files per sample: I1, R1, R2 and R3.

How should I set up the analysis ?

Thanks

**Comment by PoslavskySV** [comment]
Resolved in [MiXCR v4.1](https://github.com/milaboratory/mixcr/releases/tag/v4.1.0)

**Comment by ggruenhagen3** [comment]
Hello, I also have 5' scRNA-seq GEX data, so like the OP, I have: R1, R2, I1, and I2. I am using the current version of MiXCR (v4.7.0). Should I input just R1 and R2 like below?

```mixcr analyze 10x-sc-5gex --species hsa --rna --threads 8 --force-overwrite TCRVX-SCPOOL-RS1-SCG1_S9_L{{n}}_R1_001.fastq.gz TCRVX-SCPOOL-RS1-SCG1_S9_L{{n}}_R2_001.fastq.gz pool_1```

**Comment by mizraelson** [comment]
Yes, there is no need for I1 and I2 as they only contain the index reads. `--rna` flag is redundant in this case.
