### ISSUE TITLE
Recommend pipeline for Miseq amplicon sequencing for sample from SMARTer Mouse TCR ab Profiling Kit 

### ISSUE THREAD

**Issue by wuying1984** [milaboratory/mixcr#772]
Hi,
I am analyzing TCR profiling sequencing data from SMARTer Mouse TCR ab Profiling Kit using MIXCR. The sequencing reads are from Miseq, and both reads have 300bp.
Since this is the amplicon sequencing data, I can use "mixcr analyze amplicon" one step command to perform the analysis. However, I found that the results are different from the ones using four steps mixcr align + mixcr assemble + mixcr assembleContigs + mixcr exportClones (see the other issue #712).

I am wondering for this type of analysis, one step or four steps pipeline is recommended. Thank you!

Best,
Ying

**Comment by PoslavskySV** [comment]
Hi,

please follow this guide: https://docs.milaboratories.com/mixcr/guides/takara-mmu-tcr/

and please use this 4.1 pre-release build:

Docker images:
  - [ghcr.io/milaboratory/mixcr/mixcr:4.0.0-68-develop](http://ghcr.io/milaboratory/mixcr/mixcr:4.0.0-68-develop)
  - [ghcr.io/milaboratory/mixcr/mixcr:latest-develop](http://ghcr.io/milaboratory/mixcr/mixcr:latest-develop)

Download links:
  - https://cdn.milaboratory.com/software/mixcr/mixcr-4.0.0-68-develop-9ba4fd3636d88ce3398c995e6d44b0f94a20da38.zip

**Comment by wuying1984** [comment]
Thank you very much! I will follow the guide.

Best,
Ying
