### ISSUE TITLE
test data and tags in the full-length BCR analysis tutorial 

### ISSUE THREAD

**Issue by 0x1orz** [milaboratory/mixcr#774]
mixcr is an awesome toolkit for BCR-seq analysis,  I follow the tutorial https://github.com/milaboratory/mixcr/wiki/Analysis-of-full-length-BCR-data-with-unique-molecular-identifiers, with some confusions:
1.  how to assess to  the example files (`data_R1.fastq.gz` , `data_R2.fastq.gz` )?
2.  what is the meaning of the tags `R1F`, `R2F`?
3. the tag subsequences `gtcacatttctcagatcct`, `cagtggtatcaacgcagagt`,`cagtggtatcaacgcagagt ` is the linker of scFv antibody?

**Comment by mizraelson** [comment]
Hi, this is an old tutorial and I suggest you look into our new documentation where we have detailed tutorials for different types of data. For each tutorial data is publicly available as in most cases it is taken from published articles.

https://docs.milaboratories.com/mixcr/guides/milaboratories-human-tcr-rna-multi/

Nevertheless, answering your questions:
1) These filenames a merely an example, there are no files with these names
2) R1F and R2F tags are redundant and used in this tutorial to rather visually separate parts of the sequence (R1F and R2F groups simply include the whole sequence). Thus, the same result will be achieve using the following pattern:
```
--tag-pattern "^N{:5}(SMPL2:N{5})gtcacatttctcagatcct(R1:*) \ ^N{:5}(SMPL1:N{5}aag)cagtggtatcaacgcagagt(UMI:N{14})tctt(R2:*) | ^N{:5}(SMPL1:N{5})cagtggtatcaacgcagagt(UMI:N{14})tctt(R2:*)"
```
3) these sequences are not specific to any segments, they are adapters used in that particular experiment.

**Comment by 0x1orz** [comment]
nice. Thanks.
