### ISSUE TITLE
Can the command "mixcr exportAlignments" output umi for each instance? 

### ISSUE THREAD

**Issue by sean-takara** [milaboratory/mixcr#778]
Can the command "mixcr exportAlignments" output umi information for each instance?

**Comment by mizraelson** [comment]
Yes.
To export UMI sequence you can use  `--split-by-tag UMI -tag UMI`. You have to first split the alignments by tag value to ensure that every instance has one unique tag value. 

Note: if you have used `mixcr assemble partial`, then some alignments may include 2 UMIs. If you will use `--split-by-tag UMI` as mentioned above, these combined alignments will be split into two. If that is the case and you want to preserve aggregated alignments and export all available UMI sequences for each alignment, you can use `-tagCounts`.

Here is the link to our documentation where you can read more about the fields that available for export:
https://docs.milaboratories.com/mixcr/reference/mixcr-export/?h=exportalignments#export-fields

**Comment by sean-takara** [comment]
When I used the commend "mixcr exportAlignments" with file vdjca or "mixcr exportClones" with file clns and was told these options  is Unknown options: -uniqueTagCount umi
--split-by-tag UMI
-tag UMI
-tagCounts
even if I already used the command "mixcr align -OsaveOriginalReads=true".

My goal is to fetch the alignment sequences and the link back information (index or umi) to the corresponding pair of reads that can generate the alignment sequence. When I used the command  "mixcr exportAlignments",  I got all alignment sequences I wanted without information (index or umi), and can not tell which pair of reads mapping to the specific alignment sequence. For example, 10 pairs of R1, R2, the "mixcr" may output 6 alignment sequences into the file called alignment.txt by using the command "exportAlignments". I also used  "exportAlignments -readIds" to get an independent indexFile, and the total number of index is larger than total number of alignment sequences. I still could not link the alignment sequence back to which pair of reads.

My input data, fastq with read head like "@MIG.38 R1 UMI:GTGCACAGAATT:1"
The output file from mixcr, alignment.txt, I opened it and found no umi or index information inside. 

How to get full alignment sequences with link back information(umi or index)? Thanks!

**Comment by PoslavskySV** [comment]
Which version of MiXCR you use?

**Comment by sean-takara** [comment]
Sorry to submit wrong information. The total number of index is equal to the total number of alignment sequences. I can use the information to figure out the UMI.
MiXCR v3.0.13 (built Wed Apr 15 08:28:14 PDT 2020)

**Comment by mizraelson** [comment]
Hi, it's worth mentioning, the UMI options from above will only work if the UMIs were extracted by MiXCR. Which is available in the latest version 4.0. I see your fastq files have UMIs in header, thus I guess they were preprocessed by some other software.
You can indeed use "readIds" to backtrack the original reads. Nevertheless, I would strongly recommend updating MiXCR to v4.0 as it has a lot of major updates.

**Comment by sean-takara** [comment]
Thank you for you suggestion, mizraelson.

**Comment by mizraelson** [comment]
Hi, the new MiXCR 4.1 version supports multiple presets for different protocols including UMI-based. I will close this issue for now, feel free to open it again.
