### ISSUE TITLE
V gene alignment string empty when using IMGT reference

### ISSUE THREAD

**Issue by Irrationone** [milaboratory/mixcr#78]
All entries in `exportClones` have empty V-alignment strings (i.e. best V alignment string is empty, and top 5 V alignment string is `;;;;`) when using an IMGT reference (`align` with the human IMGT IGH reference downloaded with `mixcr importFromIMGT`). 

The command I'm using for `exportClones` is:

```
mixcr exportClones --preset full -nFeature FR2 -nFeature CDR2 -nFeature FR3 -nFeature VDJRegion -nFeature "{FR1Begin:VEndTrimmed}" -vAlignment -dAlignment -jAlignment -cAlignment -readIds $clone_file $clone_output
```

Here are the alignment strings (V, D, J) for a given set of sequences when using the IMGT reference:

```
;;;;    10|19|21|5|14||45.0;3|17|21|96|111|I7TSC14G|44.0;1|12|20|74|85|SG9C|41.0        0|48|48|301|349|ST5GST6GSA12CSC40G|184.0;11|51|51|309|349|SC14TSC43G|172.0
```

And here's the same thing (run on the same sequences), but using the default MIXCR reference:

```
157|452|453|0|295|ST177ASA212GSC222TST250CSC261GST279CSA282GSG288ASA303GST304CSG320ASG326ASA343GSG345CSG357ASA361GSC392TSA395TSG402TSG414ASG416ASG435CSC441TSG449A|1139.0       15|21|31|295|301||30.0;18|24|37|295|301||30.0   0|50|50|301|352|ST5GST6GSA12CSC40GSG48CI49C|168.0;11|53|53|309|352|SC14TSC43GSG51CI52C|156.0
```

Also,`VDJRegion` is non-empty when using the IMGT reference (and appears to contain the entire FR1-FR4) region, but `VRegionTrimmed`, FR1, CDR1, etc. are all empty strings (even though they should be contained within `VDJRegion` ...). When using the MIXCR reference there is no issue--all of the regions are non-empty.

**Comment by dbolotin** [comment]
Thanks for reporting this!

The problem with empty V-alignments is already fixed and will be available as a part of 1.8 release. For now you can use `-OvParameters.featureToAlign=VRegion` on the `assemble` stage  as a workaround.

If this also won't fix the problem with gene features, then can you please provide some more details here. Is it connected with some particular V-gene or all alignments are affected?

Relates to #73.

**Comment by Irrationone** [comment]
Thanks for the quick reply -- adding that flag worked, and seems to have fixed the features as well.

**Comment by dbolotin** [comment]
Good!
