### ISSUE TITLE
Ig analysis

### ISSUE THREAD

**Issue by arnavaz** [milaboratory/mixcr#784]
Hi,
I see very low alignment percentage when I use mouse samples for Ig profiling. 
I was wondering if mixcr/3.0.13 version supports Ig analysis for mouse species?

Thank you very much,
Arna

**Comment by PoslavskySV** [comment]
Hi Arna,

yes, v3.0.13 fully supports mouse species IG. Typically the reason of low alignment rate is bad quality of data or inproper MiXCR settings for specific data type. You can check the reasons of the low alignment rate in [align report](https://docs.milaboratories.com/mixcr/reference/report-align/). Also you can deep dive into the data to figure out the library structure and adjust MiXCR parameters (see e.g. [this](https://docs.milaboratories.com/mixcr/guides/biomed2-bcr/#quality-control) example) accordingly.

Stan

**Comment by arnavaz** [comment]
Thanks! The following is my command. Could you please check if my parameters are ok?
We are using a hybrid capture method for library construction.
`align -p rna-seq -s mmu  -OallowPartialAlignments=true -OvParameters.geneFeatureToAlign=VGeneWithP`

**Comment by PoslavskySV** [comment]
Well, these parameters does not seem optimal for average BCR data. First, it is better to use kAligner2 for B-cells. Next, depending on the library structure, presence or absence of UMIs/primers/adapters at 3' or 5' there might be many other optimizations. You can check [this guide](https://docs.milaboratories.com/mixcr/guides/generic-multiplex-bcr/) for analysis of mus musculus BCRs. Also, I would suggest using latest 4.0 version, as it has many fixes.

**Comment by arnavaz** [comment]
Thanks a lot for the detailed response.
