### ISSUE TITLE
assemblePartial error java.lang.RuntimeException

### ISSUE THREAD

**Issue by amoyguang1** [milaboratory/mixcr#785]
![Screenshot 2022-09-22 234814](https://user-images.githubusercontent.com/113442267/191918697-9b917d51-73d6-493b-8716-db0f71ed7330.png)
I am using mixcr for BCR data from 10x scRNA-Seq. In the step of partial assemble, there is an error about Java.lang.Runtime. Mixcr still produced output file, which seems fine for the downstream analysis. But i am not sure whether the error means data analysis is not completed in the partial assemble step. thank you

**Comment by xiaobai-95** [comment]
I met the same problem today，have you solve it？

**Comment by PoslavskySV** [comment]
Fixed in [MiXCR v4.1](https://github.com/milaboratory/mixcr/releases/tag/v4.1.0)
