### ISSUE TITLE
Can MIXCR accept one read R1 with two segments?

### ISSUE THREAD

**Issue by sean-takara** [milaboratory/mixcr#787]
I have a pair of reads (R1, R2) with the same umi. read R2 is one piece of sequence, and read R1 is a synthetic sequence generated from the command "MIXCR exportAlignments". read R1 has two segments separated by comma. 
Can MIXCR accept the pair of reads (R1,R2) as input to do "MIXCR align --report"? 
If not, How can I assemble the read R1? Thanks!

**Comment by sean-takara** [comment]
Below is the detailed information about my issue.
I have three reads(R1, R2, R3) that expects to map on the reference sequence, and each read is about 280-300 bp. For example, read R1 expects to map on the reference at position 1-300, read R2 expects at position 250-530, read R3 expects at position 330-610.

Can MIXCR accept three reads as input? or does MIXCR only accept a pair reads(R1,R2) as input? 
If we can only use one pair reads as input, MIXCR first requires the pair reads (R1, R2) as input and will output the alignment sequence R12, and then R12 with R3 will become new pair reads (R12, R3) as input of MIXCR.
Sometime, R12 has two segments separated by a comma. It refers to my previous question shown above.

**Comment by mehdiborji** [comment]
why and how have you generated such library? more details about your experiment will help in better answers.

If the reads have overlap you can try to use tools that try to make a consensus of overlapping r1/r2. then repeat for r3 and r1/r2 output.

if the export alignment produces overlaps of r1/r2  then you could use those. if they are separated by comma maybe aligner couldn't find a overlap?

**Comment by sean-takara** [comment]
We need whole sequence information including VDJC, CDR3, chain subclasses etc. The length of consensus sequence may need larger than 600 bp. The maximum length of one read is 300 because of the limitation of MiSeq machine. If r1, r2, r3 can be aligned together, we can get a consensus sequence (>600 bp) with all information that we expect to know.
If the first consensus, generated from r1/r2 output, are separated by comma, it means that the MIXCR aligner could not find a overlap for some reason (It can be happened for the library error 5%).
Can I use the "N" to replace the comma, and repeat the command "MIXCR align" for r3 and r1/r2 output?

**Comment by mehdiborji** [comment]
I am not sure how you are connecting the 3 reads. But these suggestions come to mind:

For TCRs full length of chains is only dependent on the CDR3 and vicinity of it to call VDJ. Rest of the chain including FR1, CDR1, etc. for TCRs are germline encoded. If you need these germline information and believe they are important for your question, you can fragment your library and do short read rna-seq and infer the germline variants from them. This would be much cheaper than using multiple runs of miseq with 300 kits.

If you have barcoded libraries, such as single cell or other UMI-appended protocols you can fragment the libraries which will give you coverage over the CDR3 as well as rest of the chain and MiXCR allows you to assemble it.

I have successfully used Oxford Nanopore for sequencing TCR and BCR and MiXCR has been able to give the full length information without fragmentation.

**Comment by sean-takara** [comment]
Thanks for your information. We need whole information(CDR3, VDJ segments, precise subclasses of BCR IGH).

**Comment by PoslavskySV** [comment]
Closing this issue so far. Please, feel free to re-open if any issues arise.
