### ISSUE TITLE
Missing FR4 aa sequence

### ISSUE THREAD

**Issue by dongspy** [milaboratory/mixcr#790]
Hi,
I have similar problems with https://github.com/milaboratory/mixcr/issues/701. 

My sequence has fully covered  FR4, while the FR4 in the exportClones is null.

Is it the NNN(X) in the tail of sequence problem ?
If so, what should I do about it

<img width="861" alt="image" src="https://user-images.githubusercontent.com/32101973/192246448-7b8a2336-16dd-416e-95a3-d6c0b8ec6990.png">

Below is the sequence

```
@seq1
CAGGTCAACTTAAGGGAGTCCGGGGGTCGCCTGGTCACGCCTGGGACACCCCTGACACTCACCTGCACAGCCTCTGGATTCTCCCTCAACAACTACGACATGAGCTGGGTCCGCTAGGCTCCAGGGAAGGGGCTGGAGTGGATCGGATACATTTATGGTGGTGGTCTCGCCTACTACGCGAGCTGGGCGAAAGGCCGATTCAACATCTCCAAAACCTCGACCACGGTGGATCTGAAAATCACCAGTCCGACAACCGAGGACACGGCCACCTATTTCTGTGCCAGAGGTGATGTTTTTAACACTGCTTATGTGATGGACCTCTGGGGCCCAGGGACCNNGGTCACCGTCTCCTCANNCCCAGACCACCAGC
```

**Comment by dbolotin** [comment]
Hi, can you please provide detailed description on how you analyzed the data (commands and mixcr version)?
Generally `N`s in nt sequence should just translate to `X`, there should be a value for `FR4` in the export for this clonotype.

**Comment by PoslavskySV** [comment]
Closing this at the moment. Feel free to reopen if the problem persists.
