### ISSUE TITLE
No clonotypes with paired chains for scRNA-seq TCR data

### ISSUE THREAD

**Issue by jsialar** [milaboratory/mixcr#791]
## Checklist before submitting the issue:

 - [X] The issue is strongly related to the MiXCR software
 - [ ] The issue can be reproduced with [the most recent version](https://github.com/milaboratory/mixcr/releases) of MiXCR (I am using 4.0.0-268-develop because I encountered an issue in stable release as described in https://github.com/milaboratory/mixcr/issues/706)
 - [X] There is no answer to the question in the [official documentation](http://mixcr.readthedocs.io/) and there is no duplicate issue in the [bug tracker](https://github.com/milaboratory/mixcr/issues?utf8=✓&q=)  
 - [X] Inspection of raw alignments with [exportAlignmentsPretty](http://mixcr.readthedocs.io/en/master/export.html#exporting-well-formatted-alignments-for-manual-inspection) shows that data has the expected architecture, and sample preparation artefacts are not the reason of the problem (if this is the matter of the issue)

## Expected Result
I am running MIXCR on single cell TCR data. According to documentation:
```
In case of single-cell data MiXCR also assembles paired B-cell heavy/light and T-cell alpha/beta clonotypes.
```
Hence, the clonotype table as exported with `exportClones` should contain at least some clonotypes with both alpha and beta chains.

## Actual Result

All clonotypes have only either alpha or beta chain, but never both.

## Exact MiXCR commands 
tag="4.0.0-268-develop"
docker run --rm \
    -e MI_LICENSE=${license} \
    -v ${SGNwork}:/work \
    -v /mnt/SGNINT004A/LargeData/fastq/SGN/TCR:/data \
    ghcr.io/milaboratory/mixcr/mixcr:${tag} \
    align \
    -f \
    --tag-pattern "^(CELL:N{24})(UMI:N{12})\^(R2:*)" \
    -p rna-seq -s hs \
    -OvParameters.geneFeatureToAlign=VTranscriptWithP \
    -OvParameters.parameters.floatingLeftBound=false \
    -OjParameters.parameters.floatingRightBound=false \
    -OcParameters.parameters.floatingRightBound=false \
    -OallowPartialAlignments=true \
    -OallowNoCDR3PartAlignments=true \
    --report /work/SGN_TCR_55M_align.report \
    /data/SGN_UC1EDC_T_downsampled55M_BC_1.fastq.gz \
    /data/SGN_UC1EDC_T_downsampled55M_2.fastq.gz \
    /work/SGN_TCR_55M_aligned.vdjca

docker run --rm \
    -e MI_LICENSE=${license} \
    -v ${SGNwork}:/work \
    ghcr.io/milaboratory/mixcr/mixcr:${tag} \
    -Xmx120g correctAndSortTags -f --report /work/SGN_TCR_55M_barcode.correction.report \
	/work/SGN_TCR_55M_aligned.vdjca \
	/work/SGN_TCR_55M_aligned.corrected.vdjca

docker run --rm \
    -e MI_LICENSE=${license} \
    -v ${SGNwork}:/work \
    ghcr.io/milaboratory/mixcr/mixcr:${tag} \
    assemblePartial -f --cell-level \
    -r /work/SGN_TCR_55M_assemblePartial.report \
    /work/SGN_TCR_55M_aligned.corrected.vdjca \
	/work/SGN_TCR_55M_aligned.assembled.vdjca 

docker run --rm \
    -e MI_LICENSE=${license} \
    -v ${SGNwork}:/work \
    ghcr.io/milaboratory/mixcr/mixcr:${tag} \
    assemble -f --cell-level \
    --report /work/SGN_TCR_55M_assemble.report \
	-a \
    /work/SGN_TCR_55M_aligned.assembled.vdjca \
	/work/SGN_TCR_55M_clones.clna

docker run --rm \
    -e MI_LICENSE=${license} \
    -v ${SGNwork}:/work \
    ghcr.io/milaboratory/mixcr/mixcr:${tag} \
    exportClones -f --split-by-tag CELL -tag CELL -uniqueTagCount UMI \
    -chains -targetSequences -cellGroup -cloneId -vGene -dGene -jGene \
    /work/SGN_TCR_55M_clones.clna \
    /work/SGN_TCR_55M_clones.clna.txt

## MiXCR report files 
There are many report files, not sure which one you need.

**Comment by dbolotin** [comment]
Hi, sorry for the late reply, please try MiXCR 4.1 with the [appropriate preset](https://docs.milaboratories.com/mixcr/reference/overview-built-in-presets/#10x-genomics-single-cell-vdj).

```
mixcr analyze 10x-vdj-tcr \
     --species hsa \
     sample_R1.fastq.gz \
     sample_R2.fastq.gz \
     sample_result
```

Let me know if the problem is still there with the new version.

**Comment by suntaosimon** [comment]
> Hi, sorry for the late reply, please try MiXCR 4.1 with the [appropriate preset](https://docs.milaboratories.com/mixcr/reference/overview-built-in-presets/#10x-genomics-single-cell-vdj).
> 
> ```
> mixcr analyze 10x-vdj-tcr \
>      --species hsa \
>      sample_R1.fastq.gz \
>      sample_R2.fastq.gz \
>      sample_result
> ```
> 
> Let me know if the problem is still there with the new version.

Hi, I am using this preset command and the `-cellGroup` is always _null_. Is there any reason why this happens? 
Thanks!

<img width="128" alt="image" src="https://user-images.githubusercontent.com/3598340/206853562-4cf7feb9-0f31-4afe-ae6d-2b6203200504.png">

**Comment by dbolotin** [comment]
Hi, the cell group field is not yet supported, this feature is in development and will be released soon.
