### ISSUE TITLE
Unknown option: '--umi-pattern' 

### ISSUE THREAD

**Issue by Jasonliu21** [milaboratory/mixcr#793]
When I run mixcr with --umi-pattern in version 
MiXCR v4.0.0b (built Wed Jul 06 18:14:53 EDT 2022; rev=8050699050; branch=400b; host=Dmitrys-MacBook-Pro-2.local)
RepSeq.IO v1.4.0 (rev=8ad610d516)
MiLib v2.0.0 (rev=ee6396596d)
Built-in V/D/J/C library: repseqio.v2.0
in the command below ( according your guides in https://docs.milaboratories.com/mixcr/guides/generic-umi-tcr/):

 mixcr analyze amplicon -s hsa --starting-material rna --receptor-type tcr --5-end no-v-primers --3-end c-primers --adapters adapters-present **--umi-pattern '^(R1:*)\^(UMI:N{12})ATTGGAGTCCT(R2:*)'** ~/bulkTCR/MJ_UMI/cleandata/58001-C002-R1-L1_S23_1P.fastq.gz ~/bulkTCR/MJ_UMI/cleandata/58001-C002-R1-L1_S23_2P.fastq.gz ~/bulkTCR/MJ_UMI/

I got the message like these:

Unknown option: '--umi-pattern'
Usage: mixcr analyze amplicon [-f] [--contig-assembly] [--do-not-extend-alignments]
                              [--extend-alignments] [--impute-germline-on-export] [--no-export]
                              [-nw] [--only-productive] [--verbose] --3-end <3End> --5-end <5End>
                              --adapters <adapters> [--align-preset <alignPreset>] [-b <library>]
                              [-j <jsonReport>] [-r <report>] [--receptor-type <chains>]
                              [--region-of-interest <regionOfInterest>] -s <species>
                              --starting-material <startingMaterial> [-t <threads>] [--align
                              <alignParameters>]... [--assemble <assembleParameters>]...
                              [--assembleContigs <assembleContigParameters>]... [--export
                              <exportParameters>]... [<inOut>...]

Which means in this version, not support the option: umi-pattern, So which version supports? or how can I get the version used in the guides?

**Comment by mizraelson** [comment]
Hi, 
right now our docs is a little bit ahead, in a few weeks we will release a new version 4.1 with a lot of updates including analyze command with `--umi-pattern`. As for now I would suggest using separate commands (`mixcr align`, `mixcr assemble`, `mixcr exportCLones` for UMI barcoded data as described in the same guide bellow `mixcr analyze`).

Let me know if you need help with that.

**Comment by Jasonliu21** [comment]
Thank you, I will try the separate steps.
