### ISSUE TITLE
D assignment 

### ISSUE THREAD

**Issue by swuecho** [milaboratory/mixcr#80]
I got this result from one of my analysis.

cmd option
``
 mixcr exportClones -vHit -jHit -dHit -count -aaFeature CDR3 
``
in mixcr version 1.6
```
IGHV4-59*00 IGHJ4*00    IGHD6-19*00 87  CAGGSGLPYW
IGHV4-59*00 IGHJ4*00    IGHD2-15*00 84  CAGGSGLPYW
```
in mixcr version 1.7.2

```
IGHV4-59*00 IGHJ4*00    IGHD6-19*00 88  CAGGSGLPYW          
IGHV4-59*00 IGHJ4*00    IGHD3-22*00 85  CAGGSGLPYW
```
seems D assignment is not that accurate? 
     

Thanks.

**Comment by dbolotin** [comment]
Could you post nucleotide sequences of corresponding clonotypes, along with alignment field and D alignment scores.
Basically you can just copy corresponding lines from default export output of either alignments or assembled clonotypes.

**Comment by swuecho** [comment]
[align](https://gist.githubusercontent.com/swuecho/09e70fd0a5de24b8b335072fa65dbff7/raw/686fb1e43dee2ed8e3aaf3e750014b8dfa0f6094/alignment)

[asseble](https://gist.githubusercontent.com/swuecho/06f5cbf8bb2983e1439feff21287fc36/raw/b66158ef07f7c91be77e08317fbe87490f59ab62/gistfile1.txt)

**Comment by dbolotin** [comment]
I don't see any problems with these two clones:

There are two clones with different nucleotide sequences, and with two different D genes that most likely be used during their rearrangement:

```
Clone1:
    TGTGCGGGAGGCAGTGGTCTCCCCTACTGG
       gggtataGCAGTGGctggtac         - IGHD6-19

Clone2:
    TGTGCGGGAGGTAGTGGTCTCCCCTACTGG
gtattactatgataGTAGTGGTtattactac      - IGHD3-22
```

So alignments are ok, and D genes were assigned as good as possible. However, as there are many similar D genes for IGH, it is practically impossible to tell for sure which D gene was used in each particular rearrangement. Situation is moreover complicated by hypermutations (which seems to be the case here).

If D genes are of particular interest in your research, you should adopt some approach like one described by Aleksandra Walczak and collegues in the following papers:
http://www.pnas.org/content/109/40/16161.short
http://rstb.royalsocietypublishing.org/content/370/1676/20140243.abstract

**Comment by swuecho** [comment]
Thanks!
