### ISSUE TITLE
Using MiXCR to reconstruct clonotype information from 10X Single Cell Immune Profiling data

### ISSUE THREAD

**Issue by xiaobai-95** [milaboratory/mixcr#803]
Hi,

I am trying to reconstruct clonotype information from a 10X Genomics Single Cell Immune Profiling data (with dedicated V(D)J amplification).  I check the R1 fastq data of Single Cell Immune Profiling data and found it quite different form the R1 fastq data of Single Cell Gene Expression data. I was wondering whether [this pipeline](https://github.com/milaboratory/mixcr/wiki/Analysis-of-10X-Single-Cell-data) also appropriate for my task? Does this require a different srtting of tag-pattern?

Thank you for considering my questions.
Kind regards

**Comment by PoslavskySV** [comment]
Hi, please use MiXCR 4.1 and

```
mixcr analyze 10x-vdj-tcr --species hds r1.fastq.gz r2.fastq.gz result
```

**Comment by xiaobai-95** [comment]
sorry I can't download MIXCR 4.1 by this code “wget https://github.com/milaboratory/mixcr/releases/download/v4.1.0/mixcr-4.1.0.zip” found in [this documentation](https://docs.milaboratories.com/mixcr/getting-started/installation/)
