### ISSUE TITLE
mixcr assemble kept printing "writing clones: 100%" periodically

### ISSUE THREAD

**Issue by Lantianqianmu** [milaboratory/mixcr#811]
Hi,
thanks for developing and maintaining mixcr.

I have a TCR dataset (paired .fq.gz file, ~2.5GB each) where all cells should have the same TCR with custom library structure. After calling mixcr align and and  mixcr correctAndSortTags, I got a 8GB .corrected.vdjca file. Then I call **mixcr assemble -Xmx64g -a -OmaxBadPointsPercent=0 -OaddReadsCountOnClustering=true**. However, after clustering mixcr kept printing "writing clones: 100%" and seemed to stuck here (see the picture). It's been 5 DAYS, and yet mixcr still kept printing "writing clones: 100%" periodically. Is this normal? It takes more than a week for mixcr to assemble clones?

When I sampled 1,000,000 lines of the fastq file and runned the same pipeline, it worked fine, but mixcr did not print "writing clones: 100%".

By the way, when I use **-t** parameter for **mixcr assemble**, it says this parameter is deprecated. So mixcr assemble does not support parallelization? Or are there other related parameters for parallelization?

Best regards,
Nigel

![out](https://user-images.githubusercontent.com/72971759/195884621-0b3838bc-2f13-419a-b754-9942f05c4b68.jpg)

**Comment by PoslavskySV** [comment]
Hi, please try 4.1, that should be fixed.
