### ISSUE TITLE
jar file for non-Mac, non-Linux systems?

### ISSUE THREAD

**Issue by agregson** [milaboratory/mixcr#82]
Hello,

Just wondering where the jar file is that you suggest using on windows? I have cloned the repository but see no jar file. I am running on FreeBSD. I've tried to modify your mixcr script, but it won't run. Thanks,

**Comment by swuecho** [comment]
I download for here and it works well.

https://github.com/milaboratory/mixcr/releases

**Comment by dbolotin** [comment]
Yap, MiXCR binary distribution can be downloaded from our [release](https://github.com/milaboratory/mixcr/releases) page.
And I just added support for FreeBSD in mixcr script, so you can just substitute mixcr script from zip file with updated one using something like:

```
curl https://raw.githubusercontent.com/milaboratory/mixcr/develop/mixcr > mixcr
```

and it should work. I just tested it on FreeBSD AMI in AWS.

Thanks for the notice: I will add explicit note about download location in the docs.

P.S. to build MiXCR from sources you need maven, after installing it just invoke `mvn clean install`

**Comment by agregson** [comment]
Awesome! Thank you very much. Appears to be running. I'll try building in a bit. Thanks again!
