### ISSUE TITLE
The mixcr kept printing "writing clones : 100%" issue is not fixed in 4.1.0

### ISSUE THREAD

**Issue by Lantianqianmu** [milaboratory/mixcr#825]
Hi,
I tried mixcr 4.1.0, but the issue in #811 still exists. Mixcr still kept printing "writing clones : 100%", but no alignments or clones were written into the .clna file.
I ran the assemble command with **-a**. As I can remember mixcr would write alignments to .clna file first, and then write clones. However I didn't see mixcr write alignments to .clna file before the wierd periodic "writing clones : 100%" .
Any solution to this issue?

best,
Nigel

**Comment by PoslavskySV** [comment]
Hi, what is the size of input file and what is the data type? If it is large sc there might be memory issues, so you can try increase memory budget with 

mixcr -Xmx64g analyze...

**Comment by Lantianqianmu** [comment]
Input file is PE150 single cell data (2.3 GB for R1 and 2.1 GB for R2), with barcode and umi in R2. Actually I have run mixcr assemble with -Xmx128g but the issue didn't get solved. Considering the fact that mixcr worked well when my data was downsampled, it seemed like a memory issue. I will try 256g and get back to you later. Thanks for your advice.

**Comment by Lantianqianmu** [comment]
Input file is PE150 single cell data (2.7 GB for R1 and 2.1 GB for R2), with barcode and umi in R2. Actually I have run mixcr assemble with -Xmx128g but the issue didn't get solved. Considering the fact that mixcr worked well when my data was downsampled, it seemed like a memory issue. I will try 256g and get back to you later. Thanks for your advice.

**Comment by Lantianqianmu** [comment]
Hi, increasing memory doesn't seem to help. I tried one-line command mixcr analyze
**mixcr analyze generic-tcr-amplicon-umi -Xmx64g \
    --force-overwrite \
    --species hsa \
    --rna \
    --tag-pattern '^(R1:*)\^(CELL:N{21})(UMI:N{10})(R2:*)' \
    --rigid-left-alignment-boundary \
    --floating-right-alignment-boundary C \
    test_R1.fq.gz \
    test_R2.fq.gz \
    test_mixcr**
and get an error during **refineTagsAndSort**:
**picocli.CommandLine$ExecutionException: Error while running command refineTagsAndSort java.lang.IllegalArgumentException: Unexpected filter tag request. Requested UMI but next level is CELL.**

I removed the CELL tag and it worked. Which preset should I run to keep the CELL tag? The data is TCR amplicon with cell barcodes and umis.

**Comment by Lantianqianmu** [comment]
Hi, increasing memory doesn't seem to help. I tried one-line command mixcr analyze
```
mixcr analyze generic-tcr-amplicon-umi -Xmx64g \\
      --force-overwrite \\
      --species hsa \\
      --rna \\
      --tag-pattern '^(R1:)\^(CELL:N{21})(UMI:N{10})(R2:)' \\
      --rigid-left-alignment-boundary --floating-right-alignment-boundary C \\
      test_R1.fq.gz test_R2.fq.gz test_mixcr
```
and get an error during refineTagsAndSort:
```
picocli.CommandLine$ExecutionException: Error while running command refineTagsAndSort java.lang.IllegalArgumentException: Unexpected filter tag request. Requested UMI but next level is CELL
```

I removed the CELL tag and it worked. Which preset should I run to keep the CELL tag? The data is TCR amplicon with cell barcodes and umis.

**Comment by dbolotin** [comment]
Hi, it seems that you are using the protocol similar to 10x, but with slightly different barcode structure. You can use one of the corresponding [10x presets](https://docs.milaboratories.com/mixcr/reference/overview-built-in-presets/#10x-genomics-single-cell-vdj), and adjust the tag pattern and turn off the CELL whitelist (let me know if you need the whitelist functionality, I will let you know how to include it into analysis), like this:

```
mixcr analyze 10x-vdj-tcr -Xmx64g \
      --force-overwrite \
      --species hsa \
      --tag-pattern '^(R1:*)\^(CELL:N{21})(UMI:N{10})(R2:*)' \
      -M refineTagsAndSort.whitelists={} \
      --floating-right-alignment-boundary C \
      test_R1.fq.gz test_R2.fq.gz test_mixcr
```

It sets several additional parameters, specifically [UMI/CELL filters](https://github.com/milaboratory/mixcr/blob/6eb33f91b425b95ff09e8544bb83be921b96fbf0/src/main/resources/mixcr_presets/protocols/10x.yaml#L15-L120)) which are important for such case.

Another suggestion, if you know the length of the primer/adapter sequence on the right (in R1, if I correctly understand the library structure and CELL/UMI are on the 5' end), try cutting it by adjusting the tag pattern. Like this, to remove first 17 nucleotides of R1 from analysis:

```
...
      --tag-pattern '^N{17}(R1:*)\^(CELL:N{21})(UMI:N{10})(R2:*)' \
      --rigid-right-alignment-boundary C \
...
```

If it is a protocol for which there are open datasets, please point us in the right direction, and we will include specifically optimized preset into the built-in collection.

**Comment by Lantianqianmu** [comment]
With **-M refineTagsAndSort.whitelists={}**, mixcr works well now. 
I don't need whitelist and there are no open datasets for now.

Thanks for taking time to answer my questions! Your suggestions are really helpful.
