### ISSUE TITLE
License expires after a few hours

### ISSUE THREAD

**Issue by helaersr** [milaboratory/mixcr#869]
## Checklist before submitting the issue:

 - [x] The issue is strongly related to the MiXCR software
 - [x] The issue can be reproduced with [the most recent version](https://github.com/milaboratory/mixcr/releases) of MiXCR
 - [x] There is no answer to the question in the [official documentation](http://mixcr.readthedocs.io/) and there is no duplicate issue in the [bug tracker](https://github.com/milaboratory/mixcr/issues?utf8=✓&q=)  
 - [ ] Inspection of raw alignments with [exportAlignmentsPretty](http://mixcr.readthedocs.io/en/master/export.html#exporting-well-formatted-alignments-for-manual-inspection) shows that data has the expected architecture, and sample preparation artefacts are not the reason of the problem (if this is the matter of the issue)

## Description of the issue

I downloaded an academic license file to use mixcr 4.1.
I copied the file in the same directory than mixcr.jar.
The software works.
After 2-3 days, the software stopped working, telling:
`License error: WrongValidityPeriod: License expired`
I redownloaded a new license, and the software worked again for 2-3 days, but then same error.
License is still valid:
![image](https://user-images.githubusercontent.com/47422337/200525679-4f4750a2-38bf-4fe2-9158-92d1b74387cb.png)

I tried also with 
`./mixcr activate-license`
but same results.

I tried using environment variable MI_LICENSE and MI_LICENSE_FILE but it doesn't seem to check them (tells me that I need a license instead of license expired).

I run the software in a HPC environment, so the software and the license file is copied on each node. Anyway, the license expires at the same time on each node, and it refuses to reuse the same key e.g. if I use `./mixcr activate-license`.

## Expected Result

The license validity is one year.

## Actual Result

The license validity is 2-3 days.

## Exact MiXCR commands 

`./mixcr`

## MiXCR report files 

`License error: WrongValidityPeriod: License expired`

**Comment by PoslavskySV** [comment]
Hi Raphael,

can you confirm that the machine you run MiXCR has internet access? MiXCR needs internet to periodically validate the license. If you workstation is offline, please contact us at support@milaboratories.com to provide you an offline license.

Best,
Stan

**Comment by helaersr** [comment]
Hi Stan,

It has internet access but it's behind a proxy. Environment variables http_proxy and https_proxy are defined, but it may not be enough for mixcr. Can the proxy be configured somewhere else ?
Anyway, I will contact support for the offline license, it will probably be easier :-)

Thanks

**Comment by PoslavskySV** [comment]
Proxy settings are fixed in [MiXCR 4.3](https://github.com/milaboratory/mixcr/releases/tag/v4.3.1). For general firewall instructions see [this doc](https://mixcr.com/mixcr/getting-started/milm/#offline-use).
