### ISSUE TITLE
Different mixcr versions analyse inconsistent top 1clone

### ISSUE THREAD

**Issue by linxianzu1995** [milaboratory/mixcr#874]
## Issue
Hi,  I have a sample of amplicon sequencing data that I analysed using a different mixcr version （3.0.13 and 4.0.0） and found that the top 1 clone is inconsistent. Is the newer version of mixcr causing the top 1 clone to be inconsistent? What are the reasons for this?

top 1 clone: the clone with the highest cloneFraction

**Comment by dbolotin** [comment]
Hi, can you please tell more about the settings you used for analysis for both versions, and what type of the data you analyzed? Please, also run the analysis with the most recent version of mixcr ([4.1.1](https://github.com/milaboratory/mixcr/releases/tag/v4.1.1)), to confirm that this problem still can be observed. If you need help with selection of the correct [preset](https://docs.milaboratories.com/mixcr/reference/overview-built-in-presets/) and generally migration to new CLI, we are also happy to help!

**Comment by linxianzu1995** [comment]
Hi, Sorry for not replying in time as I was too busy.  Our data type is BCR data based on amplicon sequencing.  The analysis commands are as follows:  mixcr align -p kAligner2 -s hsa --library imgt -t 8 -OvParameters.geneFeatureToAlign=VGeneWithP --verbose -f -OsaveOriginalReads=true -j ./Test.align.json  --not-aligned-R1 ./Test.fastq.gz -OvParameters.parameters.floatingLeftBound=false -OjParameters.parameters.floatingLeftBound=false -OvParameters.parameters.floatingRightBound=false -OjParameters.parameters.floatingRightBound=false -OallowPartialAlignments=true ./Test.assembled.fasta   ./Test.vdjca，we used MiXCR (4.0.0) and MiXCR (3.0.13) for the analysis, only the versions differed.  This analysis does result in inconsistencies in the top1 clone. Today, I added the -p parameter to the original command, mixcr used kAligner2 for align, and then tried to analyze it using MiXCR (3.0.13) and MiXCR (4.0.0) and got the result that the Top 1 clone is consistent.

**Comment by dbolotin** [comment]
That's great! Still, I highly recommend migrating to the [latest mixcr version](https://github.com/milaboratory/mixcr/releases/latest), and selecting appropriate [preset](https://docs.milaboratories.com/mixcr/reference/overview-built-in-presets/) for your case. If nothing fit's your needs there is a [generic preset](https://docs.milaboratories.com/mixcr/reference/overview-built-in-presets/#generic-bcr-amplicon). If you are running a data generated using published protocols or commercially available kits and you can't find it in the list of available presets, please let us know, and we will add it shortly.
