### ISSUE TITLE
OSX: importFromIMGT.sh: line 40: syntax error near unexpected token `('

### ISSUE THREAD

**Issue by marcovth** [milaboratory/mixcr#89]
OSX 10.10.5 and OSX 10.11.3 give the same error ...

sh ./importFromIMGT.sh
By using this script you agree to the terms of use of IMGT website. (see http://www.imgt.org/ for details).
-n Press ENTER to continue or other key to exit...

./importFromIMGT.sh: line 40: syntax error near unexpected token `('
./importFromIMGT.sh: line 40: `done < ($wg 'http://imgt.org/genedb/' | pup '#Species option attr{value}' | grep -v any )'

**Comment by dbolotin** [comment]
Thanks for reporting!

Strange error, I checked on 10.11.5, and as I remember it also worked on 10.11.4 .

Could you please confirm that line `40` of your copy of the script contains two `<` symbols, like in [original file](https://github.com/milaboratory/mixcr/blob/master/importFromIMGT.sh#L40):

```bash
done < <($wg 'http://imgt.org/genedb/' | pup '#Species option attr{value}' | grep -v any )
```

**Comment by marcovth** [comment]
On 2016-05-30 5:23 PM, Dmitry Bolotin wrote:
>
> Thanks for reporting!
>
> Strange error, I checked on 10.11.5, and as I remember it also worked 
> on 10.11.4 .
>
> Could you please confirm that line |40| of your copy of the script 
> contains two |<| symbols, like in original file 
> <https://github.com/milaboratory/mixcr/blob/master/importFromIMGT.sh#L40>:
>
> done  <  <($wg 'http://imgt.org/genedb/' | pup '#Species option attr{value}' | 
> grep -v any )
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub 
> <https://github.com/milaboratory/mixcr/issues/89#issuecomment-222556132>, 
> or mute the thread 
> <https://github.com/notifications/unsubscribe/AMGCiN4yVMgyZWzMF5rzcakyDvffkettks5qG1VIgaJpZM4IqACU>.
>

Hello ...

Here is a screenshot from a brand new MacPro, but the unaltered, 
original, script gave the exact same error with an older MacPro ...

I rebooted the new MacPro to make sure the newly installed brew tools 
were active, and it gave the same error.


Hope this helps.

Thanks for the service.

- Marco.

**Comment by dbolotin** [comment]
Could you please submit screenshot using GitHub interface, as it didn't attache properly last time.

Please, provide some instructions on how to reproduce the problem. I checked the script with both built-in bash and  with bash 4.3 installed using brew, and everything works perfectly. I am on 10.11.5, but I don't think something changed from 10.11.4, or even from Mountain Lion... What shell are you using? Script also works on at least 4 Mac's in our lab.

Try to run script through `mixcr` script:
```bash
./mixcr importFromIMGT
```

**Comment by marcovth** [comment]
Your last commend solved the issue. I ran the script with sh ./importFromIMGT.sh instead of mixcr importFromIMGT.

Thanks.

**Comment by dbolotin** [comment]
Good! I'll remove notion about direct execution of the script from docs.
