### ISSUE TITLE
Custom Library Generation

### ISSUE THREAD

**Issue by PaulDanPhillips** [milaboratory/mixcr#892]
Hello!
I have recently been working on getting my jobs updated to the most recent mixcr version. I just conda updated prior to this post.

## mixcr version info:
'mixcr -v '
MiXCR v4.1.0 (built Tue Oct 18 10:33:21 MST 2022; rev=852d9d8feb; branch=no_branch; host=fv-az200-293)
RepSeq.IO v1.5.0 (rev=6e9d72efb7)
MiLib v2.1.0 (rev=2142a7fa5a)
Built-in V/D/J/C library: repseqio.v2.0

## Documentation being followed
https://docs.milaboratories.com/mixcr/guides/create-custom-library/

I am trying to build a custom library following the above tutorial but repseqio does not seem to come installed with mixcr, nor do I see a simple install for repseqio from the github linked in the above documentation.

## Command and error
'repseqio fromFasta --taxon-id 9606 --species-name hs --species-name homsap --chain TRB --name-index 0 --gene-type V --gene-feature VRegion my_genes.v.fasta my_library.v.json'
*bash: repseqio: command not found*

**How can I install and use the repseqio fromFasta tools to build custom library's for future mixcr  analysis?**

Thanks

**Comment by PoslavskySV** [comment]
Hi Paul,

`repseqio` is currently not available in Conda. You can download it from the following link:

  https://github.com/repseqio/repseqio/releases/tag/v1.5.0

Please, let us know if you will need assistance with creating custom library, we will be happy to help.

**Comment by PaulDanPhillips** [comment]
Thanks so much for the quick help! 

Would this have been automatically installed via wget and github mixcr installation ('wget https://github.com/milaboratory/mixcr/releases/download/v4.1.0/mixcr-4.1.0.zip')?

Thanks again

**Comment by PoslavskySV** [comment]
No, it will not - You need to download `repseqio` separately, since it is a different tool (although MiXCR uses it heavily inside as a library), and has a different release cycle.

**Comment by PaulDanPhillips** [comment]
That makes sense. Thank you for the help!
