### ISSUE TITLE
--tag-pattern error

### ISSUE THREAD

**Issue by github-wow** [milaboratory/mixcr#893]
## Expected Result

`"(R1:N{*})\^tggtatcaacgcagagt(UMI:NNNNtNNNNtNNNN)tc(R2:N{*})"` worked in mixcr-3.0.13, but it does not in mixcr-4.1.1

## Actual Result

error

## Exact MiXCR commands 

java mixcr analyze generic-tcr-amplicon                                                                               ^
    --species mmu                                                                                                                   ^
    --rna                                                                                                                                   ^
    --tag-pattern `"^(R1:N{*})\^tggtatcaacgcagagt(UMI:NNNNtNNNNtNNNN)tc(R2:N{*})"`  ^
    --rigid-left-alignment-boundary                                                                                       ^
    --floating-right-alignment-boundary C                                                                            ^
      read1.fq.gz                                                                                                                      ^
      read2.fq.gz                                                                                                                      ^
      result

## MiXCR report files 

java.nio.file.InvalidPathException: Illegal char <:> at index 4: `^(R1:N{*})\^tggtatcaacgcagagt(UMI:NNNNtNNNNtNNNN)tc(R2:N{*})`
        at java.base/sun.nio.fs.WindowsPathParser.normalize(WindowsPathParser.java:182)
        at java.base/sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:153)
        at java.base/sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:77)
        at java.base/sun.nio.fs.WindowsPath.parse(WindowsPath.java:92)
        at java.base/sun.nio.fs.WindowsFileSystem.getPath(WindowsFileSystem.java:232)
        at java.base/java.nio.file.Path.of(Path.java:147)
        at java.base/java.nio.file.Paths.get(Paths.java:69)
        at com.milaboratory.milm.LM$MetricThread.run(LM.java:755)

Should we keep using minnn tool prior to the mixcr ?

**Comment by PoslavskySV** [comment]
Hi, 

`minnn` is deprecated; you should use MiXCR 4. x instead. Which protocol/kit you use? We support built-in pipelines for many of commercial kits and public protocols (see [here](https://docs.milaboratories.com/mixcr/reference/overview-built-in-presets/)). If you have a custom protocol, please reach us via support@milaboratories.com and we will be happy to help.

Regarding the exception, the tag pattern syntax is a little bit different from what was in MiNNN. You can check the details [here](https://docs.milaboratories.com/mixcr/reference/ref-tag-pattern/). 

If you share which kit/protocol you use, we can help you with a correct tag pattern.

**Comment by github-wow** [comment]
@PoslavskySV thank you for the reply.

_"Which protocol/kit you use?"_ -- In an experiment we used the "Mouse α/β TCR RNA KIT" kit (of 2021 version). I suppose [here](https://milaboratories.com/mouse-tcr-rna-kit) is its recent analogue.
When I search for the [example](https://docs.milaboratories.com/mixcr/reference/ref-tag-pattern/) `"^N{0:3}(UMI:N{12})attcGCCA(R1:*)\^N{18}(R2:*)"` pattern, the same error appears.
With `"tggtatcaacgcagagt[ATGC]{4}t[ATGC]{4}t[ATGC]{4}tc"` regex in Notepad++ I can see a lot of matches in fastq files.


_"minnn is deprecated"_ -- But after mixcr4+, the [vdjtools](https://github.com/mikessh/vdjtools) is a choice, correct?

**Comment by mizraelson** [comment]
Hi, We have recently added a dedicated `mixcr analyze` command for this kit. The command is already available in the develop version: https://link.milaboratory.com/software/mixcr/mixcr-develop.zip

The example command looks like that:

`mixcr analyze milab-mouse-tcr-rna-race-cdr3 
      input_R1.fastq.gz 
      input_R2.fastq.gz 
      result 
`
The description is available on our documentation portal:
https://docs.milaboratories.com/mixcr/reference/overview-built-in-presets/#milaboratories

**Comment by PoslavskySV** [comment]
@mizraelson thank you for the answer. For reference, the correct pattern which is used in the preset is

```
^(R1:*) \ ^tggtatcaacgcagagt(UMI:N{14})N{10}(R2:*)
```

Regarding VDJTools, same, it is legacy now. You can use downstream analysis directly in MiXCR 4.x https://docs.milaboratories.com/mixcr/reference/mixcr-postanalysis/

**Comment by github-wow** [comment]
@mizraelson, @PoslavskySV thank you guys for your helpful replies

**Comment by github-wow** [comment]
it looks like `^(R1:*) \ ^tggtatcaacgcagagt(UMI:N{14})N{10}(R2:*)` in mixcr-4.1.1-61-develop-68c417eea82d0747099e4a5419dd9cec61854e0c for "milab-mouse-tcr-rna-race-cdr3" catches less clones than `"(R1:N{*})\^tggtatcaacgcagagt(UMI:NNNNtNNNNtNNNN)tc(R2:N{*})"` in mixcr-3.0.13.   
Does "(UMI:N{14})" equals to "(UMI:NNNNtNNNNtNNNN)" ?

**Comment by zhou-jianwen** [comment]
> 

Hi，it seems that the functions contained in VDJtools have not been fully preserved in MIXCR?

**Comment by PoslavskySV** [comment]
Hi, which functions do you mean ?

**Comment by zhou-jianwen** [comment]
> Hi, which functions do you mean ?

vdjtools provided a variety of plotting tools in the past, such as PlotFancyVJUsage PlotQuantileStats, etc.
However, no analogous solution was found in MIXCR v4.1.

**Comment by PoslavskySV** [comment]
We had these functions in VDJTools long time ago, but decided not to move them in MiXCR, because they are not really informative and used quite rarely by the users. For `VJUsage` you still can use `exportPlots vjUsage` to export heatmap,  but  there is no analog  for `PlotQuantileStats`. If you really find `PlotQuantileStats` useful, we can add it back to MiXCR.

**Comment by github-wow** [comment]
`PlotFancyVJUsage` was really fancy (and nice). [Realized](https://github.com/antigenomics/vdjviz) in [vdjviz](https://vdjviz.cdr3.net/) the plot types (e.g., `PlotQuantileStats`) can be used to illustrate what's going on in a typical sample to exemplify what's going in an experimental group. Maybe it is a good idea to keep them all. IMHO
