### ISSUE TITLE
exportReadsForClones, can we export all clone IDs?

### ISSUE THREAD

**Issue by suntaosimon** [milaboratory/mixcr#898]
hi,

is it possible to export all the clones? if there are over 10M clones, I really can not type 10M IDs. 

Thanks!

**Comment by amikelov** [comment]
Hi,

Just don't put an "--id" flag at all.

Also, each MiXCR command has --help option, which displays help message, which sometimes goes beyond things covered in docs. Try it for exportReadsForClones, you may find some other useful features for you.

Best regards,
Artem

**Comment by suntaosimon** [comment]
> Hi,
> 
> Just don't put an "--id" flag at all.
> 
> Also, each MiXCR command has --help option, which displays help message, which sometimes goes beyond things covered in docs. Try it for exportReadsForClones, you may find some other useful features for you.
> 
> Best regards, Artem

thanks!
