### ISSUE TITLE
MiXCR assemble runs with an error

### ISSUE THREAD

**Issue by linxianzu1995** [milaboratory/mixcr#900]
## issue
I have encountered the following error when using the MiXCR assemble command, during which I tried to set up a temporary folder with a different version  of MiXCR （MiXCR 4.0.0 and MiXCR 4.1.1）, but all of them gave the same error. What is the cause of this error and how can I fix it?
## command
 ~/biosoft/mixcr-4.1.1/mixcr -Xmx8G assemble -j Test.clones.json -f -a -ObadQualityThreshold=15 Test.vdjca Test.clna

## ERROR
Initialization: progress unknown
Assembling initial clonotypes: 1.5%
Assembling initial clonotypes: 12.9%  ETA: 00:01:17
Assembling initial clonotypes: 23%  ETA: 00:00:44
Assembling initial clonotypes: 33.9%  ETA: 00:00:46
Assembling initial clonotypes: 45.5%  ETA: 00:00:33
Assembling initial clonotypes: 57.6%  ETA: 00:00:14
Assembling initial clonotypes: 68.1%  ETA: 00:00:14
Assembling initial clonotypes: 80.6%  ETA: 00:00:11
Assembling initial clonotypes: 91.8%  ETA: 00:00:04
Mapping low quality reads: 1%
Mapping low quality reads: 11.1%  ETA: 00:00:17
Mapping low quality reads: 22.4%  ETA: 00:00:56
Mapping low quality reads: 34.1%  ETA: 00:00:17
Mapping low quality reads: 44.1%  ETA: 00:01:18
Mapping low quality reads: 54.2%  ETA: 00:01:09
Mapping low quality reads: 64.3%  ETA: 00:00:54
Mapping low quality reads: 74.4%  ETA: 00:00:48
Mapping low quality reads: 84.6%  ETA: 00:00:32
Mapping low quality reads: 95.1%  ETA: 00:00:04
Pre-clustering: 100%  ETA: 00:00:00
Clustering: 0%
Clustering: 10.3%  ETA: 00:03:57
Clustering: 20.4%  ETA: 00:02:48
Clustering: 30.6%  ETA: 00:02:02
Clustering: 41.5%  ETA: 00:01:26
Clustering: 52.4%  ETA: 00:01:10
Clustering: 63.1%  ETA: 00:00:48
Clustering: 73.9%  ETA: 00:00:26
Clustering: 85%  ETA: 00:00:06
Clustering: 96.3%  ETA: 00:00:02
Building clones: 0.1%
Building clones: 10.3%  ETA: 00:02:58
Building clones: 20.6%  ETA: 00:02:04
Building clones: 31.1%  ETA: 00:01:56
Building clones: 41.2%  ETA: 00:01:57
Building clones: 51.7%  ETA: 00:01:18
Building clones: 62%  ETA: 00:01:10
Building clones: 72.3%  ETA: 00:00:57
Building clones: 82.6%  ETA: 00:00:42
Building clones: 92.8%  ETA: 00:00:13
java.lang.AssertionError: Assertion failed
        at com.milaboratory.mixcr.cli.CommandAssemble$Cmd.run0(CommandAssemble.kt:353)
        at com.milaboratory.mixcr.cli.MiXCRCommand.run(MiXCRCommand.kt:42)
        at com.milaboratory.mixcr.cli.MiXCRCommandWithOutputs.run(MiXCRCommandWithOutputs.kt:67)
        at picocli.CommandLine.executeUserObject(CommandLine.java:1939)
        at picocli.CommandLine.access$1300(CommandLine.java:145)
        at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2358)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2352)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2314)
        at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2179)
        at picocli.CommandLine$RunLast.execute(CommandLine.java:2316)
        at picocli.CommandLine.execute(CommandLine.java:2078)
        at com.milaboratory.mixcr.cli.Main.main(Main.kt:76)

**Comment by dbolotin** [comment]
Please confirm that you ran the whole pipeline from scratch with 4.1.1 version. Please post all the commands starting from fastq files alignment.

**Comment by linxianzu1995** [comment]
Align command ：~/mixcr-4.0/mixcr align -p kAligner2 -s hsa --library imgt -t 8 -OvParameters.geneFeatureToAlign=VGeneWithP --verbose -f -OsaveOriginalReads=true -j test_align.json --not-aligned-R1 Test.R1.fastq.gz -OvParameters.parameters.floatingLeftBound=false -OjParameters.parameters.floatingLeftBound=false -OvParameters.parameters.floatingRightBound=false -OjParameters.parameters.floatingRightBound=false -OallowPartialAlignments=true  test.assembled.fastq.gz test.vdjca

Align command ：~/mixcr-4.1.1/mixcr align --report ./test.align.report.txt --json-report ./test.align.report.json --preset generic-bcr-amplicon --rigid-left-alignment-boundary --floating-right-alignment-boundary C --dna --species hsa test.assembled.fastq.gz ./test.vdjca

 I have tried both MiXCR versions 4.0.0 and 4.1.1 and they both report an error at the assemble step.  I also considered the high GC percentage of reads to be the cause of the error and tried filtering out Reads with a GC percentage greater than 70% and then ran MiXCR, but it still reported the same error. Is it a problem with the command, please?

**Comment by dbolotin** [comment]
Can you please post the error message from mixcr 4.1.1 and confirm that there are no intermediate commands between `align` and `assemble` commands. This is a very strange error message, so, for clarity, it would be great to have all the commands and the error message for a specific mixcr version. If you can share the data to reproduce the error on our side that would also help the debug process, for that you can write us at support@milaboratories.com .

**Comment by linxianzu1995** [comment]
Hi, I'll try to reproduce the problem and get back to you.

**Comment by linxianzu1995** [comment]
Sorry, I am unable to reproduce the same problem at the moment, but other problems have arisen. mixcr exportAlignments Does this intermediate command have any effect on the analysis that follows?

## Command
mixcr align -p kAligner2 -s hsa --library imgt -t 8 -OvParameters.geneFeatureToAlign=VGeneWithP --verbose -f -OsaveOriginalReads=true -j test_align.json --not-aligned-R1 test.R1.fastq.gz -OvParameters.parameters.floatingLeftBound=false -OjParameters.parameters.floatingLeftBound=false -OvParameters.parameters.floatingRightBound=false -OjParameters.parameters.floatingRightBound=false -OallowPartialAlignments=true test.fastq.gz test.vdjca
mixcr exportAlignments -f test.vdjca test.alignment.txt
mixcr assemble -j test_clones.json -f -a -ObadQualityThreshold=15 test.vdjca test.clna

## ERROR
Initialization: progress unknown
Assembling initial clonotypes: 2.6%
Assembling initial clonotypes: 14.8%  ETA: 00:00:13
Assembling initial clonotypes: 31%  ETA: 00:00:08
Assembling initial clonotypes: 47%  ETA: 00:00:06
Assembling initial clonotypes: 60.6%  ETA: 00:00:05
Assembling initial clonotypes: 73.4%  ETA: 00:00:04
Assembling initial clonotypes: 87.2%  ETA: 00:00:01
Assembling initial clonotypes: 98.1%  ETA: 00:00:00
Mapping low quality reads: 5.4%
Mapping low quality reads: 19.2%  ETA: 00:00:11
Mapping low quality reads: 38.6%  ETA: 00:00:06
Mapping low quality reads: 54.8%  ETA: 00:00:05
Mapping low quality reads: 73.7%  ETA: 00:00:02
Mapping low quality reads: 88.4%  ETA: 00:00:01
Pre-clustering: 100%  ETA: 00:00:00
Clustering: 0%
Clustering: 10.2%  ETA: 00:04:07
Clustering: 20.8%  ETA: 00:02:37
Clustering: 31.3%  ETA: 00:01:51
Clustering: 42%  ETA: 00:01:57
Clustering: 52.5%  ETA: 00:01:07
Clustering: 62.9%  ETA: 00:00:49
Clustering: 73.4%  ETA: 00:00:30
Clustering: 84.6%  ETA: 00:00:06
Clustering: 96%  ETA: 00:00:04
Building clones: 0.3%
Building clones: 10.8%  ETA: 00:01:50
Building clones: 21.3%  ETA: 00:01:29
Building clones: 31.5%  ETA: 00:01:21
Building clones: 41.6%  ETA: 00:01:03
Building clones: 51.8%  ETA: 00:01:15
Building clones: 61.9%  ETA: 00:00:45
Building clones: 72.2%  ETA: 00:00:32
Building clones: 83%  ETA: 00:00:20
Building clones: 93.6%  ETA: 00:00:10
Initialization: progress unknown
Writing clones: 28.3%
Writing clones: 96.1%  ETA: 00:00:00
Sorting alignments: 2.2%
Sorting alignments: 13.9%  ETA: 00:00:23
Sorting alignments: 24.2%  ETA: 00:00:22
Sorting alignments: 35.5%  ETA: 00:00:17
Sorting alignments: 46.8%  ETA: 00:00:14
Sorting alignments: 58.1%  ETA: 00:00:11
Sorting alignments: 71.2%  ETA: 00:00:06
Sorting alignments: 81.3%  ETA: 00:00:05
Sorting alignments: 93.8%  ETA: 00:00:01
Sorting alignments: 106.3%  ETA: 00:00:-1
Writing alignments: 0.4%
Writing alignments: 10.6%  ETA: 00:03:30
Writing alignments: 20.8%  ETA: 00:01:02
Writing alignments: 31.2%  ETA: 00:01:25
Writing alignments: 41.4%  ETA: 00:01:49
Writing alignments: 51.9%  ETA: 00:01:49
Writing alignments: 62.3%  ETA: 00:01:05
Writing alignments: 72.7%  ETA: 00:00:47
Writing alignments: 83%  ETA: 00:00:39
Writing alignments: 93%  ETA: 00:00:11
Writing alignments: 103.7%  ETA: 00:00:-6
java.lang.AssertionError
        at com.milaboratory.mixcr.cli.CommandAssemble.run1(CommandAssemble.java:304)
        at com.milaboratory.cli.ACommandWithSmartOverwrite.run0(ACommandWithSmartOverwrite.java:118)
        at com.milaboratory.cli.ACommand.run(ACommand.java:100)
        at picocli.CommandLine.executeUserObject(CommandLine.java:1769)
        at picocli.CommandLine.access$900(CommandLine.java:145)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2141)
        at com.milaboratory.mixcr.cli.Main$1.handle(Main.java:140)
        at com.milaboratory.mixcr.cli.Main$1.handle(Main.java:129)
        at picocli.CommandLine$AbstractParseResultHandler.handleParseResult(CommandLine.java:1968)
        at com.milaboratory.mixcr.cli.Main.handleParseResult(Main.java:151)
        at com.milaboratory.mixcr.cli.Main.main(Main.java:123)
