### ISSUE TITLE
AuthorizationError

### ISSUE THREAD

**Issue by Echoloria** [milaboratory/mixcr#918]
Hi, 
I have used mixcr for a long time, it works well. But yesterday I met an error like this:

Alignment: 0.2%
License error: AuthorizationError: invalid licensing code

## Exact MiXCR commands 

java -jar ./mixcr.jar  align --species hsa  -p kAligner2  --report report.txt  /data/sample1_2.fastq.gz  /data/try.vdjca

By the way, the version of mixcr I'm using is 3.0.2, and I also tried it in version 4.0.0. I got the same error mentioned above. How could I solve this ?

Thanks!
Echo

**Comment by PoslavskySV** [comment]
Hi, this is strange. Can you send us your working email that you used to obtain license? You can send here or to support@milaboratories.com

**Comment by Echoloria** [comment]
Hi Stan,
     Mixcr works again! 

Thanks,
Echo
