### ISSUE TITLE
Miseq was analyzed using mixcr

### ISSUE THREAD

**Issue by zznx** [milaboratory/mixcr#919]
Data: miseq (FR3)
File: 5 fastq file 
Result: CDR3 seq was the same for the five first clones
I think there's a problem.What do you think?

Thank you for your help!

**Comment by PoslavskySV** [comment]
Hi,

This means that your first five clones have same CDR3 sequence and different V or J or C gene assignments (you probably used separateBy V, J or C option).

**Comment by zznx** [comment]
Thank you very much ,
Supplement (The CDR3 sequence of the first clone):
File1 :TGTGCGAGAGGGCAGCTGGTCAAAAACTGG
File2 :TGTGCGAGAGGGCAGCTGGTCAAAAACTGG
File3 :TGTGCGAGAGGGCAGCTGGTCAAAAACTGG
File4 :TGTGCGAGAGGGCAGCTGGTCAAAAACTGG
File5 :TGTGCGAGAGGGCAGCTGGTCAAAAACTGG

<html xmlns:v="urn:schemas-microsoft-com:vml" xmlns:o="urn:schemas-microsoft-com:office:office" xmlns:x="urn:schemas-microsoft-com:office:excel" xmlns="http://www.w3.org/TR/REC-html40">
<head>

<meta name=Generator content="Microsoft Excel">

<style>

</style>
</head>
<body>



nSeqFR1 | nSeqCDR1 | nSeqFR2 | nSeqCDR2 | nSeqFR3 | nSeqCDR3 | nSeqFR4
-- | -- | -- | -- | -- | -- | --
  |   |   |   |   | TGTGCGAGAGGGCAGCTGGTCAAAAACTGG |  



</body>

</html>

**Comment by zznx** [comment]
Do you think there's a problem? Why so many Spaces, and the question above

Thank you very much !

**Comment by zznx** [comment]
I didn't use separateBy
> Hi,
> 
> This means that your first five clones have same CDR3 sequence and different V or J or C gene assignments (you probably used separateBy V, J or C option).

**Comment by zznx** [comment]
Hi, 
I find that the Overlapped value is relatively low. Is this due to possible reasons
Align Report
```
Command line arguments: align -s human -t 16 -f -OallowPartialAlignments=true -OvjAlignmentOrder=JThenV -OminSumScore=200 --library imgt.201946-3.sv6 -OsaveOriginalReads=true --report /product/GR/FR3/R7-F1_S1_align.report /seqdir/illumina/miseq/20221109/FR3/R7-F1_S1_L001_R2_001.fastq.gz /seqdir/illumina/miseq/20221109/FR3/R7-F1_S1_L001_R1_001.fastq.gz /product/GR/FR3/R7-F1_S1_align.vdjca
Analysis time: 3.28m
Total sequencing reads: 165423
Successfully aligned reads: 65930 (39.86%)
Paired-end alignment conflicts eliminated: 2056 (1.24%)
Alignment failed, no hits (not TCR/IG?): 965 (0.58%)
Alignment failed because of absence of CDR3 parts: 16505 (9.98%)
Alignment failed because of low total score: 82023 (49.58%)
Overlapped: 1 (0%)
Overlapped and aligned: 0 (0%)
Alignment-aided overlaps: 0 (NaN%)
Overlapped and not aligned: 1 (0%)
V gene chimeras: 774 (0.47%)
J gene chimeras: 99 (0.06%)
IGH chains: 65930 (100%)
Realigned with forced non-floating bound: 330844 (200%)
Realigned with forced non-floating right bound in left read: 103 (0.06%)
Realigned with forced non-floating left bound in right read: 103 (0.06%)
======================================
```

**Comment by PoslavskySV** [comment]
You see only CDR3 in clonotype table because you used only CDR3 to assemble clonotypes, and didn't use other regions. For Align Report I don't see any issues. For CDR3 seq in 5 files - also I don't see problems. 

It seems you are expecting some output from your data but the way you run MiXCR is not proper for your protocol/kit. I recommend to use a single analyze command with a preset - https://docs.milaboratories.com/mixcr/reference/overview-built-in-presets/ - specific for your particular kit. If you don't find a preset for your kit in the docs, just let us know and we will create a preset for it.

**Comment by zznx** [comment]
Hi,
I compared the other analyses(PE data) and found overlap values of more than 80% for the other results, which I would sequence again
Thank you very much

**Comment by zznx** [comment]
Hi,
I compared the other analyses(PE data) and found overlap values of more than 80% for the other results, which I would sequence again.I'll talk to you if I have any questions

Thank you very much

**Comment by zznx** [comment]
Hi,
`Successfully aligned reads: 14171 (1.89%)`，Why are the reads successfully aligned so low?
```
Command line arguments: align -s human -t 16 -f -OminSumScore=200 --library imgt.201946-3.sv6 -OsaveOriginalReads=true --report /product/GR/miseq_20230101/CLLB010178-DNA-IGHV_S9_L001_align.report /home/zhangjx/miseq_20221231/CLLB010178-DNA-IGHV_S9_L001_R2_001.fastq.gz /home/zhangjx/miseq_20221231/CLLB010178-DNA-IGHV_S9_L001_R1_001.fastq.gz /product/GR/miseq_20230101/CLLB010178-DNA-IGHV_S9_L001_align.vdjca
Analysis time: 4.88m
Total sequencing reads: 748221
Successfully aligned reads: 14171 (1.89%)
Paired-end alignment conflicts eliminated: 4888 (0.65%)
Alignment failed, no hits (not TCR/IG?): 114443 (15.3%)
Alignment failed because of absence of V hits: 29296 (3.92%)
Alignment failed because of absence of J hits: 547285 (73.14%)
No target with both V and J alignments: 6427 (0.86%)
Alignment failed because of low total score: 36599 (4.89%)
Overlapped: 625995 (83.66%)
Overlapped and aligned: 2880 (0.38%)
Alignment-aided overlaps: 23 (0.8%)
Overlapped and not aligned: 623115 (83.28%)
V gene chimeras: 693 (0.09%)
J gene chimeras: 6 (0%)
IGH chains: 14167 (99.97%)
IGK chains: 2 (0.01%)
IGL chains: 2 (0.01%)
Realigned with forced non-floating bound: 244498 (32.68%)
Realigned with forced non-floating right bound in left read: 18 (0%)
Realigned with forced non-floating left bound in right read: 18 (0%)
```
Thank you very much

**Comment by PoslavskySV** [comment]
Hi, 

you can find the reasons why aligned rate is so low in the lines below:

Alignment failed, no hits (not TCR/IG?): 114443 (15.3%)
Alignment failed because of absence of V hits: 29296 (3.92%)
Alignment failed because of absence of J hits: 547285 (73.14%)
No target with both V and J alignments: 6427 (0.86%)

What is your protocol?

**Comment by zznx** [comment]
I don't have a particular idea, so how should I solve it?  Can you give me specific commands?

**Comment by PoslavskySV** [comment]
MiXCR provides you a rigorous report with all the information. According to the report you attached, you either have wet lab issues or use MiXCR commands not suitable for your library preparation protocol. To solve it, you need to contact with wet lab people who did library preparation and figure out what are the reasons of the above issues, as well as what library preparation protocol was used.
