### ISSUE TITLE
Support for BD Rhapsody fulll-length VDJ

### ISSUE THREAD

**Issue by hongduosun** [milaboratory/mixcr#920]
Thanks for developing such a great tool!

Is there any plan to add support for the BD Rhapsody full-length protocol?

https://www.bdbiosciences.com/en-us/products/reagents/single-cell-multiomics/vdj#Overview

R1 structure:
<img width="637" alt="Screenshot 2022-12-07 at 22 45 22" src="https://user-images.githubusercontent.com/14342620/206209502-33944b78-bfa0-4abd-89a0-9adaa4100cca.png">

**Comment by mizraelson** [comment]
Hi,
Yes, we surely will add a full-length protocol support. I haven't found any published data yet to test a full-length preset. If by any chance there is an open access dataset that you know of - please let me know. When the data is available it only will take me a few days to add this functionality.
Also, we are currently working on supporting sample tags for BD Rhapsody protocols.

**Comment by hongduosun** [comment]
Yes, these is a demo dataset:
https://scomix.bd.com/hc/en-us/articles/4424059302157-Rhapsody-TCR-BCR-Full-Length-Demo-Dataset
Corresonding fastqs:
http://bd-rhapsody-public.s3-website-us-east-1.amazonaws.com/Rhapsody-Demo-Data-Inputs/RhapTCRBCRdemo/

**Comment by igemuend** [comment]
Hi,
Thank you for developing and maintaining this cool tool!
Just wanted to check in: Is there any update on adding the preset for 5' barcoded TCR/BCR libraries on enhanced beads?

**Comment by mizraelson** [comment]
Hi, yes, we are preparing the preset for full-length BD rhapsody protocol. It should be ready by the end of the week.

**Comment by igemuend** [comment]
Awesome, looking forward to trying it! Thanks for getting back to me so quickly.

**Comment by PoslavskySV** [comment]
Added in [v4.2](https://github.com/milaboratory/mixcr/releases/tag/v4.2.0).
