### ISSUE TITLE
mixcr findShmTrees doesn't cluster all the sequences

### ISSUE THREAD

**Issue by NoELJ22** [milaboratory/mixcr#924]
Hello,

I would like to reconstructed somatic hypermutations trees from cloneset.

So I used the "mixcr findShmTrees" command with default parameters and  "mixcr exportShmTreesWithNodes" with --only-observed parameter, to see if all the sequences identified in upstream analysis are found in a tree. 
But this isn't the case. I lost many sequences in the tsv file obtained with exportShmTreesWithNodes.

Is it possible to recover the other sequences not clustered? 
I would like to know the number of mutations compared to their germline of all the sequences identified in upstream analysis.

Thank you

**Comment by dbolotin** [comment]
Hello, can you please specify which columns from the `exportShmTreesWithNodes` are you interested in? Many things can also be exported on `exportClones` (please see [here](https://docs.milaboratories.com/mixcr/reference/mixcr-export/#export-fields)).

**Comment by NoELJ22** [comment]
I'm interested by the DistanceFromGermline column from exportShmTreesWithNodes  (obtained with "-distance germline"). To have the number of mutations compared to the germline, for each sequence. 
Can we have a similar information with exportClones?

**Comment by dbolotin** [comment]
Got it. Yes, we definitely can add such column. This will be added in the next release. We will let you know as soon as pre-release with this feature will be available.

**Comment by PoslavskySV** [comment]
As a workaround right now you can do the following. You can export mutations with exportClone command, e.g. 
```
mixcr exportClones -nMutations CDR2 ...
```
will export mutations in CDR2 relative to germline.  MiXCR uses the following [mutations encoding format](https://docs.milaboratories.com/mixcr/reference/ref-mutations-encoding/). Then you can simply count the number of letters 'S' (substitutions), 'I' (insertions), and 'D' (deletions) in the resulting column to count the number of mutations in CDR2 relative to germline. Let us know if it will work on your end.

**Comment by amikelov** [comment]
`mixcr exportClones -vBestIdentityPercent -jBestIdentityPercent ...`

`-vBestIdentityPercent` `-jBestIdentityPercent`  could also be the fields which could help you with this question.
Just substract these from 1, аnd you will get fraction of the mutated bases for V and J genes. You can then multiply by length of corresponding segment to get the absolute number of SHM. However keep in mind that CDR3 mutations obviously can not be detected for the clones which do not appear in lineages.

**Comment by NoELJ22** [comment]
Thank you for your answers.
With nMutation I can indeed have the number of mutation in the regions I am interested in,  and also have the type of mutation 

Thanks again for your help
