### ISSUE TITLE
License error: AuthorizationError: CreateToken: invalid client current time

### ISSUE THREAD

**Issue by dstcr** [milaboratory/mixcr#929]
Getting the error "License error: AuthorizationError: CreateToken: invalid client current time" on Ubuntu.
Used to work fine untill very recently.
Have re-activated licence, which is accepted, but then throws up this error again.

(base) :/mixcr$ mixcr activate-license
Please enter the license:
(redacted)
Checking the license...
Ok
License activated successfully.
(base) :/mixcr$ mixcr -v
License error: AuthorizationError: CreateToken: invalid client current time

**Comment by PoslavskySV** [comment]
Hi,

as per error message provided - could you check that your system time is correct? If yes, can you provide the email associated with the license key or contact us directly via support@milaboratories.com.

**Comment by PoslavskySV** [comment]
Closing this at the moment. Feel free to reopen if the problem persists.
