### ISSUE TITLE
slow mixcr slurm job in HPC

### ISSUE THREAD

**Issue by github-wow** [milaboratory/mixcr#935]
Hi guys,

I tried several normal `analyze` `mixcr` scripts  (with `-Xmx350G -t 32`) for a couple of raw (PE) .fastq.gz files 440Mb each
(25774680 lines in decomressed files):

`mixcr -Xmx350g analyze -t 32 milab-mouse-tcr-rna-race-cdr3 1.fq.gz 2.fq.gz ./output/result`
(For [`-t`](https://docs.milaboratories.com/mixcr/reference/mixcr-analyze/#analyze-specific-command-line-options) this [comment](https://github.com/milaboratory/mixcr/issues/561#issuecomment-565647138) was helpful.)

on the HPC with the following parameters used:
4CPUs + 16Gb RAM --> 60 min
16CPUs + 128Gb RAM --> 60 min
32CPUs + 350Gb RAM --> 20 min

What could be a possible reason for such a slow computation...?

Thanks a lot!

**Comment by PoslavskySV** [comment]
Hi,

judging by the first two lines (4CPU or 16CPU - time is the same) - it looks like you don't have 16CPUs on the machine you running MiXCR. Especially if you are running in HPC, you need to submit job for execution on a machine with enough CPU available (and acessible).

**Comment by github-wow** [comment]
Thanks for reply!

Slurm's [sacct ](https://slurm.schedmd.com/sacct.html)showed:
about the # of CPUs: AllocCPUS=32 and
about actively used RAM: MaxRSS=141658.50M (which is 138Gb).
The job has State=completed without any reported errors.

I tried with different # of CPUs and RAM but still no substantial computational time reduction.

An annoying thing is that on a normal office PC `mixcr4` did the job in 40min (vs. 20-60min on HPC)
and after running for several samples mixcr4 throttled the PC.
I remember that mixcr3 completed 1 sample also in ~40min but without throttling.

**Comment by PoslavskySV** [comment]
Regarding slurm - unfortunately I can't advice, it is better to consult system administrator how to deal with it.

Regarding PC throttling. By default, MiXCR loads 100% of the hw resources, and if you face throttling this means that the  the cooling of the PC is not sufficient - most often because of the thermal paste is dry. You can restrict number of used CPUs by supplying `-t` option to MiXCR and prevent 100% load of your PC.

**Comment by github-wow** [comment]
@PoslavskySV , a short question: maybe instead of
`mixcr -Xmx350g analyze -t`

one should do:
`mixcr -Xms350g -Xmx350g analyze -t`
?

Or maybe `350g` makes no sense as [here](https://alvinalexander.com/blog/post/java/java-xmx-xms-memory-heap-size-control/) for example for `-Xmx` is written: "The maximum heap limit is about 2 GB (2048MB)"

**Comment by PoslavskySV** [comment]
Hi. No it should be now difference. Xms is a pre-allocated memory, it helps to speedup start of the execution, while the limit is controlled by Xmx.
