### ISSUE TITLE
Clone counts in exportReadClones and exportClones doesn't match 

### ISSUE THREAD

**Issue by sravani9408** [milaboratory/mixcr#938]
Hello,

I am trying to export sequences for a few clones using exportReadClones. However, the number of sequences returned by the exportReadClones command does not match the clone Count column in clones file (exportClones output). 

For Clone 0, exportReadClones writes out 79 sequences while the clone count column shows 78. Does the output from exportClones command contain only sequences of high quality or something else that can explain the numbers? 

Thanks!

**Comment by PoslavskySV** [comment]
Hi, 

I believe this is because of `-OaddReadsCountOnClustering=false` by default (so reads corrected and attached as PCR errors do not increase clone count, although they will appear in exportReadsForClones). You can check this by re-running assemble with `-OaddReadsCountOnClustering=true`

**Comment by sravani9408** [comment]
That worked! Thank you @PoslavskySV !! Is there a way to know the header of such sequences and/or exclude them from appearing in exportReadsForClones?

**Comment by PoslavskySV** [comment]
No, it is not possible to specifically exclude PCR-clusterized reads from exporting reads for clones with `exportReadsForClonesCommand`. You can issue a new feature request to add such filtering.

Meanwhile you can do it manually with some scripts: you can export alignments from `.clna` file with `-cloneIdWithMappingType` and `-readIds` columns and then filter original fastq/fasta manually.
