### ISSUE TITLE
Unmatched arguments from index 1 error - Mixcr v4.0

### ISSUE THREAD

**Issue by colin-leeyc** [milaboratory/mixcr#941]
Hi, I am trying to run Mixcr on some human TCRseq samples, and run into the unmatched arguments error no matter what I have tried.

## My Mixcr command is as follows:

mkdir -p results
mixcr analyze takara-human-tcr-V1-full-length \
         fastq/CMDxyz_R1_001.fastq.gz \
         fastq/CMDxyz_R2_001.fastq.gz \
         results/xyz

## MiXCR report files ($job.err output)

Unmatched arguments from index 1: 'takara-human-tcr-V1-full-length', 'fastq/CMDLxyz_R1_001.fastq.gz', 'fastq/CMDLxyz_R2_001.fastq.gz', 'results/CMDLxyz'
Usage: mixcr analyze [COMMAND]
Run full MiXCR pipeline for specific input.

-----
Not quite sure what the error message is pointing to, as the files are definitely all there!

Any advise would be very much appreciated, thank you!

**Comment by PoslavskySV** [comment]
Hi, did you try with the most recent version (4.1.2)?

**Comment by colin-leeyc** [comment]
Hi Stanislav, I think this indeed might have been the issue as I was on v4.0.. The job is running successfully. Thank you so much!
