### ISSUE TITLE
manual for v3.0.13

### ISSUE THREAD

**Issue by sean-takara** [milaboratory/mixcr#946]
## Checklist before submitting the issue:

 - [x] The issue is strongly related to the MiXCR software
 - [ ] The issue can be reproduced with [the most recent version](https://github.com/milaboratory/mixcr/releases) of MiXCR
 - [ ] There is no answer to the question in the [official documentation](http://mixcr.readthedocs.io/) and there is no duplicate issue in the [bug tracker](https://github.com/milaboratory/mixcr/issues?utf8=✓&q=)  
 - [ ] Inspection of raw alignments with [exportAlignmentsPretty](http://mixcr.readthedocs.io/en/master/export.html#exporting-well-formatted-alignments-for-manual-inspection) shows that data has the expected architecture, and sample preparation artefacts are not the reason of the problem (if this is the matter of the issue)

## Expected Result

*A description of what you wanted to happen*

## Actual Result

*A description of what actually happened*

## Exact MiXCR commands 

*Paste here __exact__ MiXCR commands you used (enclose it with single `` ` ``  for better formatting)*

## MiXCR report files 

*Paste here content of the report files produced by MiXCR (enclose it with triple ```` ``` ````  for better formatting)*

**Comment by sean-takara** [comment]
where to download the document (manual) of mixcr v3.0.13? Thanks

**Comment by PoslavskySV** [comment]
Hi Sean! Documentation for old versions is archived and absent on our documentation portal. What particularly are you looking for? We can generate and send you html/pdf version, but almost all old parameters are same in the recent versions.

**Comment by sean-takara** [comment]
Hi Stanislav,

Thanks for your prompt response. I have been testing both mixcr version v4+ and v3.0.13 and did not find some parameters, such as "-keep-non-CDR3-alignments" in v3.0.13.

If possible, could you please generate the whole document (manual) for the mixcr v3.0.13? Highly appreciate your time and help.

Best Regards,
Sean
________________________________

**Comment by PoslavskySV** [comment]
Hi Sean,

we sent you old manual via email. Regarding `-keep-non-CDR3-alignments`: it is equivalent of
```
mixcr align -OallowNoCDR3PartAlignments=true -OallowPartialAlignments=true ...
```

**Comment by sean-takara** [comment]
Hi Stanislav,

Got the two files (pdf and zip). Highly appreciate your time and help. Happy New Year!

Best Regards,
Sean
