### ISSUE TITLE
Does findShmTrees analyse SHM using the full sequence?

### ISSUE THREAD

**Issue by linxianzu1995** [milaboratory/mixcr#948]
Hi, I would like to use mixcr for SHM analysis. I would like mixcr to use only the IGHV gene alignment results to calculate identity. so I would like to confirm whether mixcr findShmTrees uses the full sequence or the IGHV gene.

**Comment by PoslavskySV** [comment]
Hi,

you don't need SHM trees to calculate identity. You can just use MiXCR export clones and add `-vBestIdentityPercent ` and `-jBestIdentityPercent ` columns to export:

```
mixcr exportClones -vBestIdentityPercent -jBestIdentityPercent input.clns output.tsv
```

Is that what you need?

**Comment by PoslavskySV** [comment]
Also, if you want to calculate identity relative to the allelic variants you can infer alleles for your animal:

```
mixcr findAlleles -r findAlleles.report.log --export-alleles-mutations strainX_alleles.tsv --export-library strainX_library.fasta --output-template {file_name}.reassigned.clns *.clns 
```

and then use `exportClones`

**Comment by linxianzu1995** [comment]
Thank you！
