### ISSUE TITLE
-OvjAlignmentOrder=VThenJ

### ISSUE THREAD

**Issue by zznx** [milaboratory/mixcr#950]
Hi,
I want to know which one I should watch and which one has higher priority
No use `-OvjAlignmentOrder=VThenJ`
```
Alignment failed, no hits (not TCR/IG?): 13391 (3.01%)
Alignment failed because of absence of V hits: 2954 (0.66%)
Alignment failed because of absence of J hits: 79269 (17.81%)
```
Use `-OvjAlignmentOrder=VThenJ`
```
Alignment failed, no hits (not TCR/IG?): 1707 (0.38%)
Alignment failed because of absence of CDR3 parts: 144038 (32.37%)
Alignment failed because of low total score: 281584 (63.27%)
```
```
-OvjAlignmentOrder=VThenJ (only for single-end analysis)
Order in which V and J genes aligned in target (possible values JThenV and VThenJ). Parameter affects only single-read alignments and alignments of overlapped paired-end reads. Non-overlapping paired-end reads are always processed in VThenJ mode. JThenV can be used for short reads (~100bp) with full (or nearly full) J gene coverage.
```

**Comment by PoslavskySV** [comment]
Hi,

as per the docs:

Order in which V and J genes aligned in target (possible values JThenV and VThenJ). Parameter affects only single-read alignments **_and alignments of overlapped paired-end reads_**. Non-overlapping paired-end reads are always processed in VThenJ mode. JThenV can be used for short reads (~100bp) with full (or nearly full) J gene coverage.
