### ISSUE TITLE
"--criteria CDR3|AA|V|J" in "mixcr postanalysis overlap " returns error?

### ISSUE THREAD

**Issue by github-wow** [milaboratory/mixcr#952]
Hi,

I do:

```
mixcr postanalysis overlap \
--default-downsampling count-reads-auto \
--default-weight-function read \
--criteria CDR3|AA|V|J \
--only-productive \
--drop-outliers \
--chains TRA \
--metadata metadata.tsv \
*.clns \
pa.overlap.json.gz
```

I see:

```
AA: command not found
V: command not found
J: command not found
positional parameter at index 0 ((cloneset.(clns|clna)|directory)... result.json[.gz]) requires at least 2 values, but none were specified.
```

It is [said](https://docs.milaboratories.com/mixcr/reference/mixcr-postanalysis/#overlap-postanalysis) `CDR3|AA|V|J` is default.

**Comment by PoslavskySV** [comment]
Hi,

use quotes: `--criteria "CDR3|AA|V|J"`

**Comment by github-wow** [comment]
Maybe edit the [help](https://docs.milaboratories.com/mixcr/reference/mixcr-postanalysis/#overlap-postanalysis)? And use a format like: `AA|CDR3|V|J` and similar for the rest cases? But certainly this is just a matter of taste.
