### ISSUE TITLE
10X 5' PBMC hashtagged data

### ISSUE THREAD

**Issue by learning-MD** [milaboratory/mixcr#966]
Hi,

Looking forward to using this package for single-cell 5' human PBMC data. I had three questions:

1. If I have hashtagged samples (e.g., 5 tagged samples pooled in one lane each), and my sequencing output looks as below (with the FB files containing feature barcodes), what modification to running the 5' preset could would you recommend?

![image](https://user-images.githubusercontent.com/88126859/211689572-4ed41d7d-87df-4f52-8d12-58511c236a5e.png)

```
mixcr analyze 10x-5gex-full-length \
     --species hsa \
     sample_R1.fastq.gz \
     sample_R2.fastq.gz \
     sample_result
```

2. Is there a way to merge Mixcr output with gene expression in scanpy or Seurat (e.g., using cell barcodes as the anchor)? That way, for example, we can pull particular clones and look at transcriptomic differences between those clones and others.

3. Does Java need to be installed in a particular spot? I have Java 8 but still keep getting `Wrong version of java. Please use Java 7 or higher.`

Thanks!

**Comment by mizraelson** [comment]
Hi,
1) We are currently working on implementation of sample tags for single cell data like 10x and BD Rhapsody. This feature will be available soon in one of the upcoming releases. 

2) yes, you can use cell barcodes to merge gene expression data with clonotypes. Also, soon we will add support for gene expression in MiXCR itself.

3) Can you please provide the exact command how you run MiXCR, do you run it on a cluster?

All the best,
Mark

**Comment by learning-MD** [comment]
@mizraelson, sorry for the delay. I haven't run it yet, as I keep getting that Java error despite having Java 8. I'm aiming to run it locally on a high-performance computer. If I can figure out how to get around this error, is is possible to run the 10x 5' preset with the BAM file as the input or would the preset only take fastq/fastq.gz files?

Would it be worth waiting until the implementation of sample tags is in place? Thanks.

**Comment by mizraelson** [comment]
Sample tags will be available next week.
Regarding the java version error -  can you try to run mixcr with `java -jar mixcr.jar ....` command. 
Right now MiXCR only works with fastq/fasta files, but .bam  files support will be added soon.

**Comment by learning-MD** [comment]
Will try shortly and that's perfect re: the sample tags availability next week. Looking forward to it!

**Comment by PoslavskySV** [comment]
Please, check out [v4.2](https://github.com/milaboratory/mixcr/releases/tag/v4.2.0) which adds complete support of sample barcodes.

**Comment by learning-MD** [comment]
@PoslavskySV Thanks for the update! Is there support for "multiple samples, one lane" (e.g., hashed samples with TotalSeq C antibodies run on one lane) for a 10X Genomics experiment, by any chance? I've tried running the below (from the one sample, multiple files section):

```
~/mixcr/mixcr analyze 10x-5gex-full-length \
>      --species hsa \
>      {{a}}_{{R}}_L{{n}}.fastq.gz \
>      Sample_result
```

With the GEX and FB files as above:

![image](https://user-images.githubusercontent.com/88126859/216232128-ad017635-1ffc-465b-a8f1-3d8e70f2c8ea.png)

I unfortunately get the following error despite running the above command in the folder harboring those 4 files:

`No matching files found for pattern {{a}}_{{R}}_L{{n}}.fastq.gz.`

Any ideas/suggestions would be appreciated. Thanks!

**Comment by PoslavskySV** [comment]
Hi,

yes, you have lane index before R1/2. Can you please try the following matching pattern:

```
{{a}}_L{{n}}_{{R}}_{{n}}.fastq.gz
```

where 

- {{a}} will match `SB-1_FB_S1` and `SB-1_S1`
- L{{n}} will match `L005`
- {{R}} will match R1 and R2
- the last {{n}} will match `001`

Let me know how it works.

**Comment by learning-MD** [comment]
It seems to have worked. However, not sure that it auto-read the cell barcodes, as the sequence_id does not contain cell barcodes when I converted the clna file to airr format:

![image](https://user-images.githubusercontent.com/88126859/216420595-7783cc4a-2d54-44d4-987e-004840490e47.png)

**Comment by PoslavskySV** [comment]
This doesn't look like standard MiXCR output. In MiXCR output you should see cell barcode column.  How do you export results?

**Comment by PoslavskySV** [comment]
@learning-MD we've added columns related to SC analysis in airr output. You can use the following build:

Docker images: ghcr.io/milaboratory/mixcr/mixcr:4.2.0-40-develop
Download links: https://cdn.milaboratory.com/software/mixcr/mixcr-4.2.0-40-develop-1f6fa69105d902d320973627435db809e4476e2f.zip
