### ISSUE TITLE
Is it possible to add additional fields to exportClones step while "analyze" ?

### ISSUE THREAD

**Issue by github-wow** [milaboratory/mixcr#977]
[Here](https://docs.milaboratories.com/mixcr/reference/mixcr-export/#single-cell-libraries) is an example for a separate `exportClones` step.
Is it possible to modify `analyze` itself by additional parameters?
I tried `--remove-step exportClones` but normal clones.tsv file is generated and with default preset-controlled fields.
Namely, these are of interest:
cloneId, cloneCount, cloneFraction, targetSequences, targetQualities. allVHitsWithScore, allDHitsWithScore, allJHitsWithScore, allCHitsWithScore, allVAlignments, allDAlignments, allJAlignments, allCAlignments, nSeqFR1, minQualFR1, nSeqCDR1, minQualCDR1, nSeqFR2minQualFR2, nSeqCDR2, minQualCDR2, nSeqFR3, minQualFR3, nSeqCDR3, minQualCDR3, nSeqFR4, minQualFR4, aaSeqFR1, aaSeqCDR1, aaSeqFR2, aaSeqCDR2, aaSeqFR3, aaSeqCDR3, aaSeqFR4, refPoints.

**Comment by mizraelson** [comment]
Hi, yes, you can add additional fields to analyze using the following parameter:

Example:
--append-export-clones-field refPoints

More on that here:
https://docs.milaboratories.com/mixcr/reference/overview-mixins-list/#export-mix-in-options

**Comment by github-wow** [comment]
Thank you for the reply, @mizraelson .

I guess to have aaSeqFR1, aaSeqCDR1, aaSeqFR2, aaSeqCDR2, aaSeqFR3, aaSeqCDR3, aaSeqFR4 in the output I have to use `-allAAFeatures` with default `FR1Begin FR4End` :
```
mixcr analyze -f milab-human-tcr-rna-race-cdr3 \
--append-export-clones-field -allAAFeatures FR1Begin FR4End \
1.fq 2.fq output
```

but in the log I see:
```
mixcr exportClones clones.clns clones.tsv
WARNING: FR1 is not covered (-allAAFeatures FR1)
WARNING: CDR1 is not covered (-allAAFeatures CDR1)
WARNING: FR2 is not covered (-allAAFeatures FR2)
WARNING: CDR2 is not covered (-allAAFeatures CDR2)
WARNING: FR3 is not covered (-allAAFeatures FR3)
WARNING: FR4 is not covered (-allAAFeatures FR4)
WARNING: FR1 is not covered (-aaFeature FR1)
WARNING: CDR1 is not covered (-aaFeature CDR1)
WARNING: FR2 is not covered (-aaFeature FR2)
WARNING: CDR2 is not covered (-aaFeature CDR2)
WARNING: FR3 is not covered (-aaFeature FR3)
WARNING: FR4 is not covered (-aaFeature FR4)
Exporting TRAD
Exporting clones: 0%
Analysis finished successfully.
```
