### ISSUE TITLE
Assemble contigs throwing up version error

### ISSUE THREAD

**Issue by dstcr** [milaboratory/mixcr#978]
## Checklist before submitting the issue:

 - [x] The issue is strongly related to the MiXCR software
 - [x] The issue can be reproduced with [the most recent version](https://github.com/milaboratory/mixcr/releases) of MiXCR
 - [x] There is no answer to the question in the [official documentation](http://mixcr.readthedocs.io/) and there is no duplicate issue in the [bug tracker](https://github.com/milaboratory/mixcr/issues?utf8=✓&q=)  
 - [x] Inspection of raw alignments with [exportAlignmentsPretty](http://mixcr.readthedocs.io/en/master/export.html#exporting-well-formatted-alignments-for-manual-inspection) shows that data has the expected architecture, and sample preparation artefacts are not the reason of the problem (if this is the matter of the issue)

## Expected Result

Assembling Contigs 

## Actual Result

mixcr assembleContigs hi.clna .clns
Unexpected file version of format: found MiXCR.CLNS.V16 expected MiXCR.CLNA.V11

## Exact MiXCR commands 

 ` mixcr assembleContigs hi.clna .clns
Unexpected file version of format: found MiXCR.CLNS.V16 expected MiXCR.CLNA.V11` 

## MiXCR report files 

I have aligned with this version:
MiXCR v4.1.2 (built Mon Nov 28 09:16:06 GMT 2022; rev=ec9c6fd320; branch=no_branch; host=fv-az165-439)
RepSeq.IO v1.6.0 (rev=43b00498ee)
MiLib v2.2.0 (rev=3fb185f8b2)
Built-in V/D/J/C library: repseqio.v2.0

**Comment by PoslavskySV** [comment]
Hi,

can you try the following command:

 mixcr assembleContigs hi.clna **some_name**.clns

**Comment by dstcr** [comment]
Same problem:
mixcr assembleContigs hi.clna some_name.clns

Unexpected file version of format: found MiXCR.CLNS.V16 expected MiXCR.CLNA.V11

**Comment by PoslavskySV** [comment]
The reason is that the assemble command was used incorrectly (without -a option). BTW, why you don't use mixcr analyze? There are [built-in presets](https://docs.milaboratories.com/mixcr/reference/overview-built-in-presets/) for most of the kits & protocols

**Comment by dstcr** [comment]
re-made assemble clones file with -a 
assembled contigs with 'mixcr assembleContigs --assemble-contigs-by VDJregion hey.clna some_name.clns  -f'
       This is now working, thank you!

'Assembling contigs: 0%
Assembling contigs: 10.4%  ETA: 00:00:34
Assembling contigs: 22.7%  ETA: 00:00:31
Assembling contigs: 32.7%  ETA: 00:00:20
Assembling contigs: 44%  ETA: 00:00:14
Assembling contigs: 54.3%  ETA: 00:00:13
Assembling contigs: 66.8%  ETA: 00:00:10
Assembling contigs: 77.4%  ETA: 00:00:08
Assembling contigs: 88.4%  ETA: 00:00:06
============== AssembleContigs Report ==============
Analysis time: 56.62s
Initial clonotype count: 32126
Final clonotype count: 3 (0.01%)
Canceled assemblies: 0 (0%)
Number of premature termination assembly events, percent of number of initial clonotypes: 0.0 (0%)
Longest contig length: 330
Clustered variants: 9 (75%)
Reads in clustered variants: 125.27598116232818 (0.02%)
Reads in divided (newly created) clones: 0.0 (0%)
Clones with ambiguous letters in splitting region: 0 (0%)
Reads in clones with ambiguous letters in splitting region: 0.0 (0%)
Average number of ambiguous letters per clone with ambiguous letters in splitting region: NaN'




Now getting this error when exporting clones:
 'mixcr exportClones --preset fullImputed   some_name.clns  htt.tsv'
Require tsv file type, got some_name.clns
Re: Built-in presets, I'm working on a new sequencing platform which requires some bespoke pipelines which take exported alignment outputs

**Comment by PoslavskySV** [comment]
Option `--preset` for export is not supported in export anymore; instead the global preset you specify on `analyze` or `align` controls the default export. Please check [here](https://docs.milaboratories.com/mixcr/reference/mixcr-export/). If you want to export imputed receptor features, you can use `--impute-germline-on-export` option on export.

**Comment by dstcr** [comment]
Thank you so much. Just a wider question, if I have the CDR2/FR3 but not the very start of the V gene (FR1/FR2) does Mixcr keep these and only impute the very start? Is there a way to impute only the FR/CDRs that are missing and not the entire gene?

My imputed sequences seem to have more imputation that seems necessary

**Comment by PoslavskySV** [comment]
Yes, of course this is possible, but you need to use correct analysis parameters for [assemble](https://docs.milaboratories.com/mixcr/reference/mixcr-assemble/) (pay attention to `featureToAlign` / `--assemble-clones-by` mix-in) and [assembleContigs](https://docs.milaboratories.com/mixcr/reference/mixcr-assembleContigs/) (use correct `--assemble-contigs-by` mix-in).

**Comment by dstcr** [comment]
All working now! Thank you so much - will close this issue now.
