### ISSUE TITLE
TCR Data From New Species

### ISSUE THREAD

**Issue by bbimber** [milaboratory/mixcr#98]
This isnt directly a MiXCR question, but I hope maybe you might have an answer.  We have TCRA sequence from a new species.  It is being submitted to IMGT; however, I was hoping to get it formatted to be usable in MiXCR in the meantime.  I looked at other IMGT data using the importIMGT script, and there's some non-trivial masking and formatting.  Do you happen to know if there is a standard way to format my input data comparable to IMGT?  Thanks.

**Comment by bbimber** [comment]
That is quite timely.  We are working in macaque, and I'd be happy to share data (though it must be offline since our collaborator is publishing it) if this was of interest.  We are quite keen to get this going, so if there is any help/testing I can provide I would be more than happy to help.

**Comment by dbolotin** [comment]
Good to here that there is a demand for such thing!

You can send me a message (bolotin.dmitriy@gmail.com), and I will contact you as soon as I'll finish writing internals of repseq.io, and it will be possible to start playing with it. We can also discuss our and your's experience of *de novo* reference assembly, as we found that it is not as straightforward as it may seem. Maybe there are some simple tools that can be incorporated into repseq.io to simplify this task for other species.

I will be very happy to have feedback on this project from outside of our lab! It seems to me that absence of good references (at least for "non-standard" species), have become a substantial bottleneck in development of the field.
