### ISSUE TITLE
Exporting AIRR compliant output files for single cell data

### ISSUE THREAD

**Issue by igemuend** [milaboratory/mixcr#999]
Dear developers,

Thank you for developing and maintaining this cool tool! I was especially pleased to see that you included new presets in the last version, which I have used here (v4.2.0). My actual question is about AIRR-compliant output for single-cell data with mixcr.

I used the following (standard) command to analyse my data:
`mixcr analyze bd-rhapsody-human-tcr-full-length  /path/to/input/TCR_R1.fastq.gz  /path/to/input/TCR_R2.fastq.gz   /path/to/output/`
It went through without any problems and I got the following output files:
![image](https://user-images.githubusercontent.com/87134578/217461465-e672ffe5-d863-428b-a3d6-750f876c599c.png)

I looked at the clones.csv file, and it contains the information I am interested in. This is of course e.g. TCR gene & CDR3 mapping, but also cloneID, cell barcodes (maybe it would be possible to include a column with merged cell1-3 bd rhapsody barcodes), umi_counts and consensus_count (I assume this corresponds to readCount?).
For downstream analysis I would like to summarize the results in a AIRR compliant format, which the clones.csv does not appear to be in. For that reason I exported with:
`mixcr exportAirr clones.contigs.clns exportAirr_clones.tsv`

However, as also mentioned at the end of this issue (https://github.com/milaboratory/mixcr/issues/966), the exported AIRR file does not contain the columns cell_id, umi_count and consensus_count, which I would like to get as output for single cell data.
![image](https://user-images.githubusercontent.com/87134578/217462191-efcba9f4-e050-4c9d-969b-ce0fd5f333d7.png)

Is there any way to get this output using the `exportAirr` command? And what does the `-t <n>` option in `mixcr exportAirr` refer to? Unfortunately, I did not get this from the documentation.

**Comment by PoslavskySV** [comment]
Hi,

thank you for reporting. You are right, there are no such columns in airr output yet, but we can add them quickly. Could you please clarify:

1. `cell_id` - here we can output concatenated cell barcodes with a separator "CB1-CB2-CB3"  - OK?
2. `consensus_count` - could you please explain what is it? 

Best,
Stan

**Comment by PoslavskySV** [comment]
Hi, 

we've added `cell_id` and `umi_counts` to `exportAirr` for single cell data, you can use the following build:

https://cdn.milaboratory.com/software/mixcr/mixcr-4.2.0-15-develop-94847ec216131cce3f3664d0faa921a5252f446e.zip

Docker: ghcr.io/milaboratory/mixcr/mixcr:4.2.0-15-develop

Please, let us know how it works.

Best,
Stan

**Comment by igemuend** [comment]
Hi Stan,

Thank you for getting back to me so quickly! The develop build worked for me. My thoughts on the output are:

1. Regarding `cell_id` I personally would just paste cb1-3 into one 27 nt without separators. This makes sense for me, because I have other data modalities for these cells with that barcode format. Other people might have different preferences though.

2. Regarding `consensus_count`: From reading the AIRR format guidelines (https://docs.airr-community.org/en/stable/datarep/rearrangements.html), I understand that the category `duplicate_count` can be used to count duplicates in non-UMI data. For UMI data though, it would make sense to use the combination of `consensus_count` and  `umi_count`, with `umi_count` counting the number of UMIs per query sequence and `consensus_count` being the total reads for all UMIs that contribute to a query sequence. So the "readCount" in the clones.tsv file might already be the `consensus_count`, if I am not mistaken. In that case I would just rename the `duplicate_count` to `consensus_count` in the exported file.
I am not an AIRR expert though, so please let me know if you disagree.

3. Could you rename `umi_counts` into `umi_count`? It's a small detail - I mention it because `umi_count` is an existing field in the AIRR format.

Best,
Ioanna

**Comment by PoslavskySV** [comment]
Hi, 

thank's for the feedback:

 - We made 'cell_id' as you requested, containing concatenated from all CBs
 - We also renamed `umi_counts`
 - Added `consensus_count` field to export
 
 Please, use this build:
 
 https://cdn.milaboratory.com/software/mixcr/mixcr-4.2.0-23-develop-9ea111e426866e47b794affadf39b12bd8a5cb5e.zip
 
 Docker: 
 
 ghcr.io/milaboratory/mixcr/mixcr:4.2.0-23-develop
 
 Let me know how it works!

**Comment by igemuend** [comment]
Hi,

perfect, works for me. The UMI field is still called `umi_counts` in my output. All the rest looks good though!
Thank you for incorporating the changes!

Best,
Ioanna

**Comment by PoslavskySV** [comment]
Great! We will fix 'umi_counts', sorry for inconvenience. Feel free to re-open if other issues related to airr arise.
